### To do list :
- [ ] Add missing metabolites to biomass equation

### Setting up

In [ ]:
%pip install cobra

In [1]:
import cobra
import numpy as np
import pandas as pd
from cobra.io import load_model
from cobra.io import load_json_model, save_json_model, load_matlab_model, save_matlab_model, read_sbml_model, write_sbml_model
from cobra import Model, Reaction, Metabolite, Gene

Upload model

In [76]:
model = read_sbml_model('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\Models\\Manual Curation\\Biomass Equation\\biomass_update_2.sbml')

In [3]:
model1 = read_sbml_model('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\Models\\Solarfood_original.sbml')

In [86]:
model1 = read_sbml_model('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\PhD\\Data\\Models\\Reference_GSMs\\iSynCJ816.xml')

No objective coefficients in model. Unclear what should be optimized

In [6]:
copy_of_model = model.copy()

In [69]:
# set reactions bounds for a specific reaction 
reaction = copy_of_model.reactions.get_by_id('Growth')
reaction.bounds = -0.0, 0.0

In [10]:
c_uptake =10

In [90]:
copy_of_model.summary()

In [5]:

# Set ammonia uptake rate to 1 mmol/(gDCW·h)
ammonia_uptake_rxn = copy_of_model.reactions.get_by_id('EX_nh4_e')  # Replace with actual ammonia exchange reaction ID


# Maximize the ATPase reaction
atp_hydrolysis_rxn = copy_of_model.reactions.get_by_id('ATPM')  # Replace with actual ATP hydrolysis reaction ID
copy_of_model.objective = atp_hydrolysis_rxn

# Perform optimization
solution = copy_of_model.optimize()

# Check the flux through the ATP hydrolysis and ammonia uptake reactions
atp_flux = solution.fluxes[atp_hydrolysis_rxn.id]
ammonia_flux = solution.fluxes[ammonia_uptake_rxn.id]

print(f'ATP Hydrolysis Flux: {atp_flux} mmol ATP/(gDCW·h)')
print(f'Ammonia Uptake Flux: {ammonia_flux} mmol NH3/(gDCW·h)')

ATP Hydrolysis Flux: 14.000000000000002 mmol ATP/(gDCW·h)
Ammonia Uptake Flux: 0.0 mmol NH3/(gDCW·h)

# Manual Curation

## Adding metabolites

In [212]:
new_metabolite = Metabolite(
    id='ethyln_c',     # Metabolite ID
    name='Ethylnitronate',     # Metabolite Name
    formula='C2H4NO2',         # Chemical Formula
    compartment='c'            # Compartment (e.g., cytoplasm)
)

new_metabolite.charge = -1   

copy_of_model.add_metabolites([new_metabolite])

print(new_metabolite.formula)

C2H4NO2

## Reactions & genes handling

### Search metabolite

#### Choose a metabolite and see the fluxes of each reactions it is involved in it

In [88]:
model1.metabolites.get_by_id('hdec_c').summary()

In [79]:
search_word = 'hepdcoa'
# Iterate over metabolites in the model
for metabolite in copy_of_model.metabolites:
    if search_word in metabolite.id:
        # Print metabolite information
        print(metabolite.id)
        print(metabolite.charge)
        print(metabolite.formula)
        print(metabolite.name)
        print(metabolite.compartment)
        print(metabolite.annotation)
        
        # Get related reactions
        related_reactions = list(metabolite.reactions)
        
        # Get genes related to the reactions
        related_genes = set()
        for reaction in related_reactions:
            related_genes.update(reaction.genes)
        
        # Print related reactions and associated genes
        print(f"Related Reactions: {', '.join(r.id for r in related_reactions)}")
        print(f"Genes Associated: {', '.join(g.id for g in related_genes)}\n")

### Search reaction

In [63]:
search_word = 'PROHEXADECA'

for reaction in copy_of_model.reactions:
    if search_word in reaction.id:
        print(f"Reaction ID: {reaction.id}")
        print(f"Name: {reaction.name}")
        print(f"Equation: {reaction.reaction}")
        print(f"Lower Bound: {reaction.lower_bound}")
        print(f"Upper Bound: {reaction.upper_bound}")
        print(f"Genes: {[gene.id for gene in reaction.genes]}")

Reaction ID: PROHEXADECA
Name: Protonation of Hexadecanoate to Hexadecanoic acid
Equation: h_c + hdca_c --> hexadecacid_c
Lower Bound: 0.0
Upper Bound: 1000.0
Genes: []

### Check reaction

In [4]:
reaction_id_to_check = 'Growth'
reaction = model1.reactions.get_by_id(reaction_id_to_check)
print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")
sum = 0
#reaction.name = '(S)-2-Acetolactate pyruvate-lyase (carboxylating)'
print("\nMetabolites and Stoichiometry:")
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id:<15}: {coefficient:>25}  Name: {metabolite.name:<60}  Charge: {metabolite.charge:>3}  Formula: {metabolite.formula}")
    sum += coefficient * metabolite.charge
print(f'\nSum charge: {sum}')
print("\nAssociated Genes:")
for gene in reaction.genes:
    print(gene.id)

Reaction ID: Growth
Name: Biomass equation measured by SolarFoods
Equation: 0.000223 10fthf_c + 0.000223 2dmmql8_c + 0.000223 5mthf_c + 0.000279 accoa_c + 0.816872 ala__L_c + 0.000223 amet_c + 0.255798 arg__L_c + 0.252959 asn__L_c + 0.252959 asp__L_c + 29.190682 atp_c + 0.004952 ca2_c + 0.000223 chor_c + 0.004952 cl_c + 0.002944 clpn160_p + 0.00229 clpn161_p + 0.00118 clpn181_p + 0.000168 coa_c + 2.4e-05 cobalt2_c + 0.010737 ctp_c + 0.006744 cu2_c + 0.037472 cys__L_c + 0.014833 datp_c + 0.015499 dctp_c + 0.024005 dgtp_c + 0.013367 dttp_c + 0.000223 enter_c + 0.000223 fad_c + 0.006388 fe2_c + 0.007428 fe3_c + 0.644556 fru_c + 0.005772 gal_c + 0.117367 glc__D_c + 0.275321 gln__L_c + 0.275321 glu__L_c + 0.637966 gly_c + 0.000223 gthrd_c + 0.01659 gtp_c + 29.180423 h2o_c + 0.000223 hemeO_c + 0.093522 his__L_c + 0.245064 ile__L_c + 0.18569 k_c + 0.480939 leu__L_c + 0.257602 lys__L_c + 3.1e-05 malcoa_c + 0.00481 man_c + 0.142675 met__L_c + 0.008253 mg2_c + 0.000223 mlthf_c + 0.000658 mn2_c + 7e-06 mobd_c + 0.000223 mql8_c + 0.000605 murein3px4p_p + 0.001345 murein4p3p_p + 0.005381 murein4p4p_p + 0.005448 murein4px4p_p + 0.000673 murein4px4px4p_p + 0.000502 nac_c + 0.001787 nad_c + 4.5e-05 nadh_c + 0.000112 nadp_c + 0.000335 nadph_c + 0.012379 nh4_c + 0.000307 ni2_c + 0.044164 pe160_p + 0.017704 pe181_p + 0.010599 pg160_p + 0.008244 pg161_p + 0.228463 phe__L_c + 0.000223 pheme_c + 8.6e-05 pnto__R_c + 0.289116 pro__L_c + 0.03327 ptrc_c + 0.000223 pydx5p_c + 6.4e-05 pydxn_c + 5.4e-05 rbflvrd_c + 0.000223 ribflv_c + 0.298559 ser__L_c + 0.000223 sheme_c + 0.004126 so4_c + 0.006744 spmd_c + 9.8e-05 succoa_c + 0.000223 thf_c + 1.3e-05 thm_c + 0.000223 thmpp_c + 0.330852 thr__L_c + 0.080977 trp__L_c + 0.159326 tyr__L_c + 0.006775 utp_c + 0.410868 val__L_c + 0.005772 xyl__D_c + 0.000324 zn2_c --> 29.180423 adp_c + 29.180423 h_c + 29.180423 pi_c + 0.110381 ppi_c
Lower Bound: 0.0
Upper Bound: 1000.0

Metabolites and Stoichiometry:
cu2_c          :                 -0.006744  Name: Copper                                                        Charge:   2  Formula: Cu
h2o_c          :                -29.180423  Name: H2O H2O                                                       Charge:   0  Formula: H2O
ca2_c          :                 -0.004952  Name: Calcium                                                       Charge:   2  Formula: Ca
10fthf_c       :                 -0.000223  Name: 10-Formyltetrahydrofolate                                     Charge:  -2  Formula: C20H21N7O7
pydx5p_c       :                 -0.000223  Name: Pyridoxal 5'-phosphate                                        Charge:  -2  Formula: C8H8NO6P
murein3px4p_p  :                 -0.000605  Name: Two disacharide linked murein units, tripeptide crosslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C71H107N13O38
thr__L_c       :                 -0.330852  Name: L-Threonine                                                   Charge:   0  Formula: C4H9NO3
gthrd_c        :                 -0.000223  Name: Reduced glutathione                                           Charge:  -1  Formula: C10H16N3O6S
thmpp_c        :                 -0.000223  Name: Thiamine diphosphate                                          Charge:  -2  Formula: C12H16N4O7P2S
ni2_c          :                 -0.000307  Name: Nickel                                                        Charge:   2  Formula: Ni
mn2_c          :                 -0.000658  Name: Manganese                                                     Charge:   2  Formula: Mn
sheme_c        :                 -0.000223  Name: Siroheme C42H36FeN4O16                                        Charge:  -8  Formula: C42H36FeN4O16
ser__L_c       :                 -0.298559  Name: L-Serine                                                      Charge:   0  Formula: C3H7NO3
ctp_c          :                 -0.010737  Name: CTP C9H12N3O14P3                                              Charge:  -4  Formula: C9H12N3O14P3
accoa_c        :                 -0.000279  Name: Acetyl-CoA                                                    Charge:  -4  Formula: C23H34N7O17P3S
arg__L_c       :                 -0.255798  Name: L-Arginine                                                    Charge:   1  Formula: C6H15N4O2
asp__L_c       :                 -0.252959  Name: L-Aspartate                                                   Charge:  -1  Formula: C4H6NO4
murein4p3p_p   :                 -0.001345  Name: Two linked disacharide tetrapeptide and tripeptide murein units (uncrosslinked, middle of chain)  Charge:  -4  Formula: C71H109N13O39
5mthf_c        :                 -0.000223  Name: 5-Methyltetrahydrofolate                                      Charge:  -1  Formula: C20H24N7O6
nad_c          :                 -0.001787  Name: Nicotinamide adenine dinucleotide                             Charge:  -1  Formula: C21H26N7O14P2
mg2_c          :                 -0.008253  Name: Magnesium                                                     Charge:   2  Formula: Mg
met__L_c       :                 -0.142675  Name: L-Methionine                                                  Charge:   0  Formula: C5H11NO2S
nh4_c          :                 -0.012379  Name: Ammonium                                                      Charge:   1  Formula: H4N
chor_c         :                 -0.000223  Name: Chorismate                                                    Charge:  -2  Formula: C10H8O6
zn2_c          :                 -0.000324  Name: Zinc                                                          Charge:   2  Formula: Zn
thf_c          :                 -0.000223  Name: 5,6,7,8-Tetrahydrofolate                                      Charge:  -2  Formula: C19H21N7O6
dttp_c         :                 -0.013367  Name: DTTP C10H13N2O14P3                                            Charge:  -4  Formula: C10H13N2O14P3
dctp_c         :                 -0.015499  Name: DCTP C9H12N3O13P3                                             Charge:  -4  Formula: C9H12N3O13P3
cobalt2_c      :                  -2.4e-05  Name: Co2+                                                          Charge:   2  Formula: Co
utp_c          :                 -0.006775  Name: UTP C9H11N2O15P3                                              Charge:  -4  Formula: C9H11N2O15P3
k_c            :                  -0.18569  Name: Potassium                                                     Charge:   1  Formula: K
fe2_c          :                 -0.006388  Name: Fe2+                                                          Charge:   2  Formula: Fe
datp_c         :                 -0.014833  Name: DATP C10H12N5O12P3                                            Charge:  -4  Formula: C10H12N5O12P3
nadp_c         :                 -0.000112  Name: Nicotinamide adenine dinucleotide phosphate                   Charge:  -3  Formula: C21H25N7O17P3
glu__L_c       :                 -0.275321  Name: L-Glutamate                                                   Charge:  -1  Formula: C5H8NO4
spmd_c         :                 -0.006744  Name: Spermidine                                                    Charge:   3  Formula: C7H22N3
ile__L_c       :                 -0.245064  Name: L-Isoleucine                                                  Charge:   0  Formula: C6H13NO2
hemeO_c        :                 -0.000223  Name: Heme O C49H56FeN4O5                                           Charge:   0  Formula: C49FeH56N4O5
murein4p4p_p   :                 -0.005381  Name: Two linked disacharide tetrapeptide murein units (uncrosslinked, middle of chain)  Charge:  -4  Formula: C74H114N14O40
gln__L_c       :                 -0.275321  Name: L-Glutamine                                                   Charge:   0  Formula: C5H10N2O3
fe3_c          :                 -0.007428  Name: Iron (Fe3+)                                                   Charge:   3  Formula: Fe
ala__L_c       :                 -0.816872  Name: L-Alanine                                                     Charge:   0  Formula: C3H7NO2
phe__L_c       :                 -0.228463  Name: L-Phenylalanine                                               Charge:   0  Formula: C9H11NO2
mlthf_c        :                 -0.000223  Name: 5,10-Methylenetetrahydrofolate                                Charge:  -2  Formula: C20H21N7O6
2dmmql8_c      :                 -0.000223  Name: 2-Demethylmenaquinol 8                                        Charge:   0  Formula: C50H72O2
gly_c          :                 -0.637966  Name: Glycine                                                       Charge:   0  Formula: C2H5NO2
malcoa_c       :                  -3.1e-05  Name: Malonyl CoA C24H33N7O19P3S                                    Charge:  -5  Formula: C24H33N7O19P3S
murein4px4p_p  :                 -0.005448  Name: Two disacharide linked murein units, tetrapeptide corsslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:   0  Formula: C74H112N14O39
mql8_c         :                 -0.000223  Name: Menaquinol 8                                                  Charge:   0  Formula: C51H74O2
cl_c           :                 -0.004952  Name: Chloride                                                      Charge:  -1  Formula: Cl
his__L_c       :                 -0.093522  Name: L-Histidine                                                   Charge:   0  Formula: C6H9N3O2
ribflv_c       :                 -0.000223  Name: Riboflavin C17H20N4O6                                         Charge:   0  Formula: C17H22N4O6
so4_c          :                 -0.004126  Name: Sulfate                                                       Charge:  -2  Formula: O4S
ptrc_c         :                  -0.03327  Name: Putrescine                                                    Charge:   2  Formula: C4H14N2
gtp_c          :                  -0.01659  Name: GTP C10H12N5O14P3                                             Charge:  -4  Formula: C10H12N5O14P3
pheme_c        :                 -0.000223  Name: Protoheme C34H30FeN4O4                                        Charge:  -2  Formula: C34H30FeN4O4
nadph_c        :                 -0.000335  Name: Nicotinamide adenine dinucleotide phosphate - reduced         Charge:  -4  Formula: C21H26N7O17P3
val__L_c       :                 -0.410868  Name: L-Valine                                                      Charge:   0  Formula: C5H11NO2
pro__L_c       :                 -0.289116  Name: L-Proline                                                     Charge:   0  Formula: C5H9NO2
mobd_c         :                    -7e-06  Name: Molybdate                                                     Charge:  -2  Formula: MoO4
nadh_c         :                  -4.5e-05  Name: Nicotinamide adenine dinucleotide - reduced                   Charge:  -2  Formula: C21H27N7O14P2
coa_c          :                 -0.000168  Name: Coenzyme A                                                    Charge:  -4  Formula: C21H32N7O16P3S
asn__L_c       :                 -0.252959  Name: L-Asparagine                                                  Charge:   0  Formula: C4H8N2O3
leu__L_c       :                 -0.480939  Name: L-Leucine                                                     Charge:   0  Formula: C6H13NO2
enter_c        :                 -0.000223  Name: Enterochelin                                                  Charge:  -1  Formula: C30H26N3O15
murein4px4px4p_p:                 -0.000673  Name: Three disacharide linked murein units (tetrapeptide crosslinked tetrapeptide (A2pm->D-ala) & tetrapeptide corsslinked tetrapeptide (A2pm->D-ala)) (middle of chain)  Charge:  -6  Formula: C111H167N21O58
dgtp_c         :                 -0.024005  Name: DGTP C10H12N5O13P3                                            Charge:  -4  Formula: C10H12N5O13P3
fad_c          :                 -0.000223  Name: Flavin adenine dinucleotide oxidized                          Charge:   0  Formula: C27H33N9O15P2
succoa_c       :                  -9.8e-05  Name: Succinyl-CoA                                                  Charge:  -5  Formula: C25H35N7O19P3S
thm_c          :                  -1.3e-05  Name: Thiamin                                                       Charge:   1  Formula: C12H17N4OS
rbflvrd_c      :                  -5.4e-05  Name: Reduced riboflavin                                            Charge:   0  Formula: C17H24N4O6
pydxn_c        :                  -6.4e-05  Name: Pyridoxine                                                    Charge:   0  Formula: C8H11NO3
nac_c          :                 -0.000502  Name: Nicotinate                                                    Charge:  -1  Formula: C6H4NO2
pnto__R_c      :                  -8.6e-05  Name: (R)-Pantothenate                                              Charge:  -1  Formula: C9H16NO5
clpn161_p      :                  -0.00229  Name: Cardiolipin (tetrahexadec-9-enoyl, n-C16:1)                   Charge:  -2  Formula: C73H132O17P2
pe160_p        :                 -0.044164  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pg160_p        :                 -0.010599  Name: Phosphatidylglycerol (dihexadecanoyl, n-C16:0)                Charge:   0  Formula: C38H74O10P
clpn160_p      :                 -0.002944  Name: Cardiolipin (tetrahexadecanoyl, n-C16:0)                      Charge:  -2  Formula: C73H140O17P2
clpn181_p      :                  -0.00118  Name: Cardiolipin (tetraoctadec-11-enoyl, n-C18:1)                  Charge:  -2  Formula: C81H148O17P2
pe181_p        :                 -0.017704  Name: Phosphatidylethanolamine (dioctadec-11-enoyl, n-C18:1)        Charge:   0  Formula: C41H78NO8P
pg161_p        :                 -0.008244  Name: Phosphatidylglycerol (dihexadec-9-enoyl, n-C16:1)             Charge:  -1  Formula: C38H70O10P
tyr__L_c       :                 -0.159326  Name: L-Tyrosine                                                    Charge:   0  Formula: C9H11NO3
cys__L_c       :                 -0.037472  Name: L-Cysteine                                                    Charge:   0  Formula: C3H7NO2S
amet_c         :                 -0.000223  Name: S-Adenosyl-L-methionine                                       Charge:   1  Formula: C15H23N6O5S
trp__L_c       :                 -0.080977  Name: L-Tryptophan                                                  Charge:   0  Formula: C11H12N2O2
lys__L_c       :                 -0.257602  Name: L-Lysine                                                      Charge:   1  Formula: C6H15N2O2
atp_c          :                -29.190682  Name: ATP C10H12N5O13P3                                             Charge:  -4  Formula: C10H12N5O13P3
gal_c          :                 -0.005772  Name: D-Galactose                                                   Charge:   0  Formula: C6H12O6
glc__D_c       :                 -0.117367  Name: D-Glucose                                                     Charge:   0  Formula: C6H12O6
fru_c          :                 -0.644556  Name: D-Fructose                                                    Charge:   0  Formula: C6H12O6
xyl__D_c       :                 -0.005772  Name: D-Xylose                                                      Charge:   0  Formula: C5H10O5
man_c          :                  -0.00481  Name: D-Mannose                                                     Charge:   0  Formula: C6H12O6
h_c            :                 29.180423  Name: H+                                                            Charge:   1  Formula: H
pi_c           :                 29.180423  Name: Phosphate                                                     Charge:  -2  Formula: HO4P
ppi_c          :                  0.110381  Name: Diphosphate                                                   Charge:  -3  Formula: HO7P2
adp_c          :                 29.180423  Name: ADP C10H12N5O10P2                                             Charge:  -3  Formula: C10H12N5O10P2

Sum charge: -0.1508630000000153

Associated Genes:

<b>We found out that the model contains one reaction of three for the polyhydroxybutyrate which is 'Acetoacetyl CoA reductase' </b>

### Modify bounds of reaction

In [96]:
copy_of_model.reactions.bounds = -1000.,1000.

### Check gene

In [ ]:

# Example gene ID to check
gene_id = 'AAFOLC_01125'

# Get the gene
gene = copy_of_model.genes.get_by_id(gene_id)

# Print information about the gene
print(f"Gene ID: {gene.id}")
print(f"Name: {gene.name}")

# Print reactions associated with the gene
print("\nReactions Associated with the Gene:")
for reaction in gene.reactions:
    print(f"Reaction ID: {reaction.id}")
    print(f"Name: {reaction.name}")
    print(f"Equation: {reaction.reaction}")
    print(f"Lower Bound: {reaction.lower_bound}")
    print(f"Upper Bound: {reaction.upper_bound}")

    # Print metabolites and stoichiometry
    print("\nMetabolites and Stoichiometry:")
    for metabolite, coefficient in reaction.metabolites.items():
        print(f"{metabolite.id}: {coefficient}")

Add a new gene to the model

In [38]:
if gene_id not in copy_of_model.genes:
    new_gene = Gene(id=gene_id)
    copy_of_model.genes.append(new_gene)
else:
    new_gene = copy_of_model.genes.get_by_id(gene_id)

Add gene to specific reaction

In [ ]:
reaction = copy_of_model.reactions.get_by_id('ACACDC')

reaction.gene_reaction_rule = gene_id
reaction.genes

### Add annotation to reaction

In [6]:
reaction = copy_of_model.reactions.get_by_id('ACACDC')
reaction.annotation["kegg.reaction"] = "R01366"
reaction.annotation["ec-code"] = "4.1.1.4"
reaction.annotation["metanetx.reaction"] = "MNXR95442"

print(reaction.annotation)

{'kegg.reaction': 'R01366', 'ec-code': '4.1.1.4', 'metanetx.reaction': 'MNXR95442'}

### Add annotation to gene

In [41]:
gene = copy_of_model.genes.get_by_id("AAFOLC_01125")
# Add annotations
gene.annotation["uniprot"] = "Q89CN4"

# Verify the annotation
print(gene.annotation)

{'uniprot': 'Q89CN4'}

### Add reaction

In [67]:

# more realistic fluxes by forcing TCA activity
# model.reactions.get_by_id('MDH').bounds = 0,0
# model.reactions.get_by_id('AKGMALtm').bounds = 0,0

ID = 'PROHEXADECE'
if ID not in copy_of_model.reactions:
    reaction = Reaction(ID)
    reaction.name = 'Protonation of Hexadecenoate to Hexadecenoic acid'
    reaction.lower_bound = 0.
    reaction.upper_bound = 1000.
    # reaction.annotation = {'biocyc':'4.2.3.27-RXN' , 'brenda': '4.2.3.27'}
    # HAA.annotation = {'biocyc':'CPD-9436', 'chebi':'35194', 'chemspider':'6309', 'inchi':' InChI=1S/C5H8/c1-4-5(2)3/h4H,1-2H2,3H3', 'kegg.compound':'C16521', 'pubchem':'6557'}    
    hdca = copy_of_model.metabolites.get_by_id('hdcea_c')
    hexedecacid = copy_of_model.metabolites.get_by_id('hexedecacid_c')
    co2 = copy_of_model.metabolites.get_by_id('co2_c')
    h = copy_of_model.metabolites.get_by_id('h_c')    
    reaction.add_metabolites({hdca:-1.,h:-1.,hexedecacid:1.})
    
    copy_of_model.add_reactions([reaction])

    print(copy_of_model.reactions.get_by_id(ID).id)
    print(copy_of_model.reactions.get_by_id(ID).reaction)

PROHEXADECE
h_c + hdcea_c --> hexedecacid_c

#### Add a sink reaction

In [32]:
copy_of_model.add_boundary(copy_of_model.metabolites.get_by_id('rb15bp_c'), type='sink',lb=0.0, ub=1000)

#### Run FBA with an objective function

In [62]:
from cobra.flux_analysis import pfba
# Set the sink reaction as the objective
copy_of_model.objective = "Growth"

# Perform FBA
solution = copy_of_model.optimize()
print(f"Yield: {solution.objective_value/co2_uptake}")

# Perform parsimonious FBA (optional, to minimize overall flux)
fba_solution = pfba(copy_of_model)
print(fba_solution.fluxes)

# Print the flux through the sink reaction for 3PG
print(f"Flux through the objective reaction: {fba_solution.fluxes['Growth']}")

Yield: 0.024372205498150633
EX_25dkglcn_e      0.000000
EX_2ameph_e        0.000000
EX_2m35mdntha_e    0.000000
EX_2pglyc_e        0.000000
EX_34dhbz_e        0.000000
                     ...
5DH4DGLCD          0.000000
ETOHt              0.000000
RBPC               9.073133
SBP                3.072408
PRUK               9.073133
Name: fluxes, Length: 2364, dtype: float64
Flux through the objective reaction: 0.24372205498149893

#### Show the fluxes with a detailed description of the reaction

In [69]:
significant_reactions = [
    [
        copy_of_model.reactions[RctIdx].name, 
        solution.to_frame().iloc[RctIdx].name, 
        copy_of_model.reactions[RctIdx].reaction, 
        round(solution.fluxes[RctIdx], 2)
    ]
    for RctIdx in np.where(np.abs(solution.fluxes) > 3)[0]
]

# Create a DataFrame for better visualization
df = pd.DataFrame(significant_reactions, columns=["Reaction Name", "Reaction ID", "Reaction Equation", "Flux"])

# Print the DataFrame
df

C:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\Temp\ipykernel_14784\2195648100.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  round(solution.fluxes[RctIdx], 2)

,Reaction Name,Reaction ID,Reaction Equation,Flux
0,EX_co2_e,EX_co2_e,co2_e <=>,-10.00
1,EX_h2_e,EX_h2_e,h2_e <=>,-67.07
2,EX_h2o_e,EX_h2o_e,h2o_e <=>,64.62
3,EX_o2_e,EX_o2_e,o2_e <=>,-23.57
4,Acetate-CoA ligase (ADP-forming),ACCOAL,atp_c + coa_c + ppa_c --> adp_c + pi_c + ppcoa_c,4.58
5,,APAT_1,atp_c + h_c + ppa_c <=> ppad_c + ppi_c,-3.96
6,ATP synthase (four protons for one ATP) (perip...,ATPS4rpp,adp_c + 4.0 h_p + pi_c <=> atp_c + h2o_c + 3.0...,47.19
7,CO2 transport via diffusion (extracellular to ...,CO2tex,co2_e <=> co2_p,10.00
8,CO2 transporter via diffusion (periplasm),CO2tpp,co2_p <=> co2_c,10.00
9,Cytochrome oxidase bd (ubiquinol-8: 2 protons)...,CYTBDpp,2.0 h_c + 0.5 o2_c + q8h2_c --> h2o_c + 2.0 h_...,47.14
10,Fructose-bisphosphate aldolase,FBA,fdp_c <=> dhap_c + g3p_c,-3.19
11,"Sedoheptulose 1,7-bisphosphate D-glyceraldehyd...",FBA3,s17bp_c <=> dhap_c + e4p_c,-3.07
12,Fructose-bisphosphatase,FBP,fdp_c + h2o_c --> f6p_c + pi_c,3.19
13,Glyceraldehyde-3-phosphate dehydrogenase,GAPD,g3p_c + nad_c + pi_c <=> 13dpg_c + h_c + nadh_c,-15.71
14,Bidirectional [NiFe] Hydrogenase,H2ASE_syn,h_c + nadph_c <=> h2_c + nadp_c,-19.83
15,H2O transport via diffusion,H2Ot,h2o_e <=> h2o_c,-64.62
16,Hydrogen transport via diffusion (extracellula...,H2tex,h2_e <=> h2_p,67.07
17,Hydrogen transport diffusion (periplasm),H2tpp,h2_p <=> h2_c,67.07
18,Hydrogenase (ubiquinone-8: 2 protons) (periplasm),HYD1pp,h2_c + 2.0 h_c + q8_c --> 2.0 h_p + q8h2_c,47.24
19,NAD transhydrogenase,NADTRHD,nad_c + nadph_c --> nadh_c + nadp_c,17.91
20,Oxygen transport via diffusion (extracellular ...,O2tex,o2_e <=> o2_p,23.57
21,O2 transport via diffusion (periplasm),O2tpp,o2_p <=> o2_c,23.57
22,,PACPT_1,coa_c + ppad_c <=> amp_c + h_c + ppcoa_c,-3.96
23,Phosphoglycerate kinase,PGK,3pg_c + atp_c <=> 13dpg_c + adp_c,15.71
24,Ribulose 5-phosphate 3-epimerase,RPE,ru5p__D_c <=> xu5p__D_c,-6.24
25,Transketolase,TKT1,r5p_c + xu5p__D_c <=> g3p_c + s7p_c,-3.07
26,Transketolase,TKT2,e4p_c + xu5p__D_c <=> f6p_c + g3p_c,-3.17
27,Triose-phosphate isomerase,TPI,dhap_c <=> g3p_c,-6.30
28,Ribulose-bisphosphate carboxylase,RBPC,co2_c + h2o_c + rb15bp_c <=> 2.0 3pg_c + 2.0 h_c,9.07
29,Sedoheptulose-bisphosphatase,SBP,h2o_c + s17bp_c <=> pi_c + s7p_c,3.07
30,Phosphoribulokinase,PRUK,atp_c + ru5p__D_c <=> adp_c + h_c + rb15bp_c,9.07

## Remove reaction

In [39]:
# Reaction ID to be removed
reaction_id = "SK_rb15bp_c"

# Remove the reaction from the model
copy_of_model.remove_reactions([reaction_id])

# Verify the removal
if reaction_id not in copy_of_model.reactions:
    print(f"Reaction {reaction_id} has been successfully removed.")
else:
    print(f"Failed to remove reaction {reaction_id}.")

Reaction SK_rb15bp_c has been successfully removed.

## Mass and charge balance

### Read excel files

In [70]:
file_path = 'C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified reactions.xlsx'
file_path_1 = 'C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified formula.xlsx'
file_path_2 = 'C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\Models\\Manual Curation\\Manually modified reactions.xlsx'
# Read Excel files into DataFrames
excel_data_charge = pd.read_excel(file_path)
excel_data_formula = pd.read_excel(file_path_1)
excel_data_Manualcuration = pd.read_excel(file_path_2)

### Check number of unbalanced reactions

In [71]:
used_model = copy_of_model

In [72]:
print(len(cobra.manipulation.validate.check_mass_balance(used_model)))
list_reactions = cobra.manipulation.validate.check_mass_balance(used_model)
for reaction, balance_dict in list_reactions.items():
    reaction_id = reaction.id
    charge_balance = balance_dict
    print(f"Reaction ID: {reaction_id}, Charge Balance: {charge_balance}")

6
Reaction ID: DHNAOT, Charge Balance: {'charge': 2.0}
Reaction ID: HDECH, Charge Balance: {'charge': 2.0}
Reaction ID: MECDPDH4E, Charge Balance: {'charge': -1.0}
Reaction ID: P9DH, Charge Balance: {'charge': 4.0}
Reaction ID: THZSN_1, Charge Balance: {'H': -1.0}
Reaction ID: ACACDC, Charge Balance: {'charge': -1.0, 'C': -1.0, 'H': -3.0, 'O': 1.0}

### Reaction information

In [13]:
reaction_id_to_check = 'Growth'
reaction = used_model.reactions.get_by_id(reaction_id_to_check)
print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")
sum = 0
#reaction.name = '(S)-2-Acetolactate pyruvate-lyase (carboxylating)'
print("\nMetabolites and Stoichiometry:")
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id:<15}: {coefficient:>25}  Name: {metabolite.name:<60}  Charge: {metabolite.charge:>3}  Formula: {metabolite.formula}")
    sum += coefficient * metabolite.charge
print(f'\nSum charge: {sum}')
print("\nAssociated Genes:")
for gene in reaction.genes:
    print(gene.id)

Reaction ID: Growth
Name: Biomass reaction
Equation: 0.000223 10fthf_c + 0.513689 ala__L_c + 0.000223 amet_c + 0.295792 arg__L_c + 0.241055 asn__L_c + 0.241055 asp__L_c + 54.124831 atp_c + 0.005205 ca2_c + 0.005205 cl_c + 0.000576 coa_c + 0.0001 cobalt2_c + 0.133508 ctp_c + 0.000709 cu2_c + 0.09158 cys__L_c + 0.026166 datp_c + 0.027017 dctp_c + 0.027017 dgtp_c + 0.026166 dttp_c + 0.000223 fad_c + 0.006715 fe2_c + 0.007808 fe3_c + 0.26316 gln__L_c + 0.26316 glu__L_c + 0.612638 gly_c + 0.215096 gtp_c + 48.601527 h2o_c + 0.094738 his__L_c + 0.290529 ile__L_c + 0.195193 k_c + 0.019456 kdo2lipid4_p + 0.450531 leu__L_c + 0.343161 lys__L_c + 0.153686 met__L_c + 0.008675 mg2_c + 0.000223 mlthf_c + 0.000691 mn2_c + 0.0001 mql8_c + 0.013894 murein5px4p_p + 0.001831 nad_c + 0.000447 nadp_c + 0.017868 pe160_c + 0.045946 pe160_p + 0.054154 pe161_c + 0.02106 pe161_p + 0.185265 phe__L_c + 0.000223 pheme_c + 0.221055 pro__L_c + 0.000223 pydx5p_c + 0.000223 ribflv_c + 0.215792 ser__L_c + 0.000223 sheme_c + 0.004338 so4_c + 0.000223 thf_c + 0.000223 thmpp_c + 0.253687 thr__L_c + 0.056843 trp__L_c + 0.137896 tyr__L_c + 0.144104 utp_c + 0.423162 val__L_c + 0.000341 zn2_c --> 53.95 adp_c + 53.95 h_c + 53.945662 pi_c + 0.773903 ppi_c
Lower Bound: 0.0
Upper Bound: 1000.0

Metabolites and Stoichiometry:
10fthf_c       :                 -0.000223  Name: 10-Formyltetrahydrofolate                                     Charge:  -2  Formula: C20H21N7O7
ala__L_c       :                 -0.513689  Name: L-Alanine                                                     Charge:   0  Formula: C3H7NO2
amet_c         :                 -0.000223  Name: S-Adenosyl-L-methionine                                       Charge:   1  Formula: C15H23N6O5S
arg__L_c       :                 -0.295792  Name: L-Arginine                                                    Charge:   1  Formula: C6H15N4O2
asn__L_c       :                 -0.241055  Name: L-Asparagine                                                  Charge:   0  Formula: C4H8N2O3
asp__L_c       :                 -0.241055  Name: L-Aspartate                                                   Charge:  -1  Formula: C4H6NO4
atp_c          :                -54.124831  Name: ATP C10H12N5O13P3                                             Charge:  -4  Formula: C10H12N5O13P3
ca2_c          :                 -0.005205  Name: Calcium                                                       Charge:   2  Formula: Ca
cl_c           :                 -0.005205  Name: Chloride                                                      Charge:  -1  Formula: Cl
coa_c          :                 -0.000576  Name: Coenzyme A                                                    Charge:  -4  Formula: C21H32N7O16P3S
cobalt2_c      :                   -0.0001  Name: Co2+                                                          Charge:   2  Formula: Co
ctp_c          :                 -0.133508  Name: CTP C9H12N3O14P3                                              Charge:  -4  Formula: C9H12N3O14P3
cu2_c          :                 -0.000709  Name: Copper                                                        Charge:   2  Formula: Cu
cys__L_c       :                  -0.09158  Name: L-Cysteine                                                    Charge:   0  Formula: C3H7NO2S
datp_c         :                 -0.026166  Name: DATP C10H12N5O12P3                                            Charge:  -4  Formula: C10H12N5O12P3
dctp_c         :                 -0.027017  Name: DCTP C9H12N3O13P3                                             Charge:  -4  Formula: C9H12N3O13P3
dgtp_c         :                 -0.027017  Name: DGTP C10H12N5O13P3                                            Charge:  -4  Formula: C10H12N5O13P3
dttp_c         :                 -0.026166  Name: DTTP C10H13N2O14P3                                            Charge:  -4  Formula: C10H13N2O14P3
fad_c          :                 -0.000223  Name: Flavin adenine dinucleotide oxidized                          Charge:  -2  Formula: C27H31N9O15P2
fe2_c          :                 -0.006715  Name: Fe2+ mitochondria                                             Charge:   2  Formula: Fe
fe3_c          :                 -0.007808  Name: Iron (Fe3+)                                                   Charge:   3  Formula: Fe
gln__L_c       :                  -0.26316  Name: L-Glutamine                                                   Charge:   0  Formula: C5H10N2O3
glu__L_c       :                  -0.26316  Name: L-Glutamate                                                   Charge:  -1  Formula: C5H8NO4
gly_c          :                 -0.612638  Name: Glycine                                                       Charge:   0  Formula: C2H5NO2
gtp_c          :                 -0.215096  Name: GTP C10H12N5O14P3                                             Charge:  -4  Formula: C10H12N5O14P3
h2o_c          :                -48.601527  Name: H2O H2O                                                       Charge:   0  Formula: H2O
his__L_c       :                 -0.094738  Name: L-Histidine                                                   Charge:   0  Formula: C6H9N3O2
ile__L_c       :                 -0.290529  Name: L-Isoleucine                                                  Charge:   0  Formula: C6H13NO2
k_c            :                 -0.195193  Name: Potassium                                                     Charge:   1  Formula: K
kdo2lipid4_p   :                 -0.019456  Name: KDO(2)-lipid IV(A)                                            Charge:  -6  Formula: C84H148N2O37P2
leu__L_c       :                 -0.450531  Name: L-Leucine                                                     Charge:   0  Formula: C6H13NO2
lys__L_c       :                 -0.343161  Name: L-Lysine                                                      Charge:   1  Formula: C6H15N2O2
met__L_c       :                 -0.153686  Name: L-Methionine                                                  Charge:   0  Formula: C5H11NO2S
mg2_c          :                 -0.008675  Name: Magnesium                                                     Charge:   2  Formula: Mg
mlthf_c        :                 -0.000223  Name: 5,10-Methylenetetrahydrofolate                                Charge:  -2  Formula: C20H21N7O6
mn2_c          :                 -0.000691  Name: Manganese                                                     Charge:   2  Formula: Mn
mql8_c         :                   -0.0001  Name: Menaquinol 8                                                  Charge:   0  Formula: C51H74O2
murein5px4p_p  :                 -0.013894  Name: Two disacharide linked murein units, pentapeptide crosslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C77H117N15O40
nad_c          :                 -0.001831  Name: Nicotinamide adenine dinucleotide                             Charge:  -1  Formula: C21H26N7O14P2
nadp_c         :                 -0.000447  Name: Nicotinamide adenine dinucleotide phosphate                   Charge:  -3  Formula: C21H25N7O17P3
pe160_c        :                 -0.017868  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pe160_p        :                 -0.045946  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pe161_c        :                 -0.054154  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70NO8P
pe161_p        :                  -0.02106  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70NO8P
phe__L_c       :                 -0.185265  Name: L-Phenylalanine                                               Charge:   0  Formula: C9H11NO2
pheme_c        :                 -0.000223  Name: Protoheme C34H30FeN4O4                                        Charge:  -2  Formula: C34H30FeN4O4
pro__L_c       :                 -0.221055  Name: L-Proline                                                     Charge:   0  Formula: C5H9NO2
pydx5p_c       :                 -0.000223  Name: Pyridoxal 5'-phosphate                                        Charge:  -2  Formula: C8H8NO6P
ribflv_c       :                 -0.000223  Name: Riboflavin C17H20N4O6                                         Charge:   0  Formula: C17H20N4O6
ser__L_c       :                 -0.215792  Name: L-Serine                                                      Charge:   0  Formula: C3H7NO3
sheme_c        :                 -0.000223  Name: Siroheme C42H36FeN4O16                                        Charge:  -8  Formula: C42H36FeN4O16
so4_c          :                 -0.004338  Name: Sulfate                                                       Charge:  -2  Formula: O4S
thf_c          :                 -0.000223  Name: 5,6,7,8-Tetrahydrofolate                                      Charge:  -2  Formula: C19H21N7O6
thmpp_c        :                 -0.000223  Name: Thiamine diphosphate                                          Charge:  -2  Formula: C12H16N4O7P2S
thr__L_c       :                 -0.253687  Name: L-Threonine                                                   Charge:   0  Formula: C4H9NO3
trp__L_c       :                 -0.056843  Name: L-Tryptophan                                                  Charge:   0  Formula: C11H12N2O2
tyr__L_c       :                 -0.137896  Name: L-Tyrosine                                                    Charge:   0  Formula: C9H11NO3
utp_c          :                 -0.144104  Name: UTP C9H11N2O15P3                                              Charge:  -4  Formula: C9H11N2O15P3
val__L_c       :                 -0.423162  Name: L-Valine                                                      Charge:   0  Formula: C5H11NO2
zn2_c          :                 -0.000341  Name: Zinc                                                          Charge:   2  Formula: Zn
adp_c          :                     53.95  Name: ADP C10H12N5O10P2                                             Charge:  -3  Formula: C10H12N5O10P2
h_c            :                     53.95  Name: H+                                                            Charge:   1  Formula: H
pi_c           :                 53.945662  Name: Phosphate                                                     Charge:  -2  Formula: HO4P
ppi_c          :                  0.773903  Name: Diphosphate                                                   Charge:  -3  Formula: HO7P2

Sum charge: 0.5807120000000463

Associated Genes:

### Add metabolite

In [66]:
new_metabolite = Metabolite(
    id='hexedecacid_c',     # Metabolite ID
    name='Hexadecenoic acid',     # Metabolite Name
    formula='C16H30O2',         # Chemical Formula
    compartment='c'            # Compartment (e.g., cytoplasm)
)

new_metabolite.charge = 0

copy_of_model.add_metabolites([new_metabolite])

print(new_metabolite.formula)

C16H30O2

In [221]:
reaction = copy_of_model.reactions.get_by_id('Growth')
metabolite_to_add = 'murein3px4p_p'
reaction.add_metabolites({metabolite_to_add: -0.000605})
copy_of_model.slim_optimize()

1.0554787605796536

Add modification to Excel file

In [65]:
modification =f'{metabolite_to_add} was added'
# Create a new row with the modification information
new_row = {'reaction ': reaction_id_to_check, 'modification': modification}
# Concatenate the new row to the DataFrame
excel_data_Manualcuration = pd.concat([excel_data_Manualcuration, pd.DataFrame([new_row])], ignore_index=True)

NameError: name 'metabolite_to_add' is not defined

### Remove metabolite

In [266]:
reaction = used_model.reactions.get_by_id(reaction_id_to_check)
metabolite_to_add = 'h_c'
reaction.subtract_metabolites({metabolite_to_add: 4.0})
print(reaction.reaction)

mqn8_c + pppg9_c --> mql8_c + ppp9_c

Add modification to Excel file

In [217]:
modification =f'{metabolite_to_add} was removed'
# Create a new row with the modification information
new_row = {'reaction ': reaction_id_to_check, 'modification': modification}
# Concatenate the new row to the DataFrame
excel_data_Manualcuration = pd.concat([excel_data_Manualcuration, pd.DataFrame([new_row])], ignore_index=True)

### Change charge of metabolite

In [18]:
metabolite_id = 'gam_c'
if metabolite_id in model.metabolites:
    metabolite = used_model.metabolites.get_by_id(metabolite_id)
    initial_charge = metabolite.charge  # Store the initial charge for reference
    metabolite.charge = 1
    metabolite.compartment = 'c'
    
    print(list(metabolite.reactions))  
    # Print information about the modified metabolite
    print(f"Modified metabolite: {metabolite.id}")
    print(f"Updated charge: {metabolite.charge}")
    print(f"Updated charge: {metabolite.compartment}")
else:
    print("Metabolite not found in the model.")

Metabolite not found in the model.

#### Add to excel file

In [155]:
# Create a dictionary containing information about the modified reaction
new_row = {'Reaction': reaction_id_to_check, 'metabolite changed': metabolite_id, 'initial charge': initial_charge, 'New charge': metabolite.charge}
excel_data_charge = pd.concat([excel_data_charge, pd.DataFrame([new_row])], ignore_index=True)
excel_data_charge

         Reaction metabolite changed  initial charge  New charge
0    2AGPG161tipp         2agpg161_c               0          -1
1          3HACPH          r3hbACP_c               0          -1
2         3HAD140        tmrs2eACP_c               0          -1
3   4HOXPACt2pp_1          4hoxpac_p               0          -1
4       4OXPTNtpp           4oxptn_p               0          -1
5       4OXPTNtex           4oxptn_e               0          -1
6      4hoxpactex          4hoxpac_e               0          -1
7       6ATHAtexi            6atha_e               0          -1
8            AADa              aad_c               0          -1
9          ACLS_b          hethmpp_c              -1          -2
10       AEPPYRTA             Pald_c               0          -2
11          AHGDx          S2hglut_c               0          -2
12          AKGDa           sdhlam_c               0          -1
13         ALCDpp            pqqh2_p              -4          -3
14         APAT_1             ppad_c               0          -1
15        CMCBTFL           cmcbtt_c               0           1
16        CMCBTFL          fcmcbtt_c               0           4
17       RHA50tpp           R_3hpt_p               0          -1
18       RHA50tex           R_3hpt_e               0          -1
19      RHAP40tpp          R_3hpba_p               0          -1
20      RHAP40tex          R_3hpba_e               0          -1

### Change formula of metabolite

In [256]:
metabolite_id = 'octadecacid_c'
metabolite = used_model.metabolites.get_by_id(metabolite_id)
initial_formula = metabolite.formula
metabolite.formula = 'C18H43O10'

#### Add to excel file

In [186]:
new_row_1 = {
    'Reaction': reaction_id_to_check,        # ID of the reaction associated with the metabolite change
    'metabolite changed': metabolite_id,     # ID of the metabolite that was changed
    'initial formula': initial_formula,      # Initial formula of the metabolite
    'New formula': metabolite.formula        # New formula of the metabolite after modification
}
excel_data_formula = pd.concat([excel_data_formula, pd.DataFrame([new_row_1])], ignore_index=False)

excel_data_formula = excel_data_formula.reset_index(drop=True)

In [ ]:
excel_data_formula

### Save updated files

#### Save Excel

In [264]:
# Save the updated DataFrame to the Excel file
excel_data_charge.to_excel(file_path, index=False)
excel_data_formula.to_excel(file_path_1, index=False)
excel_data_Manualcuration.to_excel(file_path_2, index=False)

#### Save model in SBML

In [75]:
sbml_filename = "C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\Models\\Manual Curation\\biomass_update_2.sbml"
cobra.io.write_sbml_model(copy_of_model, sbml_filename)

## Exchange reaction

In [47]:
copy_of_model = model.copy()

In [89]:
# set exchange reactions bounds to zero if they significally affect the growth
ex_list = []

not_to_change_list = ['EX_ca2_e','EX_cl_e','EX_cobalt2_e','EX_cu2_e','EX_h2o_e','EX_h2_e','EX_fe_e','EX_fe2_e','EX_fe3_e'
                      ,'EX_k_e','EX_mg2_e','EX_mn2_e','EX_zn2_e','EX_o2_e','EX_so4_e','EX_pi_e','EX_nh4_e','EX_mobd_e','EX_ni2_e']

for element in copy_of_model.exchanges:
    reaction = copy_of_model.reactions.get_by_id(element.id)
    
    # Iterate over metabolites associated with the reaction
    for metabolite, coefficient in reaction.metabolites.items():
        if element.id not in not_to_change_list:
            # Set reaction bounds to zero
            reaction.bounds = 0.0, 0.0
            
            # Optimize the model
            solution = copy_of_model.slim_optimize()
            
            # Check if the solution is not zero
            if solution != 0.0:
                ex_list.append(reaction.id)
                
            # Print reaction information
            print(reaction.name)
            print(solution)

EX_25dkglcn_e
0.0
EX_2ameph_e
0.0
EX_2m35mdntha_e
0.0
EX_2pglyc_e
0.0
EX_34dhbz_e
0.0
EX_35dnta_e
0.0
EX_3cmp_e
0.0
EX_3h4atb_e
0.0
EX_4abut_e
0.0
EX_4abz_e
0.0
EX_4hba_e
0.0
EX_4hoxpac_e
0.0
EX_4hphac_e
0.0
EX_4hpro_DC_e
0.0
EX_4hpro_LT_e
0.0
EX_4oxptn_e
0.0
EX_5drib_e
0.0
EX_5mcsn_e
0.0
EX_6atha_e
0.0
EX_LalaDgluMdapDala_e
0.0
EX_LalaLglu_e
0.0
EX_Lcyst_e
0.0
EX_Ncbmpts_e
0.0
EX_R_3hhpa_e
0.0
EX_R_3hnonaa_e
0.0
EX_R_3hpba_e
0.0
EX_R_3hpdeca_e
0.0
EX_R_3hphpa_e
0.0
EX_R_3hpnona_e
0.0
EX_R_3hpocta_e
0.0
EX_R_3hpt_e
0.0
EX_R_3htd58e_e
0.0
EX_abt_e
0.0
EX_ac_e
0.0
EX_acald_e
0.0
EX_acgam_e
0.0
EX_acmana_e
0.0
EX_acnam_e
0.0
EX_acon_C_e
0.0
EX_actn__R_e
0.0
EX_ade_e
0.0
EX_agm_e
0.0
EX_ala__D_e
0.0
EX_ala__L_e
0.0
EX_alahis_e
0.0
EX_alaleu_e
0.0
EX_alathr_e
0.0
EX_alatrp_e
0.0
EX_anhgm_e
0.0
EX_apc_e
0.0
EX_arab__L_e
0.0
EX_arbt6p_e
0.0
EX_arbt_e
0.0
EX_arg__L_e
0.0
EX_ascb__L_e
0.0
EX_asn__L_e
0.0
EX_aso3_e
0.0
EX_aso4_e
0.0
EX_asp__L_e
0.0
EX_bhb_e
0.0
EX_bz_e
0.0
EX_carn_e
0.0
EX_cd2_e
0.0
EX_cellb_e
0.0
EX_cgly_e
0.0
EX_chol_e
0.0
EX_chols_e
0.0
EX_chtbs_e
0.0
EX_cinnm_e
0.0
EX_cm_e
0.0
EX_co2_e
0.0
EX_co_e
0.0
EX_coa_e
0.0
EX_crn_e
0.0
EX_csn_e
0.0
EX_cyan_e
0.0
EX_cynt_e
0.0
EX_cys__L_e
0.0
EX_dca_e
0.0
EX_ddca_e
0.0
EX_dextrin_e
0.0
EX_drib_e
0.0
EX_dxyl_e
0.0
EX_enter_e
0.0
EX_fald_e
0.0
EX_fe3dcit_e
0.0
EX_fe3pyovd_kt_e
0.0
EX_feenter_e
0.0
EX_fol_e
0.0
EX_for_e
0.0
EX_frmd_e
0.0
EX_fru_e
0.0
EX_fuc_e
0.0
EX_gal_bD_e
0.0
EX_gal_e
0.0
EX_galt_e
0.0
EX_galur_e
0.0
EX_gam_e
0.0
EX_glc__D_e
0.0
EX_glc__aD_e
0.0
EX_glcr_e
0.0
EX_glcur_e
0.0
EX_gln__L_e
0.0
EX_glu__L_e
0.0
EX_gly_e
0.0
EX_glyb_e
0.0
EX_glyc2p_e
0.0
EX_glyc3p_e
0.0
EX_glyclt_e
0.0
EX_glygln_e
0.0
EX_glyglu_e
0.0
EX_glygly_e
0.0
EX_glymet_e
0.0
EX_glyphe_e
0.0
EX_glyser_e
0.0
EX_gthrd_e
0.0
EX_gua_e
0.0
EX_h2o2_e
0.0
EX_h2s_e
0.0
EX_h_e
0.0
EX_hco3_e
0.0
EX_hdca_e
0.0
EX_hdcea_e
0.0
EX_hexs_e
0.0
EX_his__L_e
0.0
EX_hisgly_e
0.0
EX_hishis_e
0.0
EX_hpta_e
0.0
EX_hxa_e
0.0
EX_icit_e
0.0
EX_ile__L_e
0.0
EX_ind3ac_e
0.0
EX_indole_e
0.0
EX_inost_e
0.0
EX_lcts_e
0.0
EX_leu__D_e
0.0
EX_leu__L_e
0.0
EX_leuleu_e
0.0
EX_lnlc_e
0.0
EX_lys__L_e
0.0
EX_m_xyl_e
0.0
EX_malt_e
0.0
EX_malthp_e
0.0
EX_malthx_e
0.0
EX_malttr_e
0.0
EX_maltttr_e
0.0
EX_man_e
0.0
EX_melib_e
0.0
EX_met__D_e
0.0
EX_met__L_e
0.0
EX_metox__R_e
0.0
EX_metox_e
0.0
EX_mnl_e
0.0
EX_mso3_e
0.0
EX_na1_e
0.0
EX_nmn_e
0.0
EX_no2_e
0.0
EX_no3_e
0.0
EX_no_e
0.0
EX_nona_e
0.0
EX_novbcn_e
0.0
EX_ocdca_e
0.0
EX_ocdcea_e
0.0
EX_octa_e
0.0
EX_orn__D_e
0.0
EX_orn_e
0.0
EX_p_xyl_e
0.0
EX_pea_e
0.0
EX_peamn_e
0.0
EX_pentso3_e
0.0
EX_phe__L_e
0.0
EX_phedca_e
0.0
EX_phehpa_e
0.0
EX_phehxa_e
0.0
EX_pheme_e
0.0
EX_phenona_e
0.0
EX_pheocta_e
0.0
EX_phept_e
0.0
EX_ppap_e
0.0
EX_pro__L_e
0.0
EX_progly_e
0.0
EX_pta_e
0.0
EX_ptrc_e
0.0
EX_ptsla_e
0.0
EX_pydam_e
0.0
EX_pydxn_e
0.0
EX_pyovd_kt_e
0.0
EX_raffin_e
0.0
EX_rib__D_e
0.0
EX_rmn_e
0.0
EX_rnam_e
0.0
EX_s_e
0.0
EX_salchs4_e
0.0
EX_salchs4fe_e
0.0
EX_sbt__D_e
0.0
EX_sel_e
0.0
EX_ser__L_e
0.0
EX_sheme_e
0.0
EX_slnt_e
0.0
EX_so3_e
0.0
EX_spmd_e
0.0
EX_sucr_e
0.0
EX_tartr__D_e
0.0
EX_taur_e
0.0
EX_tcynt_e
0.0
EX_tet_e
0.0
EX_thr__L_e
0.0
EX_tnt_e
0.0
EX_tol_e
0.0
EX_tre_e
0.0
EX_trp__L_e
0.0
EX_tsul_e
0.0
EX_ttdca_e
0.0
EX_ttdcea_e
0.0
EX_ttrcyc_e
0.0
EX_tyr__D_e
0.0
EX_tyr__L_e
0.0
EX_urate_e
0.0
EX_urea_e
0.0
EX_vacc_e
0.0
EX_val__D_e
0.0
EX_val__L_e
0.0
EX_vanln_e
0.0
EX_xyl__D_e
0.0
EX_glcn_e
0.0
EX_n2_e
0.0
EX_succ_e
0.0
EX_etoh_e
0.0

In [90]:
# change bounds of the exchange reactions
for element in reac:
    reaction = copy_of_model.reactions.get_by_id(element)
    for metabolite, coefficient in reaction.metabolites.items():
        print(reaction.name)
        print(metabolite.name)
        print(metabolite.formula)
        reaction.bounds = -1000.0 , 1000.0

In [ ]:
# set reactions bounds for a specific reaction 
reaction = copy_of_model.reactions.get_by_id('EX_co2_e')
reaction.bounds = -1000.0, 1000.0

In [82]:
# set reactions bounds for a specific reaction 
reaction = copy_of_model.reactions.get_by_id('EX_h2_e')
reaction.bounds = -10.0, 10.0

In [88]:
solution = copy_of_model.slim_optimize()

copy_of_model.summary()

## Biomass Equation Curation

Updating the coefficient and adding metabolites from the Solar Food Biomass Equation

In [27]:
file_path = 'C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\Models\\Manual Curation\\Biomass_equation.xlsx'
# Read Excel files into DataFrames
pd_biomass = pd.read_excel(file_path)
pd_biomass

,Biomass_equation,Unnamed: 1,molar mass g/mol,measured mmol/g,Unmeasured mmol/g,unmeasured g/g,measured g/g,GAM,normalized g/g,normalized_mmol/g
0,10fthf_c,10-Formyltetrahydrofolate,471.43007,NaN,-0.000223,-0.000105,NaN,NaN,0.000000,-0.000223
1,pydx5p_c,Pyridoxal 5'-phosphate,245.12862,NaN,-0.000223,-0.000055,NaN,NaN,0.000000,-0.000223
2,murein3px4p_p,"Two disacharide linked murein units, tripeptid...",1750.69809,NaN,-0.000605,-0.001059,NaN,NaN,0.000000,-0.000605
3,thr__L_c,L-Threonine,119.12063,-0.381786,NaN,0.000000,-0.045479,NaN,-0.039411,-0.330852
4,adocbl_c,Adenosylcobalamin,1579.60636,NaN,-0.000223,-0.000352,NaN,NaN,0.000000,-0.000223
...,...,...,...,...,...,...,...,...,...,...
124,tmndnc_c,"Timnodonic acid C20:5, n-3",302.50000,-0.000044,NaN,0.000000,-0.000013,NaN,-0.000011,-0.000038
125,doco13ac_c,13Z)-13-docosenoic acid,338.60000,-0.000077,NaN,0.000000,-0.000026,NaN,-0.000023,-0.000067
126,ttc_c,Tetracosanoate n C240 C24H47O2,368.60000,-0.000035,NaN,0.000000,-0.000013,NaN,-0.000011,-0.000030
127,lnlc_c,Linoleic acid (all cis C18:2) n-6,280.40000,-0.000222,NaN,0.000000,-0.000062,NaN,-0.000054,-0.000193
128,lnlncg_c,Gamma-linolenic acid,278.40000,-0.000968,NaN,0.000000,-0.000269,NaN,-0.000233,-0.000838

In [28]:
copy_of_model.summary()

Change the coeff from the excel file of the already exisiting metabolite of the growth equation

In [109]:
i = 0
reaction = copy_of_model.reactions.get_by_id('Growth')
for element in pd_biomass.Biomass_equation:
    found = False
    for metabolite, coefficient in reaction.metabolites.items():
        if element == metabolite.id:
            found = True
            # Get the value of the 'normalized_mmol/g' column for the current metabolite
            normalized_mmol_g = pd_biomass.loc[pd_biomass['Biomass_equation'] == element, 'normalized_mmol/g'].values[0]
            print(f'The metabolite from the solar food BE = {element} coefficient {normalized_mmol_g}')
            print(f'The metabolite from the model = {metabolite.id} coefficient {coefficient}')
            initial_coefficient = coefficient
            # Update the coefficient of the metabolite in the reaction
            reaction.add_metabolites({metabolite: normalized_mmol_g}, combine=False)
            print(f'The coefficient was updated {initial_coefficient} ------> {coefficient}')
            i += 1
            solution = copy_of_model.slim_optimize()
            print(solution)
    if not found:
        pass
print(i)

The metabolite from the solar food BE = 10fthf_c coefficient -0.000223
The metabolite from the model = 10fthf_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.24372205498150215
The metabolite from the solar food BE = pydx5p_c coefficient -0.000223
The metabolite from the model = pydx5p_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.24372205498151733
The metabolite from the solar food BE = thr__L_c coefficient -0.33085175798343425
The metabolite from the model = thr__L_c coefficient -0.253687
The coefficient was updated -0.253687 ------> -0.253687
0.24190229624969578
The metabolite from the solar food BE = h_c coefficient 29.1804227450256
The metabolite from the model = h_c coefficient 53.95
The coefficient was updated 53.95 ------> 53.95
0.24190229624968937
The metabolite from the solar food BE = thmpp_c coefficient -0.000223
The metabolite from the model = thmpp_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.24190229624968662
The metabolite from the solar food BE = mn2_c coefficient -0.000658
The metabolite from the model = mn2_c coefficient -0.000691
The coefficient was updated -0.000691 ------> -0.000691
0.24190229624968843
The metabolite from the solar food BE = sheme_c coefficient -0.000223
The metabolite from the model = sheme_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.24190229624968843
The metabolite from the solar food BE = ser__L_c coefficient -0.29855906692147155
The metabolite from the model = ser__L_c coefficient -0.215792
The coefficient was updated -0.215792 ------> -0.215792
0.24045799418947766
The metabolite from the solar food BE = ctp_c coefficient -0.010737250405651103
The metabolite from the model = ctp_c coefficient -0.133508
The coefficient was updated -0.133508 ------> -0.133508
0.2470211199073512
The metabolite from the solar food BE = arg__L_c coefficient -0.2557979323259868
The metabolite from the model = arg__L_c coefficient -0.295792
The coefficient was updated -0.295792 ------> -0.295792
0.24849410040325975
The metabolite from the solar food BE = asp__L_c coefficient -0.2529593526847482
The metabolite from the model = asp__L_c coefficient -0.241055
The coefficient was updated -0.241055 ------> -0.241055
0.24820041364889056
The metabolite from the solar food BE = nad_c coefficient -0.001787
The metabolite from the model = nad_c coefficient -0.001831
The coefficient was updated -0.001831 ------> -0.001831
0.2482061059377917
The metabolite from the solar food BE = mg2_c coefficient -0.008253
The metabolite from the model = mg2_c coefficient -0.008675
The coefficient was updated -0.008675 ------> -0.008675
0.2482061059377917
The metabolite from the solar food BE = adp_c coefficient 29.1804227450256
The metabolite from the model = adp_c coefficient 53.95
The coefficient was updated 53.95 ------> 53.95
0.03472404643544085
The metabolite from the solar food BE = met__L_c coefficient -0.14267468516500864
The metabolite from the model = met__L_c coefficient -0.153686
The coefficient was updated -0.153686 ------> -0.153686
0.03473068620300898
The metabolite from the solar food BE = pi_c coefficient 29.1804227450256
The metabolite from the model = pi_c coefficient 53.945662
The coefficient was updated 53.945662 ------> 53.945662
0.03473068620300884
The metabolite from the solar food BE = zn2_c coefficient -0.000324
The metabolite from the model = zn2_c coefficient -0.000341
The coefficient was updated -0.000341 ------> -0.000341
0.03473068620300884
The metabolite from the solar food BE = tyr__L_c coefficient -0.1593258444308896
The metabolite from the model = tyr__L_c coefficient -0.137896
The coefficient was updated -0.137896 ------> -0.137896
0.03470743756887628
The metabolite from the solar food BE = cys__L_c coefficient -0.037472225353906465
The metabolite from the model = cys__L_c coefficient -0.09158
The coefficient was updated -0.09158 ------> -0.09158
0.03472700215983686
The metabolite from the solar food BE = amet_c coefficient -0.000223
The metabolite from the model = amet_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.03472700215983686
The metabolite from the solar food BE = trp__L_c coefficient -0.08097676930208217
The metabolite from the model = trp__L_c coefficient -0.056843
The coefficient was updated -0.056843 ------> -0.056843
0.03469501672661412
The metabolite from the solar food BE = lys__L_c coefficient -0.25760196352578224
The metabolite from the model = lys__L_c coefficient -0.343161
The coefficient was updated -0.343161 ------> -0.343161
0.0347569217001421
The metabolite from the solar food BE = atp_c coefficient -29.190681913288
The metabolite from the model = atp_c coefficient -54.124831
The coefficient was updated -54.124831 ------> -54.124831
0.2606135852131607
The metabolite from the solar food BE = thf_c coefficient -0.000223
The metabolite from the model = thf_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.2606135852131588
The metabolite from the solar food BE = dttp_c coefficient -0.013367475433835764
The metabolite from the model = dttp_c coefficient -0.026166
The coefficient was updated -0.026166 ------> -0.026166
0.26148576296691567
The metabolite from the solar food BE = dctp_c coefficient -0.0154992827580827
The metabolite from the model = dctp_c coefficient -0.027017
The coefficient was updated -0.027017 ------> -0.027017
0.2621964588370779
The metabolite from the solar food BE = cobalt2_c coefficient -2.4e-05
The metabolite from the model = cobalt2_c coefficient -0.0001
The coefficient was updated -0.0001 ------> -0.0001
0.2621964588370689
The metabolite from the solar food BE = utp_c coefficient -0.006775403427840368
The metabolite from the model = utp_c coefficient -0.144104
The coefficient was updated -0.144104 ------> -0.144104
9.12016748251772e-14
The metabolite from the solar food BE = k_c coefficient -0.18569
The metabolite from the model = k_c coefficient -0.195193
The coefficient was updated -0.195193 ------> -0.195193
1.4154167572579381e-13
The metabolite from the solar food BE = fe2_c coefficient -0.006388
The metabolite from the model = fe2_c coefficient -0.006715
The coefficient was updated -0.006715 ------> -0.006715
-1.214096438713825e-13
The metabolite from the solar food BE = datp_c coefficient -0.014832979735072188
The metabolite from the model = datp_c coefficient -0.026166
The coefficient was updated -0.026166 ------> -0.026166
1.671617548361831e-13
The metabolite from the solar food BE = ppi_c coefficient 0.110381072928369
The metabolite from the model = ppi_c coefficient 0.773903
The coefficient was updated 0.773903 ------> 0.773903
0.27181260222117454
The metabolite from the solar food BE = nadp_c coefficient -0.000112
The metabolite from the model = nadp_c coefficient -0.000447
The coefficient was updated -0.000447 ------> -0.000447
0.271864588212774
The metabolite from the solar food BE = glu__L_c coefficient -0.275320637946572
The metabolite from the model = glu__L_c coefficient -0.26316
The coefficient was updated -0.26316 ------> -0.26316
0.2714159313233971
The metabolite from the solar food BE = ile__L_c coefficient -0.24506430675451657
The metabolite from the model = ile__L_c coefficient -0.290529
The coefficient was updated -0.290529 ------> -0.290529
0.2734404585662429
The metabolite from the solar food BE = gln__L_c coefficient -0.2753206379465721
The metabolite from the model = gln__L_c coefficient -0.26316
The coefficient was updated -0.26316 ------> -0.26316
0.27298658964050837
The metabolite from the solar food BE = fe3_c coefficient -0.007428
The metabolite from the model = fe3_c coefficient -0.007808
The coefficient was updated -0.007808 ------> -0.007808
0.27298658964051137
The metabolite from the solar food BE = ala__L_c coefficient -0.8168723181883314
The metabolite from the model = ala__L_c coefficient -0.513689
The coefficient was updated -0.513689 ------> -0.513689
0.26637269051417867
The metabolite from the solar food BE = phe__L_c coefficient -0.22846254459317583
The metabolite from the model = phe__L_c coefficient -0.185265
The coefficient was updated -0.185265 ------> -0.185265
0.2636424145310731
The metabolite from the solar food BE = mlthf_c coefficient -0.000223
The metabolite from the model = mlthf_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.2636424145310731
The metabolite from the solar food BE = cu2_c coefficient -0.006744
The metabolite from the model = cu2_c coefficient -0.000709
The coefficient was updated -0.000709 ------> -0.000709
0.2636424145310716
The metabolite from the solar food BE = h2o_c coefficient -29.1804227450256
The metabolite from the model = h2o_c coefficient -48.601527
The coefficient was updated -48.601527 ------> -48.601527
0.2636424145310722
The metabolite from the solar food BE = ca2_c coefficient -0.004952
The metabolite from the model = ca2_c coefficient -0.005205
The coefficient was updated -0.005205 ------> -0.005205
0.26364241453106724
The metabolite from the solar food BE = gly_c coefficient -0.6379660350235106
The metabolite from the model = gly_c coefficient -0.612638
The coefficient was updated -0.612638 ------> -0.612638
0.26329078735132405
The metabolite from the solar food BE = mql8_c coefficient -0.000223
The metabolite from the model = mql8_c coefficient -0.0001
The coefficient was updated -0.0001 ------> -0.0001
0.2632473088174673
The metabolite from the solar food BE = cl_c coefficient -0.004952
The metabolite from the model = cl_c coefficient -0.005205
The coefficient was updated -0.005205 ------> -0.005205
0.2632473088174673
The metabolite from the solar food BE = his__L_c coefficient -0.09352200626083922
The metabolite from the model = his__L_c coefficient -0.094738
The coefficient was updated -0.094738 ------> -0.094738
0.26329787892648254
The metabolite from the solar food BE = ribflv_c coefficient -0.000223
The metabolite from the model = ribflv_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.26329787892648254
The metabolite from the solar food BE = so4_c coefficient -0.004126
The metabolite from the model = so4_c coefficient -0.004338
The coefficient was updated -0.004338 ------> -0.004338
0.26329787892649
The metabolite from the solar food BE = gtp_c coefficient -0.01659016153669234
The metabolite from the model = gtp_c coefficient -0.215096
The coefficient was updated -0.215096 ------> -0.215096
0.2778183805856855
The metabolite from the solar food BE = pheme_c coefficient -0.000223
The metabolite from the model = pheme_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.2778183805856855
The metabolite from the solar food BE = val__L_c coefficient -0.4108677675755479
The metabolite from the model = val__L_c coefficient -0.423162
The coefficient was updated -0.423162 ------> -0.423162
0.2782936454282651
The metabolite from the solar food BE = pro__L_c coefficient -0.28911581930944585
The metabolite from the model = pro__L_c coefficient -0.221055
The coefficient was updated -0.221055 ------> -0.221055
0.2756828060910092
The metabolite from the solar food BE = coa_c coefficient -0.000168
The metabolite from the model = coa_c coefficient -0.000576
The coefficient was updated -0.000576 ------> -0.000576
0.27574793914077045
The metabolite from the solar food BE = asn__L_c coefficient -0.2529593526847482
The metabolite from the model = asn__L_c coefficient -0.241055
The coefficient was updated -0.241055 ------> -0.241055
0.2753863457740318
The metabolite from the solar food BE = leu__L_c coefficient -0.4809387020057383
The metabolite from the model = leu__L_c coefficient -0.450531
The coefficient was updated -0.450531 ------> -0.450531
0.2740096338103705
The metabolite from the solar food BE = dgtp_c coefficient -0.02400546922059191
The metabolite from the model = dgtp_c coefficient -0.027017
The coefficient was updated -0.027017 ------> -0.027017
0.27423593013141034
The metabolite from the solar food BE = fad_c coefficient -0.000223
The metabolite from the model = fad_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.27423593013141034
The metabolite from the solar food BE = pe160_p coefficient -0.044164
The metabolite from the model = pe160_p coefficient -0.045946
The coefficient was updated -0.045946 ------> -0.045946
0.2747326872656163
59

Compare the coeff of the excel to the one in the model

In [110]:
i=0
reaction = copy_of_model.reactions.get_by_id('Growth')
for element in pd_biomass.Biomass_equation:
    for metabolite, coefficient in reaction.metabolites.items():
        if element == metabolite.id:
            print(element)
            normalized_mmol_g = pd_biomass.loc[pd_biomass['Biomass_equation'] == element, 'normalized_mmol/g'].values[0]
            print(normalized_mmol_g)
            print(coefficient)
            i+=1
print(i)

10fthf_c
-0.000223
-0.000223
pydx5p_c
-0.000223
-0.000223
thr__L_c
-0.33085175798343425
-0.33085175798343425
h_c
29.1804227450256
29.1804227450256
thmpp_c
-0.000223
-0.000223
mn2_c
-0.000658
-0.000658
sheme_c
-0.000223
-0.000223
ser__L_c
-0.29855906692147155
-0.29855906692147155
ctp_c
-0.010737250405651103
-0.010737250405651103
arg__L_c
-0.2557979323259868
-0.2557979323259868
asp__L_c
-0.2529593526847482
-0.2529593526847482
nad_c
-0.001787
-0.001787
mg2_c
-0.008253
-0.008253
adp_c
29.1804227450256
29.1804227450256
met__L_c
-0.14267468516500864
-0.14267468516500864
pi_c
29.1804227450256
29.1804227450256
zn2_c
-0.000324
-0.000324
tyr__L_c
-0.1593258444308896
-0.1593258444308896
cys__L_c
-0.037472225353906465
-0.037472225353906465
amet_c
-0.000223
-0.000223
trp__L_c
-0.08097676930208217
-0.08097676930208217
lys__L_c
-0.25760196352578224
-0.25760196352578224
atp_c
-29.190681913288
-29.190681913288
thf_c
-0.000223
-0.000223
dttp_c
-0.013367475433835764
-0.013367475433835764
dctp_c
-0.0154992827580827
-0.0154992827580827
cobalt2_c
-2.4e-05
-2.4e-05
utp_c
-0.006775403427840368
-0.006775403427840368
k_c
-0.18569
-0.18569
fe2_c
-0.006388
-0.006388
datp_c
-0.014832979735072188
-0.014832979735072188
ppi_c
0.110381072928369
0.110381072928369
nadp_c
-0.000112
-0.000112
glu__L_c
-0.275320637946572
-0.275320637946572
ile__L_c
-0.24506430675451657
-0.24506430675451657
gln__L_c
-0.2753206379465721
-0.2753206379465721
fe3_c
-0.007428
-0.007428
ala__L_c
-0.8168723181883314
-0.8168723181883314
phe__L_c
-0.22846254459317583
-0.22846254459317583
mlthf_c
-0.000223
-0.000223
cu2_c
-0.006744
-0.006744
h2o_c
-29.1804227450256
-29.1804227450256
ca2_c
-0.004952
-0.004952
gly_c
-0.6379660350235106
-0.6379660350235106
mql8_c
-0.000223
-0.000223
cl_c
-0.004952
-0.004952
his__L_c
-0.09352200626083922
-0.09352200626083922
ribflv_c
-0.000223
-0.000223
so4_c
-0.004126
-0.004126
gtp_c
-0.01659016153669234
-0.01659016153669234
pheme_c
-0.000223
-0.000223
val__L_c
-0.4108677675755479
-0.4108677675755479
pro__L_c
-0.28911581930944585
-0.28911581930944585
coa_c
-0.000168
-0.000168
asn__L_c
-0.2529593526847482
-0.2529593526847482
leu__L_c
-0.4809387020057383
-0.4809387020057383
dgtp_c
-0.02400546922059191
-0.02400546922059191
fad_c
-0.000223
-0.000223
pe160_p
-0.044164
-0.044164
59

Create a dict to see which metabolite are not in the biomass equation

In [94]:
metabolite_not_found = {}
i = 0
reaction = copy_of_model.reactions.get_by_id('Growth')
for element in pd_biomass.Biomass_equation:
    found = False
    for metabolite, coefficient in reaction.metabolites.items():
        if element == metabolite.id:
            found = True
    if not found:
        normalized_mmol_g = pd_biomass.loc[pd_biomass['Biomass_equation'] == element, 'normalized_mmol/g'].values[0]
        print(f'{element:<15}  {normalized_mmol_g:>25}')
        metabolite_not_found[element] = normalized_mmol_g
        i+=1
print(i)

adocbl_c                         -0.000223
gthrd_c                          -0.000223
ni2_c                            -0.000307
q8h2_c                           -0.000223
spmd_c                           -0.006744
mococdp_c                           -7e-06
2fe2s_c                           -2.5e-05
btn_c              -1.1414549099588767e-07
4fe4s_c                          -0.000248
enter_c                          -0.000223
rmn_c                 -0.12458295393473183
arab__L_c             -0.03001579312991268
gal__L_c             -0.005772139750897219
fru_c                  -0.6445556055168562
xyl__D_c             -0.005772267909598585
man_c                -0.004810116459081017
galam_c              -0.004836694654618716
gam_c                -0.004836694654618716
retinol_c           -9.074246924272647e-09
avite1_c           -3.0180772507593555e-06
vitd3_c             -5.633064100806269e-10
vitd2_c             -5.462623432098053e-10
thm_c              -1.3154306833538052e-05
pydxn_c             -6.433607814591869e-05
chol_c              -0.0013841118723877054
fol_c              -2.1226953703375583e-05
phllqne_c          -1.9227658781185626e-09
caro_c              -3.993838208771886e-05
colipa_e                         -0.008151
hexadecacid_c        -0.049934570136758984
hexedecacid_c        -0.007033277906537638
hpdca_c             -0.0002921739778619036
octadecacid_c        -0.007173968847108888
octedecacid_c         -0.13197873979176503
lnlc_c               -0.005902952960848603
lnlncg_c            -0.0003641921623863511
arach_c             -7.320957230552366e-05
tmndnc_c            -3.781486172805971e-05
doco13ac_c          -6.705455767638082e-05
ttc_c              -3.0093216061396738e-05
lnlc_c               -0.005902952960848603
lnlncg_c            -0.0003641921623863511
42

Compare metabolite from another model biomass equation to the model

In [30]:
df_met_notfound = pd.DataFrame(columns=['metabolite_id','metabolite_name'])

In [95]:
# Initialize a counter for metabolites not found and a dictionary to store them
metabolomic_data = []
i = 0

# Retrieve the 'Growth' reaction from both models
reaction = copy_of_model.reactions.get_by_id('Growth')
reaction1 = model1.reactions.get_by_id('Growth')

# Iterate over metabolites in the 'Growth' reaction of model1
for metabolite1 in reaction1.metabolites:
    found = False  # Initialize the found flag for each metabolite in reaction1
    for metabolite in reaction.metabolites:
        if metabolite1.id == metabolite.id:
            found = True
            break  # If metabolite is found, break the inner loop
    
    # If the metabolite was not found, add it to the dictionary and increment the counter
    if not found:
        metabolomic_data.append({'metabolite_id': metabolite1.id, 'metabolite_name': metabolite1.name})
        i += 1

# Print the number of metabolites not found
print(f"Number of metabolites not found: {i}")

# Create the df_metabolomic DataFrame from the list
df_met_notfound = pd.concat([df_met_notfound, pd.DataFrame(metabolomic_data)], ignore_index=True)

df_met_notfound

Number of metabolites not found: 10

       metabolite_id                                    metabolite_name
0      murein3px4p_p  Two disacharide linked murein units, tripeptid...
1            gthrd_c                                Reduced glutathione
2              ni2_c                                             Nickel
3            accoa_c                                         Acetyl-CoA
4       murein4p3p_p  Two linked disacharide tetrapeptide and tripep...
5            5mthf_c                           5-Methyltetrahydrofolate
6              nh4_c                                           Ammonium
7             chor_c                                         Chorismate
8             spmd_c                                         Spermidine
9            hemeO_c                                Heme O C49H56FeN4O5
10      murein4p4p_p  Two linked disacharide tetrapeptide murein uni...
11         2dmmql8_c                             2-Demethylmenaquinol 8
12          malcoa_c                         Malonyl CoA C24H33N7O19P3S
13     murein4px4p_p  Two disacharide linked murein units, tetrapept...
14            ptrc_c                                         Putrescine
15           nadph_c  Nicotinamide adenine dinucleotide phosphate - ...
16            mobd_c                                          Molybdate
17            nadh_c        Nicotinamide adenine dinucleotide - reduced
18           enter_c                                       Enterochelin
19  murein4px4px4p_p  Three disacharide linked murein units (tetrape...
20          succoa_c                                       Succinyl-CoA
21             thm_c                                            Thiamin
22         rbflvrd_c                                 Reduced riboflavin
23           pydxn_c                                         Pyridoxine
24             nac_c                                         Nicotinate
25         pnto__R_c                                   (R)-Pantothenate
26         clpn161_p        Cardiolipin (tetrahexadec-9-enoyl, n-C16:1)
27           pg160_p     Phosphatidylglycerol (dihexadecanoyl, n-C16:0)
28         clpn160_p           Cardiolipin (tetrahexadecanoyl, n-C16:0)
29         clpn181_p       Cardiolipin (tetraoctadec-11-enoyl, n-C18:1)
30           pe181_p  Phosphatidylethanolamine (dioctadec-11-enoyl, ...
31           pg161_p  Phosphatidylglycerol (dihexadec-9-enoyl, n-C16:1)
32             gal_c                                        D-Galactose
33          glc__D_c                                          D-Glucose
34             fru_c                                         D-Fructose
35          xyl__D_c                                           D-Xylose
36             man_c                                          D-Mannose
37           gthrd_c                                Reduced glutathione
38             ni2_c                                             Nickel
39            spmd_c                                         Spermidine
40           enter_c                                       Enterochelin
41             thm_c                                            Thiamin
42           pydxn_c                                         Pyridoxine
43             gal_c                                        D-Galactose
44             fru_c                                         D-Fructose
45          xyl__D_c                                           D-Xylose
46             man_c                                          D-Mannose

In [37]:
df_met_notfound.to_excel('C:\\Users\\adam-1y9pxi6q95ggpmx\\Desktop\\metabolitenotfound.xlsx',index=False)

In [61]:
new_metabolite = Metabolite(
    id='vitd2_c',     # Metabolite ID
    name='Vitamin D2; ergocalciferol',     # Metabolite Name
    formula='C28H44O',         # Chemical Formula
    compartment='c'            # Compartment (e.g., cytoplasm)
)

new_metabolite.charge = 0

copy_of_model.add_metabolites([new_metabolite])

print(new_metabolite.formula)

C28H44O

In [68]:
reaction = copy_of_model.reactions.get_by_id('Growth')
metabolite_to_add = 'hexedecacid_c'
reaction.add_metabolites({metabolite_to_add: -0.007033})
copy_of_model.slim_optimize()

0.056786881745949085

In [16]:
reaction = used_model.reactions.get_by_id(reaction_id_to_check)
metabolite_to_add = 'atp_c'
reaction.subtract_metabolites({metabolite_to_add: -83.30525375})
copy_of_model.slim_optimize()

-1.4893506896496426e-17

Create a dict with the metabolite that are only in the model biomass equation

In [ ]:
model_BE_metabolite = {}

# Get the 'Growth' reaction
reaction = model1.reactions.get_by_id('BIOMASS_KT2440_WT3')

# Iterate over metabolites in the 'Growth' reaction
for metabolite, coefficient in reaction.metabolites.items():
    # Check if the metabolite ID is not in the 'Biomass_equation' column
    if metabolite.id not in pd_biomass['Biomass_equation'].values:
        # Add the metabolite ID and its coefficient to the dictionary
        model_BE_metabolite[metabolite.id] = coefficient

model_BE_metabolite

In [33]:
reaction_id_to_check = 'Growth'
reaction = copy_of_model.reactions.get_by_id(reaction_id_to_check)
print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")
sum = 0
#reaction.name = '(S)-2-Acetolactate pyruvate-lyase (carboxylating)'
print("\nMetabolites and Stoichiometry:")
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id:<15}: {coefficient:>25}  Name: {metabolite.name:<60}  Charge: {metabolite.charge:>3}  Formula: {metabolite.formula}")
    sum += coefficient * metabolite.charge
print(f'\nSum charge: {sum}')
print("\nAssociated Genes:")
for gene in reaction.genes:
    print(gene.id)

Reaction ID: Growth
Name: Biomass reaction
Equation: 0.000223 10fthf_c + 0.513689 ala__L_c + 0.000223 amet_c + 0.295792 arg__L_c + 0.241055 asn__L_c + 0.241055 asp__L_c + 29.18042275 atp_c + 0.005205 ca2_c + 0.005205 cl_c + 0.000576 coa_c + 0.0001 cobalt2_c + 0.133508 ctp_c + 0.000709 cu2_c + 0.09158 cys__L_c + 0.026166 datp_c + 0.027017 dctp_c + 0.027017 dgtp_c + 0.026166 dttp_c + 0.000223 fad_c + 0.006715 fe2_c + 0.007808 fe3_c + 0.26316 gln__L_c + 0.26316 glu__L_c + 0.612638 gly_c + 0.215096 gtp_c + 29.18042275 h2o_c + 0.094738 his__L_c + 0.290529 ile__L_c + 0.195193 k_c + 0.019456 kdo2lipid4_p + 0.450531 leu__L_c + 0.343161 lys__L_c + 0.153686 met__L_c + 0.008675 mg2_c + 0.000223 mlthf_c + 0.000691 mn2_c + 0.0001 mql8_c + 0.013894 murein5px4p_p + 0.001831 nad_c + 0.000447 nadp_c + 0.017868 pe160_c + 0.045946 pe160_p + 0.054154 pe161_c + 0.02106 pe161_p + 0.185265 phe__L_c + 0.000223 pheme_c + 0.221055 pro__L_c + 0.000223 pydx5p_c + 0.000223 ribflv_c + 0.215792 ser__L_c + 0.000223 sheme_c + 0.004338 so4_c + 0.000223 thf_c + 0.000223 thmpp_c + 0.253687 thr__L_c + 0.056843 trp__L_c + 0.137896 tyr__L_c + 0.144104 utp_c + 0.423162 val__L_c + 0.000341 zn2_c --> 29.18042275 adp_c + 29.18042275 h_c + 29.18042275 pi_c + 0.773903 ppi_c
Lower Bound: 0.0
Upper Bound: 1000.0

Metabolites and Stoichiometry:
10fthf_c       :                 -0.000223  Name: 10-Formyltetrahydrofolate                                     Charge:  -2  Formula: C20H21N7O7
ala__L_c       :                 -0.513689  Name: L-Alanine                                                     Charge:   0  Formula: C3H7NO2
amet_c         :                 -0.000223  Name: S-Adenosyl-L-methionine                                       Charge:   1  Formula: C15H23N6O5S
arg__L_c       :                 -0.295792  Name: L-Arginine                                                    Charge:   1  Formula: C6H15N4O2
asn__L_c       :                 -0.241055  Name: L-Asparagine                                                  Charge:   0  Formula: C4H8N2O3
asp__L_c       :                 -0.241055  Name: L-Aspartate                                                   Charge:  -1  Formula: C4H6NO4
atp_c          :              -29.18042275  Name: ATP C10H12N5O13P3                                             Charge:  -4  Formula: C10H12N5O13P3
ca2_c          :                 -0.005205  Name: Calcium                                                       Charge:   2  Formula: Ca
cl_c           :                 -0.005205  Name: Chloride                                                      Charge:  -1  Formula: Cl
coa_c          :                 -0.000576  Name: Coenzyme A                                                    Charge:  -4  Formula: C21H32N7O16P3S
cobalt2_c      :                   -0.0001  Name: Co2+                                                          Charge:   2  Formula: Co
ctp_c          :                 -0.133508  Name: CTP C9H12N3O14P3                                              Charge:  -4  Formula: C9H12N3O14P3
cu2_c          :                 -0.000709  Name: Copper                                                        Charge:   2  Formula: Cu
cys__L_c       :                  -0.09158  Name: L-Cysteine                                                    Charge:   0  Formula: C3H7NO2S
datp_c         :                 -0.026166  Name: DATP C10H12N5O12P3                                            Charge:  -4  Formula: C10H12N5O12P3
dctp_c         :                 -0.027017  Name: DCTP C9H12N3O13P3                                             Charge:  -4  Formula: C9H12N3O13P3
dgtp_c         :                 -0.027017  Name: DGTP C10H12N5O13P3                                            Charge:  -4  Formula: C10H12N5O13P3
dttp_c         :                 -0.026166  Name: DTTP C10H13N2O14P3                                            Charge:  -4  Formula: C10H13N2O14P3
fad_c          :                 -0.000223  Name: Flavin adenine dinucleotide oxidized                          Charge:  -2  Formula: C27H31N9O15P2
fe2_c          :                 -0.006715  Name: Fe2+ mitochondria                                             Charge:   2  Formula: Fe
fe3_c          :                 -0.007808  Name: Iron (Fe3+)                                                   Charge:   3  Formula: Fe
gln__L_c       :                  -0.26316  Name: L-Glutamine                                                   Charge:   0  Formula: C5H10N2O3
glu__L_c       :                  -0.26316  Name: L-Glutamate                                                   Charge:  -1  Formula: C5H8NO4
gly_c          :                 -0.612638  Name: Glycine                                                       Charge:   0  Formula: C2H5NO2
gtp_c          :                 -0.215096  Name: GTP C10H12N5O14P3                                             Charge:  -4  Formula: C10H12N5O14P3
h2o_c          :              -29.18042275  Name: H2O H2O                                                       Charge:   0  Formula: H2O
his__L_c       :                 -0.094738  Name: L-Histidine                                                   Charge:   0  Formula: C6H9N3O2
ile__L_c       :                 -0.290529  Name: L-Isoleucine                                                  Charge:   0  Formula: C6H13NO2
k_c            :                 -0.195193  Name: Potassium                                                     Charge:   1  Formula: K
kdo2lipid4_p   :                 -0.019456  Name: KDO(2)-lipid IV(A)                                            Charge:  -6  Formula: C84H148N2O37P2
leu__L_c       :                 -0.450531  Name: L-Leucine                                                     Charge:   0  Formula: C6H13NO2
lys__L_c       :                 -0.343161  Name: L-Lysine                                                      Charge:   1  Formula: C6H15N2O2
met__L_c       :                 -0.153686  Name: L-Methionine                                                  Charge:   0  Formula: C5H11NO2S
mg2_c          :                 -0.008675  Name: Magnesium                                                     Charge:   2  Formula: Mg
mlthf_c        :                 -0.000223  Name: 5,10-Methylenetetrahydrofolate                                Charge:  -2  Formula: C20H21N7O6
mn2_c          :                 -0.000691  Name: Manganese                                                     Charge:   2  Formula: Mn
mql8_c         :                   -0.0001  Name: Menaquinol 8                                                  Charge:   0  Formula: C51H74O2
murein5px4p_p  :                 -0.013894  Name: Two disacharide linked murein units, pentapeptide crosslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C77H117N15O40
nad_c          :                 -0.001831  Name: Nicotinamide adenine dinucleotide                             Charge:  -1  Formula: C21H26N7O14P2
nadp_c         :                 -0.000447  Name: Nicotinamide adenine dinucleotide phosphate                   Charge:  -3  Formula: C21H25N7O17P3
pe160_c        :                 -0.017868  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pe160_p        :                 -0.045946  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pe161_c        :                 -0.054154  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70NO8P
pe161_p        :                  -0.02106  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70NO8P
phe__L_c       :                 -0.185265  Name: L-Phenylalanine                                               Charge:   0  Formula: C9H11NO2
pheme_c        :                 -0.000223  Name: Protoheme C34H30FeN4O4                                        Charge:  -2  Formula: C34H30FeN4O4
pro__L_c       :                 -0.221055  Name: L-Proline                                                     Charge:   0  Formula: C5H9NO2
pydx5p_c       :                 -0.000223  Name: Pyridoxal 5'-phosphate                                        Charge:  -2  Formula: C8H8NO6P
ribflv_c       :                 -0.000223  Name: Riboflavin C17H20N4O6                                         Charge:   0  Formula: C17H20N4O6
ser__L_c       :                 -0.215792  Name: L-Serine                                                      Charge:   0  Formula: C3H7NO3
sheme_c        :                 -0.000223  Name: Siroheme C42H36FeN4O16                                        Charge:  -8  Formula: C42H36FeN4O16
so4_c          :                 -0.004338  Name: Sulfate                                                       Charge:  -2  Formula: O4S
thf_c          :                 -0.000223  Name: 5,6,7,8-Tetrahydrofolate                                      Charge:  -2  Formula: C19H21N7O6
thmpp_c        :                 -0.000223  Name: Thiamine diphosphate                                          Charge:  -2  Formula: C12H16N4O7P2S
thr__L_c       :                 -0.253687  Name: L-Threonine                                                   Charge:   0  Formula: C4H9NO3
trp__L_c       :                 -0.056843  Name: L-Tryptophan                                                  Charge:   0  Formula: C11H12N2O2
tyr__L_c       :                 -0.137896  Name: L-Tyrosine                                                    Charge:   0  Formula: C9H11NO3
utp_c          :                 -0.144104  Name: UTP C9H11N2O15P3                                              Charge:  -4  Formula: C9H11N2O15P3
val__L_c       :                 -0.423162  Name: L-Valine                                                      Charge:   0  Formula: C5H11NO2
zn2_c          :                 -0.000341  Name: Zinc                                                          Charge:   2  Formula: Zn
adp_c          :               29.18042275  Name: ADP C10H12N5O10P2                                             Charge:  -3  Formula: C10H12N5O10P2
h_c            :               29.18042275  Name: H+                                                            Charge:   1  Formula: H
pi_c           :               29.18042275  Name: Phosphate                                                     Charge:  -2  Formula: HO4P
ppi_c          :                  0.773903  Name: Diphosphate                                                   Charge:  -3  Formula: HO7P2

Sum charge: -0.12728800000003027

Associated Genes:

add metabolite to the biomass composition

In [90]:
copy_of_model = model.copy()

In [87]:
metabolite_not_found.pop('lnlc_c', None)

-0.005902952960848603

In [93]:
# Convert the dictionary to a DataFrame
df_metabolite_not_found = pd.DataFrame(list(metabolite_not_found.items()), columns=['Metabolite', 'Coefficient'])

# Save the DataFrame to an Excel file
output_file = 'C:\\Users\\adam-1y9pxi6q95ggpmx\\Desktop\\metabolite_not_found.xlsx'
df_metabolite_not_found.to_excel(output_file, index=False)

print(f"The data has been saved to {output_file}")

The data has been saved to C:\Users\adam-1y9pxi6q95ggpmx\Desktop\metabolite_not_found.xlsx

In [91]:
# Get the reaction 'Growth'
reaction = copy_of_model.reactions.get_by_id('Growth')

for metabolite_id, coefficient in metabolite_not_found.items():
    try:
        print(metabolite_id)
        # Add the metabolite to the reaction with its coefficient
        reaction.add_metabolites({metabolite_id: coefficient})
        # Optimize the model and print the result
        print(copy_of_model.slim_optimize())
    except KeyError:
        # If the metabolite is not found in the model, pass
        pass

murein3px4p_p
0.06357280701152104
accoa_c
0.06356243497722236
murein4p3p_p
0.06340848185333318
5mthf_c
0.06340130985077432
nh4_c
0.06340130985077487
chor_c
0.06339772445786857
hemeO_c
0.06338016189270824
murein4p4p_p
0.06274673112747187
mococdp_c
2dmmql8_c
0.06272917634107245
malcoa_c
0.06272800532194366
murein4px4p_p
0.062099830246387024
2fe2s_c
ptrc_c
0.06189522332031643
nadph_c
0.061884444711125974
mobd_c
0.061884444711124656
4fe4s_c
nadh_c
0.06188299712424866
murein4px4px4p_p
0.0617687781162228
succoa_c
0.061765039268234574
gal__L_c
glc__D_c
0.06070882696360335
galam_c
gam_c
retinol_c
avite1_c
vitd3_c
vitd2_c
thm_c
rbflvrd_c
0.06070746642455039
nac_c
0.06070302380473093
pnto__R_c
0.060701881750210775
phllqne_c
caro_c
clpn161_p
0.060456488053340945
pg160_p
0.059873331953638254
clpn160_p
0.05956674199177274
clpn181_p
0.05943139556552227
colipa_e
pe181_p
0.058423264500054826
pg161_p
0.05799865926385473
ttdca_c
0.05798746728729021
hexadecacid_c
hexedecacid_c
hpdca_c
octadecacid_c
octedecacid_c
lnlncg_c
arach_c
tmndnc_c
doco13ac_c
ttc_c

GAM update

In [34]:
GAM_metabolites_1 = {'atp_c': -29.18042275, 'h2o_c': -29.18042275}
GAM_metabolites_2 = {'adp_c': 29.18042275, 'pi_c': 29.18042275, 'h_c': 29.18042275}

# Get the biomass reaction
reaction = copy_of_model.reactions.get_by_id('Growth')

# Update the coefficients for GAM_metabolites_1
for element, new_coefficient in GAM_metabolites_1.items():
    metabolite = copy_of_model.metabolites.get_by_id(element)
    if metabolite in reaction.metabolites:
        print(f'Old coefficient for {element}: {reaction.metabolites[metabolite]}')
        reaction.add_metabolites({metabolite: new_coefficient - reaction.metabolites[metabolite]})
        print(f'Updated {element} coefficient to {new_coefficient}')

# Update the coefficients for GAM_metabolites_2
for element, new_coefficient in GAM_metabolites_2.items():
    metabolite = copy_of_model.metabolites.get_by_id(element)
    if metabolite in reaction.metabolites:
        print(f'Old coefficient for {element}: {reaction.metabolites[metabolite]}')
        reaction.add_metabolites({metabolite: new_coefficient - reaction.metabolites[metabolite]})
        print(f'Updated {element} coefficient to {new_coefficient}')

# Optimize the model
solution = copy_of_model.slim_optimize()
print(f'Optimal solution: {solution}')

Old coefficient for atp_c: -54.124831
Updated atp_c coefficient to -29.18042275
Old coefficient for h2o_c: -48.601527
Updated h2o_c coefficient to -29.18042275
Old coefficient for adp_c: 53.95
Updated adp_c coefficient to 29.18042275
Old coefficient for pi_c: 53.945662
Updated pi_c coefficient to 29.18042275
Old coefficient for h_c: 53.95
Updated h_c coefficient to 29.18042275
Optimal solution: 0.0636423240292905

# Update new model

### Update charges from excel

In [11]:
file_path = 'C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified reactions.xlsx'
file_path_1 = 'C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified formula.xlsx'

excel_data_charge = pd.read_excel(file_path)

# Iterate over each component in the Excel file
for component in excel_data_charge['metabolite changed']:
    # Check if a metabolite is present in the model's metabolites
    metabolite_id = component
    if metabolite_id in copy_of_model.metabolites:
        # Get the metabolite from the model
        metabolite = copy_of_model.metabolites.get_by_id(metabolite_id)
        
        # Change the charge of the metabolite to a new value from the Excel file
        new_charge = int(excel_data_charge.loc[excel_data_charge['metabolite changed'] == metabolite_id, 'New charge'].values[0])
        metabolite.charge = new_charge
        
        # Print information about the modified metabolite
        print(f"Modified metabolite: {metabolite.id}")
        print(f"Updated charge: {metabolite.charge}")
    else:
        print("Metabolite not found in the model.")

Modified metabolite: 2agpg161_c
Updated charge: -1
Modified metabolite: r3hbACP_c
Updated charge: -1
Modified metabolite: tmrs2eACP_c
Updated charge: -1
Modified metabolite: 4hoxpac_p
Updated charge: -1
Modified metabolite: 4oxptn_p
Updated charge: -1
Modified metabolite: 4oxptn_e
Updated charge: -1
Modified metabolite: 4hoxpac_e
Updated charge: -1
Modified metabolite: 6atha_e
Updated charge: -1
Metabolite not found in the model.
Modified metabolite: hethmpp_c
Updated charge: -2
Modified metabolite: Pald_c
Updated charge: -2
Modified metabolite: S2hglut_c
Updated charge: -2
Modified metabolite: sdhlam_c
Updated charge: -1
Modified metabolite: pqqh2_p
Updated charge: -3
Modified metabolite: ppad_c
Updated charge: -1
Modified metabolite: cmcbtt_c
Updated charge: 1
Modified metabolite: fcmcbtt_c
Updated charge: 4
Modified metabolite: R_3hpt_p
Updated charge: -1
Modified metabolite: R_3hpt_e
Updated charge: -1
Modified metabolite: R_3hpba_p
Updated charge: -1
Modified metabolite: R_3hpba_e
Updated charge: -1

In [23]:
print(len(cobra.manipulation.validate.check_mass_balance(copy_of_model)))
list_reactions = cobra.manipulation.validate.check_mass_balance(copy_of_model)
for reaction, balance_dict in list_reactions.items():
    reaction_id = reaction.id
    charge_balance = balance_dict
    print(f"Reaction ID: {reaction_id}, Charge Balance: {charge_balance}")

5
Reaction ID: DHNAOT, Charge Balance: {'charge': 2.0}
Reaction ID: HDECH, Charge Balance: {'charge': 2.0}
Reaction ID: MECDPDH4E, Charge Balance: {'charge': -1.0}
Reaction ID: P9DH, Charge Balance: {'charge': 4.0}
Reaction ID: THZSN_1, Charge Balance: {'H': -1.0}

### Create a list of reaction to update with the related model

In [15]:
import requests
list_reactions = cobra.manipulation.validate.check_mass_balance(copy_of_model)

# Dictionary to store reaction ID and associated model
reaction_model_mapping = {}

for reaction, balance_dict in list_reactions.items():
    reaction_id = reaction.id  # Get the ID of the reaction
    # URL of the API endpoint for the reaction
    url = f'http://bigg.ucsd.edu/api/v2/universal/reactions/{reaction_id}'
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        # Extract the model ID from the JSON data
        model_of_reaction = data['models_containing_reaction'][0]['bigg_id']
        # Store the mapping of reaction ID to its model in the dictionary
        reaction_model_mapping[reaction_id] = model_of_reaction
    else:
        # If the request was not successful, print the status code
        print("Failed to retrieve data. Status code:", response.status_code)
print(reaction_model_mapping)

{'1P2CBXLCYCL': 'iJN1463', '1P2CBXLR': 'iJN1463', '3HAACOAT140': 'iJN1463', '3HACPH': 'iYS854', '3HAD40': 'iAF1260', '3HOXTPP': 'iYS854', '3OAR40': 'iAF1260', '4HDPROO': 'iJN1463', 'AACLAM': 'iYS854', 'AACPS3': 'iAF1260', 'AACPS5': 'iAF1260', 'AADa': 'iCN718', 'AADb': 'iCN718', 'AALDH': 'iNF517', 'ACGAMPM': 'iAM_Pb448', 'ACHBS': 'iAF1260', 'ACHBS2': 'iSynCJ816', 'ACM6PH': 'iAF1260', 'ACMANApts': 'iJR904', 'ACOAD10f': 'iJN1463', 'ACOAD11f': 'iJN1463', 'ACOAD12f': 'iJN1463', 'ACOAD13f': 'iJN1463', 'ACOAD14f': 'iJN1463', 'ACOAD15f': 'iJN1463', 'ACOAD16f': 'iJN1463', 'ACOAD17f': 'iJN1463', 'ACOAD18f': 'iJN1463', 'ACOAD19f': 'iJN1463', 'ACOAD20f': 'iJN1463', 'ACOAD21f': 'iJN1463', 'ACOAD22f': 'iJN1463', 'ACOAD23f': 'iJN1463', 'ACOAD29f': 'iJN1463', 'ACOAD3': 'iAPECO1_1312', 'ACOAD30f': 'iJN1463', 'ACOAD31f': 'iJN1463', 'ACOAD33f': 'iJN1463', 'ACOAD3f': 'iAF1260', 'ACOAD6': 'iAPECO1_1312', 'ACOAD6f': 'iAF1260', 'ACOAM': 'iYS854', 'ACPPAT140': 'iAF987', 'ACPPAT160': 'iAF987', 'ACPPAT181': 'iAF987', 'ADCPS1': 'iAF987', 'ADK2': 'iAF692', 'ADOCBIAH': 'iAF692', 'ADPRDP': 'iAF1260', 'ADSELK': 'iCHOv1', 'ADSELR': 'iJN1463', 'ADSELR2': 'iJN1463', 'ADSL1r': 'iAF1260', 'ADSS': 'iAF1260', 'AEPPYRTA': 'iCN718', 'AGM3PApp': 'iAF1260', 'AGM3PH': 'iAF1260', 'AGPAT160': 'iAF1260', 'AGPAT181': 'iAF1260', 'AHMMPS_1': 'iNF517', 'AHSERL4': 'iCN718', 'AIRC1': 'iCN718', 'AIRC2': 'iAF1260', 'AIRC3': 'iAF1260', 'ALCDpp': 'iJN1463', 'AMANAPEr': 'iAF1260', 'AMPMS2': 'iAF1260', 'ANHMK': 'iAF1260', 'APAT_1': 'iCN718', 'APPLDHr': 'iAPECO1_1312', 'ARGSL': 'iAF1260', 'ARGSS': 'iAF1260', 'ATPPRT': 'iAF1260', 'BSCT': 'iAF987', 'BTS3r': 'iAF692', 'BTS4': 'iAF1260', 'BUP': 'iJN1463', 'CCPpp': 'iJN1463', 'CHORM': 'iAF1260', 'CLPNH120pp': 'iAF1260', 'CLPNH140pp': 'iAF1260', 'CLPNH141pp': 'iAF1260', 'CLPNH160pp': 'iAF1260', 'CLPNH161pp': 'iAF1260', 'CLPNH180pp': 'iAF1260', 'CLPNH181pp': 'iAF1260', 'CLPNS120pp': 'iAF1260', 'CLPNS160pp': 'iAF1260', 'CLPNS180pp': 'iAF1260', 'CMCBTFL': 'iEK1008', 'CMCBTFU': 'iEK1008', 'CYANST': 'iAF1260', 'CYO4pp': 'iJN1463', 'CYTCBB3pp': 'iJN1463', 'DAAD11': 'iJN1463', 'DAAD12': 'iJN1463', 'DAAD3': 'iJN1463', 'DAAD7': 'iJN1463', 'DAGK120': 'iAF1260', 'DAGK140': 'iAF1260', 'DAGK141': 'iAF1260', 'DAGK161': 'iAF1260', 'DAGK180': 'iAF1260', 'DAGK181': 'iAF1260', 'DASYN120': 'iAF1260', 'DASYN140': 'iAF1260', 'DASYN141': 'iAF1260', 'DASYN161': 'iAF1260', 'DASYN180': 'iAF1260', 'DASYN181': 'iAF1260', 'DB4PS': 'iAF1260', 'DESATPG160': 'iJN1463', 'DHGLYH': 'iML1515', 'DHNAOT': 'iCN718', 'DHNCOAS': 'iAM_Pb448', 'DHPM2': 'iAF692', 'DNMPPA': 'iAF1260', 'DNTPPA': 'iAF1260', 'DRPA': 'iAF1260', 'DURIPP_1': 'iYS854', 'DXPRIi': 'iAF1260', 'DXPS': 'iAF1260', 'ECOAH6': 'iAF1260', 'ECOAH8': 'iAF1260', 'EDA': 'iAF1260', 'FACOAE141': 'iAF1260', 'FACOAE1829Z12Z': 'iJN1463', 'FACOAL141t2pp': 'iAF1260', 'FACOAL1812': 'iCHOv1', 'FACOAL181d11tpp': 'iJN1463', 'FACOAL1821': 'iAB_RBC_283', 'FACOAL182t2pp': 'iJN1463', 'FBA': 'e_coli_core', 'FBP': 'e_coli_core', 'FCLPA': 'iAF1260', 'FDMO3_1': 'iYO844', 'FDMO4_1': 'iYO844', 'FE3DCITCH': 'iJN1463', 'FE3DCITR3': 'iJN1463', 'FE3DCITabcpp': 'iAF1260', 'FE3PYOVDDR2': 'iJN1463', 'FEENTERR3': 'iAF1260', 'FFSD_2': 'iCN900', 'FMNRy': 'iYO844', 'FUCpts': 'iCN900', 'G1PACT': 'iAF1260', 'GAL6PI': 'iCN900', 'GAPD': 'e_coli_core', 'GARFT': 'iAF1260', 'GCCa': 'iAF987', 'GCCb': 'iAF987', 'GCVHADPr': 'iYS854', 'GCVHRADPr': 'iYS854', 'GDPDPK': 'iAF1260', 'GDPMNP': 'iAF1260', 'GDPTPDP': 'iAF987', 'GGLUCT2': 'iEK1008', 'GLTPD': 'iAF1260', 'GLUTRR': 'iAF1260', 'GLUTRS': 'iAF1260', 'GLUTRS_3': 'iYS854', 'GPDDA4': 'iAF1260', 'GTMLT': 'iEK1008', 'GTPDPK': 'iAF1260', 'GUI1': 'iAF1260', 'HACD3': 'iAF987', 'HACD3i': 'iAF1260', 'HACD8': 'iAF987', 'HACD8i': 'iAF1260', 'HACD9': 'iCN718', 'HDECH': 'iEK1008', 'HEMEOS': 'iAF1260', 'HEX4': 'iAB_RBC_283', 'HMR_0260': 'iJN1463', 'HMSH': 'iJN1463', 'KARA2': 'iAF1260', 'KARI_1': 'iJB785', 'LASP2OA': 'iYS854', 'LPLIPAL1E181d11pp': 'iJN1463', 'LPLIPAL1G181d11pp': 'iJN1463', 'LPLIPAL2G160': 'iAF1260', 'LPLIPAL2G161': 'iAF1260', 'LPLIPAL2G181': 'iAF1260', 'MACCOAT': 'iCN718', 'MAN1PT': 'iAF987', 'MAN1PT2': 'iAF1260', 'MAN6PI': 'iAB_RBC_283', 'MANAO': 'iAF1260', 'MANpts': 'iCN900', 'MANptspp': 'iAF1260', 'MCCC': 'iAF987', 'MCTP1App': 'iAF1260', 'MCTP2App': 'iAF1260', 'MDDCP2pp': 'iAF1260', 'MDDEP1pp': 'iAF1260', 'MDDEP3pp': 'iAF1260', 'MECDPDH4E': 'iCN900', 'MEPCT': 'iAF1260', 'MGCH': 'iAF987', 'MLDCP1App': 'iAF1260', 'MLDCP3App': 'iAF1260', 'MLDEP1pp': 'iAF1260', 'MLTGY2pp': 'iAF1260', 'MLTGY3pp': 'iAF1260', 'MLTGY4pp': 'iAF1260', 'MPTG': 'iAF1260', 'MPTG2': 'iAF1260', 'NPHS': 'iAF1260', 'NTPTP1': 'iAF1260', 'OP4ENH': 'iAF1260', 'P9DH': 'iCN900', 'PACPT_1': 'iCN718', 'PALDH': 'iCN718', 'PAPA120pp': 'iAF1260', 'PAPA140pp': 'iAF1260', 'PAPA141pp': 'iAF1260', 'PAPA161pp': 'iAF1260', 'PAPA180pp': 'iAF1260', 'PAPA181pp': 'iAF1260', 'PAPPT3': 'iAF1260', 'PEAOpp': 'iJN1463', 'PGPP120pp': 'iAF1260', 'PGPP140pp': 'iAF1260', 'PGPP141pp': 'iAF1260', 'PGPP160': 'iAF1260', 'PGPP160pp': 'iAF1260', 'PGPP161pp': 'iAF1260', 'PGPP180pp': 'iAF1260', 'PGPP181': 'iAF1260', 'PGPP181pp': 'iAF1260', 'PGSA120': 'iAF1260', 'PGSA140': 'iAF1260', 'PGSA141': 'iAF1260', 'PGSA160': 'iAF1260', 'PGSA161': 'iAF1260', 'PGSA180': 'iAF1260', 'PGSA181': 'iAF1260', 'PHER': 'iJN1463', 'PHET': 'iCN718', 'PLIPA1G160pp': 'iAF1260', 'PLIPA2A181pp': 'iAF1260', 'PPA2': 'iAF1260', 'PPGPPDP': 'iAF1260', 'PPK2': 'iAF1260', 'PPM': 'iAB_RBC_283', 'PPND': 'iAF1260', 'PPNDH': 'iAF1260', 'PRAIS': 'iAF1260', 'PRAMPC': 'iAF1260', 'PRASCSi': 'iAF1260', 'PRATPP': 'iAF1260', 'PRFGS': 'iAF1260', 'PRFGS_1': 'iNF517', 'PROR': 'iCN718', 'PRPPS': 'iAB_RBC_283', 'PSD160': 'iAF1260', 'PSD181': 'iAF1260', 'PSSA160': 'iAF1260', 'PSSA181': 'iAF1260', 'PSUDS': 'iAPECO1_1312', 'PUNP6': 'iAF1260', 'RBFK': 'iAB_RBC_283', 'RBFSa': 'iAF1260', 'RECOAH3': 'iJN1463', 'RECOAH6': 'iJN1463', 'RPI': 'e_coli_core', 'SALCHS4FER1': 'iECO111_1330', 'SALCHS4FEabcpp': 'iAPECO1_1312', 'SBTPD': 'iAF1260', 'SBTpts': 'iCN900', 'SELADT': 'iCHOv1', 'SHCHF': 'iAF1260', 'SUCpts': 'iCN900', 'SUCptspp': 'iAF1260', 'TALA': 'e_coli_core', 'TETDHpp2': 'iYS1720', 'THZSN_1': 'iJN678', 'TKT2': 'e_coli_core', 'TPI': 'e_coli_core', 'TRPS1': 'iAF1260', 'TRPS3': 'iAF1260', 'TYRL': 'iAF987', 'U23GAAT': 'iAF1260', 'UAGAAT': 'iAF1260', 'UAGDP': 'iAF1260', 'UAGDP_1': 'iYS854', 'UAMAS': 'iAF1260', 'UAPGR': 'iAF1260', 'UDCPDP': 'iAF1260', 'UM4PL': 'iAF1260', 'UPP3MT': 'iAF1260', 'YUMPS': 'iAF692', 'ilvg': 'iYL1228'}

### Update charge from BIGG API

In [18]:
for reaction, model_name in reaction_model_mapping.items():
    reaction_to_modify = copy_of_model.reactions.get_by_id(reaction)
    for metabolite, coefficient in reaction_to_modify.metabolites.items():
        if metabolite.charge == 0:
            url = f'http://bigg.ucsd.edu/api/v2/models/{model_name}/metabolites/{metabolite.id}'
            response = requests.get(url)
            if response.status_code == 200:
                data = response.json()
                # Check if the charge information is available and matches the current metabolite charge
                if data['charge'] is not None and data['charge'] != metabolite.charge:
                    print(metabolite.id)
                    print(f' metabolite charge : {metabolite.charge}')
                    print(f' bigg metabolite charge : {data['charge']}')
                    metabolite.charge = data['charge']
            else:
                print("Failed to retrieve data. Status code:", response.status_code)

1p2cbxl_c
 metabolite charge : 0
 bigg metabolite charge : -1
3hmrsACP_c
 metabolite charge : 0
 bigg metabolite charge : -1
but2eACP_c
 metabolite charge : 0
 bigg metabolite charge : -1
actACP_c
 metabolite charge : 0
 bigg metabolite charge : -1
palmACP_c
 metabolite charge : 0
 bigg metabolite charge : -1
octeACP_c
 metabolite charge : 0
 bigg metabolite charge : -1
acgam1p_c
 metabolite charge : 0
 bigg metabolite charge : -2
2ahbut_c
 metabolite charge : 0
 bigg metabolite charge : -1
acmum6p_c
 metabolite charge : 0
 bigg metabolite charge : -3
acmanap_c
 metabolite charge : 0
 bigg metabolite charge : -2
fad_c
 metabolite charge : 0
 bigg metabolite charge : -2
fadh2_c
 metabolite charge : 0
 bigg metabolite charge : -2
myrsACP_c
 metabolite charge : 0
 bigg metabolite charge : -1
appl_c
 metabolite charge : 0
 bigg metabolite charge : 1
r5p_c
 metabolite charge : 0
 bigg metabolite charge : -2
adsel_c
 metabolite charge : 0
 bigg metabolite charge : -2
3padsel_c
 metabolite charge : 0
 bigg metabolite charge : -4
dcamp_c
 metabolite charge : 0
 bigg metabolite charge : -4
anhgm3p_p
 metabolite charge : 0
 bigg metabolite charge : -2
anhgm3p_c
 metabolite charge : 0
 bigg metabolite charge : -2
pa181_c
 metabolite charge : 0
 bigg metabolite charge : -2
air_c
 metabolite charge : 0
 bigg metabolite charge : -2
5aizc_c
 metabolite charge : 0
 bigg metabolite charge : -3
pqq_p
 metabolite charge : 0
 bigg metabolite charge : -3
argsuc_c
 metabolite charge : 0
 bigg metabolite charge : -1
prbatp_c
 metabolite charge : 0
 bigg metabolite charge : -6
dtbt_c
 metabolite charge : 0
 bigg metabolite charge : -1
3uib_c
 metabolite charge : 0
 bigg metabolite charge : -1
pphn_c
 metabolite charge : 0
 bigg metabolite charge : -2
pa120_p
 metabolite charge : 0
 bigg metabolite charge : -2
pg120_p
 metabolite charge : 0
 bigg metabolite charge : -1
pa140_p
 metabolite charge : 0
 bigg metabolite charge : -2
pa141_p
 metabolite charge : 0
 bigg metabolite charge : -2
pg160_p
 metabolite charge : 0
 bigg metabolite charge : -1
pa161_p
 metabolite charge : 0
 bigg metabolite charge : -2
pa180_p
 metabolite charge : 0
 bigg metabolite charge : -2
pg180_p
 metabolite charge : 0
 bigg metabolite charge : -1
pa181_p
 metabolite charge : 0
 bigg metabolite charge : -2
tsul_c
 metabolite charge : 0
 bigg metabolite charge : -2
pa120_c
 metabolite charge : 0
 bigg metabolite charge : -2
pa140_c
 metabolite charge : 0
 bigg metabolite charge : -2
pa141_c
 metabolite charge : 0
 bigg metabolite charge : -2
pa161_c
 metabolite charge : 0
 bigg metabolite charge : -2
pa180_c
 metabolite charge : 0
 bigg metabolite charge : -2
db4p_c
 metabolite charge : 0
 bigg metabolite charge : -2
pg160_c
 metabolite charge : 0
 bigg metabolite charge : -1
dhgly_c
 metabolite charge : 0
 bigg metabolite charge : -1
dhpmp_c
 metabolite charge : 0
 bigg metabolite charge : -2
g3p_c
 metabolite charge : 0
 bigg metabolite charge : -2
2dr1p_c
 metabolite charge : 0
 bigg metabolite charge : -2
2me4p_c
 metabolite charge : 0
 bigg metabolite charge : -2
vacc_c
 metabolite charge : 0
 bigg metabolite charge : -1
vacc_p
 metabolite charge : 0
 bigg metabolite charge : -1
fdp_c
 metabolite charge : 0
 bigg metabolite charge : -4
fc1p_c
 metabolite charge : 0
 bigg metabolite charge : -2
fmn_c
 metabolite charge : 0
 bigg metabolite charge : -2
taur_c
 metabolite charge : 0
 bigg metabolite charge : -1
fe3dcit_c
 metabolite charge : 0
 bigg metabolite charge : -3
fmnh2_c
 metabolite charge : 0
 bigg metabolite charge : -2
fe3dcit_p
 metabolite charge : 0
 bigg metabolite charge : -3
feenter_c
 metabolite charge : 0
 bigg metabolite charge : 3
suc6p_c
 metabolite charge : 0
 bigg metabolite charge : -2
tag6p__D_c
 metabolite charge : 0
 bigg metabolite charge : -2
fgam_c
 metabolite charge : 0
 bigg metabolite charge : -2
alpro_c
 metabolite charge : 0
 bigg metabolite charge : 1
ppgpp_c
 metabolite charge : 0
 bigg metabolite charge : -6
man1p_c
 metabolite charge : 0
 bigg metabolite charge : -2
gdptp_c
 metabolite charge : 0
 bigg metabolite charge : -7
g3pg_c
 metabolite charge : 0
 bigg metabolite charge : -1
fruur_c
 metabolite charge : 0
 bigg metabolite charge : -1
hemeO_c
 metabolite charge : 0
 bigg metabolite charge : -2
man6p_c
 metabolite charge : 0
 bigg metabolite charge : -2
op4en_c
 metabolite charge : 0
 bigg metabolite charge : -1
Largn_c
 metabolite charge : 0
 bigg metabolite charge : -1
g3pg_p
 metabolite charge : 0
 bigg metabolite charge : -1
murein5px4p_p
 metabolite charge : 0
 bigg metabolite charge : -4
murein5px4px4p_p
 metabolite charge : 0
 bigg metabolite charge : -6
murein4px4p_p
 metabolite charge : 0
 bigg metabolite charge : -4
murein3px3p_p
 metabolite charge : 0
 bigg metabolite charge : -4
uaagmda_c
 metabolite charge : 0
 bigg metabolite charge : -4
udcpdp_c
 metabolite charge : 0
 bigg metabolite charge : -3
pppi_c
 metabolite charge : 0
 bigg metabolite charge : -4
uagmda_c
 metabolite charge : 0
 bigg metabolite charge : -4
pgp120_p
 metabolite charge : 0
 bigg metabolite charge : -3
pgp140_p
 metabolite charge : 0
 bigg metabolite charge : -3
pgp141_p
 metabolite charge : 0
 bigg metabolite charge : -3
pgp160_c
 metabolite charge : 0
 bigg metabolite charge : -3
pgp160_p
 metabolite charge : 0
 bigg metabolite charge : -3
pgp161_p
 metabolite charge : 0
 bigg metabolite charge : -3
pgp180_p
 metabolite charge : 0
 bigg metabolite charge : -3
pgp181_c
 metabolite charge : 0
 bigg metabolite charge : -3
pgp181_p
 metabolite charge : 0
 bigg metabolite charge : -3
pgp120_c
 metabolite charge : 0
 bigg metabolite charge : -3
pgp140_c
 metabolite charge : 0
 bigg metabolite charge : -3
pgp141_c
 metabolite charge : 0
 bigg metabolite charge : -3
pgp161_c
 metabolite charge : 0
 bigg metabolite charge : -3
pgp180_c
 metabolite charge : 0
 bigg metabolite charge : -3
fpram_c
 metabolite charge : 0
 bigg metabolite charge : -1
prbamp_c
 metabolite charge : 0
 bigg metabolite charge : -4
ps160_c
 metabolite charge : 0
 bigg metabolite charge : -1
ps181_c
 metabolite charge : 0
 bigg metabolite charge : -1
sbt6p_c
 metabolite charge : 0
 bigg metabolite charge : -2
scl_c
 metabolite charge : 0
 bigg metabolite charge : -7
tsul_p
 metabolite charge : 0
 bigg metabolite charge : -2
uamr_c
 metabolite charge : 0
 bigg metabolite charge : -3
dscl_c
 metabolite charge : 0
 bigg metabolite charge : -7

### Update charge and formula from a curated model

In [65]:
model1 = read_sbml_model('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\Models\\Manual Curation\\updated_growth_gapfilled_autotrophic_1.sbml')

In [66]:
list_reactions = cobra.manipulation.validate.check_mass_balance(copy_of_model)
copy_of_model1 = model1.copy()
# Iterate through metabolites in the non-curated model
for metabolite in copy_of_model.metabolites:
    # Check if the metabolite exists in the curated model
    if metabolite.id in copy_of_model1.metabolites:
        # Find the corresponding metabolite in the curated model
        curated_metabolite = copy_of_model1.metabolites.get_by_id(metabolite.id)
        # Update the charge and formula of the non-curated metabolite
        metabolite.charge = curated_metabolite.charge
        metabolite.formula = curated_metabolite.formula
    else:
        print(f"Metabolite '{metabolite.id}' not found in the curated model.")

Metabolite 'etoh_e' not found in the curated model.

### Update metabolite with coa substring

In [16]:
substring_to_check = 'coa'
for metabolite in copy_of_model.metabolites:
    if substring_to_check in metabolite.id:
        if metabolite.charge == 0:
            metabolite.charge = -4
            # Print information about the modified metabolite
            print(f"Modified metabolite: {metabolite.id}")
            print(f"Updated charge of : {metabolite.charge}")

Modified metabolite: 2maacoa_c
Updated charge of : -4
Modified metabolite: 3hhd710coa_c
Updated charge of : -4
Modified metabolite: 3hhdccoa_c
Updated charge of : -4
Modified metabolite: 3hhdd4coa_c
Updated charge of : -4
Modified metabolite: 3hlnlccoa_c
Updated charge of : -4
Modified metabolite: 3hocoa_c
Updated charge of : -4
Modified metabolite: 3hodcoa_c
Updated charge of : -4
Modified metabolite: 3mgcoa_c
Updated charge of : -4
Modified metabolite: 3ohd710coa_c
Updated charge of : -4
Modified metabolite: 3ohdccoa_c
Updated charge of : -4
Modified metabolite: 3ohdd4coa_c
Updated charge of : -4
Modified metabolite: 3olnlccoa_c
Updated charge of : -4
Modified metabolite: benzcoa_c
Updated charge of : -4
Modified metabolite: ctncoa_c
Updated charge of : -4
Modified metabolite: hd2coa_c
Updated charge of : -4
Modified metabolite: hd710_2_coa_c
Updated charge of : -4
Modified metabolite: hd_7_10_coa_c
Updated charge of : -4
Modified metabolite: hdd4_2_coa_c
Updated charge of : -4
Modified metabolite: hmpscoa_c
Updated charge of : -4
Modified metabolite: lnlc2coa_c
Updated charge of : -4
Modified metabolite: lnlccoa_c
Updated charge of : -4
Modified metabolite: m2bcoa_c
Updated charge of : -4
Modified metabolite: oc2coa_c
Updated charge of : -4
Modified metabolite: phitcoa_c
Updated charge of : -4
Modified metabolite: sbzcoa_c
Updated charge of : -4
Modified metabolite: td2coa_c
Updated charge of : -4
Modified metabolite: td_5_8_coa_c
Updated charge of : -4
Modified metabolite: tde_2Z_coa_c
Updated charge of : -4
Modified metabolite: tdecoa_c
Updated charge of : -4
Modified metabolite: vacccoa_c
Updated charge of : -4

I noticed that carveme doesn't provide the appropriate charge for metabolites with Coa molecules

# Create a list of all reactions

In [ ]:
df_reactions = pd.DataFrame(columns=['reaction_id','reaction_name','reaction_equation','reaction_lower_bound','reaction_upper_bound','reaction_gene','reaction_annotation'])

In [16]:
# Iterate over all reactions in the model and populate the DataFrame
for reaction in copy_of_model.reactions:
    # Create a DataFrame for the current reaction
    reaction_data = pd.DataFrame([{
        "reaction_id": reaction.id,
        "reaction_name": reaction.name,
        "reaction_equation": reaction.reaction,
        "reaction_lower_bound": reaction.lower_bound,
        "reaction_upper_bound": reaction.upper_bound,
        "reaction_gene": reaction.gene_reaction_rule,
        "reaction_annotation": reaction.annotation
    }])
    
    # Concatenate the current reaction's DataFrame to the main DataFrame
    df_reactions = pd.concat([df_reactions, reaction_data], ignore_index=True)

# Print the resulting DataFrame to verify the results
df_reactions.to_excel('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\reaction_list.xlsx',index=False)

# Create a list of all metabolites

In [18]:
df_metabolites = pd.DataFrame(columns=['metabolite_id','metabolite_name','metabolite_formula','metabolite_charge','related_reactions'])

In [19]:
# Iterate over all reactions in the model and populate the DataFrame
for metabolite in copy_of_model.metabolites:
    # Create a DataFrame for the current reaction
    metabolite_data = pd.DataFrame([{
        "metabolite_id": metabolite.id,
        "metabolite_name": metabolite.name,
        "metabolite_formula": metabolite.formula,
        "metabolite_charge": metabolite.charge,
        "related_reactions": list(metabolite.reactions),
    }])
    # Concatenate the current reaction's DataFrame to the main DataFrame
    df_metabolites = pd.concat([df_metabolites, metabolite_data], ignore_index=True)

# Print the resulting DataFrame to verify the results
df_metabolites.to_excel('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\metabolites_list.xlsx',index=False)

# Create a list of all metabolites in a reaction

In [97]:
df_reaction2 = pd.DataFrame(columns=['met_id','met_name','met_coeff','met_charge'])

In [98]:
reaction_id_to_check = 'Growth'
reaction = copy_of_model.reactions.get_by_id(reaction_id_to_check)
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id:<15}: {coefficient:>25}  Name: {metabolite.name:<60}  Charge: {metabolite.charge:>3}  Formula: {metabolite.formula}")
    # Create a DataFrame for the current reaction
    reaction_data = pd.DataFrame([{
        "met_id": metabolite.id,
        "met_name": metabolite.name,
        "met_coeff": coefficient,
        "met_charge": metabolite.charge,
    }])
    # Concatenate the current reaction's DataFrame to the main DataFrame
    df_reaction2 = pd.concat([df_reaction2, reaction_data], ignore_index=True)

df_reaction2.to_excel('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\growth_met_list_updated.xlsx',index=False)

10fthf_c       :                 -0.000223  Name: 10-Formyltetrahydrofolate                                     Charge:  -2  Formula: C20H21N7O7
ala__L_c       :                 -0.513689  Name: L-Alanine                                                     Charge:   0  Formula: C3H7NO2
amet_c         :                 -0.000223  Name: S-Adenosyl-L-methionine                                       Charge:   1  Formula: C15H23N6O5S
arg__L_c       :                 -0.295792  Name: L-Arginine                                                    Charge:   1  Formula: C6H15N4O2
asn__L_c       :                 -0.241055  Name: L-Asparagine                                                  Charge:   0  Formula: C4H8N2O3
asp__L_c       :                 -0.241055  Name: L-Aspartate                                                   Charge:  -1  Formula: C4H6NO4
atp_c          :              -29.18042275  Name: ATP C10H12N5O13P3                                             Charge:  -4  Formula: C10H12N5O13P3
ca2_c          :                 -0.005205  Name: Calcium                                                       Charge:   2  Formula: Ca
cl_c           :                 -0.005205  Name: Chloride                                                      Charge:  -1  Formula: Cl
coa_c          :                 -0.000576  Name: Coenzyme A                                                    Charge:  -4  Formula: C21H32N7O16P3S
cobalt2_c      :                   -0.0001  Name: Co2+                                                          Charge:   2  Formula: Co
ctp_c          :                 -0.133508  Name: CTP C9H12N3O14P3                                              Charge:  -4  Formula: C9H12N3O14P3
cu2_c          :                 -0.000709  Name: Copper                                                        Charge:   2  Formula: Cu
cys__L_c       :                  -0.09158  Name: L-Cysteine                                                    Charge:   0  Formula: C3H7NO2S
datp_c         :                 -0.026166  Name: DATP C10H12N5O12P3                                            Charge:  -4  Formula: C10H12N5O12P3
dctp_c         :                 -0.027017  Name: DCTP C9H12N3O13P3                                             Charge:  -4  Formula: C9H12N3O13P3
dgtp_c         :                 -0.027017  Name: DGTP C10H12N5O13P3                                            Charge:  -4  Formula: C10H12N5O13P3
dttp_c         :                 -0.026166  Name: DTTP C10H13N2O14P3                                            Charge:  -4  Formula: C10H13N2O14P3
fad_c          :                 -0.000223  Name: Flavin adenine dinucleotide oxidized                          Charge:  -2  Formula: C27H31N9O15P2
fe2_c          :                 -0.006715  Name: Fe2+ mitochondria                                             Charge:   2  Formula: Fe
fe3_c          :                 -0.007808  Name: Iron (Fe3+)                                                   Charge:   3  Formula: Fe
gln__L_c       :                  -0.26316  Name: L-Glutamine                                                   Charge:   0  Formula: C5H10N2O3
glu__L_c       :                  -0.26316  Name: L-Glutamate                                                   Charge:  -1  Formula: C5H8NO4
gly_c          :                 -0.612638  Name: Glycine                                                       Charge:   0  Formula: C2H5NO2
gtp_c          :                 -0.215096  Name: GTP C10H12N5O14P3                                             Charge:  -4  Formula: C10H12N5O14P3
h2o_c          :              -29.18042275  Name: H2O H2O                                                       Charge:   0  Formula: H2O
his__L_c       :                 -0.094738  Name: L-Histidine                                                   Charge:   0  Formula: C6H9N3O2
ile__L_c       :                 -0.290529  Name: L-Isoleucine                                                  Charge:   0  Formula: C6H13NO2
k_c            :                 -0.195193  Name: Potassium                                                     Charge:   1  Formula: K
kdo2lipid4_p   :                 -0.019456  Name: KDO(2)-lipid IV(A)                                            Charge:  -6  Formula: C84H148N2O37P2
leu__L_c       :                 -0.450531  Name: L-Leucine                                                     Charge:   0  Formula: C6H13NO2
lys__L_c       :                 -0.343161  Name: L-Lysine                                                      Charge:   1  Formula: C6H15N2O2
met__L_c       :                 -0.153686  Name: L-Methionine                                                  Charge:   0  Formula: C5H11NO2S
mg2_c          :                 -0.008675  Name: Magnesium                                                     Charge:   2  Formula: Mg
mlthf_c        :                 -0.000223  Name: 5,10-Methylenetetrahydrofolate                                Charge:  -2  Formula: C20H21N7O6
mn2_c          :                 -0.000691  Name: Manganese                                                     Charge:   2  Formula: Mn
mql8_c         :                   -0.0001  Name: Menaquinol 8                                                  Charge:   0  Formula: C51H74O2
murein5px4p_p  :                 -0.013894  Name: Two disacharide linked murein units, pentapeptide crosslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C77H117N15O40
nad_c          :                 -0.001831  Name: Nicotinamide adenine dinucleotide                             Charge:  -1  Formula: C21H26N7O14P2
nadp_c         :                 -0.000447  Name: Nicotinamide adenine dinucleotide phosphate                   Charge:  -3  Formula: C21H25N7O17P3
pe160_c        :                 -0.017868  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pe160_p        :                 -0.045946  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pe161_c        :                 -0.054154  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70NO8P
pe161_p        :                  -0.02106  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70NO8P
phe__L_c       :                 -0.185265  Name: L-Phenylalanine                                               Charge:   0  Formula: C9H11NO2
pheme_c        :                 -0.000223  Name: Protoheme C34H30FeN4O4                                        Charge:  -2  Formula: C34H30FeN4O4
pro__L_c       :                 -0.221055  Name: L-Proline                                                     Charge:   0  Formula: C5H9NO2
pydx5p_c       :                 -0.000223  Name: Pyridoxal 5'-phosphate                                        Charge:  -2  Formula: C8H8NO6P
ribflv_c       :                 -0.000223  Name: Riboflavin C17H20N4O6                                         Charge:   0  Formula: C17H20N4O6
ser__L_c       :                 -0.215792  Name: L-Serine                                                      Charge:   0  Formula: C3H7NO3
sheme_c        :                 -0.000223  Name: Siroheme C42H36FeN4O16                                        Charge:  -8  Formula: C42H36FeN4O16
so4_c          :                 -0.004338  Name: Sulfate                                                       Charge:  -2  Formula: O4S
thf_c          :                 -0.000223  Name: 5,6,7,8-Tetrahydrofolate                                      Charge:  -2  Formula: C19H21N7O6
thmpp_c        :                 -0.000223  Name: Thiamine diphosphate                                          Charge:  -2  Formula: C12H16N4O7P2S
thr__L_c       :                 -0.253687  Name: L-Threonine                                                   Charge:   0  Formula: C4H9NO3
trp__L_c       :                 -0.056843  Name: L-Tryptophan                                                  Charge:   0  Formula: C11H12N2O2
tyr__L_c       :                 -0.137896  Name: L-Tyrosine                                                    Charge:   0  Formula: C9H11NO3
utp_c          :                 -0.144104  Name: UTP C9H11N2O15P3                                              Charge:  -4  Formula: C9H11N2O15P3
val__L_c       :                 -0.423162  Name: L-Valine                                                      Charge:   0  Formula: C5H11NO2
zn2_c          :                 -0.000341  Name: Zinc                                                          Charge:   2  Formula: Zn
adp_c          :               29.18042275  Name: ADP C10H12N5O10P2                                             Charge:  -3  Formula: C10H12N5O10P2
h_c            :               29.18042275  Name: H+                                                            Charge:   1  Formula: H
pi_c           :               29.18042275  Name: Phosphate                                                     Charge:  -2  Formula: HO4P
ppi_c          :                  0.773903  Name: Diphosphate                                                   Charge:  -3  Formula: HO7P2
murein3px4p_p  :                 -0.000605  Name: Two disacharide linked murein units, tripeptide crosslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C71H107N13O38
accoa_c        :                 -0.000279  Name: Acetyl-CoA                                                    Charge:  -4  Formula: C23H34N7O17P3S
murein4p3p_p   :                 -0.001345  Name: Two linked disacharide tetrapeptide and tripeptide murein units (uncrosslinked, middle of chain)  Charge:  -4  Formula: C71H109N13O39
5mthf_c        :                 -0.000223  Name: 5-Methyltetrahydrofolate                                      Charge:  -1  Formula: C20H24N7O6
nh4_c          :                 -0.012379  Name: Ammonium                                                      Charge:   1  Formula: H4N
chor_c         :                 -0.000223  Name: Chorismate                                                    Charge:  -2  Formula: C10H8O6
hemeO_c        :                 -0.000223  Name: Heme O C49H56FeN4O5                                           Charge:  -2  Formula: C49FeH56N4O5
murein4p4p_p   :                 -0.005381  Name: Two linked disacharide tetrapeptide murein units (uncrosslinked, middle of chain)  Charge:  -4  Formula: C74H114N14O40
2dmmql8_c      :                 -0.000223  Name: 2-Demethylmenaquinol 8                                        Charge:   0  Formula: C50H72O2
malcoa_c       :                  -3.1e-05  Name: Malonyl CoA C24H33N7O19P3S                                    Charge:  -5  Formula: C24H33N7O19P3S
murein4px4p_p  :                 -0.005448  Name: Two disacharide linked murein units, tetrapeptide corsslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C74H112N14O39
ptrc_c         :                  -0.03327  Name: Putrescine                                                    Charge:   2  Formula: C4H14N2
nadph_c        :                 -0.000335  Name: Nicotinamide adenine dinucleotide phosphate - reduced         Charge:  -4  Formula: C21H26N7O17P3
mobd_c         :                    -7e-06  Name: Molybdate                                                     Charge:  -2  Formula: MoO4
nadh_c         :                  -4.5e-05  Name: Nicotinamide adenine dinucleotide - reduced                   Charge:  -2  Formula: C21H27N7O14P2
murein4px4px4p_p:                 -0.000673  Name: Three disacharide linked murein units (tetrapeptide crosslinked tetrapeptide (A2pm->D-ala) & tetrapeptide corsslinked tetrapeptide (A2pm->D-ala)) (middle of chain)  Charge:  -6  Formula: C111H167N21O58
succoa_c       :                  -9.8e-05  Name: Succinyl-CoA                                                  Charge:  -5  Formula: C25H35N7O19P3S
glc__D_c       :      -0.11736684160157697  Name: D-Glucose                                                     Charge:   0  Formula: C6H12O6
rbflvrd_c      :     -5.42885385395863e-05  Name: Reduced riboflavin                                            Charge:   0  Formula: C17H22N4O6
nac_c          :    -0.0005023142220720257  Name: Nicotinate                                                    Charge:  -1  Formula: C6H4NO2
pnto__R_c      :    -8.609379583094386e-05  Name: (R)-Pantothenate                                              Charge:  -1  Formula: C9H16NO5
clpn161_p      :                  -0.00229  Name: Cardiolipin (tetrahexadec-9-enoyl, n-C16:1)                   Charge:  -2  Formula: C73H132O17P2
pg160_p        :                 -0.010599  Name: Phosphatidylglycerol (dihexadecanoyl, n-C16:0)                Charge:  -1  Formula: C38H74O10P
clpn160_p      :                 -0.002944  Name: Cardiolipin (tetrahexadecanoyl, n-C16:0)                      Charge:  -2  Formula: C73H140O17P2
clpn181_p      :                  -0.00118  Name: Cardiolipin (tetraoctadec-11-enoyl, n-C18:1)                  Charge:  -2  Formula: C81H148O17P2
pe181_p        :                 -0.017704  Name: Phosphatidylethanolamine (dioctadec-11-enoyl, n-C18:1)        Charge:   0  Formula: C41H78NO8P
pg161_p        :                 -0.008244  Name: Phosphatidylglycerol (dihexadec-9-enoyl, n-C16:1)             Charge:  -1  Formula: C38H70O10P
ttdca_c        :    -0.0005942465517650057  Name: Tetradecanoate (n-C14:0)                                      Charge:  -1  Formula: C14H27O2

C:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\Temp\ipykernel_15784\98607269.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_reaction2 = pd.concat([df_reaction2, reaction_data], ignore_index=True)