### To do list :
- [ ] Ajoute une rubrique pour les reactions d'echanges

### Setting up

In [ ]:
%pip install cobra

In [1]:
import cobra
import pandas as pd
from cobra.io import load_model
from cobra.io import load_json_model, save_json_model, load_matlab_model, save_matlab_model, read_sbml_model, write_sbml_model
from cobra import Model, Reaction, Metabolite

Upload model

In [2]:
model = read_sbml_model('C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\updated_growth_gapfilled_autotrophic_1.sbml')

In [4]:
model1 = read_sbml_model('C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Solarfood_original.sbml')

In [6]:
model1 = read_sbml_model('C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Reference_GSMs\\iJN1463.xml')

In [8]:
copy_of_model = model.copy()

In [4]:
# set reactions bounds for a specific reaction 
reaction = copy_of_model.reactions.get_by_id('EX_o2_e')
reaction.bounds = -10.0, 10.0

In [9]:
copy_of_model.summary()

In [7]:
model1.summary()

# Manual Curation

## Adding metabolites

In [212]:
new_metabolite = Metabolite(
    id='ethyln_c',     # Metabolite ID
    name='Ethylnitronate',     # Metabolite Name
    formula='C2H4NO2',         # Chemical Formula
    compartment='c'            # Compartment (e.g., cytoplasm)
)

new_metabolite.charge = -1   

copy_of_model.add_metabolites([new_metabolite])

print(new_metabolite.formula)

C2H4NO2

## Adding reactions

### Search metabolite

In [59]:
search_word = 'vitd2_c'
# Iterate over metabolites in the model
for metabolite in copy_of_model.metabolites:
    if search_word in metabolite.id:
        # Print metabolite information
        print(metabolite.charge)
        print(metabolite.formula)
        print(metabolite.name)
        print(metabolite.compartment)
        
        # Get related reactions
        related_reactions = list(metabolite.reactions)
        
        # Get genes related to the reactions
        related_genes = set()
        for reaction in related_reactions:
            related_genes.update(reaction.genes)
        
        # Print related reactions and associated genes
        print(f"Related Reactions: {', '.join(r.id for r in related_reactions)}")
        print(f"Genes Associated: {', '.join(g.id for g in related_genes)}\n")

### Search reaction

In [321]:
search_word = 'ADOCBLS'

for reaction in copy_of_model.reactions:
    if search_word in reaction.id:
        print(f"Reaction ID: {reaction.id}")
        print(f"Name: {reaction.name}")
        print(f"Equation: {reaction.reaction}")
        print(f"Lower Bound: {reaction.lower_bound}")
        print(f"Upper Bound: {reaction.upper_bound}")
        print(f"Genes: {[gene.id for gene in reaction.genes]}")

### Check reaction

In [17]:

# Example reaction ID to check
reaction_id_to_check = 'EX_o2_e'

# Get the reaction
reaction = copy_of_model.reactions.get_by_id(reaction_id_to_check)

# Print information
print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")

# Print metabolites and stoichiometry
print("\nMetabolites and Stoichiometry:")
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id}: {coefficient} {metabolite.charge}")

# Print associated genes
print("\nAssociated Genes:")
for gene in reaction.genes:
    print(gene.id)

Reaction ID: EX_o2_e
Name: EX_o2_e
Equation: o2_e <=>
Lower Bound: -10.0
Upper Bound: 10.0

Metabolites and Stoichiometry:
o2_e: -1.0 0

Associated Genes:

<b>We found out that the model contains one reaction of three for the polyhydroxybutyrate which is 'Acetoacetyl CoA reductase' </b>

### Check gene

In [ ]:

# Example gene ID to check
gene_id_to_check = 'AAFOLC_08105'

# Get the gene
gene = model.genes.get_by_id(gene_id_to_check)

# Print information about the gene
print(f"Gene ID: {gene.id}")
print(f"Name: {gene.name}")

# Print reactions associated with the gene
print("\nReactions Associated with the Gene:")
for reaction in gene.reactions:
    print(f"Reaction ID: {reaction.id}")
    print(f"Name: {reaction.name}")
    print(f"Equation: {reaction.reaction}")
    print(f"Lower Bound: {reaction.lower_bound}")
    print(f"Upper Bound: {reaction.upper_bound}")

    # Print metabolites and stoichiometry
    print("\nMetabolites and Stoichiometry:")
    for metabolite, coefficient in reaction.metabolites.items():
        print(f"{metabolite.id}: {coefficient}")

In [ ]:

# more realistic fluxes by forcing TCA activity
# model.reactions.get_by_id('MDH').bounds = 0,0
# model.reactions.get_by_id('AKGMALtm').bounds = 0,0

ID = 'GLCNtex'
if ID not in model.reactions:
    reaction = Reaction(ID)
    reaction.name = 'D-gluconate transport via diffusion (extracellular to periplasm)'
    reaction.lower_bound = -1000.
    reaction.upper_bound = 1000.
    # reaction.annotation = {'biocyc':'4.2.3.27-RXN' , 'brenda': '4.2.3.27'}
    haa = Metabolite(
        'glcn_e',
        formula = 'C6H11O7',
        name = 'D-Gluconate',
        charge = -1,
        compartment = 'e',
    )
    # HAA.annotation = {'biocyc':'CPD-9436', 'chebi':'35194', 'chemspider':'6309', 'inchi':' InChI=1S/C5H8/c1-4-5(2)3/h4H,1-2H2,3H3', 'kegg.compound':'C16521', 'pubchem':'6557'}    
    h2o = model.metabolites.get_by_id('h2o_c')
    acp = model.metabolites.get_by_id('ACP_c')
    dacp = model.metabolites.get_by_id('3hdecACP_c')        
    reaction.add_metabolites({dacp:-2., h2o:-1., haa:1., acp:2.})
    model.add_reactions([reaction])

    print(model.reactions.get_by_id(ID).id)
    print(model.reactions.get_by_id(ID).reaction)
    print(model.reactions.get_by_id(ID).check_mass_balance())

In [162]:
copy_of_model.add_boundary(model.metabolites.get_by_id('etoh_c'), type='sink',lb=-10, ub=1000)

## Mass and charge balance

### Read excel files

In [66]:
file_path = 'C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified reactions.xlsx'
file_path_1 = 'C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified formula.xlsx'
file_path_2 = 'C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Manually modified reactions.xlsx'
# Read Excel files into DataFrames
excel_data_charge = pd.read_excel(file_path)
excel_data_formula = pd.read_excel(file_path_1)
excel_data_Manualcuration = pd.read_excel(file_path_2)

### Check number of unbalanced reactions

In [21]:
used_model = copy_of_model

In [22]:
print(len(cobra.manipulation.validate.check_mass_balance(used_model)))
list_reactions = cobra.manipulation.validate.check_mass_balance(used_model)
for reaction, balance_dict in list_reactions.items():
    reaction_id = reaction.id
    charge_balance = balance_dict
    print(f"Reaction ID: {reaction_id}, Charge Balance: {charge_balance}")

5
Reaction ID: DHNAOT, Charge Balance: {'charge': 2.0}
Reaction ID: HDECH, Charge Balance: {'charge': 2.0}
Reaction ID: MECDPDH4E, Charge Balance: {'charge': -1.0}
Reaction ID: P9DH, Charge Balance: {'charge': 4.0}
Reaction ID: THZSN_1, Charge Balance: {'H': -1.0}

### Reaction information

In [23]:
reaction_id_to_check = 'ACHBS2'
reaction = used_model.reactions.get_by_id(reaction_id_to_check)
print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")
sum = 0
#reaction.name = '(S)-2-Acetolactate pyruvate-lyase (carboxylating)'
print("\nMetabolites and Stoichiometry:")
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id:<15}: {coefficient:>25}  Name: {metabolite.name:<60}  Charge: {metabolite.charge:>3}  Formula: {metabolite.formula}")
    sum += coefficient * metabolite.charge
print(f'\nSum charge: {sum}')
print("\nAssociated Genes:")
for gene in reaction.genes:
    print(gene.id)

Reaction ID: ACHBS2
Name: 2-aceto-2-hydroxybutanoate synthase
Equation: 2hetdp_c + 2obut_c --> 2ahbut_c + h_c + thmpp_c
Lower Bound: 0.0
Upper Bound: 1000.0

Metabolites and Stoichiometry:
2hetdp_c       :                      -1.0  Name: 2-(alpha-Hydroxyethyl)thiamine diphosphate                    Charge:  -1  Formula: C14H21N4O8P2S
2obut_c        :                      -1.0  Name: 2-Oxobutanoate                                                Charge:  -1  Formula: C4H5O3
2ahbut_c       :                       1.0  Name: (S)-2-Aceto-2-hydroxybutanoate                                Charge:  -1  Formula: C6H9O4
h_c            :                       1.0  Name: H+                                                            Charge:   1  Formula: H
thmpp_c        :                       1.0  Name: Thiamine diphosphate                                          Charge:  -2  Formula: C12H16N4O7P2S

Sum charge: 0.0

Associated Genes:
AAFOLC_18280
AAFOLC_19745

### Add metabolite

In [19]:
new_metabolite = Metabolite(
    id='hexedecacid_c',     # Metabolite ID
    name='Hexadecenoic acid',     # Metabolite Name
    formula='C16H38O9',         # Chemical Formula
    compartment='c'            # Compartment (e.g., cytoplasm)
)

new_metabolite.charge = 0

used_model.add_metabolites([new_metabolite])

print(new_metabolite.formula)

C16H38O9

In [221]:
reaction = used_model.reactions.get_by_id('Growth')
metabolite_to_add = 'murein3px4p_p'
reaction.add_metabolites({metabolite_to_add: -0.000605})
used_model.slim_optimize()

1.0554787605796536

Add modification to Excel file

In [245]:
modification =f'{metabolite_to_add} was added'
# Create a new row with the modification information
new_row = {'reaction ': reaction_id_to_check, 'modification': modification}
# Concatenate the new row to the DataFrame
excel_data_Manualcuration = pd.concat([excel_data_Manualcuration, pd.DataFrame([new_row])], ignore_index=True)

### Remove metabolite

In [266]:
reaction = used_model.reactions.get_by_id(reaction_id_to_check)
metabolite_to_add = 'h_c'
reaction.subtract_metabolites({metabolite_to_add: 4.0})
print(reaction.reaction)

mqn8_c + pppg9_c --> mql8_c + ppp9_c

Add modification to Excel file

In [217]:
modification =f'{metabolite_to_add} was removed'
# Create a new row with the modification information
new_row = {'reaction ': reaction_id_to_check, 'modification': modification}
# Concatenate the new row to the DataFrame
excel_data_Manualcuration = pd.concat([excel_data_Manualcuration, pd.DataFrame([new_row])], ignore_index=True)

### Change charge of metabolite

In [18]:
metabolite_id = 'gam_c'
if metabolite_id in model.metabolites:
    metabolite = used_model.metabolites.get_by_id(metabolite_id)
    initial_charge = metabolite.charge  # Store the initial charge for reference
    metabolite.charge = 1
    metabolite.compartment = 'c'
    
    print(list(metabolite.reactions))  
    # Print information about the modified metabolite
    print(f"Modified metabolite: {metabolite.id}")
    print(f"Updated charge: {metabolite.charge}")
    print(f"Updated charge: {metabolite.compartment}")
else:
    print("Metabolite not found in the model.")

Metabolite not found in the model.

#### Add to excel file

In [155]:
# Create a dictionary containing information about the modified reaction
new_row = {'Reaction': reaction_id_to_check, 'metabolite changed': metabolite_id, 'initial charge': initial_charge, 'New charge': metabolite.charge}
excel_data_charge = pd.concat([excel_data_charge, pd.DataFrame([new_row])], ignore_index=True)
excel_data_charge

         Reaction metabolite changed  initial charge  New charge
0    2AGPG161tipp         2agpg161_c               0          -1
1          3HACPH          r3hbACP_c               0          -1
2         3HAD140        tmrs2eACP_c               0          -1
3   4HOXPACt2pp_1          4hoxpac_p               0          -1
4       4OXPTNtpp           4oxptn_p               0          -1
5       4OXPTNtex           4oxptn_e               0          -1
6      4hoxpactex          4hoxpac_e               0          -1
7       6ATHAtexi            6atha_e               0          -1
8            AADa              aad_c               0          -1
9          ACLS_b          hethmpp_c              -1          -2
10       AEPPYRTA             Pald_c               0          -2
11          AHGDx          S2hglut_c               0          -2
12          AKGDa           sdhlam_c               0          -1
13         ALCDpp            pqqh2_p              -4          -3
14         APAT_1             ppad_c               0          -1
15        CMCBTFL           cmcbtt_c               0           1
16        CMCBTFL          fcmcbtt_c               0           4
17       RHA50tpp           R_3hpt_p               0          -1
18       RHA50tex           R_3hpt_e               0          -1
19      RHAP40tpp          R_3hpba_p               0          -1
20      RHAP40tex          R_3hpba_e               0          -1

### Change formula of metabolite

In [256]:
metabolite_id = 'octadecacid_c'
metabolite = used_model.metabolites.get_by_id(metabolite_id)
initial_formula = metabolite.formula
metabolite.formula = 'C18H43O10'

#### Add to excel file

In [186]:
new_row_1 = {
    'Reaction': reaction_id_to_check,        # ID of the reaction associated with the metabolite change
    'metabolite changed': metabolite_id,     # ID of the metabolite that was changed
    'initial formula': initial_formula,      # Initial formula of the metabolite
    'New formula': metabolite.formula        # New formula of the metabolite after modification
}
excel_data_formula = pd.concat([excel_data_formula, pd.DataFrame([new_row_1])], ignore_index=False)

excel_data_formula = excel_data_formula.reset_index(drop=True)

In [ ]:
excel_data_formula

### Save updated files

#### Save Excel

In [264]:
# Save the updated DataFrame to the Excel file
excel_data_charge.to_excel(file_path, index=False)
excel_data_formula.to_excel(file_path_1, index=False)
excel_data_Manualcuration.to_excel(file_path_2, index=False)

#### Save model in SBML

In [63]:
sbml_filename = "C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\updated_growth_gapfilled_autotrophic_1.sbml"
cobra.io.write_sbml_model(used_model, sbml_filename)

## Exchange reaction

In [ ]:
# set exchange reactions bounds to zero if they significally affect the growth
ex_list = []
copy_of_model = model.copy()
not_to_change_list = ['EX_ca2_e','EX_cl_e','EX_cobalt2_e','EX_cu2_e','EX_h2o_e','EX_h2_e','EX_fe_e','EX_fe2_e','EX_fe3_e'
                      ,'EX_co2_e','EX_k_e','EX_mg2_e','EX_mn2_e','EX_zn2_e','EX_o2_e','EX_so4_e','EX_pi_e','EX_nh4_e','EX_mobd_e']

for element in copy_of_model.exchanges:
    reaction = copy_of_model.reactions.get_by_id(element.id)
    
    # Iterate over metabolites associated with the reaction
    for metabolite, coefficient in reaction.metabolites.items():
        if element.id not in not_to_change_list:
            # Set reaction bounds to zero
            reaction.bounds = 0.0, 0.0
            
            # Optimize the model
            solution = copy_of_model.slim_optimize()
            
            # Check if the solution is not zero
            if solution != 0.0:
                ex_list.append(reaction.id)
                
            # Print reaction information
            print(reaction.name)
            print(solution)

In [ ]:
# change bounds of the exchange reactions
for element in ex_list:
    reaction = copy_of_model.reactions.get_by_id(element)
    for metabolite, coefficient in reaction.metabolites.items():
        print(reaction.name)
        print(metabolite.name)
        print(metabolite.formula)
        reaction.bounds = -1000.0 , 1000.0

In [ ]:
# set reactions bounds for a specific reaction 
reaction = copy_of_model.reactions.get_by_id('EX_o2_e')
reaction.bounds = -10.0, 10.0

In [25]:
model1.exchanges

Could not identify an external compartment by name and choosing one with the most boundary reactions. That might be complete nonsense or change suddenly. Consider renaming your compartments using `Model.compartments` to fix this.
c:\Users\benammara\AppData\Local\Programs\Python\Python312\Lib\site-packages\cobra\medium\boundary_types.py:97: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return most[0]

[<Reaction EX_23camp_e at 0x25ff0d2f9e0>,
 <Reaction EX_23ccmp_e at 0x25ff0d2d940>,
 <Reaction EX_23cgmp_e at 0x25ff0d5c950>,
 <Reaction EX_23cump_e at 0x25ff0cb0bc0>,
 <Reaction EX_25dkglcn_e at 0x25ff0d5cce0>,
 <Reaction EX_2ddglcn_e at 0x25ff0cb1280>,
 <Reaction EX_2mbald_e at 0x25ff0c3ce90>,
 <Reaction EX_3ump_e at 0x25ff0d2f470>,
 <Reaction EX_4hoxpac_e at 0x25ff0d2cf80>,
 <Reaction EX_4hpro_LT_e at 0x25ff0d5cfe0>,
 <Reaction EX_5dglcn_e at 0x25ff0d5d010>,
 <Reaction EX_5drib_e at 0x25ff0d5d130>,
 <Reaction EX_5mcsn_e at 0x25ff0d5d220>,
 <Reaction EX_acald_e at 0x25ff0d5d2e0>,
 <Reaction EX_ad_e at 0x25ff0d5d4f0>,
 <Reaction EX_ala__D_e at 0x25ff0d5d370>,
 <Reaction EX_ala__L_e at 0x25ff0d5d640>,
 <Reaction EX_alaala_e at 0x25ff0d2c080>,
 <Reaction EX_alahis_e at 0x25ff0d5d670>,
 <Reaction EX_alaleu_e at 0x25ff0d5d3d0>,
 <Reaction EX_alathr_e at 0x25ff0d5d7f0>,
 <Reaction EX_alatrp_e at 0x25ff0d5d880>,
 <Reaction EX_amp_e at 0x25ff0cb1e80>,
 <Reaction EX_anhgm_e at 0x25ff084fe30>,
 <Reaction EX_arg__L_e at 0x25ff0d5da90>,
 <Reaction EX_asn__L_e at 0x25ff0cb3980>,
 <Reaction EX_asp__L_e at 0x25ff0d5da00>,
 <Reaction EX_bz_e at 0x25ff0d5dd90>,
 <Reaction EX_ca2_e at 0x25ff0d5dd30>,
 <Reaction EX_carn_e at 0x25ff0d5dd00>,
 <Reaction EX_cgly_e at 0x25ff0d2c470>,
 <Reaction EX_chol_e at 0x25ff0d2eba0>,
 <Reaction EX_chols_e at 0x25ff0d5ddf0>,
 <Reaction EX_cit_e at 0x25ff0d2c440>,
 <Reaction EX_cl_e at 0x25ff0d5e240>,
 <Reaction EX_cmp_e at 0x25ff0d5e0f0>,
 <Reaction EX_co2_e at 0x25ff0d5df10>,
 <Reaction EX_cobalt2_e at 0x25ff0d5dee0>,
 <Reaction EX_cu2_e at 0x25ff0ce8410>,
 <Reaction EX_cu_e at 0x25ff0d5e5d0>,
 <Reaction EX_cys__L_e at 0x25ff0d5e390>,
 <Reaction EX_cytd_e at 0x25ff0d2e870>,
 <Reaction EX_dextrin_e at 0x25ff0d5e000>,
 <Reaction EX_etha_e at 0x25ff0d5e6f0>,
 <Reaction EX_fe2_e at 0x25ff0d5e720>,
 <Reaction EX_fe3_e at 0x25ff0d2e7b0>,
 <Reaction EX_fe3pyovd_kt_e at 0x25ff0d5e8a0>,
 <Reaction EX_fol_e at 0x25ff0ce9af0>,
 <Reaction EX_g3pc_e at 0x25ff0d2e450>,
 <Reaction EX_g3pe_e at 0x25ff0c71a60>,
 <Reaction EX_g3pg_e at 0x25ff0d5e900>,
 <Reaction EX_g3pi_e at 0x25ff0d5ea20>,
 <Reaction EX_g3ps_e at 0x25ff0d5db80>,
 <Reaction EX_glc__D_e at 0x25ff0d2f710>,
 <Reaction EX_gln__L_e at 0x25ff0d5cf50>,
 <Reaction EX_glu__L_e at 0x25ff0d5ed80>,
 <Reaction EX_gly_e at 0x25ff0d5eea0>,
 <Reaction EX_glyb_e at 0x25ff0ce9f40>,
 <Reaction EX_glyc2p_e at 0x25ff0d5efc0>,
 <Reaction EX_glyc3p_e at 0x25ff0d2cc80>,
 <Reaction EX_glygln_e at 0x25ff0d5c410>,
 <Reaction EX_glyglu_e at 0x25ff0ce9e50>,
 <Reaction EX_glymet_e at 0x25ff0d5f230>,
 <Reaction EX_glyphe_e at 0x25ff0d5f2c0>,
 <Reaction EX_glyser_e at 0x25ff0d5f350>,
 <Reaction EX_gmp_e at 0x25ff0d5f410>,
 <Reaction EX_gsn_e at 0x25ff0ceab10>,
 <Reaction EX_gthrd_e at 0x25ff0d5ca40>,
 <Reaction EX_h2o2_e at 0x25ff0ce87a0>,
 <Reaction EX_h2o_e at 0x25ff0d5e1b0>,
 <Reaction EX_h2s_e at 0x25ff0d5f710>,
 <Reaction EX_h_e at 0x25ff0d5c710>,
 <Reaction EX_hexs_e at 0x25ff0d5f860>,
 <Reaction EX_his__L_e at 0x25ff0d5f650>,
 <Reaction EX_hisgly_e at 0x25ff0d5f8c0>,
 <Reaction EX_hishis_e at 0x25ff0cb1b20>,
 <Reaction EX_ibtol_e at 0x25ff0d2fad0>,
 <Reaction EX_ile__L_e at 0x25ff0cb2ff0>,
 <Reaction EX_ind3ac_e at 0x25ff0d5fb00>,
 <Reaction EX_inost_e at 0x25ff0c3c890>,
 <Reaction EX_k_e at 0x25ff0d5fda0>,
 <Reaction EX_leu__L_e at 0x25ff0d5fd10>,
 <Reaction EX_leuleu_e at 0x25ff0d5ff20>,
 <Reaction EX_lys__L_e at 0x25ff0d5fe00>,
 <Reaction EX_malt_e at 0x25ff0d5ff80>,
 <Reaction EX_malthx_e at 0x25ff0cb1610>,
 <Reaction EX_man1p_e at 0x25ff0d5ff50>,
 <Reaction EX_meoh_e at 0x25ff0d5fe60>,
 <Reaction EX_met__L_e at 0x25ff0da8230>,
 <Reaction EX_mg2_e at 0x25ff0da82f0>,
 <Reaction EX_mn2_e at 0x25ff0ce9430>,
 <Reaction EX_mobd_e at 0x25ff0da8470>,
 <Reaction EX_nh4_e at 0x25ff0d2c920>,
 <Reaction EX_nmn_e at 0x25ff0da80b0>,
 <Reaction EX_no_e at 0x25ff0da87d0>,
 <Reaction EX_o2_e at 0x25ff0da8860>,
 <Reaction EX_orn_e at 0x25ff0d5ce00>,
 <Reaction EX_pacald_e at 0x25ff0cb0650>,
 <Reaction EX_peamn_e at 0x25ff0d5cb60>,
 <Reaction EX_phe__L_e at 0x25ff0cb1700>,
 <Reaction EX_pheme_e at 0x25ff0d5cd10>,
 <Reaction EX_pi_e at 0x25ff0cea450>,
 <Reaction EX_ppap_e at 0x25ff0da8b30>,
 <Reaction EX_ppoh_e at 0x25ff0da8ce0>,
 <Reaction EX_ppt_e at 0x25ff0da89b0>,
 <Reaction EX_pro__L_e at 0x25ff0d5fa70>,
 <Reaction EX_progly_e at 0x25ff0da8a70>,
 <Reaction EX_pser__D_e at 0x25ff0d5d070>,
 <Reaction EX_pser__L_e at 0x25ff0ce90a0>,
 <Reaction EX_ptrc_e at 0x25ff0d5cec0>,
 <Reaction EX_pydam_e at 0x25ff0d5e930>,
 <Reaction EX_pyovd_kt_e at 0x25ff0d5fad0>,
 <Reaction EX_r5p_e at 0x25ff0da8f50>,
 <Reaction EX_rib__D_e at 0x25ff0ce9400>,
 <Reaction EX_rnam_e at 0x25ff0d5eba0>,
 <Reaction EX_s_e at 0x25ff0da9460>,
 <Reaction EX_salc_e at 0x25ff0da93a0>,
 <Reaction EX_sel_e at 0x25ff0cea810>,
 <Reaction EX_ser__L_e at 0x25ff0da9400>,
 <Reaction EX_slnt_e at 0x25ff0d5d820>,
 <Reaction EX_so4_e at 0x25ff0d2f530>,
 <Reaction EX_spmd_e at 0x25ff0d5ede0>,
 <Reaction EX_starch_e at 0x25ff0d5edb0>,
 <Reaction EX_sucr_e at 0x25ff0da95b0>,
 <Reaction EX_tartr__D_e at 0x25ff0da9640>,
 <Reaction EX_taur_e at 0x25ff0da9910>,
 <Reaction EX_thm_e at 0x25ff0d5f440>,
 <Reaction EX_thr__L_e at 0x25ff0d5cef0>,
 <Reaction EX_thrp_e at 0x25ff0d5eb70>,
 <Reaction EX_tol_e at 0x25ff0d5cb30>,
 <Reaction EX_trp__L_e at 0x25ff0d5eff0>,
 <Reaction EX_tsul_e at 0x25ff0cb2990>,
 <Reaction EX_tyr__L_e at 0x25ff0d5ef30>,
 <Reaction EX_udpg_e at 0x25ff0cebd10>,
 <Reaction EX_urate_e at 0x25ff0da9df0>,
 <Reaction EX_urea_e at 0x25ff0d5dac0>,
 <Reaction EX_uri_e at 0x25ff0d5ddc0>,
 <Reaction EX_val__L_e at 0x25ff0d5e960>,
 <Reaction EX_zn2_e at 0x25ff0da9f40>,
 <Reaction EX_glcn_e at 0x25ff0daae70>,
 <Reaction EX_no3_e at 0x25ff0d5e9c0>,
 <Reaction EX_succ_e at 0x25ff0d5e570>,
 <Reaction EX_Ni2_e at 0x25ff0dab920>,
 <Reaction EX_etoh_e at 0x25ff0daa720>,
 <Reaction EX_n2_e at 0x25ff0e3c9e0>,
 <Reaction EX_no2_e at 0x25ff0da9100>]

## Biomass Equation Curation

Updating the coefficient and adding metabolites from the Solar Food Biomass Equation

In [14]:
file_path = 'C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Biomass_equation.xlsx'
# Read Excel files into DataFrames
pd_biomass = pd.read_excel(file_path)
pd_biomass

,Biomass_equation,Unnamed: 1,molar mass g/mol,measured mmol/g,Unmeasured mmol/g,unmeasured g/g,measured g/g,GAM,normalized g/g,normalized_mmol/g
0,10fthf_c,10-Formyltetrahydrofolate,471.43007,NaN,-0.000223,-0.000105,NaN,NaN,0.000000,-0.000223
1,pydx5p_c,Pyridoxal 5'-phosphate,245.12862,NaN,-0.000223,-0.000055,NaN,NaN,0.000000,-0.000223
2,murein3px4p_p,"Two disacharide linked murein units, tripeptid...",1750.69809,NaN,-0.000605,-0.001059,NaN,NaN,0.000000,-0.000605
3,thr__L_c,L-Threonine,119.12063,-0.381786,NaN,0.000000,-0.045479,NaN,-0.039411,-0.330852
4,adocbl_c,Adenosylcobalamin,1579.60636,NaN,-0.000223,-0.000352,NaN,NaN,0.000000,-0.000223
...,...,...,...,...,...,...,...,...,...,...
124,tmndnc_c,"Timnodonic acid C20:5, n-3",302.50000,-0.000044,NaN,0.000000,-0.000013,NaN,-0.000011,-0.000038
125,doco13ac_c,13Z)-13-docosenoic acid,338.60000,-0.000077,NaN,0.000000,-0.000026,NaN,-0.000023,-0.000067
126,ttc_c,Tetracosanoate n C240 C24H47O2,368.60000,-0.000035,NaN,0.000000,-0.000013,NaN,-0.000011,-0.000030
127,lnlc_c,Linoleic acid (all cis C18:2) n-6,280.40000,-0.000222,NaN,0.000000,-0.000062,NaN,-0.000054,-0.000193
128,lnlncg_c,Gamma-linolenic acid,278.40000,-0.000968,NaN,0.000000,-0.000269,NaN,-0.000233,-0.000838

In [74]:
copy_of_model.summary()

Change the coeff from the excel file of the already exisiting metabolite of the growth equation

In [75]:
i = 0
reaction = copy_of_model.reactions.get_by_id('Growth')
for element in pd_biomass.Biomass_equation:
    found = False
    for metabolite, coefficient in reaction.metabolites.items():
        if element == metabolite.id:
            found = True
            # Get the value of the 'normalized_mmol/g' column for the current metabolite
            normalized_mmol_g = pd_biomass.loc[pd_biomass['Biomass_equation'] == element, 'normalized_mmol/g'].values[0]
            print(f'The metabolite from the solar food BE = {element} coefficient {normalized_mmol_g}')
            print(f'The metabolite from the model = {metabolite.id} coefficient {coefficient}')
            initial_coefficient = coefficient
            # Update the coefficient of the metabolite in the reaction
            reaction.add_metabolites({metabolite: normalized_mmol_g}, combine=False)
            print(f'The coefficient was updated {initial_coefficient} ------> {coefficient}')
            i += 1
            solution = copy_of_model.slim_optimize()
            print(solution)
    if not found:
        pass
print(i)

The metabolite from the solar food BE = 10fthf_c coefficient -0.000223
The metabolite from the model = 10fthf_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.13262155367579156
The metabolite from the solar food BE = pydx5p_c coefficient -0.000223
The metabolite from the model = pydx5p_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.13262155367579292
The metabolite from the solar food BE = thr__L_c coefficient -0.33085175798343425
The metabolite from the model = thr__L_c coefficient -0.253687
The coefficient was updated -0.253687 ------> -0.253687
0.13197999728641752
The metabolite from the solar food BE = h_c coefficient 29.1804227450256
The metabolite from the model = h_c coefficient 53.95
The coefficient was updated 53.95 ------> 53.95
0.15206920580980376
The metabolite from the solar food BE = thmpp_c coefficient -0.000223
The metabolite from the model = thmpp_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.15206920580980415
The metabolite from the solar food BE = mn2_c coefficient -0.000658
The metabolite from the model = mn2_c coefficient -0.000691
The coefficient was updated -0.000691 ------> -0.000691
0.15206921534888487
The metabolite from the solar food BE = sheme_c coefficient -0.000223
The metabolite from the model = sheme_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.15206921534888487
The metabolite from the solar food BE = ser__L_c coefficient -0.29855906692147155
The metabolite from the model = ser__L_c coefficient -0.215792
The coefficient was updated -0.215792 ------> -0.215792
0.15168737808408336
The metabolite from the solar food BE = ctp_c coefficient -0.010737250405651103
The metabolite from the model = ctp_c coefficient -0.133508
The coefficient was updated -0.133508 ------> -0.133508
0.15504391983341426
The metabolite from the solar food BE = arg__L_c coefficient -0.2557979323259868
The metabolite from the model = arg__L_c coefficient -0.295792
The coefficient was updated -0.295792 ------> -0.295792
0.15567136010991156
The metabolite from the solar food BE = asp__L_c coefficient -0.2529593526847482
The metabolite from the model = asp__L_c coefficient -0.241055
The coefficient was updated -0.241055 ------> -0.241055
0.155599272259571
The metabolite from the solar food BE = nad_c coefficient -0.001787
The metabolite from the model = nad_c coefficient -0.001831
The coefficient was updated -0.001831 ------> -0.001831
0.15560193552985013
The metabolite from the solar food BE = mg2_c coefficient -0.008253
The metabolite from the model = mg2_c coefficient -0.008675
The coefficient was updated -0.008675 ------> -0.008675
0.15560193552985013
The metabolite from the solar food BE = adp_c coefficient 29.1804227450256
The metabolite from the model = adp_c coefficient 53.95
The coefficient was updated 53.95 ------> 53.95
0.0201943321250827
The metabolite from the solar food BE = met__L_c coefficient -0.14267468516500864
The metabolite from the model = met__L_c coefficient -0.153686
The coefficient was updated -0.153686 ------> -0.153686
0.020194949592642713
The metabolite from the solar food BE = pi_c coefficient 29.1804227450256
The metabolite from the model = pi_c coefficient 53.945662
The coefficient was updated 53.945662 ------> 53.945662
0.02006948202508115
The metabolite from the solar food BE = zn2_c coefficient -0.000324
The metabolite from the model = zn2_c coefficient -0.000341
The coefficient was updated -0.000341 ------> -0.000341
0.02006948202508123
The metabolite from the solar food BE = tyr__L_c coefficient -0.1593258444308896
The metabolite from the model = tyr__L_c coefficient -0.137896
The coefficient was updated -0.137896 ------> -0.137896
0.020060207342310357
The metabolite from the solar food BE = cys__L_c coefficient -0.037472225353906465
The metabolite from the model = cys__L_c coefficient -0.09158
The coefficient was updated -0.09158 ------> -0.09158
0.020058846583784446
The metabolite from the solar food BE = amet_c coefficient -0.000223
The metabolite from the model = amet_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.020058846583784446
The metabolite from the solar food BE = trp__L_c coefficient -0.08097676930208217
The metabolite from the model = trp__L_c coefficient -0.056843
The coefficient was updated -0.056843 ------> -0.056843
0.020044776381812335
The metabolite from the solar food BE = lys__L_c coefficient -0.25760196352578224
The metabolite from the model = lys__L_c coefficient -0.343161
The coefficient was updated -0.343161 ------> -0.343161
0.020068007768517984
The metabolite from the solar food BE = atp_c coefficient -29.190681913288
The metabolite from the model = atp_c coefficient -54.124831
The coefficient was updated -54.124831 ------> -54.124831
0.16994897661641545
The metabolite from the solar food BE = thf_c coefficient -0.000223
The metabolite from the model = thf_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.16994897661642008
The metabolite from the solar food BE = dttp_c coefficient -0.013367475433835764
The metabolite from the model = dttp_c coefficient -0.026166
The coefficient was updated -0.026166 ------> -0.026166
0.1703983689308043
The metabolite from the solar food BE = dctp_c coefficient -0.0154992827580827
The metabolite from the model = dctp_c coefficient -0.027017
The coefficient was updated -0.027017 ------> -0.027017
0.17083003041707773
The metabolite from the solar food BE = cobalt2_c coefficient -2.4e-05
The metabolite from the model = cobalt2_c coefficient -0.0001
The coefficient was updated -0.0001 ------> -0.0001
0.17083014131216245
The metabolite from the solar food BE = utp_c coefficient -0.006775403427840368
The metabolite from the model = utp_c coefficient -0.144104
The coefficient was updated -0.144104 ------> -0.144104
1.0412895428846828e-13
The metabolite from the solar food BE = k_c coefficient -0.18569
The metabolite from the model = k_c coefficient -0.195193
The coefficient was updated -0.195193 ------> -0.195193
-5.346479051004205e-30
The metabolite from the solar food BE = fe2_c coefficient -0.006388
The metabolite from the model = fe2_c coefficient -0.006715
The coefficient was updated -0.006715 ------> -0.006715
2.234961245107898e-31
The metabolite from the solar food BE = datp_c coefficient -0.014832979735072188
The metabolite from the model = datp_c coefficient -0.026166
The coefficient was updated -0.026166 ------> -0.026166
1.4935762549045509e-29
The metabolite from the solar food BE = ppi_c coefficient 0.110381072928369
The metabolite from the model = ppi_c coefficient 0.773903
The coefficient was updated 0.773903 ------> 0.773903
0.17706309859122285
The metabolite from the solar food BE = nadp_c coefficient -0.000112
The metabolite from the model = nadp_c coefficient -0.000447
The coefficient was updated -0.000447 ------> -0.000447
0.1770952689514375
The metabolite from the solar food BE = glu__L_c coefficient -0.275320637946572
The metabolite from the model = glu__L_c coefficient -0.26316
The coefficient was updated -0.26316 ------> -0.26316
0.1768477114341521
The metabolite from the solar food BE = ile__L_c coefficient -0.24506430675451657
The metabolite from the model = ile__L_c coefficient -0.290529
The coefficient was updated -0.290529 ------> -0.290529
0.17766910912692274
The metabolite from the solar food BE = gln__L_c coefficient -0.2753206379465721
The metabolite from the model = gln__L_c coefficient -0.26316
The coefficient was updated -0.26316 ------> -0.26316
0.17740080835773828
The metabolite from the solar food BE = fe3_c coefficient -0.007428
The metabolite from the model = fe3_c coefficient -0.007808
The coefficient was updated -0.007808 ------> -0.007808
0.17740021040986642
The metabolite from the solar food BE = ala__L_c coefficient -0.8168723181883314
The metabolite from the model = ala__L_c coefficient -0.513689
The coefficient was updated -0.513689 ------> -0.513689
0.17435251880179636
The metabolite from the solar food BE = phe__L_c coefficient -0.22846254459317583
The metabolite from the model = phe__L_c coefficient -0.185265
The coefficient was updated -0.185265 ------> -0.185265
0.1729522162403303
The metabolite from the solar food BE = mlthf_c coefficient -0.000223
The metabolite from the model = mlthf_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.1729522162403303
The metabolite from the solar food BE = cu2_c coefficient -0.006744
The metabolite from the model = cu2_c coefficient -0.000709
The coefficient was updated -0.000709 ------> -0.000709
0.17294319062381158
The metabolite from the solar food BE = h2o_c coefficient -29.1804227450256
The metabolite from the model = h2o_c coefficient -48.601527
The coefficient was updated -48.601527 ------> -48.601527
0.17294319062380323
The metabolite from the solar food BE = ca2_c coefficient -0.004952
The metabolite from the model = ca2_c coefficient -0.005205
The coefficient was updated -0.005205 ------> -0.005205
0.17294356897787255
The metabolite from the solar food BE = gly_c coefficient -0.6379660350235106
The metabolite from the model = gly_c coefficient -0.612638
The coefficient was updated -0.612638 ------> -0.612638
0.1727732884324298
The metabolite from the solar food BE = mql8_c coefficient -0.000223
The metabolite from the model = mql8_c coefficient -0.0001
The coefficient was updated -0.0001 ------> -0.0001
0.17275438163326148
The metabolite from the solar food BE = cl_c coefficient -0.004952
The metabolite from the model = cl_c coefficient -0.005205
The coefficient was updated -0.005205 ------> -0.005205
0.17275438163326148
The metabolite from the solar food BE = his__L_c coefficient -0.09352200626083922
The metabolite from the model = his__L_c coefficient -0.094738
The coefficient was updated -0.094738 ------> -0.094738
0.172797033157721
The metabolite from the solar food BE = ribflv_c coefficient -0.000223
The metabolite from the model = ribflv_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.172797033157721
The metabolite from the solar food BE = so4_c coefficient -0.004126
The metabolite from the model = so4_c coefficient -0.004338
The coefficient was updated -0.004338 ------> -0.004338
0.17279711228361308
The metabolite from the solar food BE = gtp_c coefficient -0.01659016153669234
The metabolite from the model = gtp_c coefficient -0.215096
The coefficient was updated -0.215096 ------> -0.215096
0.183915919864884
The metabolite from the solar food BE = pheme_c coefficient -0.000223
The metabolite from the model = pheme_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.183915919864884
The metabolite from the solar food BE = val__L_c coefficient -0.4108677675755479
The metabolite from the model = val__L_c coefficient -0.423162
The coefficient was updated -0.423162 ------> -0.423162
0.1840928274853937
The metabolite from the solar food BE = pro__L_c coefficient -0.28911581930944585
The metabolite from the model = pro__L_c coefficient -0.221055
The coefficient was updated -0.221055 ------> -0.221055
0.18277602356677583
The metabolite from the solar food BE = coa_c coefficient -0.000168
The metabolite from the model = coa_c coefficient -0.000576
The coefficient was updated -0.000576 ------> -0.000576
0.18281317310168876
The metabolite from the solar food BE = asn__L_c coefficient -0.2529593526847482
The metabolite from the model = asn__L_c coefficient -0.241055
The coefficient was updated -0.241055 ------> -0.241055
0.18257477362757304
The metabolite from the solar food BE = leu__L_c coefficient -0.4809387020057383
The metabolite from the model = leu__L_c coefficient -0.450531
The coefficient was updated -0.450531 ------> -0.450531
0.18199381014711513
The metabolite from the solar food BE = dgtp_c coefficient -0.02400546922059191
The metabolite from the model = dgtp_c coefficient -0.027017
The coefficient was updated -0.027017 ------> -0.027017
0.18216978450687443
The metabolite from the solar food BE = fad_c coefficient -0.000223
The metabolite from the model = fad_c coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.18216978450687443
The metabolite from the solar food BE = pe160_p coefficient -0.044164
The metabolite from the model = pe160_p coefficient -0.045946
The coefficient was updated -0.045946 ------> -0.045946
0.1823258923993216
59

Compare the coeff of the excel to the one in the model

In [15]:
i=0
reaction = model1.reactions.get_by_id('BIOMASS_KT2440_WT3')
for element in pd_biomass.Biomass_equation:
    for metabolite, coefficient in reaction.metabolites.items():
        if element == metabolite.id:
            print(element)
            normalized_mmol_g = pd_biomass.loc[pd_biomass['Biomass_equation'] == element, 'normalized_mmol/g'].values[0]
            print(normalized_mmol_g)
            print(coefficient)
            i+=1
print(i)

10fthf_c
-0.000223
-0.000223
pydx5p_c
-0.000223
-0.000223
murein3px4p_p
-0.000605
-0.000326
thr__L_c
-0.33085175798343425
-0.256324
adocbl_c
-0.000223
-0.000223
h_c
29.1804227450256
46.7502
gthrd_c
-0.000223
-0.000223
thmpp_c
-0.000223
-0.000223
ni2_c
-0.000307
-0.002817
mn2_c
-0.000658
-0.002817
sheme_c
-0.000223
-0.000223
ser__L_c
-0.29855906692147155
-0.301274
ctp_c
-0.010737250405651103
-0.159783
accoa_c
-0.000279
-0.000279
arg__L_c
-0.2557979323259868
-0.354251
asp__L_c
-0.2529593526847482
-0.284685
5mthf_c
-0.000223
-0.000223
nad_c
-0.001787
-0.001786
mg2_c
-0.008253
-0.007044
adp_c
29.1804227450256
46.7502
met__L_c
-0.14267468516500864
-0.122008
nh4_c
-0.012379
-0.010567
pi_c
29.1804227450256
46.746677
chor_c
-0.000223
-0.000223
zn2_c
-0.000324
-0.002817
q8h2_c
-0.000223
-0.000223
tyr__L_c
-0.1593258444308896
-0.135921
cys__L_c
-0.037472225353906465
-0.055652
amet_c
-0.000223
-0.000223
trp__L_c
-0.08097676930208217
-0.077592
lys__L_c
-0.25760196352578224
-0.180336
atp_c
-29.190681913288
-46.918883
thf_c
-0.000223
-0.000223
dttp_c
-0.013367475433835764
-0.010854
dctp_c
-0.0154992827580827
-0.01721
cobalt2_c
-2.4e-05
-0.002817
utp_c
-0.006775403427840368
-0.143215
k_c
-0.18569
-0.158509
fe2_c
-0.006388
-0.00634
datp_c
-0.014832979735072188
-0.010804
ppi_c
0.110381072928369
0.73868
nadp_c
-0.000112
-0.000111
glu__L_c
-0.275320637946572
-0.301809
ile__L_c
-0.24506430675451657
-0.244551
hemeO_c
-0.000223
-0.000223
murein4p4p_p
-0.005381
-0.007917
gln__L_c
-0.2753206379465721
-0.251507
fe3_c
-0.007428
-0.00634
ala__L_c
-0.8168723181883314
-0.598267
phe__L_c
-0.22846254459317583
-0.191038
mlthf_c
-0.000223
-0.000223
cu2_c
-0.006744
-0.002817
h2o_c
-29.1804227450256
-41.397362
ca2_c
-0.004952
-0.004226
gly_c
-0.6379660350235106
-0.431309
malcoa_c
-3.1e-05
-3.1e-05
murein4px4p_p
-0.005448
-0.002941
cl_c
-0.004952
-0.004226
his__L_c
-0.09352200626083922
-0.126289
2fe2s_c
-2.5e-05
-0.000223
ribflv_c
-0.000223
-0.000223
so4_c
-0.004126
-0.003522
ptrc_c
-0.03327
-0.03327
gtp_c
-0.01659016153669234
-0.210704
pheme_c
-0.000223
-0.000223
nadph_c
-0.000335
-0.000335
val__L_c
-0.4108677675755479
-0.389034
pro__L_c
-0.28911581930944585
-0.26328
mobd_c
-7e-06
-0.002817
4fe4s_c
-0.000248
-0.000223
nadh_c
-4.5e-05
-4.4e-05
coa_c
-0.000168
-0.000167
asn__L_c
-0.2529593526847482
-0.158931
leu__L_c
-0.4809387020057383
-0.628769
murein4px4px4p_p
-0.000673
-6.6e-05
dgtp_c
-0.02400546922059191
-0.017423
fad_c
-0.000223
-0.000223
succoa_c
-9.8e-05
-9.8e-05
clpn161_p
-0.00229
-0.002873
clpn160_p
-0.002944
-0.000578
clpn181_p
-0.00118
-0.001309
81

Create a dict to see which metabolite are not in the biomass equation

In [16]:
metabolite_not_found = {}
i = 0
reaction = model1.reactions.get_by_id('BIOMASS_KT2440_WT3')
for element in pd_biomass.Biomass_equation:
    found = False
    for metabolite, coefficient in reaction.metabolites.items():
        if element == metabolite.id:
            found = True
    if not found:
        normalized_mmol_g = pd_biomass.loc[pd_biomass['Biomass_equation'] == element, 'normalized_mmol/g'].values[0]
        print(f'{element:<15}  {normalized_mmol_g:>25}')
        metabolite_not_found[element] = normalized_mmol_g
        i+=1
print(i)

murein4p3p_p                     -0.001345
spmd_c                           -0.006744
mococdp_c                           -7e-06
2dmmql8_c                        -0.000223
mql8_c                           -0.000223
btn_c              -1.1414549099588767e-07
enter_c                          -0.000223
rmn_c                 -0.12458295393473183
arab__L_c             -0.03001579312991268
gal__L_c             -0.005772139750897219
glc__D_c              -0.11736684160157697
fru_c                  -0.6445556055168562
xyl__D_c             -0.005772267909598585
man_c                -0.004810116459081017
galam_c              -0.004836694654618716
gam_c                -0.004836694654618716
retinol_c           -9.074246924272647e-09
avite1_c           -3.0180772507593555e-06
vitd3_c             -5.633064100806269e-10
vitd2_c             -5.462623432098053e-10
thm_c              -1.3154306833538052e-05
rbflvrd_c            -5.42885385395863e-05
pydxn_c             -6.433607814591869e-05
chol_c              -0.0013841118723877054
fol_c              -2.1226953703375583e-05
nac_c               -0.0005023142220720257
pnto__R_c           -8.609379583094386e-05
phllqne_c          -1.9227658781185626e-09
caro_c              -3.993838208771886e-05
pe160_p                          -0.044164
pg160_p                          -0.010599
colipa_e                         -0.008151
pe181_p                          -0.017704
pg161_p                          -0.008244
ttdca_c             -0.0005942465517650057
hexadecacid_c        -0.049934570136758984
hexedecacid_c        -0.007033277906537638
hpdca_c             -0.0002921739778619036
octadecacid_c        -0.007173968847108888
octedecacid_c         -0.13197873979176503
lnlc_c               -0.005902952960848603
lnlncg_c            -0.0003641921623863511
arach_c             -7.320957230552366e-05
tmndnc_c            -3.781486172805971e-05
doco13ac_c          -6.705455767638082e-05
ttc_c              -3.0093216061396738e-05
lnlc_c               -0.005902952960848603
lnlncg_c            -0.0003641921623863511
48

In [60]:
copy_of_model = model.copy()

In [61]:
new_metabolite = Metabolite(
    id='vitd2_c',     # Metabolite ID
    name='Vitamin D2; ergocalciferol',     # Metabolite Name
    formula='C28H44O',         # Chemical Formula
    compartment='c'            # Compartment (e.g., cytoplasm)
)

new_metabolite.charge = 0

copy_of_model.add_metabolites([new_metabolite])

print(new_metabolite.formula)

C28H44O

In [ ]:
reaction = copy_of_model.reactions.get_by_id('Growth')
metabolite_to_add = 'adocbl_c'
reaction.add_metabolites({metabolite_to_add: -0.000223})
copy_of_model.slim_optimize()

Create a dict with the metabolite that are only in the model biomass equation

In [18]:
model_BE_metabolite = {}

# Get the 'Growth' reaction
reaction = model1.reactions.get_by_id('BIOMASS_KT2440_WT3')

# Iterate over metabolites in the 'Growth' reaction
for metabolite, coefficient in reaction.metabolites.items():
    # Check if the metabolite ID is not in the 'Biomass_equation' column
    if metabolite.id not in pd_biomass['Biomass_equation'].values:
        # Add the metabolite ID and its coefficient to the dictionary
        model_BE_metabolite[metabolite.id] = coefficient

model_BE_metabolite

{'bmocogdp_c': -0.000223,
 'btamp_c': -0.000223,
 'clpn140_p': -1.8e-05,
 'clpn180_p': -0.000192,
 'cpe160_c': -0.00041,
 'cpg160_c': -0.000226,
 'lipopb_c': -0.000223,
 'lpspput_e': -0.008696,
 'mocogdp_c': -0.000223,
 'murein3p3p_p': -0.001979,
 'na1_c': -0.003522,
 'pe140_c': -0.000251,
 'pe160_c': -0.007882,
 'pe161_c': -0.039155,
 'pe180_c': -0.002622,
 'pe181_c': -0.017845,
 'pg140_c': -0.000138,
 'pg160_c': -0.004354,
 'pg161_c': -0.021632,
 'pg180_c': -0.001449,
 'pg181_c': -0.009859,
 'pqqh2_c': -0.000223,
 'pyovd_kt_e': -0.000223,
 'thmnp_c': -0.000223,
 'udcpdp_c': -5.5e-05}

In [11]:
reaction_id_to_check = 'Growth'
reaction = copy_of_model.reactions.get_by_id(reaction_id_to_check)
print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")
sum = 0
#reaction.name = '(S)-2-Acetolactate pyruvate-lyase (carboxylating)'
print("\nMetabolites and Stoichiometry:")
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id:<15}: {coefficient:>25}  Name: {metabolite.name:<60}  Charge: {metabolite.charge:>3}  Formula: {metabolite.formula}")
    sum += coefficient * metabolite.charge
print(f'\nSum charge: {sum}')
print("\nAssociated Genes:")
for gene in reaction.genes:
    print(gene.id)

Reaction ID: Growth
Name: Biomass reaction
Equation: 0.000223 10fthf_c + 0.513689 ala__L_c + 0.000223 amet_c + 0.295792 arg__L_c + 0.241055 asn__L_c + 0.241055 asp__L_c + 54.124831 atp_c + 0.005205 ca2_c + 0.005205 cl_c + 0.000576 coa_c + 0.0001 cobalt2_c + 0.133508 ctp_c + 0.000709 cu2_c + 0.09158 cys__L_c + 0.026166 datp_c + 0.027017 dctp_c + 0.027017 dgtp_c + 0.026166 dttp_c + 0.000223 fad_c + 0.006715 fe2_c + 0.007808 fe3_c + 0.26316 gln__L_c + 0.26316 glu__L_c + 0.612638 gly_c + 0.215096 gtp_c + 48.601527 h2o_c + 0.094738 his__L_c + 0.290529 ile__L_c + 0.195193 k_c + 0.019456 kdo2lipid4_p + 0.450531 leu__L_c + 0.343161 lys__L_c + 0.153686 met__L_c + 0.008675 mg2_c + 0.000223 mlthf_c + 0.000691 mn2_c + 0.0001 mql8_c + 0.013894 murein5px4p_p + 0.001831 nad_c + 0.000447 nadp_c + 0.017868 pe160_c + 0.045946 pe160_p + 0.054154 pe161_c + 0.02106 pe161_p + 0.185265 phe__L_c + 0.000223 pheme_c + 0.221055 pro__L_c + 0.000223 pydx5p_c + 0.000223 ribflv_c + 0.215792 ser__L_c + 0.000223 sheme_c + 0.004338 so4_c + 0.000223 thf_c + 0.000223 thmpp_c + 0.253687 thr__L_c + 0.056843 trp__L_c + 0.137896 tyr__L_c + 0.144104 utp_c + 0.423162 val__L_c + 0.000341 zn2_c --> 53.95 adp_c + 53.95 h_c + 53.945662 pi_c + 0.773903 ppi_c
Lower Bound: 0.0
Upper Bound: 1000.0

Metabolites and Stoichiometry:
10fthf_c       :                 -0.000223  Name: 10-Formyltetrahydrofolate                                     Charge:  -2  Formula: C20H21N7O7
ala__L_c       :                 -0.513689  Name: L-Alanine                                                     Charge:   0  Formula: C3H7NO2
amet_c         :                 -0.000223  Name: S-Adenosyl-L-methionine                                       Charge:   1  Formula: C15H23N6O5S
arg__L_c       :                 -0.295792  Name: L-Arginine                                                    Charge:   1  Formula: C6H15N4O2
asn__L_c       :                 -0.241055  Name: L-Asparagine                                                  Charge:   0  Formula: C4H8N2O3
asp__L_c       :                 -0.241055  Name: L-Aspartate                                                   Charge:  -1  Formula: C4H6NO4
atp_c          :                -54.124831  Name: ATP C10H12N5O13P3                                             Charge:  -4  Formula: C10H12N5O13P3
ca2_c          :                 -0.005205  Name: Calcium                                                       Charge:   2  Formula: Ca
cl_c           :                 -0.005205  Name: Chloride                                                      Charge:  -1  Formula: Cl
coa_c          :                 -0.000576  Name: Coenzyme A                                                    Charge:  -4  Formula: C21H32N7O16P3S
cobalt2_c      :                   -0.0001  Name: Co2+                                                          Charge:   2  Formula: Co
ctp_c          :                 -0.133508  Name: CTP C9H12N3O14P3                                              Charge:  -4  Formula: C9H12N3O14P3
cu2_c          :                 -0.000709  Name: Copper                                                        Charge:   2  Formula: Cu
cys__L_c       :                  -0.09158  Name: L-Cysteine                                                    Charge:   0  Formula: C3H7NO2S
datp_c         :                 -0.026166  Name: DATP C10H12N5O12P3                                            Charge:  -4  Formula: C10H12N5O12P3
dctp_c         :                 -0.027017  Name: DCTP C9H12N3O13P3                                             Charge:  -4  Formula: C9H12N3O13P3
dgtp_c         :                 -0.027017  Name: DGTP C10H12N5O13P3                                            Charge:  -4  Formula: C10H12N5O13P3
dttp_c         :                 -0.026166  Name: DTTP C10H13N2O14P3                                            Charge:  -4  Formula: C10H13N2O14P3
fad_c          :                 -0.000223  Name: Flavin adenine dinucleotide oxidized                          Charge:  -2  Formula: C27H31N9O15P2
fe2_c          :                 -0.006715  Name: Fe2+ mitochondria                                             Charge:   2  Formula: Fe
fe3_c          :                 -0.007808  Name: Iron (Fe3+)                                                   Charge:   3  Formula: Fe
gln__L_c       :                  -0.26316  Name: L-Glutamine                                                   Charge:   0  Formula: C5H10N2O3
glu__L_c       :                  -0.26316  Name: L-Glutamate                                                   Charge:  -1  Formula: C5H8NO4
gly_c          :                 -0.612638  Name: Glycine                                                       Charge:   0  Formula: C2H5NO2
gtp_c          :                 -0.215096  Name: GTP C10H12N5O14P3                                             Charge:  -4  Formula: C10H12N5O14P3
h2o_c          :                -48.601527  Name: H2O H2O                                                       Charge:   0  Formula: H2O
his__L_c       :                 -0.094738  Name: L-Histidine                                                   Charge:   0  Formula: C6H9N3O2
ile__L_c       :                 -0.290529  Name: L-Isoleucine                                                  Charge:   0  Formula: C6H13NO2
k_c            :                 -0.195193  Name: Potassium                                                     Charge:   1  Formula: K
kdo2lipid4_p   :                 -0.019456  Name: KDO(2)-lipid IV(A)                                            Charge:  -6  Formula: C84H148N2O37P2
leu__L_c       :                 -0.450531  Name: L-Leucine                                                     Charge:   0  Formula: C6H13NO2
lys__L_c       :                 -0.343161  Name: L-Lysine                                                      Charge:   1  Formula: C6H15N2O2
met__L_c       :                 -0.153686  Name: L-Methionine                                                  Charge:   0  Formula: C5H11NO2S
mg2_c          :                 -0.008675  Name: Magnesium                                                     Charge:   2  Formula: Mg
mlthf_c        :                 -0.000223  Name: 5,10-Methylenetetrahydrofolate                                Charge:  -2  Formula: C20H21N7O6
mn2_c          :                 -0.000691  Name: Manganese                                                     Charge:   2  Formula: Mn
mql8_c         :                   -0.0001  Name: Menaquinol 8                                                  Charge:   0  Formula: C51H74O2
murein5px4p_p  :                 -0.013894  Name: Two disacharide linked murein units, pentapeptide crosslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C77H117N15O40
nad_c          :                 -0.001831  Name: Nicotinamide adenine dinucleotide                             Charge:  -1  Formula: C21H26N7O14P2
nadp_c         :                 -0.000447  Name: Nicotinamide adenine dinucleotide phosphate                   Charge:  -3  Formula: C21H25N7O17P3
pe160_c        :                 -0.017868  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pe160_p        :                 -0.045946  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pe161_c        :                 -0.054154  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70NO8P
pe161_p        :                  -0.02106  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70NO8P
phe__L_c       :                 -0.185265  Name: L-Phenylalanine                                               Charge:   0  Formula: C9H11NO2
pheme_c        :                 -0.000223  Name: Protoheme C34H30FeN4O4                                        Charge:  -2  Formula: C34H30FeN4O4
pro__L_c       :                 -0.221055  Name: L-Proline                                                     Charge:   0  Formula: C5H9NO2
pydx5p_c       :                 -0.000223  Name: Pyridoxal 5'-phosphate                                        Charge:  -2  Formula: C8H8NO6P
ribflv_c       :                 -0.000223  Name: Riboflavin C17H20N4O6                                         Charge:   0  Formula: C17H20N4O6
ser__L_c       :                 -0.215792  Name: L-Serine                                                      Charge:   0  Formula: C3H7NO3
sheme_c        :                 -0.000223  Name: Siroheme C42H36FeN4O16                                        Charge:  -8  Formula: C42H36FeN4O16
so4_c          :                 -0.004338  Name: Sulfate                                                       Charge:  -2  Formula: O4S
thf_c          :                 -0.000223  Name: 5,6,7,8-Tetrahydrofolate                                      Charge:  -2  Formula: C19H21N7O6
thmpp_c        :                 -0.000223  Name: Thiamine diphosphate                                          Charge:  -2  Formula: C12H16N4O7P2S
thr__L_c       :                 -0.253687  Name: L-Threonine                                                   Charge:   0  Formula: C4H9NO3
trp__L_c       :                 -0.056843  Name: L-Tryptophan                                                  Charge:   0  Formula: C11H12N2O2
tyr__L_c       :                 -0.137896  Name: L-Tyrosine                                                    Charge:   0  Formula: C9H11NO3
utp_c          :                 -0.144104  Name: UTP C9H11N2O15P3                                              Charge:  -4  Formula: C9H11N2O15P3
val__L_c       :                 -0.423162  Name: L-Valine                                                      Charge:   0  Formula: C5H11NO2
zn2_c          :                 -0.000341  Name: Zinc                                                          Charge:   2  Formula: Zn
adp_c          :                     53.95  Name: ADP C10H12N5O10P2                                             Charge:  -3  Formula: C10H12N5O10P2
h_c            :                     53.95  Name: H+                                                            Charge:   1  Formula: H
pi_c           :                 53.945662  Name: Phosphate                                                     Charge:  -2  Formula: HO4P
ppi_c          :                  0.773903  Name: Diphosphate                                                   Charge:  -3  Formula: HO7P2

Sum charge: 0.5807120000000463

Associated Genes:

In [13]:
reaction_id_to_check = 'BIOMASS_KT2440_WT3'
reaction = model1.reactions.get_by_id(reaction_id_to_check)
print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")
sum = 0
#reaction.name = '(S)-2-Acetolactate pyruvate-lyase (carboxylating)'
print("\nMetabolites and Stoichiometry:")
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id:<15}: {coefficient:>25}  Name: {metabolite.name:<60}  Charge: {metabolite.charge:>3}  Formula: {metabolite.formula}")
    sum += coefficient * metabolite.charge
print(f'\nSum charge: {sum}')
print("\nAssociated Genes:")
for gene in reaction.genes:
    print(gene.id)

Reaction ID: BIOMASS_KT2440_WT3
Name: Biomass P putida KT2440  aa DNA RNA ATP murein FA ions soluble
Equation: 0.000223 10fthf_c + 0.000223 2fe2s_c + 0.000223 4fe4s_c + 0.000223 5mthf_c + 0.000279 accoa_c + 0.000223 adocbl_c + 0.598267 ala__L_c + 0.000223 amet_c + 0.354251 arg__L_c + 0.158931 asn__L_c + 0.284685 asp__L_c + 46.918883 atp_c + 0.000223 bmocogdp_c + 0.000223 btamp_c + 0.004226 ca2_c + 0.000223 chor_c + 0.004226 cl_c + 1.8e-05 clpn140_p + 0.000578 clpn160_p + 0.002873 clpn161_p + 0.000192 clpn180_p + 0.001309 clpn181_p + 0.000167 coa_c + 0.002817 cobalt2_c + 0.00041 cpe160_c + 0.000226 cpg160_c + 0.159783 ctp_c + 0.002817 cu2_c + 0.055652 cys__L_c + 0.010804 datp_c + 0.01721 dctp_c + 0.017423 dgtp_c + 0.010854 dttp_c + 0.000223 fad_c + 0.00634 fe2_c + 0.00634 fe3_c + 0.251507 gln__L_c + 0.301809 glu__L_c + 0.431309 gly_c + 0.000223 gthrd_c + 0.210704 gtp_c + 41.397362 h2o_c + 0.000223 hemeO_c + 0.126289 his__L_c + 0.244551 ile__L_c + 0.158509 k_c + 0.628769 leu__L_c + 0.000223 lipopb_c + 0.008696 lpspput_e + 0.180336 lys__L_c + 3.1e-05 malcoa_c + 0.122008 met__L_c + 0.007044 mg2_c + 0.000223 mlthf_c + 0.002817 mn2_c + 0.002817 mobd_c + 0.000223 mocogdp_c + 0.001979 murein3p3p_p + 0.000326 murein3px4p_p + 0.007917 murein4p4p_p + 0.002941 murein4px4p_p + 6.6e-05 murein4px4px4p_p + 0.003522 na1_c + 0.001786 nad_c + 4.4e-05 nadh_c + 0.000111 nadp_c + 0.000335 nadph_c + 0.010567 nh4_c + 0.002817 ni2_c + 0.000251 pe140_c + 0.007882 pe160_c + 0.039155 pe161_c + 0.002622 pe180_c + 0.017845 pe181_c + 0.000138 pg140_c + 0.004354 pg160_c + 0.021632 pg161_c + 0.001449 pg180_c + 0.009859 pg181_c + 0.191038 phe__L_c + 0.000223 pheme_c + 0.000223 pqqh2_c + 0.26328 pro__L_c + 0.03327 ptrc_c + 0.000223 pydx5p_c + 0.000223 pyovd_kt_e + 0.000223 q8h2_c + 0.000223 ribflv_c + 0.301274 ser__L_c + 0.000223 sheme_c + 0.003522 so4_c + 9.8e-05 succoa_c + 0.000223 thf_c + 0.000223 thmnp_c + 0.000223 thmpp_c + 0.256324 thr__L_c + 0.077592 trp__L_c + 0.135921 tyr__L_c + 5.5e-05 udcpdp_c + 0.143215 utp_c + 0.389034 val__L_c + 0.002817 zn2_c --> 46.7502 adp_c + 46.7502 h_c + 46.746677 pi_c + 0.73868 ppi_c
Lower Bound: 0.0
Upper Bound: 999999.0

Metabolites and Stoichiometry:
10fthf_c       :                 -0.000223  Name: 10-Formyltetrahydrofolate                                     Charge:  -2  Formula: C20H21N7O7
2fe2s_c        :                 -0.000223  Name: [2Fe-2S] iron-sulfur cluster                                  Charge:   2  Formula: S2Fe2
4fe4s_c        :                 -0.000223  Name: [4Fe-4S] iron-sulfur cluster                                  Charge:   2  Formula: S4Fe4
5mthf_c        :                 -0.000223  Name: 5-Methyltetrahydrofolate                                      Charge:  -1  Formula: C20H24N7O6
accoa_c        :                 -0.000279  Name: Acetyl-CoA                                                    Charge:  -4  Formula: C23H34N7O17P3S
adocbl_c       :                 -0.000223  Name: Adenosylcobalamin                                             Charge:   0  Formula: C72H100CoN18O17P
ala__L_c       :                 -0.598267  Name: L-Alanine                                                     Charge:   0  Formula: C3H7NO2
amet_c         :                 -0.000223  Name: S-Adenosyl-L-methionine                                       Charge:   1  Formula: C15H23N6O5S
arg__L_c       :                 -0.354251  Name: L-Arginine                                                    Charge:   1  Formula: C6H15N4O2
asn__L_c       :                 -0.158931  Name: L-Asparagine                                                  Charge:   0  Formula: C4H8N2O3
asp__L_c       :                 -0.284685  Name: L-Aspartate                                                   Charge:  -1  Formula: C4H6NO4
atp_c          :                -46.918883  Name: ATP C10H12N5O13P3                                             Charge:  -4  Formula: C10H12N5O13P3
bmocogdp_c     :                 -0.000223  Name: Bis-molybdopterin guanine dinucleotide                        Charge:  -4  Formula: C40H44N20O27P4S4Mo
btamp_c        :                 -0.000223  Name: Biotinyl 5  AMP C20H27N7O9PS                                  Charge:  -1  Formula: C20H27N7O9PS
ca2_c          :                 -0.004226  Name: Calcium                                                       Charge:   2  Formula: Ca
chor_c         :                 -0.000223  Name: Chorismate                                                    Charge:  -2  Formula: C10H8O6
cl_c           :                 -0.004226  Name: Chloride                                                      Charge:  -1  Formula: Cl
clpn140_p      :                  -1.8e-05  Name: Cardiolipin (tetratetradecanoyl, n-C14:0)                     Charge:  -2  Formula: C65H124O17P2
clpn160_p      :                 -0.000578  Name: Cardiolipin (tetrahexadecanoyl, n-C16:0)                      Charge:  -2  Formula: C73H140O17P2
clpn161_p      :                 -0.002873  Name: Cardiolipin (tetrahexadec-9-enoyl, n-C16:1)                   Charge:  -2  Formula: C73H132O17P2
clpn180_p      :                 -0.000192  Name: Cardiolipin (tetraoctadecanoyl, n-C18:0)                      Charge:  -2  Formula: C81H156O17P2
clpn181_p      :                 -0.001309  Name: Cardiolipin (tetraoctadec-11-enoyl, n-C18:1)                  Charge:  -2  Formula: C81H148O17P2
coa_c          :                 -0.000167  Name: Coenzyme A                                                    Charge:  -4  Formula: C21H32N7O16P3S
cobalt2_c      :                 -0.002817  Name: Co2+                                                          Charge:   2  Formula: Co
cpe160_c       :                  -0.00041  Name: Cyclopropane phosphatidylethanolamine (dihexadec-9,10-cyclo-anoyl, n-C16:0 cyclo)  Charge:   0  Formula: C39H74N1O8P1
cpg160_c       :                 -0.000226  Name: Cyclopropane phosphatidylglycerol (dihexadec-9,10-cyclo-anoyl, n-C16:0 cyclo)  Charge:  -1  Formula: C40H74O10P1
ctp_c          :                 -0.159783  Name: CTP C9H12N3O14P3                                              Charge:  -4  Formula: C9H12N3O14P3
cu2_c          :                 -0.002817  Name: Copper                                                        Charge:   2  Formula: Cu
cys__L_c       :                 -0.055652  Name: L-Cysteine                                                    Charge:   0  Formula: C3H7NO2S
datp_c         :                 -0.010804  Name: DATP C10H12N5O12P3                                            Charge:  -4  Formula: C10H12N5O12P3
dctp_c         :                  -0.01721  Name: DCTP C9H12N3O13P3                                             Charge:  -4  Formula: C9H12N3O13P3
dgtp_c         :                 -0.017423  Name: DGTP C10H12N5O13P3                                            Charge:  -4  Formula: C10H12N5O13P3
dttp_c         :                 -0.010854  Name: DTTP C10H13N2O14P3                                            Charge:  -4  Formula: C10H13N2O14P3
fad_c          :                 -0.000223  Name: Flavin adenine dinucleotide oxidized                          Charge:  -2  Formula: C27H31N9O15P2
fe2_c          :                  -0.00634  Name: Fe2+ mitochondria                                             Charge:   2  Formula: Fe
fe3_c          :                  -0.00634  Name: Iron (Fe3+)                                                   Charge:   3  Formula: Fe
gln__L_c       :                 -0.251507  Name: L-Glutamine                                                   Charge:   0  Formula: C5H10N2O3
glu__L_c       :                 -0.301809  Name: L-Glutamate                                                   Charge:  -1  Formula: C5H8NO4
gly_c          :                 -0.431309  Name: Glycine                                                       Charge:   0  Formula: C2H5NO2
gthrd_c        :                 -0.000223  Name: Reduced glutathione                                           Charge:  -1  Formula: C10H16N3O6S
gtp_c          :                 -0.210704  Name: GTP C10H12N5O14P3                                             Charge:  -4  Formula: C10H12N5O14P3
h2o_c          :                -41.397362  Name: H2O H2O                                                       Charge:   0  Formula: H2O
hemeO_c        :                 -0.000223  Name: Heme O C49H56FeN4O5                                           Charge:  -2  Formula: C49H56FeN4O5
his__L_c       :                 -0.126289  Name: L-Histidine                                                   Charge:   0  Formula: C6H9N3O2
ile__L_c       :                 -0.244551  Name: L-Isoleucine                                                  Charge:   0  Formula: C6H13NO2
k_c            :                 -0.158509  Name: Potassium                                                     Charge:   1  Formula: K
leu__L_c       :                 -0.628769  Name: L-Leucine                                                     Charge:   0  Formula: C6H13NO2
lipopb_c       :                 -0.000223  Name: Lipoate (protein bound)                                       Charge:   1  Formula: C8H13OS2
lpspput_e      :                 -0.008696  Name: Lipopolysacharide  LPS  from P putida KT2440                  Charge: -12  Formula: C148H254N6O91P6
lys__L_c       :                 -0.180336  Name: L-Lysine                                                      Charge:   1  Formula: C6H15N2O2
malcoa_c       :                  -3.1e-05  Name: Malonyl CoA C24H33N7O19P3S                                    Charge:  -5  Formula: C24H33N7O19P3S
met__L_c       :                 -0.122008  Name: L-Methionine                                                  Charge:   0  Formula: C5H11NO2S
mg2_c          :                 -0.007044  Name: Magnesium                                                     Charge:   2  Formula: Mg
mlthf_c        :                 -0.000223  Name: 5,10-Methylenetetrahydrofolate                                Charge:  -2  Formula: C20H21N7O6
mn2_c          :                 -0.002817  Name: Manganese                                                     Charge:   2  Formula: Mn
mobd_c         :                 -0.002817  Name: Molybdate                                                     Charge:  -2  Formula: MoO4
mocogdp_c      :                 -0.000223  Name: Molybdopterin guanine dinucleotide                            Charge:  -2  Formula: C20H22N10O15P2S2Mo
murein3p3p_p   :                 -0.001979  Name: Two linked disacharide tripeptide murein units (uncrosslinked, middle of chain)  Charge:  -4  Formula: C68H104N12O38
murein3px4p_p  :                 -0.000326  Name: Two disacharide linked murein units, tripeptide crosslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C71H107N13O38
murein4p4p_p   :                 -0.007917  Name: Two linked disacharide tetrapeptide murein units (uncrosslinked, middle of chain)  Charge:  -4  Formula: C74H114N14O40
murein4px4p_p  :                 -0.002941  Name: Two disacharide linked murein units, tetrapeptide corsslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C74H112N14O39
murein4px4px4p_p:                  -6.6e-05  Name: Three disacharide linked murein units (tetrapeptide crosslinked tetrapeptide (A2pm->D-ala) & tetrapeptide corsslinked tetrapeptide (A2pm->D-ala)) (middle of chain)  Charge:  -6  Formula: C111H167N21O58
na1_c          :                 -0.003522  Name: Sodium                                                        Charge:   1  Formula: Na
nad_c          :                 -0.001786  Name: Nicotinamide adenine dinucleotide                             Charge:  -1  Formula: C21H26N7O14P2
nadh_c         :                  -4.4e-05  Name: Nicotinamide adenine dinucleotide - reduced                   Charge:  -2  Formula: C21H27N7O14P2
nadp_c         :                 -0.000111  Name: Nicotinamide adenine dinucleotide phosphate                   Charge:  -3  Formula: C21H25N7O17P3
nadph_c        :                 -0.000335  Name: Nicotinamide adenine dinucleotide phosphate - reduced         Charge:  -4  Formula: C21H26N7O17P3
nh4_c          :                 -0.010567  Name: Ammonium                                                      Charge:   1  Formula: H4N
ni2_c          :                 -0.002817  Name: Nickel                                                        Charge:   2  Formula: Ni
pe140_c        :                 -0.000251  Name: Phosphatidylethanolamine (ditetradecanoyl, n-C14:0)           Charge:   0  Formula: C33H66N1O8P1
pe160_c        :                 -0.007882  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74N1O8P1
pe161_c        :                 -0.039155  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70N1O8P1
pe180_c        :                 -0.002622  Name: Phosphatidylethanolamine (dioctadecanoyl, n-C18:0)            Charge:   0  Formula: C41H82N1O8P1
pe181_c        :                 -0.017845  Name: Phosphatidylethanolamine (dioctadec-11-enoyl, n-C18:1)        Charge:   0  Formula: C41H78N1O8P1
pg140_c        :                 -0.000138  Name: Phosphatidylglycerol (ditetradecanoyl, n-C14:0)               Charge:  -1  Formula: C34H66O10P1
pg160_c        :                 -0.004354  Name: Phosphatidylglycerol (dihexadecanoyl, n-C16:0)                Charge:  -1  Formula: C38H74O10P1
pg161_c        :                 -0.021632  Name: Phosphatidylglycerol (dihexadec-9-enoyl, n-C16:1)             Charge:  -1  Formula: C38H70O10P1
pg180_c        :                 -0.001449  Name: Phosphatidylglycerol (dioctadecanoyl, n-C18:0)                Charge:  -1  Formula: C42H82O10P1
pg181_c        :                 -0.009859  Name: Phosphatidylglycerol (dioctadec-11-enoyl, n-C18:1)            Charge:  -1  Formula: C42H78O10P1
phe__L_c       :                 -0.191038  Name: L-Phenylalanine                                               Charge:   0  Formula: C9H11NO2
pheme_c        :                 -0.000223  Name: Protoheme C34H30FeN4O4                                        Charge:  -2  Formula: C34H30FeN4O4
pqqh2_c        :                 -0.000223  Name: Reduced pyrroloquinoline-quinone                              Charge:  -3  Formula: C14H5N2O8
pro__L_c       :                  -0.26328  Name: L-Proline                                                     Charge:   0  Formula: C5H9NO2
ptrc_c         :                  -0.03327  Name: Putrescine                                                    Charge:   2  Formula: C4H14N2
pydx5p_c       :                 -0.000223  Name: Pyridoxal 5'-phosphate                                        Charge:  -2  Formula: C8H8NO6P
pyovd_kt_e     :                 -0.000223  Name: Pyoverdine  P putida specific                                 Charge:  -1  Formula: C27H47N10O15
q8h2_c         :                 -0.000223  Name: Ubiquinol-8                                                   Charge:   0  Formula: C49H76O4
ribflv_c       :                 -0.000223  Name: Riboflavin C17H20N4O6                                         Charge:   0  Formula: C17H20N4O6
ser__L_c       :                 -0.301274  Name: L-Serine                                                      Charge:   0  Formula: C3H7NO3
sheme_c        :                 -0.000223  Name: Siroheme C42H36FeN4O16                                        Charge:  -8  Formula: C42H36FeN4O16
so4_c          :                 -0.003522  Name: Sulfate                                                       Charge:  -2  Formula: O4S
succoa_c       :                  -9.8e-05  Name: Succinyl-CoA                                                  Charge:  -5  Formula: C25H35N7O19P3S
thf_c          :                 -0.000223  Name: 5,6,7,8-Tetrahydrofolate                                      Charge:  -2  Formula: C19H21N7O6
thmnp_c        :                 -0.000223  Name: Tetrahydromonapterin                                          Charge:   0  Formula: C9H15N5O4
thmpp_c        :                 -0.000223  Name: Thiamine diphosphate                                          Charge:  -2  Formula: C12H16N4O7P2S
thr__L_c       :                 -0.256324  Name: L-Threonine                                                   Charge:   0  Formula: C4H9NO3
trp__L_c       :                 -0.077592  Name: L-Tryptophan                                                  Charge:   0  Formula: C11H12N2O2
tyr__L_c       :                 -0.135921  Name: L-Tyrosine                                                    Charge:   0  Formula: C9H11NO3
udcpdp_c       :                  -5.5e-05  Name: Undecaprenyl diphosphate                                      Charge:  -3  Formula: C55H89O7P2
utp_c          :                 -0.143215  Name: UTP C9H11N2O15P3                                              Charge:  -4  Formula: C9H11N2O15P3
val__L_c       :                 -0.389034  Name: L-Valine                                                      Charge:   0  Formula: C5H11NO2
zn2_c          :                 -0.002817  Name: Zinc                                                          Charge:   2  Formula: Zn
adp_c          :                   46.7502  Name: ADP C10H12N5O10P2                                             Charge:  -3  Formula: C10H12N5O10P2
h_c            :                   46.7502  Name: H+                                                            Charge:   1  Formula: H
pi_c           :                 46.746677  Name: Phosphate                                                     Charge:  -2  Formula: HO4P
ppi_c          :                   0.73868  Name: Diphosphate                                                   Charge:  -3  Formula: HO7P2

Sum charge: 0.711471000000166

Associated Genes:

add metabolite to the biomass composition

In [77]:
# Get the reaction 'Growth'
reaction = copy_of_model.reactions.get_by_id('Growth')

for metabolite_id, coefficient in metabolite_not_found.items():
    try:
        print(metabolite_id)
        # Add the metabolite to the reaction with its coefficient
        reaction.add_metabolites({metabolite_id: coefficient})
        # Optimize the model and print the result
        print(copy_of_model.slim_optimize())
    except KeyError:
        # If the metabolite is not found in the model, pass
        pass

murein3px4p_p
0.18214556704844082
adocbl_c
4.2232648503392224e-16
gthrd_c
0.0
ni2_c
0.0
accoa_c
0.0
murein4p3p_p
0.0
5mthf_c
0.0
nh4_c
0.0
chor_c
0.0
q8h2_c
0.0
spmd_c
0.0
hemeO_c
0.0
murein4p4p_p
0.0
mococdp_c
0.0
2dmmql8_c
0.0
malcoa_c
0.0
murein4px4p_p
0.0
2fe2s_c
0.0
ptrc_c
0.0
btn_c
0.0
nadph_c
0.0
mobd_c
0.0
4fe4s_c
0.0
nadh_c
0.0
enter_c
0.0
murein4px4px4p_p
0.0
succoa_c
0.0
rmn_c
0.0
arab__L_c
0.0
gal__L_c
0.0
glc__D_c
0.0
fru_c
0.0
xyl__D_c
0.0
man_c
0.0
galam_c
0.0
gam_c
0.0
retinol_c
0.0
avite1_c
0.0
vitd3_c
0.0
vitd2_c
0.0
thm_c
0.0
rbflvrd_c
0.0
pydxn_c
0.0
chol_c
0.0
fol_c
0.0
nac_c
0.0
pnto__R_c
0.0
phllqne_c
0.0
caro_c
0.0
clpn161_p
0.0
pg160_p
0.0
clpn160_p
0.0
clpn181_p
0.0
colipa_e
0.0
pe181_p
0.0
pg161_p
0.0
ttdca_c
0.0
hexadecacid_c
0.0
hexedecacid_c
0.0
hpdca_c
0.0
octadecacid_c
0.0
octedecacid_c
0.0
lnlc_c
0.0
lnlncg_c
0.0
arach_c
0.0
tmndnc_c
0.0
doco13ac_c
0.0
ttc_c
0.0

# Update new model

### Update charges from excel

In [11]:
file_path = 'C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified reactions.xlsx'
file_path_1 = 'C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified formula.xlsx'

excel_data_charge = pd.read_excel(file_path)

# Iterate over each component in the Excel file
for component in excel_data_charge['metabolite changed']:
    # Check if a metabolite is present in the model's metabolites
    metabolite_id = component
    if metabolite_id in copy_of_model.metabolites:
        # Get the metabolite from the model
        metabolite = copy_of_model.metabolites.get_by_id(metabolite_id)
        
        # Change the charge of the metabolite to a new value from the Excel file
        new_charge = int(excel_data_charge.loc[excel_data_charge['metabolite changed'] == metabolite_id, 'New charge'].values[0])
        metabolite.charge = new_charge
        
        # Print information about the modified metabolite
        print(f"Modified metabolite: {metabolite.id}")
        print(f"Updated charge: {metabolite.charge}")
    else:
        print("Metabolite not found in the model.")

Modified metabolite: 2agpg161_c
Updated charge: -1
Modified metabolite: r3hbACP_c
Updated charge: -1
Modified metabolite: tmrs2eACP_c
Updated charge: -1
Modified metabolite: 4hoxpac_p
Updated charge: -1
Modified metabolite: 4oxptn_p
Updated charge: -1
Modified metabolite: 4oxptn_e
Updated charge: -1
Modified metabolite: 4hoxpac_e
Updated charge: -1
Modified metabolite: 6atha_e
Updated charge: -1
Metabolite not found in the model.
Modified metabolite: hethmpp_c
Updated charge: -2
Modified metabolite: Pald_c
Updated charge: -2
Modified metabolite: S2hglut_c
Updated charge: -2
Modified metabolite: sdhlam_c
Updated charge: -1
Modified metabolite: pqqh2_p
Updated charge: -3
Modified metabolite: ppad_c
Updated charge: -1
Modified metabolite: cmcbtt_c
Updated charge: 1
Modified metabolite: fcmcbtt_c
Updated charge: 4
Modified metabolite: R_3hpt_p
Updated charge: -1
Modified metabolite: R_3hpt_e
Updated charge: -1
Modified metabolite: R_3hpba_p
Updated charge: -1
Modified metabolite: R_3hpba_e
Updated charge: -1

In [23]:
print(len(cobra.manipulation.validate.check_mass_balance(copy_of_model)))
list_reactions = cobra.manipulation.validate.check_mass_balance(copy_of_model)
for reaction, balance_dict in list_reactions.items():
    reaction_id = reaction.id
    charge_balance = balance_dict
    print(f"Reaction ID: {reaction_id}, Charge Balance: {charge_balance}")

5
Reaction ID: DHNAOT, Charge Balance: {'charge': 2.0}
Reaction ID: HDECH, Charge Balance: {'charge': 2.0}
Reaction ID: MECDPDH4E, Charge Balance: {'charge': -1.0}
Reaction ID: P9DH, Charge Balance: {'charge': 4.0}
Reaction ID: THZSN_1, Charge Balance: {'H': -1.0}

### Create a list of reaction to update with the related model

In [15]:
import requests
list_reactions = cobra.manipulation.validate.check_mass_balance(copy_of_model)

# Dictionary to store reaction ID and associated model
reaction_model_mapping = {}

for reaction, balance_dict in list_reactions.items():
    reaction_id = reaction.id  # Get the ID of the reaction
    # URL of the API endpoint for the reaction
    url = f'http://bigg.ucsd.edu/api/v2/universal/reactions/{reaction_id}'
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        # Extract the model ID from the JSON data
        model_of_reaction = data['models_containing_reaction'][0]['bigg_id']
        # Store the mapping of reaction ID to its model in the dictionary
        reaction_model_mapping[reaction_id] = model_of_reaction
    else:
        # If the request was not successful, print the status code
        print("Failed to retrieve data. Status code:", response.status_code)
print(reaction_model_mapping)

{'1P2CBXLCYCL': 'iJN1463', '1P2CBXLR': 'iJN1463', '3HAACOAT140': 'iJN1463', '3HACPH': 'iYS854', '3HAD40': 'iAF1260', '3HOXTPP': 'iYS854', '3OAR40': 'iAF1260', '4HDPROO': 'iJN1463', 'AACLAM': 'iYS854', 'AACPS3': 'iAF1260', 'AACPS5': 'iAF1260', 'AADa': 'iCN718', 'AADb': 'iCN718', 'AALDH': 'iNF517', 'ACGAMPM': 'iAM_Pb448', 'ACHBS': 'iAF1260', 'ACHBS2': 'iSynCJ816', 'ACM6PH': 'iAF1260', 'ACMANApts': 'iJR904', 'ACOAD10f': 'iJN1463', 'ACOAD11f': 'iJN1463', 'ACOAD12f': 'iJN1463', 'ACOAD13f': 'iJN1463', 'ACOAD14f': 'iJN1463', 'ACOAD15f': 'iJN1463', 'ACOAD16f': 'iJN1463', 'ACOAD17f': 'iJN1463', 'ACOAD18f': 'iJN1463', 'ACOAD19f': 'iJN1463', 'ACOAD20f': 'iJN1463', 'ACOAD21f': 'iJN1463', 'ACOAD22f': 'iJN1463', 'ACOAD23f': 'iJN1463', 'ACOAD29f': 'iJN1463', 'ACOAD3': 'iAPECO1_1312', 'ACOAD30f': 'iJN1463', 'ACOAD31f': 'iJN1463', 'ACOAD33f': 'iJN1463', 'ACOAD3f': 'iAF1260', 'ACOAD6': 'iAPECO1_1312', 'ACOAD6f': 'iAF1260', 'ACOAM': 'iYS854', 'ACPPAT140': 'iAF987', 'ACPPAT160': 'iAF987', 'ACPPAT181': 'iAF987', 'ADCPS1': 'iAF987', 'ADK2': 'iAF692', 'ADOCBIAH': 'iAF692', 'ADPRDP': 'iAF1260', 'ADSELK': 'iCHOv1', 'ADSELR': 'iJN1463', 'ADSELR2': 'iJN1463', 'ADSL1r': 'iAF1260', 'ADSS': 'iAF1260', 'AEPPYRTA': 'iCN718', 'AGM3PApp': 'iAF1260', 'AGM3PH': 'iAF1260', 'AGPAT160': 'iAF1260', 'AGPAT181': 'iAF1260', 'AHMMPS_1': 'iNF517', 'AHSERL4': 'iCN718', 'AIRC1': 'iCN718', 'AIRC2': 'iAF1260', 'AIRC3': 'iAF1260', 'ALCDpp': 'iJN1463', 'AMANAPEr': 'iAF1260', 'AMPMS2': 'iAF1260', 'ANHMK': 'iAF1260', 'APAT_1': 'iCN718', 'APPLDHr': 'iAPECO1_1312', 'ARGSL': 'iAF1260', 'ARGSS': 'iAF1260', 'ATPPRT': 'iAF1260', 'BSCT': 'iAF987', 'BTS3r': 'iAF692', 'BTS4': 'iAF1260', 'BUP': 'iJN1463', 'CCPpp': 'iJN1463', 'CHORM': 'iAF1260', 'CLPNH120pp': 'iAF1260', 'CLPNH140pp': 'iAF1260', 'CLPNH141pp': 'iAF1260', 'CLPNH160pp': 'iAF1260', 'CLPNH161pp': 'iAF1260', 'CLPNH180pp': 'iAF1260', 'CLPNH181pp': 'iAF1260', 'CLPNS120pp': 'iAF1260', 'CLPNS160pp': 'iAF1260', 'CLPNS180pp': 'iAF1260', 'CMCBTFL': 'iEK1008', 'CMCBTFU': 'iEK1008', 'CYANST': 'iAF1260', 'CYO4pp': 'iJN1463', 'CYTCBB3pp': 'iJN1463', 'DAAD11': 'iJN1463', 'DAAD12': 'iJN1463', 'DAAD3': 'iJN1463', 'DAAD7': 'iJN1463', 'DAGK120': 'iAF1260', 'DAGK140': 'iAF1260', 'DAGK141': 'iAF1260', 'DAGK161': 'iAF1260', 'DAGK180': 'iAF1260', 'DAGK181': 'iAF1260', 'DASYN120': 'iAF1260', 'DASYN140': 'iAF1260', 'DASYN141': 'iAF1260', 'DASYN161': 'iAF1260', 'DASYN180': 'iAF1260', 'DASYN181': 'iAF1260', 'DB4PS': 'iAF1260', 'DESATPG160': 'iJN1463', 'DHGLYH': 'iML1515', 'DHNAOT': 'iCN718', 'DHNCOAS': 'iAM_Pb448', 'DHPM2': 'iAF692', 'DNMPPA': 'iAF1260', 'DNTPPA': 'iAF1260', 'DRPA': 'iAF1260', 'DURIPP_1': 'iYS854', 'DXPRIi': 'iAF1260', 'DXPS': 'iAF1260', 'ECOAH6': 'iAF1260', 'ECOAH8': 'iAF1260', 'EDA': 'iAF1260', 'FACOAE141': 'iAF1260', 'FACOAE1829Z12Z': 'iJN1463', 'FACOAL141t2pp': 'iAF1260', 'FACOAL1812': 'iCHOv1', 'FACOAL181d11tpp': 'iJN1463', 'FACOAL1821': 'iAB_RBC_283', 'FACOAL182t2pp': 'iJN1463', 'FBA': 'e_coli_core', 'FBP': 'e_coli_core', 'FCLPA': 'iAF1260', 'FDMO3_1': 'iYO844', 'FDMO4_1': 'iYO844', 'FE3DCITCH': 'iJN1463', 'FE3DCITR3': 'iJN1463', 'FE3DCITabcpp': 'iAF1260', 'FE3PYOVDDR2': 'iJN1463', 'FEENTERR3': 'iAF1260', 'FFSD_2': 'iCN900', 'FMNRy': 'iYO844', 'FUCpts': 'iCN900', 'G1PACT': 'iAF1260', 'GAL6PI': 'iCN900', 'GAPD': 'e_coli_core', 'GARFT': 'iAF1260', 'GCCa': 'iAF987', 'GCCb': 'iAF987', 'GCVHADPr': 'iYS854', 'GCVHRADPr': 'iYS854', 'GDPDPK': 'iAF1260', 'GDPMNP': 'iAF1260', 'GDPTPDP': 'iAF987', 'GGLUCT2': 'iEK1008', 'GLTPD': 'iAF1260', 'GLUTRR': 'iAF1260', 'GLUTRS': 'iAF1260', 'GLUTRS_3': 'iYS854', 'GPDDA4': 'iAF1260', 'GTMLT': 'iEK1008', 'GTPDPK': 'iAF1260', 'GUI1': 'iAF1260', 'HACD3': 'iAF987', 'HACD3i': 'iAF1260', 'HACD8': 'iAF987', 'HACD8i': 'iAF1260', 'HACD9': 'iCN718', 'HDECH': 'iEK1008', 'HEMEOS': 'iAF1260', 'HEX4': 'iAB_RBC_283', 'HMR_0260': 'iJN1463', 'HMSH': 'iJN1463', 'KARA2': 'iAF1260', 'KARI_1': 'iJB785', 'LASP2OA': 'iYS854', 'LPLIPAL1E181d11pp': 'iJN1463', 'LPLIPAL1G181d11pp': 'iJN1463', 'LPLIPAL2G160': 'iAF1260', 'LPLIPAL2G161': 'iAF1260', 'LPLIPAL2G181': 'iAF1260', 'MACCOAT': 'iCN718', 'MAN1PT': 'iAF987', 'MAN1PT2': 'iAF1260', 'MAN6PI': 'iAB_RBC_283', 'MANAO': 'iAF1260', 'MANpts': 'iCN900', 'MANptspp': 'iAF1260', 'MCCC': 'iAF987', 'MCTP1App': 'iAF1260', 'MCTP2App': 'iAF1260', 'MDDCP2pp': 'iAF1260', 'MDDEP1pp': 'iAF1260', 'MDDEP3pp': 'iAF1260', 'MECDPDH4E': 'iCN900', 'MEPCT': 'iAF1260', 'MGCH': 'iAF987', 'MLDCP1App': 'iAF1260', 'MLDCP3App': 'iAF1260', 'MLDEP1pp': 'iAF1260', 'MLTGY2pp': 'iAF1260', 'MLTGY3pp': 'iAF1260', 'MLTGY4pp': 'iAF1260', 'MPTG': 'iAF1260', 'MPTG2': 'iAF1260', 'NPHS': 'iAF1260', 'NTPTP1': 'iAF1260', 'OP4ENH': 'iAF1260', 'P9DH': 'iCN900', 'PACPT_1': 'iCN718', 'PALDH': 'iCN718', 'PAPA120pp': 'iAF1260', 'PAPA140pp': 'iAF1260', 'PAPA141pp': 'iAF1260', 'PAPA161pp': 'iAF1260', 'PAPA180pp': 'iAF1260', 'PAPA181pp': 'iAF1260', 'PAPPT3': 'iAF1260', 'PEAOpp': 'iJN1463', 'PGPP120pp': 'iAF1260', 'PGPP140pp': 'iAF1260', 'PGPP141pp': 'iAF1260', 'PGPP160': 'iAF1260', 'PGPP160pp': 'iAF1260', 'PGPP161pp': 'iAF1260', 'PGPP180pp': 'iAF1260', 'PGPP181': 'iAF1260', 'PGPP181pp': 'iAF1260', 'PGSA120': 'iAF1260', 'PGSA140': 'iAF1260', 'PGSA141': 'iAF1260', 'PGSA160': 'iAF1260', 'PGSA161': 'iAF1260', 'PGSA180': 'iAF1260', 'PGSA181': 'iAF1260', 'PHER': 'iJN1463', 'PHET': 'iCN718', 'PLIPA1G160pp': 'iAF1260', 'PLIPA2A181pp': 'iAF1260', 'PPA2': 'iAF1260', 'PPGPPDP': 'iAF1260', 'PPK2': 'iAF1260', 'PPM': 'iAB_RBC_283', 'PPND': 'iAF1260', 'PPNDH': 'iAF1260', 'PRAIS': 'iAF1260', 'PRAMPC': 'iAF1260', 'PRASCSi': 'iAF1260', 'PRATPP': 'iAF1260', 'PRFGS': 'iAF1260', 'PRFGS_1': 'iNF517', 'PROR': 'iCN718', 'PRPPS': 'iAB_RBC_283', 'PSD160': 'iAF1260', 'PSD181': 'iAF1260', 'PSSA160': 'iAF1260', 'PSSA181': 'iAF1260', 'PSUDS': 'iAPECO1_1312', 'PUNP6': 'iAF1260', 'RBFK': 'iAB_RBC_283', 'RBFSa': 'iAF1260', 'RECOAH3': 'iJN1463', 'RECOAH6': 'iJN1463', 'RPI': 'e_coli_core', 'SALCHS4FER1': 'iECO111_1330', 'SALCHS4FEabcpp': 'iAPECO1_1312', 'SBTPD': 'iAF1260', 'SBTpts': 'iCN900', 'SELADT': 'iCHOv1', 'SHCHF': 'iAF1260', 'SUCpts': 'iCN900', 'SUCptspp': 'iAF1260', 'TALA': 'e_coli_core', 'TETDHpp2': 'iYS1720', 'THZSN_1': 'iJN678', 'TKT2': 'e_coli_core', 'TPI': 'e_coli_core', 'TRPS1': 'iAF1260', 'TRPS3': 'iAF1260', 'TYRL': 'iAF987', 'U23GAAT': 'iAF1260', 'UAGAAT': 'iAF1260', 'UAGDP': 'iAF1260', 'UAGDP_1': 'iYS854', 'UAMAS': 'iAF1260', 'UAPGR': 'iAF1260', 'UDCPDP': 'iAF1260', 'UM4PL': 'iAF1260', 'UPP3MT': 'iAF1260', 'YUMPS': 'iAF692', 'ilvg': 'iYL1228'}

### Update charge from BIGG API

In [18]:
for reaction, model_name in reaction_model_mapping.items():
    reaction_to_modify = copy_of_model.reactions.get_by_id(reaction)
    for metabolite, coefficient in reaction_to_modify.metabolites.items():
        if metabolite.charge == 0:
            url = f'http://bigg.ucsd.edu/api/v2/models/{model_name}/metabolites/{metabolite.id}'
            response = requests.get(url)
            if response.status_code == 200:
                data = response.json()
                # Check if the charge information is available and matches the current metabolite charge
                if data['charge'] is not None and data['charge'] != metabolite.charge:
                    print(metabolite.id)
                    print(f' metabolite charge : {metabolite.charge}')
                    print(f' bigg metabolite charge : {data['charge']}')
                    metabolite.charge = data['charge']
            else:
                print("Failed to retrieve data. Status code:", response.status_code)

1p2cbxl_c
 metabolite charge : 0
 bigg metabolite charge : -1
3hmrsACP_c
 metabolite charge : 0
 bigg metabolite charge : -1
but2eACP_c
 metabolite charge : 0
 bigg metabolite charge : -1
actACP_c
 metabolite charge : 0
 bigg metabolite charge : -1
palmACP_c
 metabolite charge : 0
 bigg metabolite charge : -1
octeACP_c
 metabolite charge : 0
 bigg metabolite charge : -1
acgam1p_c
 metabolite charge : 0
 bigg metabolite charge : -2
2ahbut_c
 metabolite charge : 0
 bigg metabolite charge : -1
acmum6p_c
 metabolite charge : 0
 bigg metabolite charge : -3
acmanap_c
 metabolite charge : 0
 bigg metabolite charge : -2
fad_c
 metabolite charge : 0
 bigg metabolite charge : -2
fadh2_c
 metabolite charge : 0
 bigg metabolite charge : -2
myrsACP_c
 metabolite charge : 0
 bigg metabolite charge : -1
appl_c
 metabolite charge : 0
 bigg metabolite charge : 1
r5p_c
 metabolite charge : 0
 bigg metabolite charge : -2
adsel_c
 metabolite charge : 0
 bigg metabolite charge : -2
3padsel_c
 metabolite charge : 0
 bigg metabolite charge : -4
dcamp_c
 metabolite charge : 0
 bigg metabolite charge : -4
anhgm3p_p
 metabolite charge : 0
 bigg metabolite charge : -2
anhgm3p_c
 metabolite charge : 0
 bigg metabolite charge : -2
pa181_c
 metabolite charge : 0
 bigg metabolite charge : -2
air_c
 metabolite charge : 0
 bigg metabolite charge : -2
5aizc_c
 metabolite charge : 0
 bigg metabolite charge : -3
pqq_p
 metabolite charge : 0
 bigg metabolite charge : -3
argsuc_c
 metabolite charge : 0
 bigg metabolite charge : -1
prbatp_c
 metabolite charge : 0
 bigg metabolite charge : -6
dtbt_c
 metabolite charge : 0
 bigg metabolite charge : -1
3uib_c
 metabolite charge : 0
 bigg metabolite charge : -1
pphn_c
 metabolite charge : 0
 bigg metabolite charge : -2
pa120_p
 metabolite charge : 0
 bigg metabolite charge : -2
pg120_p
 metabolite charge : 0
 bigg metabolite charge : -1
pa140_p
 metabolite charge : 0
 bigg metabolite charge : -2
pa141_p
 metabolite charge : 0
 bigg metabolite charge : -2
pg160_p
 metabolite charge : 0
 bigg metabolite charge : -1
pa161_p
 metabolite charge : 0
 bigg metabolite charge : -2
pa180_p
 metabolite charge : 0
 bigg metabolite charge : -2
pg180_p
 metabolite charge : 0
 bigg metabolite charge : -1
pa181_p
 metabolite charge : 0
 bigg metabolite charge : -2
tsul_c
 metabolite charge : 0
 bigg metabolite charge : -2
pa120_c
 metabolite charge : 0
 bigg metabolite charge : -2
pa140_c
 metabolite charge : 0
 bigg metabolite charge : -2
pa141_c
 metabolite charge : 0
 bigg metabolite charge : -2
pa161_c
 metabolite charge : 0
 bigg metabolite charge : -2
pa180_c
 metabolite charge : 0
 bigg metabolite charge : -2
db4p_c
 metabolite charge : 0
 bigg metabolite charge : -2
pg160_c
 metabolite charge : 0
 bigg metabolite charge : -1
dhgly_c
 metabolite charge : 0
 bigg metabolite charge : -1
dhpmp_c
 metabolite charge : 0
 bigg metabolite charge : -2
g3p_c
 metabolite charge : 0
 bigg metabolite charge : -2
2dr1p_c
 metabolite charge : 0
 bigg metabolite charge : -2
2me4p_c
 metabolite charge : 0
 bigg metabolite charge : -2
vacc_c
 metabolite charge : 0
 bigg metabolite charge : -1
vacc_p
 metabolite charge : 0
 bigg metabolite charge : -1
fdp_c
 metabolite charge : 0
 bigg metabolite charge : -4
fc1p_c
 metabolite charge : 0
 bigg metabolite charge : -2
fmn_c
 metabolite charge : 0
 bigg metabolite charge : -2
taur_c
 metabolite charge : 0
 bigg metabolite charge : -1
fe3dcit_c
 metabolite charge : 0
 bigg metabolite charge : -3
fmnh2_c
 metabolite charge : 0
 bigg metabolite charge : -2
fe3dcit_p
 metabolite charge : 0
 bigg metabolite charge : -3
feenter_c
 metabolite charge : 0
 bigg metabolite charge : 3
suc6p_c
 metabolite charge : 0
 bigg metabolite charge : -2
tag6p__D_c
 metabolite charge : 0
 bigg metabolite charge : -2
fgam_c
 metabolite charge : 0
 bigg metabolite charge : -2
alpro_c
 metabolite charge : 0
 bigg metabolite charge : 1
ppgpp_c
 metabolite charge : 0
 bigg metabolite charge : -6
man1p_c
 metabolite charge : 0
 bigg metabolite charge : -2
gdptp_c
 metabolite charge : 0
 bigg metabolite charge : -7
g3pg_c
 metabolite charge : 0
 bigg metabolite charge : -1
fruur_c
 metabolite charge : 0
 bigg metabolite charge : -1
hemeO_c
 metabolite charge : 0
 bigg metabolite charge : -2
man6p_c
 metabolite charge : 0
 bigg metabolite charge : -2
op4en_c
 metabolite charge : 0
 bigg metabolite charge : -1
Largn_c
 metabolite charge : 0
 bigg metabolite charge : -1
g3pg_p
 metabolite charge : 0
 bigg metabolite charge : -1
murein5px4p_p
 metabolite charge : 0
 bigg metabolite charge : -4
murein5px4px4p_p
 metabolite charge : 0
 bigg metabolite charge : -6
murein4px4p_p
 metabolite charge : 0
 bigg metabolite charge : -4
murein3px3p_p
 metabolite charge : 0
 bigg metabolite charge : -4
uaagmda_c
 metabolite charge : 0
 bigg metabolite charge : -4
udcpdp_c
 metabolite charge : 0
 bigg metabolite charge : -3
pppi_c
 metabolite charge : 0
 bigg metabolite charge : -4
uagmda_c
 metabolite charge : 0
 bigg metabolite charge : -4
pgp120_p
 metabolite charge : 0
 bigg metabolite charge : -3
pgp140_p
 metabolite charge : 0
 bigg metabolite charge : -3
pgp141_p
 metabolite charge : 0
 bigg metabolite charge : -3
pgp160_c
 metabolite charge : 0
 bigg metabolite charge : -3
pgp160_p
 metabolite charge : 0
 bigg metabolite charge : -3
pgp161_p
 metabolite charge : 0
 bigg metabolite charge : -3
pgp180_p
 metabolite charge : 0
 bigg metabolite charge : -3
pgp181_c
 metabolite charge : 0
 bigg metabolite charge : -3
pgp181_p
 metabolite charge : 0
 bigg metabolite charge : -3
pgp120_c
 metabolite charge : 0
 bigg metabolite charge : -3
pgp140_c
 metabolite charge : 0
 bigg metabolite charge : -3
pgp141_c
 metabolite charge : 0
 bigg metabolite charge : -3
pgp161_c
 metabolite charge : 0
 bigg metabolite charge : -3
pgp180_c
 metabolite charge : 0
 bigg metabolite charge : -3
fpram_c
 metabolite charge : 0
 bigg metabolite charge : -1
prbamp_c
 metabolite charge : 0
 bigg metabolite charge : -4
ps160_c
 metabolite charge : 0
 bigg metabolite charge : -1
ps181_c
 metabolite charge : 0
 bigg metabolite charge : -1
sbt6p_c
 metabolite charge : 0
 bigg metabolite charge : -2
scl_c
 metabolite charge : 0
 bigg metabolite charge : -7
tsul_p
 metabolite charge : 0
 bigg metabolite charge : -2
uamr_c
 metabolite charge : 0
 bigg metabolite charge : -3
dscl_c
 metabolite charge : 0
 bigg metabolite charge : -7

### Update charge and formula from a curated model

In [21]:
model1 = read_sbml_model('C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Biomass Equation\\curated_gramneg_updated_EX.sbml')

In [22]:
list_reactions = cobra.manipulation.validate.check_mass_balance(copy_of_model)
copy_of_model1 = model1.copy()
# Iterate through metabolites in the non-curated model
for metabolite in copy_of_model.metabolites:
    # Check if the metabolite exists in the curated model
    if metabolite.id in copy_of_model1.metabolites:
        # Find the corresponding metabolite in the curated model
        curated_metabolite = copy_of_model1.metabolites.get_by_id(metabolite.id)
        # Update the charge and formula of the non-curated metabolite
        metabolite.charge = curated_metabolite.charge
        metabolite.formula = curated_metabolite.formula
    else:
        print(f"Metabolite '{metabolite.id}' not found in the curated model.")

Metabolite 'glcn_e' not found in the curated model.
Metabolite 'n2_c' not found in the curated model.
Metabolite 'n2_e' not found in the curated model.
Metabolite 'n2_p' not found in the curated model.
Metabolite 'n2o_c' not found in the curated model.
Metabolite 'succ_e' not found in the curated model.

### Update metabolite with coa substring

In [16]:
substring_to_check = 'coa'
for metabolite in copy_of_model.metabolites:
    if substring_to_check in metabolite.id:
        if metabolite.charge == 0:
            metabolite.charge = -4
            # Print information about the modified metabolite
            print(f"Modified metabolite: {metabolite.id}")
            print(f"Updated charge of : {metabolite.charge}")

Modified metabolite: 2maacoa_c
Updated charge of : -4
Modified metabolite: 3hhd710coa_c
Updated charge of : -4
Modified metabolite: 3hhdccoa_c
Updated charge of : -4
Modified metabolite: 3hhdd4coa_c
Updated charge of : -4
Modified metabolite: 3hlnlccoa_c
Updated charge of : -4
Modified metabolite: 3hocoa_c
Updated charge of : -4
Modified metabolite: 3hodcoa_c
Updated charge of : -4
Modified metabolite: 3mgcoa_c
Updated charge of : -4
Modified metabolite: 3ohd710coa_c
Updated charge of : -4
Modified metabolite: 3ohdccoa_c
Updated charge of : -4
Modified metabolite: 3ohdd4coa_c
Updated charge of : -4
Modified metabolite: 3olnlccoa_c
Updated charge of : -4
Modified metabolite: benzcoa_c
Updated charge of : -4
Modified metabolite: ctncoa_c
Updated charge of : -4
Modified metabolite: hd2coa_c
Updated charge of : -4
Modified metabolite: hd710_2_coa_c
Updated charge of : -4
Modified metabolite: hd_7_10_coa_c
Updated charge of : -4
Modified metabolite: hdd4_2_coa_c
Updated charge of : -4
Modified metabolite: hmpscoa_c
Updated charge of : -4
Modified metabolite: lnlc2coa_c
Updated charge of : -4
Modified metabolite: lnlccoa_c
Updated charge of : -4
Modified metabolite: m2bcoa_c
Updated charge of : -4
Modified metabolite: oc2coa_c
Updated charge of : -4
Modified metabolite: phitcoa_c
Updated charge of : -4
Modified metabolite: sbzcoa_c
Updated charge of : -4
Modified metabolite: td2coa_c
Updated charge of : -4
Modified metabolite: td_5_8_coa_c
Updated charge of : -4
Modified metabolite: tde_2Z_coa_c
Updated charge of : -4
Modified metabolite: tdecoa_c
Updated charge of : -4
Modified metabolite: vacccoa_c
Updated charge of : -4

I noticed that carveme doesn't provide the appropriate charge for metabolites with Coa molecules