To do list :
- [ ] Add missing metabolites to biomass equation

### Setting up

In [ ]:
%pip install cobra

In [1]:
import cobra
import pandas as pd
from cobra.io import load_model
from cobra.io import load_json_model, save_json_model, load_matlab_model, save_matlab_model, read_sbml_model, write_sbml_model
from cobra import Model, Reaction, Metabolite, Gene
import numpy as np

Upload model

In [2]:
model = read_sbml_model('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.09 Models\\Manual_curation\\Biomass_equation\\GAM_NGAM_update.sbml')

In [63]:
model1 = read_sbml_model('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\Models\\Solarfood_original.sbml')

In [4]:
model = read_sbml_model('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.09 Models\\Reference_GSMs\\iCN1361.xml')

In [9]:
# set reactions bounds for a specific reaction 
reaction = model.reactions.get_by_id('EX_h2_e')
reaction.bounds = -19.48, 0.0

reaction = model.reactions.get_by_id('EX_o2_e')
reaction.bounds = -6.92, 0.0

reaction = model.reactions.get_by_id('EX_ac_e')
reaction.bounds = -2.50, 0.0

In [10]:
c_uptake =10

In [5]:
model.summary()

In [5]:

# Set ammonia uptake rate 
ammonia_uptake_rxn = copy_of_model.reactions.get_by_id('EX_nh4_e')  # Replace with actual ammonia exchange reaction ID


# Maximize the ATPase reaction
atp_hydrolysis_rxn = copy_of_model.reactions.get_by_id('ATPM')  # Replace with actual ATP hydrolysis reaction ID
copy_of_model.objective = atp_hydrolysis_rxn

# Perform optimization
solution = copy_of_model.optimize()

# Check the flux through the ATP hydrolysis and ammonia uptake reactions
atp_flux = solution.fluxes[atp_hydrolysis_rxn.id]


print(f'ATP Hydrolysis Flux: {atp_flux} mmol ATP/(gDCW·h)')

ATP Hydrolysis Flux: 5.000000000000001 mmol ATP/(gDCW·h)

# Manual Curation

## Adding metabolites

In [ ]:
new_metabolite = Metabolite(
    id='lnlncg_c',     # Metabolite ID
    name='Gamma-linolenic acid',     # Metabolite Name
    formula='C18H29O2',         # Chemical Formula
    compartment='c'            # Compartment (e.g., cytoplasm)
)


new_metabolite.annotation = {'kegg.compound':'C03035'}
new_metabolite.charge = -1 

model.add_metabolites([new_metabolite])

print(new_metabolite.formula)

C18H29O2

## Reactions & genes handling

#### Choose a metabolite and see the fluxes of each reactions it is involved in it

In [8]:
summary = model.metabolites.get_by_id('M_PROTON').summary()

In [9]:
summary

##### Create a dataframe of this metabolite summary

In [8]:
# Extract the producing and consuming fluxes
producing_flux_df = summary.producing_flux
consuming_flux_df = summary.consuming_flux

# Add a 'type' column to distinguish between producing and consuming
producing_flux_df['type'] = 'producing'
consuming_flux_df['type'] = 'consuming'

# Combine both DataFrames
df_summary = pd.concat([producing_flux_df, consuming_flux_df])
df_summary_sorted = df_summary.sort_values(by='flux', key=abs, ascending=False)
# Add a new column for the reaction names
df_summary_sorted['reaction_name'] = df_summary_sorted.index.map(lambda x: model.reactions.get_by_id(x).name)

# Add a new column for the reaction formulas
df_summary_sorted['reaction_formula'] = df_summary_sorted.index.map(lambda x: model.reactions.get_by_id(x).reaction)

# Display the DataFrame
df_summary_sorted.to_excel('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.03 Fluxes values\\q8h2_summary.xlsx', index=False)

### Search metabolite

In [6]:
search_word = 'succ'
# Iterate over metabolites in the model
for metabolite in model.metabolites:
    if search_word in metabolite.id:
        # Print metabolite information
        print(metabolite.id)
        print(metabolite.charge)
        print(metabolite.formula)
        print(metabolite.name)
        print(metabolite.compartment)
        print(metabolite.annotation)
        
        # Get related reactions
        related_reactions = list(metabolite.reactions)
        
        # Get genes related to the reactions
        related_genes = set()
        for reaction in related_reactions:
            related_genes.update(reaction.genes)
        
        # Print related reactions and associated genes
        print(f"Related Reactions: {', '.join(r.id for r in related_reactions)}")
        print(f"Genes Associated: {', '.join(g.id for g in related_genes)}\n")

succoa_c
-5
C25H35N7O19P3S
Succinyl-CoA
c
{'sbo': 'SBO:0000247', 'kegg.compound': 'C00091', 'seed.compound': 'cpd00078'}
Related Reactions: 3OADPCOAT, MMM, THDPS, AKGDH, OCOAT1, AKGDb, SUCOAS, HSST, rxn25164, BIOMASS, ALAS
Genes Associated: ESD82_11685, ESD82_12275, ESD82_12285, GCF08824185.1.CDS.4046, ESD82_01930, ESD82_05385, ESD82_12295, ESD82_06785, ESD82_09890, GCF08824185.1.CDS.4047, ESD82_06045, ESD82_09895

succ_c
-2
C4H4O4
Succinate
c
{'sbo': 'SBO:0000247', 'kegg.compound': 'C00042', 'seed.compound': 'cpd00036'}
Related Reactions: 3OADPCOAT, SDPDS, ICL, OCOAT1, SSALy, SUCOAS, FRDNAD, SUCD7, rxn25164, SHSL2, SUCCtex
Genes Associated: ESD82_12285, GCF08824185.1.CDS.4046, GCF08824185.1.CDS.2439, GCF08824185.1.CDS.1584, GCF08824185.1.CDS.3706, ESD82_06315, ESD82_12295, ESD82_12365, ESD82_05990, ESD82_09890, ESD82_07190, ESD82_12350, GCF08824185.1.CDS.4047, ESD82_06045, ESD82_09895

succ_e
-2
C4H4O4
Succinate
e
{'sbo': 'SBO:0000247', 'kegg.compound': 'C00042', 'seed.compound': 'cpd00036'}
Related Reactions: EX_succ_e, SUCCtex
Genes Associated:

### Search reaction

In [7]:
search_word = 'ATPM'

for reaction in model.reactions:
    if search_word in reaction.id:
        print(f"Reaction ID: {reaction.id}")
        print(f"Name: {reaction.name}")
        print(f"Equation: {reaction.reaction}")
        print(f"Lower Bound: {reaction.lower_bound}")
        print(f"Upper Bound: {reaction.upper_bound}")
        print(reaction.annotation)
        print(f"Genes: {[gene.id for gene in reaction.genes]}")

Reaction ID: R_ATPM
Name: ATP maintenance requirement
Equation: M_ATP + M_WATER --> M_ADP + M_PROTON + M_Pi
Lower Bound: 3.0
Upper Bound: 1000.0
{'sbo': 'SBO:0000176', 'kegg.reaction': 'atp non-growth associated maintenance ', 'enz_name': 'nan'}
Genes: []

Check flux through a reaction

In [48]:
# Check if the optimization was successful
if solution.status == 'optimal':
    # Check flux in a specific reaction
    reaction_id = 'NADHHYD'  # Replace with your specific reaction ID
    flux_value = solution.fluxes[reaction_id]


    # Check if there is any flux (non-zero)
    if flux_value != 0:
        print(f"The reaction {reaction_id} has a flux of {flux_value} mmol/gDW/hr.")
    else:
        print(f"There is no flux through the reaction {reaction_id}.")
else:
    print("Optimization was not successful. Check the model constraints or the objective function.")

There is no flux through the reaction NADHHYD.

In [15]:
copy_of_model.objective = 'ATPM'
solution = copy_of_model.optimize()
print(f"Flux through ATPM: {solution.objective_value} mmol/gDW/hr")

Flux through ATPM: 0.049259398600701075 mmol/gDW/hr

In [73]:
# This is a hardcoded code to check fluxes
met = 'h2_c'
[[reaction.name,reaction.id,reaction.reaction,solution.fluxes[reaction.id]] for reaction in copy_of_model.metabolites.get_by_id(met).reactions if abs(solution.fluxes[reaction.id])>0.5]

[['Bidirectional [NiFe] Hydrogenase',
  'H2ASE_syn',
  'h_c + nadph_c <=> h2_c + nadp_c',
  -14.000000000011179],
 ['Hydrogen transport diffusion (periplasm)',
  'H2tpp',
  'h2_p <=> h2_c',
  14.000000000011177]]

set the bounds

In [12]:
copy_of_model.reactions.get_by_id('HYD1pp').bounds = -0.0, 0.0

### Search in annotation

In [ ]:
for reaction in copy_of_model.reactions:
    print(reaction.annotation)

add reaction from a curated model

In [75]:
reaction_id_to_check = 'ADCYRS'
reaction = copy_of_model1.reactions.get_by_id(reaction_id_to_check)
copy_of_model.add_reactions([reaction])

### Check reaction

In [14]:
reaction_id_to_check = 'HYD1pp'
reaction = copy_of_model.reactions.get_by_id(reaction_id_to_check)
print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")
sum = 0
#reaction.name = '(S)-2-Acetolactate pyruvate-lyase (carboxylating)'
print("\nMetabolites and Stoichiometry:")
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id:<15}: {coefficient:>25}  Name: {metabolite.name:<60}  Charge: {metabolite.charge:>3}  Formula: {metabolite.formula}")
    sum += coefficient * metabolite.charge
print(f'\nSum charge: {sum}')
print("\nAssociated Genes:")
for gene in reaction.genes:
    print(gene.id)

Reaction ID: HYD1pp
Name: Hydrogenase (ubiquinone-8: 2 protons) (periplasm)
Equation: h2_c + 2.0 h_c + q8_c --> 2.0 h_p + q8h2_c
Lower Bound: 0.0
Upper Bound: 1000.0

Metabolites and Stoichiometry:
h2_c           :                      -1.0  Name: Hydrogen                                                      Charge:   0  Formula: H2
h_c            :                      -2.0  Name: H+                                                            Charge:   1  Formula: H
q8_c           :                      -1.0  Name: Ubiquinone-8                                                  Charge:   0  Formula: C49H74O4
h_p            :                       2.0  Name: H+                                                            Charge:   1  Formula: H
q8h2_c         :                       1.0  Name: Ubiquinol-8                                                   Charge:   0  Formula: C49H76O4

Sum charge: 0.0

Associated Genes:
AAFOLC_02505
AAFOLC_02510
AAFOLC_02515

<b>We found out that the model contains one reaction of three for the polyhydroxybutyrate which is 'Acetoacetyl CoA reductase' </b>

### Modify bounds of reaction

In [96]:
copy_of_model.reactions.bounds = -1000.,1000.

### Check gene

In [ ]:

# Example gene ID to check
gene_id = 'AAFOLC_14360'

# Get the gene
gene = copy_of_model.genes.get_by_id(gene_id)

# Print information about the gene
print(f"Gene ID: {gene.id}")
print(f"Name: {gene.name}")

# Print reactions associated with the gene
print("\nReactions Associated with the Gene:")
for reaction in gene.reactions:
    print(f"Reaction ID: {reaction.id}")
    print(f"Name: {reaction.name}")
    print(f"Equation: {reaction.reaction}")
    print(f"Lower Bound: {reaction.lower_bound}")
    print(f"Upper Bound: {reaction.upper_bound}")

    # Print metabolites and stoichiometry
    print("\nMetabolites and Stoichiometry:")
    for metabolite, coefficient in reaction.metabolites.items():
        print(f"{metabolite.id}: {coefficient}")

Add a new gene to the model

In [37]:
if gene_id not in copy_of_model.genes:
    new_gene = Gene(id=gene_id)
    copy_of_model.genes.append(new_gene)
else:
    new_gene = copy_of_model.genes.get_by_id(gene_id)

Add gene to specific reaction

In [38]:
reaction = copy_of_model.reactions.get_by_id('ADOCBLS')

reaction.gene_reaction_rule = gene_id
reaction.genes

frozenset({<Gene AAFOLC_14360 at 0x1ff3836b250>})

### Add annotation to reaction

In [61]:
reaction = copy_of_model.reactions.get_by_id('LINO_6_DESA')
reaction.name = 'Δ6-Desaturation of Linoleoyl-CoA'
reaction.annotation["kegg.reaction"] = "R00878"
reaction.annotation["ec-code"] = "5.3.1.5"
#reaction.annotation["metanetx.reaction"] = "MNXR95442"

print(reaction.annotation)

{'kegg.reaction': 'R03814', 'ec-code': '1.14.19.3'}

### Add annotation to gene

In [41]:
gene = copy_of_model.genes.get_by_id("AAFOLC_01125")
# Add annotations
gene.annotation["uniprot"] = "Q89CN4"

# Verify the annotation
print(gene.annotation)

{'uniprot': 'Q89CN4'}

### Add reaction

In [18]:

# more realistic fluxes by forcing TCA activity
# model.reactions.get_by_id('MDH').bounds = 0,0
# model.reactions.get_by_id('AKGMALtm').bounds = 0,0

ID = 'NADHHYD'
if ID not in copy_of_model.reactions:
    reaction = Reaction(ID)
    reaction.name = 'NADH hydrogenase'
    reaction.lower_bound =  0.
    reaction.upper_bound = 1000.
    #reaction.annotation = {'kegg.reaction':'R08181' , 'ec-code': '3.1.2.2'}
    # HAA.annotation = {'biocyc':'CPD-9436', 'chebi':'35194', 'chemspider':'6309', 'inchi':' InChI=1S/C5H8/c1-4-5(2)3/h4H,1-2H2,3H3', 'kegg.compound':'C16521', 'pubchem':'6557'}    
    h2 = copy_of_model.metabolites.get_by_id('h2_c')
    nad = copy_of_model.metabolites.get_by_id('nad_c')
    nadh = copy_of_model.metabolites.get_by_id('nadh_c')
    h = copy_of_model.metabolites.get_by_id('h_c')  
    o2 = copy_of_model.metabolites.get_by_id('o2_c')       
    reaction.add_metabolites({h2:-1.,nad:-1.,nadh:1.,h:1.})
    
    copy_of_model.add_reactions([reaction])
    

    print(copy_of_model.reactions.get_by_id(ID).id)
    print(copy_of_model.reactions.get_by_id(ID).reaction)

NADHHYD
h2_c + nad_c --> h_c + nadh_c

#### Add a sink reaction

In [93]:
copy_of_model.add_boundary(copy_of_model.metabolites.get_by_id('focytb5_c'), type='sink',lb=0.0, ub=1000)

#### Run FBA with an objective function

In [12]:
from cobra.flux_analysis import pfba
# Set the sink reaction as the objective
model.objective = "Growth"

# Perform FBA
solution = model.optimize()

# Perform parsimonious FBA (optional, to minimize overall flux)
fba_solution = pfba(model)
print(fba_solution.fluxes)

# Print the flux through the sink reaction for 3PG
print(f"Flux through the objective reaction: {fba_solution.fluxes['Growth']}")

EX_25dkglcn_e       0.000000e+00
EX_2ameph_e         0.000000e+00
EX_2m35mdntha_e     0.000000e+00
EX_2pglyc_e         0.000000e+00
EX_34dhbz_e         0.000000e+00
                        ...
THMP                6.019355e-07
STEA_9_DESA         2.901792e-04
OLEO_12_DESA        2.901792e-04
LINO_6_DESA         1.685419e-05
FACOAE1836Z9Z12Z    1.685419e-05
Name: fluxes, Length: 2387, dtype: float64
Flux through the objective reaction: 0.04630273156737808

#### Show the fluxes with a detailed description of the reaction

In [13]:
significant_reactions = [
    [
        model.reactions[RctIdx].name, 
        solution.to_frame().iloc[RctIdx].name, 
        model.reactions[RctIdx].reaction, 
        round(solution.fluxes[RctIdx], 2)
    ]
    for RctIdx in np.where(np.abs(solution.fluxes) > 3)[0]
]

# Create a DataFrame for better visualization
df = pd.DataFrame(significant_reactions, columns=["Reaction Name", "Reaction ID", "Reaction Equation", "Flux"])

# Print the DataFrame
df

C:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\Temp\ipykernel_1316\1631945521.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  round(solution.fluxes[RctIdx], 2)

,Reaction Name,Reaction ID,Reaction Equation,Flux
0,EX_h2_e,EX_h2_e,h2_e <--,-18.78
1,EX_h2o_e,EX_h2o_e,h2o_e <=>,17.54
2,EX_o2_e,EX_o2_e,o2_e <--,-6.92
3,ATP synthase (four protons for one ATP) (perip...,ATPS4rpp,adp_c + 4.0 h_p + pi_c <=> atp_c + h2o_c + 3.0...,20.78
4,Cytochrome oxidase bd (ubiquinol-8: 2 protons)...,CYTBDpp,2.0 h_c + 0.5 o2_c + q8h2_c --> h2o_c + 2.0 h_...,13.85
5,Glyceraldehyde-3-phosphate dehydrogenase,GAPD,g3p_c + nad_c + pi_c <=> 13dpg_c + h_c + nadh_c,-3.72
6,Bidirectional [NiFe] Hydrogenase,H2ASE_syn,h_c + nadph_c <=> h2_c + nadp_c,-18.78
7,H2O transport via diffusion,H2Ot,h2o_e <=> h2o_c,-17.73
8,Hydrogen transport via diffusion (extracellula...,H2tex,h2_e <=> h2_p,18.78
9,Hydrogen transport diffusion (periplasm),H2tpp,h2_p <=> h2_c,18.78
10,NADH dehydrogenase (ubiquinone-8 ),NADH5,5.0 h_c + nadh_c + q8_c --> 4.0 h_p + nad_c + ...,13.85
11,NAD transhydrogenase,NADTRHD,nad_c + nadph_c --> nadh_c + nadp_c,18.26
12,Oxygen transport via diffusion (extracellular ...,O2tex,o2_e <=> o2_p,6.92
13,O2 transport via diffusion (periplasm),O2tpp,o2_p <=> o2_c,6.92
14,Phosphoglycerate kinase,PGK,3pg_c + atp_c <=> 13dpg_c + adp_c,3.72
15,R_ATPM,ATPM,atp_c + h2o_c --> adp_c + h_c + pi_c,9.68

## Remove reaction

In [39]:
# Reaction ID to be removed
reaction_id = "SK_rb15bp_c"

# Remove the reaction from the model
copy_of_model.remove_reactions([reaction_id])

# Verify the removal
if reaction_id not in copy_of_model.reactions:
    print(f"Reaction {reaction_id} has been successfully removed.")
else:
    print(f"Failed to remove reaction {reaction_id}.")

Reaction SK_rb15bp_c has been successfully removed.

## Mass and charge balance

### Read excel files

In [70]:
file_path = 'C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified reactions.xlsx'
file_path_1 = 'C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified formula.xlsx'
file_path_2 = 'C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\Models\\Manual Curation\\Manually modified reactions.xlsx'
# Read Excel files into DataFrames
excel_data_charge = pd.read_excel(file_path)
excel_data_formula = pd.read_excel(file_path_1)
excel_data_Manualcuration = pd.read_excel(file_path_2)

### Check number of unbalanced reactions

In [4]:
used_model = model

In [5]:
print(len(cobra.manipulation.validate.check_mass_balance(used_model)))
list_reactions = cobra.manipulation.validate.check_mass_balance(used_model)
for reaction, balance_dict in list_reactions.items():
    reaction_id = reaction.id
    charge_balance = balance_dict
    print(f"Reaction ID: {reaction_id}, Charge Balance: {charge_balance}")

6
Reaction ID: DHNAOT, Charge Balance: {'charge': 2.0}
Reaction ID: HDECH, Charge Balance: {'charge': 2.0}
Reaction ID: MECDPDH4E, Charge Balance: {'charge': -1.0}
Reaction ID: P9DH, Charge Balance: {'charge': 4.0}
Reaction ID: THZSN_1, Charge Balance: {'H': -1.0}
Reaction ID: ACACDC, Charge Balance: {'charge': -1.0, 'C': -1.0, 'H': -3.0, 'O': 1.0}

### Reaction information

In [6]:
reaction_id_to_check = 'DHNAOT'
reaction = model.reactions.get_by_id(reaction_id_to_check)
print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")
sum = 0
#reaction.name = '(S)-2-Acetolactate pyruvate-lyase (carboxylating)'
print("\nMetabolites and Stoichiometry:")
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id:<15}: {coefficient:>25}  Name: {metabolite.name:<60}  Charge: {metabolite.charge:>3}  Formula: {metabolite.formula}")
    sum += coefficient * metabolite.charge
print(f'\nSum charge: {sum}')
print("\nAssociated Genes:")
for gene in reaction.genes:
    print(gene.id)

Reaction ID: DHNAOT
Name: 1,4-dihydroxy-2-naphthoate octaprenyltransferase
Equation: dhna_c + octdp_c --> 2dmmq8_c + co2_c + h_c + ppi_c
Lower Bound: 0.0
Upper Bound: 1000.0

Metabolites and Stoichiometry:
dhna_c         :                      -1.0  Name: 1,4-Dihydroxy-2-naphthoate                                    Charge:  -1  Formula: C11H7O4
octdp_c        :                      -1.0  Name: All-trans-Octaprenyl diphosphate                              Charge:  -3  Formula: C40H65O7P2
2dmmq8_c       :                       1.0  Name: 2-Demethylmenaquinone 8                                       Charge:   0  Formula: C50H70O2
co2_c          :                       1.0  Name: CO2 CO2                                                       Charge:   0  Formula: CO2
h_c            :                       1.0  Name: H+                                                            Charge:   1  Formula: H
ppi_c          :                       1.0  Name: Diphosphate                                                   Charge:  -3  Formula: HO7P2

Sum charge: 2.0

Associated Genes:

### Add metabolite

In [74]:
new_metabolite = Metabolite(
    id='octadecacid_c',     # Metabolite ID
    name='Octadecanoic acid',     # Metabolite Name
    formula='C18H36O2',         # Chemical Formula
    compartment='c'            # Compartment (e.g., cytoplasm)
)

new_metabolite.charge = 0

copy_of_model.add_metabolites([new_metabolite])

print(new_metabolite.formula)

C18H36O2

In [34]:
reaction = model.reactions.get_by_id('CYTBDpp')
metabolite_to_add = 'h_c'
reaction.add_metabolites({metabolite_to_add: -4.0})
model.slim_optimize()

0.0771000434189166

In [14]:
model.slim_optimize()

0.04925939860069994

Add modification to Excel file

In [ ]:
modification =f'{metabolite_to_add} was added'
# Create a new row with the modification information
new_row = {'reaction ': reaction_id_to_check, 'modification': modification}
# Concatenate the new row to the DataFrame
excel_data_Manualcuration = pd.concat([excel_data_Manualcuration, pd.DataFrame([new_row])], ignore_index=True)

### Remove metabolite

In [46]:
reaction = copy_of_model.reactions.get_by_id('Growth')
metabolite_to_add = 'pe161_p'
reaction.subtract_metabolites({metabolite_to_add: -0.02106})
print(reaction.reaction)

0.000223 10fthf_c + 0.000223 2dmmql8_c + 0.000223 5mthf_c + 0.000279 accoa_c + 0.8168723181883314 ala__L_c + 0.000223 amet_c + 0.03001579312991268 arab__L_c + 0.2557979323259868 arg__L_c + 0.2529593526847482 asn__L_c + 0.2529593526847482 asp__L_c + 37.86 atp_c + 0.004952 ca2_c + 0.000223 chor_c + 0.004952 cl_c + 0.002944 clpn160_p + 0.00229 clpn161_p + 0.00118 clpn181_p + 0.000168 coa_c + 2.4e-05 cobalt2_c + 0.010737250405651103 ctp_c + 0.006744 cu2_c + 0.037472225353906465 cys__L_c + 0.014832979735072188 datp_c + 0.0154992827580827 dctp_c + 0.02400546922059191 dgtp_c + 0.013367475433835764 dttp_c + 0.000223 fad_c + 0.006388 fe2_c + 0.007428 fe3_c + 0.6445556055168562 fru_c + 0.005772 gal_c + 0.11736684160157697 glc__D_c + 0.2753206379465721 gln__L_c + 0.275320637946572 glu__L_c + 0.6379660350235106 gly_c + 0.01659016153669234 gtp_c + 37.86 h2o_c + 0.000223 hemeO_c + 0.049934570136758984 hexadecacid_c + 0.007033277906537638 hexedecacid_c + 0.09352200626083922 his__L_c + 0.24506430675451657 ile__L_c + 0.18569 k_c + 0.019456 kdo2lipid4_p + 0.4809387020057383 leu__L_c + 0.005902952960848603 lnlc_c + 0.0003641921623863511 lnlncg_c + 0.25760196352578224 lys__L_c + 3.1e-05 malcoa_c + 0.004810116459081017 man_c + 0.14267468516500864 met__L_c + 0.008253 mg2_c + 0.000223 mlthf_c + 0.000658 mn2_c + 7e-06 mobd_c + 0.000223 mql8_c + 0.000605 murein3px4p_p + 0.001345 murein4p3p_p + 0.005381 murein4p4p_p + 0.005448 murein4px4p_p + 0.000673 murein4px4px4p_p + 0.013894 murein5px4p_p + 0.0005023142220720257 nac_c + 0.001787 nad_c + 4.5e-05 nadh_c + 0.000112 nadp_c + 0.000335 nadph_c + 0.012379 nh4_c + 0.007173968847108888 octadecacid_c + 0.13197873979176503 octedecacid_c + 0.044164 pe160_p + 0.017704 pe181_p + 0.010599 pg160_p + 0.008244 pg161_p + 0.22846254459317583 phe__L_c + 0.000223 pheme_c + 8.609379583094386e-05 pnto__R_c + 0.28911581930944585 pro__L_c + 0.03327 ptrc_c + 0.000223 pydx5p_c + 5.42885385395863e-05 rbflvrd_c + 0.000223 ribflv_c + 0.29855906692147155 ser__L_c + 0.000223 sheme_c + 0.004126 so4_c + 9.8e-05 succoa_c + 0.000223 thf_c + 1.3154306833538052e-05 thm_c + 0.000223 thmpp_c + 0.33085175798343425 thr__L_c + 0.08097676930208217 trp__L_c + 0.0005942465517650057 ttdca_c + 0.1593258444308896 tyr__L_c + 0.006775403427840368 utp_c + 0.4108677675755479 val__L_c + 0.005772267909598585 xyl__D_c + 0.000324 zn2_c --> 37.86 adp_c + 37.86 h_c + 37.86 pi_c + 0.110381072928369 ppi_c

Add modification to Excel file

In [217]:
modification =f'{metabolite_to_add} was removed'
# Create a new row with the modification information
new_row = {'reaction ': reaction_id_to_check, 'modification': modification}
# Concatenate the new row to the DataFrame
excel_data_Manualcuration = pd.concat([excel_data_Manualcuration, pd.DataFrame([new_row])], ignore_index=True)

### Change charge of metabolite

In [18]:
metabolite_id = 'gam_c'
if metabolite_id in model.metabolites:
    metabolite = used_model.metabolites.get_by_id(metabolite_id)
    initial_charge = metabolite.charge  # Store the initial charge for reference
    metabolite.charge = 1
    metabolite.compartment = 'c'
    
    print(list(metabolite.reactions))  
    # Print information about the modified metabolite
    print(f"Modified metabolite: {metabolite.id}")
    print(f"Updated charge: {metabolite.charge}")
    print(f"Updated charge: {metabolite.compartment}")
else:
    print("Metabolite not found in the model.")

Metabolite not found in the model.

#### Add to excel file

In [155]:
# Create a dictionary containing information about the modified reaction
new_row = {'Reaction': reaction_id_to_check, 'metabolite changed': metabolite_id, 'initial charge': initial_charge, 'New charge': metabolite.charge}
excel_data_charge = pd.concat([excel_data_charge, pd.DataFrame([new_row])], ignore_index=True)
excel_data_charge

         Reaction metabolite changed  initial charge  New charge
0    2AGPG161tipp         2agpg161_c               0          -1
1          3HACPH          r3hbACP_c               0          -1
2         3HAD140        tmrs2eACP_c               0          -1
3   4HOXPACt2pp_1          4hoxpac_p               0          -1
4       4OXPTNtpp           4oxptn_p               0          -1
5       4OXPTNtex           4oxptn_e               0          -1
6      4hoxpactex          4hoxpac_e               0          -1
7       6ATHAtexi            6atha_e               0          -1
8            AADa              aad_c               0          -1
9          ACLS_b          hethmpp_c              -1          -2
10       AEPPYRTA             Pald_c               0          -2
11          AHGDx          S2hglut_c               0          -2
12          AKGDa           sdhlam_c               0          -1
13         ALCDpp            pqqh2_p              -4          -3
14         APAT_1             ppad_c               0          -1
15        CMCBTFL           cmcbtt_c               0           1
16        CMCBTFL          fcmcbtt_c               0           4
17       RHA50tpp           R_3hpt_p               0          -1
18       RHA50tex           R_3hpt_e               0          -1
19      RHAP40tpp          R_3hpba_p               0          -1
20      RHAP40tex          R_3hpba_e               0          -1

### Change formula of metabolite

In [256]:
metabolite_id = 'Cytochrome b5 Synthesis:'
metabolite = used_model.metabolites.get_by_id(metabolite_id)
initial_formula = metabolite.formula
metabolite.formula = 'C18H43O10'

#### Add to excel file

In [186]:
new_row_1 = {
    'Reaction': reaction_id_to_check,        # ID of the reaction associated with the metabolite change
    'metabolite changed': metabolite_id,     # ID of the metabolite that was changed
    'initial formula': initial_formula,      # Initial formula of the metabolite
    'New formula': metabolite.formula        # New formula of the metabolite after modification
}
excel_data_formula = pd.concat([excel_data_formula, pd.DataFrame([new_row_1])], ignore_index=False)

excel_data_formula = excel_data_formula.reset_index(drop=True)

In [ ]:
excel_data_formula

### Save updated files

#### Save Excel

In [264]:
# Save the updated DataFrame to the Excel file
excel_data_charge.to_excel(file_path, index=False)
excel_data_formula.to_excel(file_path_1, index=False)
excel_data_Manualcuration.to_excel(file_path_2, index=False)

#### Save model in SBML

In [ ]:
sbml_filename = "C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.09 Models\\Manual Curation\\Biomass Equation\\ATPM_update.sbml"
cobra.io.write_sbml_model(copy_of_model, sbml_filename)

## Exchange reaction

In [47]:
copy_of_model = model.copy()

In [89]:
# set exchange reactions bounds to zero if they significally affect the growth
ex_list = []

not_to_change_list = ['EX_ca2_e','EX_cl_e','EX_cobalt2_e','EX_cu2_e','EX_h2o_e','EX_h2_e','EX_fe_e','EX_fe2_e','EX_fe3_e'
                      ,'EX_k_e','EX_mg2_e','EX_mn2_e','EX_zn2_e','EX_o2_e','EX_so4_e','EX_pi_e','EX_nh4_e','EX_mobd_e','EX_ni2_e']

for element in copy_of_model.exchanges:
    reaction = copy_of_model.reactions.get_by_id(element.id)
    
    # Iterate over metabolites associated with the reaction
    for metabolite, coefficient in reaction.metabolites.items():
        if element.id not in not_to_change_list:
            # Set reaction bounds to zero
            reaction.bounds = 0.0, 0.0
            
            # Optimize the model
            solution = copy_of_model.slim_optimize()
            
            # Check if the solution is not zero
            if solution != 0.0:
                ex_list.append(reaction.id)
                
            # Print reaction information
            print(reaction.name)
            print(solution)

EX_25dkglcn_e
0.0
EX_2ameph_e
0.0
EX_2m35mdntha_e
0.0
EX_2pglyc_e
0.0
EX_34dhbz_e
0.0
EX_35dnta_e
0.0
EX_3cmp_e
0.0
EX_3h4atb_e
0.0
EX_4abut_e
0.0
EX_4abz_e
0.0
EX_4hba_e
0.0
EX_4hoxpac_e
0.0
EX_4hphac_e
0.0
EX_4hpro_DC_e
0.0
EX_4hpro_LT_e
0.0
EX_4oxptn_e
0.0
EX_5drib_e
0.0
EX_5mcsn_e
0.0
EX_6atha_e
0.0
EX_LalaDgluMdapDala_e
0.0
EX_LalaLglu_e
0.0
EX_Lcyst_e
0.0
EX_Ncbmpts_e
0.0
EX_R_3hhpa_e
0.0
EX_R_3hnonaa_e
0.0
EX_R_3hpba_e
0.0
EX_R_3hpdeca_e
0.0
EX_R_3hphpa_e
0.0
EX_R_3hpnona_e
0.0
EX_R_3hpocta_e
0.0
EX_R_3hpt_e
0.0
EX_R_3htd58e_e
0.0
EX_abt_e
0.0
EX_ac_e
0.0
EX_acald_e
0.0
EX_acgam_e
0.0
EX_acmana_e
0.0
EX_acnam_e
0.0
EX_acon_C_e
0.0
EX_actn__R_e
0.0
EX_ade_e
0.0
EX_agm_e
0.0
EX_ala__D_e
0.0
EX_ala__L_e
0.0
EX_alahis_e
0.0
EX_alaleu_e
0.0
EX_alathr_e
0.0
EX_alatrp_e
0.0
EX_anhgm_e
0.0
EX_apc_e
0.0
EX_arab__L_e
0.0
EX_arbt6p_e
0.0
EX_arbt_e
0.0
EX_arg__L_e
0.0
EX_ascb__L_e
0.0
EX_asn__L_e
0.0
EX_aso3_e
0.0
EX_aso4_e
0.0
EX_asp__L_e
0.0
EX_bhb_e
0.0
EX_bz_e
0.0
EX_carn_e
0.0
EX_cd2_e
0.0
EX_cellb_e
0.0
EX_cgly_e
0.0
EX_chol_e
0.0
EX_chols_e
0.0
EX_chtbs_e
0.0
EX_cinnm_e
0.0
EX_cm_e
0.0
EX_co2_e
0.0
EX_co_e
0.0
EX_coa_e
0.0
EX_crn_e
0.0
EX_csn_e
0.0
EX_cyan_e
0.0
EX_cynt_e
0.0
EX_cys__L_e
0.0
EX_dca_e
0.0
EX_ddca_e
0.0
EX_dextrin_e
0.0
EX_drib_e
0.0
EX_dxyl_e
0.0
EX_enter_e
0.0
EX_fald_e
0.0
EX_fe3dcit_e
0.0
EX_fe3pyovd_kt_e
0.0
EX_feenter_e
0.0
EX_fol_e
0.0
EX_for_e
0.0
EX_frmd_e
0.0
EX_fru_e
0.0
EX_fuc_e
0.0
EX_gal_bD_e
0.0
EX_gal_e
0.0
EX_galt_e
0.0
EX_galur_e
0.0
EX_gam_e
0.0
EX_glc__D_e
0.0
EX_glc__aD_e
0.0
EX_glcr_e
0.0
EX_glcur_e
0.0
EX_gln__L_e
0.0
EX_glu__L_e
0.0
EX_gly_e
0.0
EX_glyb_e
0.0
EX_glyc2p_e
0.0
EX_glyc3p_e
0.0
EX_glyclt_e
0.0
EX_glygln_e
0.0
EX_glyglu_e
0.0
EX_glygly_e
0.0
EX_glymet_e
0.0
EX_glyphe_e
0.0
EX_glyser_e
0.0
EX_gthrd_e
0.0
EX_gua_e
0.0
EX_h2o2_e
0.0
EX_h2s_e
0.0
EX_h_e
0.0
EX_hco3_e
0.0
EX_hdca_e
0.0
EX_hdcea_e
0.0
EX_hexs_e
0.0
EX_his__L_e
0.0
EX_hisgly_e
0.0
EX_hishis_e
0.0
EX_hpta_e
0.0
EX_hxa_e
0.0
EX_icit_e
0.0
EX_ile__L_e
0.0
EX_ind3ac_e
0.0
EX_indole_e
0.0
EX_inost_e
0.0
EX_lcts_e
0.0
EX_leu__D_e
0.0
EX_leu__L_e
0.0
EX_leuleu_e
0.0
EX_lnlc_e
0.0
EX_lys__L_e
0.0
EX_m_xyl_e
0.0
EX_malt_e
0.0
EX_malthp_e
0.0
EX_malthx_e
0.0
EX_malttr_e
0.0
EX_maltttr_e
0.0
EX_man_e
0.0
EX_melib_e
0.0
EX_met__D_e
0.0
EX_met__L_e
0.0
EX_metox__R_e
0.0
EX_metox_e
0.0
EX_mnl_e
0.0
EX_mso3_e
0.0
EX_na1_e
0.0
EX_nmn_e
0.0
EX_no2_e
0.0
EX_no3_e
0.0
EX_no_e
0.0
EX_nona_e
0.0
EX_novbcn_e
0.0
EX_ocdca_e
0.0
EX_ocdcea_e
0.0
EX_octa_e
0.0
EX_orn__D_e
0.0
EX_orn_e
0.0
EX_p_xyl_e
0.0
EX_pea_e
0.0
EX_peamn_e
0.0
EX_pentso3_e
0.0
EX_phe__L_e
0.0
EX_phedca_e
0.0
EX_phehpa_e
0.0
EX_phehxa_e
0.0
EX_pheme_e
0.0
EX_phenona_e
0.0
EX_pheocta_e
0.0
EX_phept_e
0.0
EX_ppap_e
0.0
EX_pro__L_e
0.0
EX_progly_e
0.0
EX_pta_e
0.0
EX_ptrc_e
0.0
EX_ptsla_e
0.0
EX_pydam_e
0.0
EX_pydxn_e
0.0
EX_pyovd_kt_e
0.0
EX_raffin_e
0.0
EX_rib__D_e
0.0
EX_rmn_e
0.0
EX_rnam_e
0.0
EX_s_e
0.0
EX_salchs4_e
0.0
EX_salchs4fe_e
0.0
EX_sbt__D_e
0.0
EX_sel_e
0.0
EX_ser__L_e
0.0
EX_sheme_e
0.0
EX_slnt_e
0.0
EX_so3_e
0.0
EX_spmd_e
0.0
EX_sucr_e
0.0
EX_tartr__D_e
0.0
EX_taur_e
0.0
EX_tcynt_e
0.0
EX_tet_e
0.0
EX_thr__L_e
0.0
EX_tnt_e
0.0
EX_tol_e
0.0
EX_tre_e
0.0
EX_trp__L_e
0.0
EX_tsul_e
0.0
EX_ttdca_e
0.0
EX_ttdcea_e
0.0
EX_ttrcyc_e
0.0
EX_tyr__D_e
0.0
EX_tyr__L_e
0.0
EX_urate_e
0.0
EX_urea_e
0.0
EX_vacc_e
0.0
EX_val__D_e
0.0
EX_val__L_e
0.0
EX_vanln_e
0.0
EX_xyl__D_e
0.0
EX_glcn_e
0.0
EX_n2_e
0.0
EX_succ_e
0.0
EX_etoh_e
0.0

In [90]:
# change bounds of the exchange reactions
for element in reaction:
    reaction = copy_of_model.reactions.get_by_id(element)
    for metabolite, coefficient in reaction.metabolites.items():
        print(reaction.name)
        print(metabolite.name)
        print(metabolite.formula)
        reaction.bounds = -1000.0 , 1000.0

In [ ]:
# set reactions bounds for a specific reaction 
reaction = copy_of_model.reactions.get_by_id('EX_co2_e')
reaction.bounds = -1000.0, 1000.0

In [82]:
# set reactions bounds for a specific reaction 
reaction = copy_of_model.reactions.get_by_id('EX_h2_e')
reaction.bounds = -10.0, 10.0

In [88]:
solution = copy_of_model.slim_optimize()

copy_of_model.summary()

## Biomass Equation Curation

Updating the coefficient and adding metabolites from the Solar Food Biomass Equation

In [6]:
file_path = 'C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.09 Models\\Manual_curation\\Biomass_equation\\Biomass_equation.xlsx'
# Read Excel files into DataFrames
pd_biomass = pd.read_excel(file_path)
pd_biomass

,Biomass_equation,Unnamed: 1,molar mass g/mol,measured mmol/g,Unmeasured mmol/g,unmeasured g/g,measured g/g,GAM,normalized g/g,normalized_mmol/g
0,10fthf_c,10-Formyltetrahydrofolate,471.43007,NaN,-0.000223,-0.000105,NaN,NaN,0.000000,-0.000223
1,pydx5p_c,Pyridoxal 5'-phosphate,245.12862,NaN,-0.000223,-0.000055,NaN,NaN,0.000000,-0.000223
2,murein3px4p_p,"Two disacharide linked murein units, tripeptid...",1750.69809,NaN,-0.000605,-0.001059,NaN,NaN,0.000000,-0.000605
3,thr__L_c,L-Threonine,119.12063,-0.381786,NaN,0.000000,-0.045479,NaN,-0.039411,-0.330852
4,adocbl_c,Adenosylcobalamin,1579.60636,NaN,-0.000223,-0.000352,NaN,NaN,0.000000,-0.000223
...,...,...,...,...,...,...,...,...,...,...
124,tmndnc_c,"Timnodonic acid C20:5, n-3",302.50000,-0.000044,NaN,0.000000,-0.000013,NaN,-0.000011,-0.000038
125,doco13ac_c,13Z)-13-docosenoic acid,338.60000,-0.000077,NaN,0.000000,-0.000026,NaN,-0.000023,-0.000067
126,ttc_c,Tetracosanoate n C240 C24H47O2,368.60000,-0.000035,NaN,0.000000,-0.000013,NaN,-0.000011,-0.000030
127,lnlc_c,Linoleic acid (all cis C18:2) n-6,280.40000,-0.000222,NaN,0.000000,-0.000062,NaN,-0.000054,-0.000193
128,lnlncg_c,Gamma-linolenic acid,278.40000,-0.000968,NaN,0.000000,-0.000269,NaN,-0.000233,-0.000838

Change the coeff from the excel file of the already exisiting metabolite of the growth equation

In [8]:
i = 0
reaction = model.reactions.get_by_id('Growth')
for element in pd_biomass.Biomass_equation:
    found = False
    for metabolite, coefficient in reaction.metabolites.items():
        if element == metabolite.id:
            found = True
            # Get the value of the 'normalized_mmol/g' column for the current metabolite
            normalized_mmol_g = pd_biomass.loc[pd_biomass['Biomass_equation'] == element, 'normalized_mmol/g'].values[0]
            print(f'The metabolite from the solar food BE = {element} coefficient {normalized_mmol_g}')
            print(f'The metabolite from the model = {metabolite.id} initial coefficient {coefficient}')
            initial_coefficient = coefficient
            # Update the coefficient of the metabolite in the reaction
            reaction.add_metabolites({metabolite: normalized_mmol_g}, combine=False)
            updated_coefficient = reaction.metabolites[metabolite]  # Get the updated coefficient
            print(f'The coefficient was updated {initial_coefficient} ------> {updated_coefficient}')
            i += 1
            solution = model.slim_optimize()
            print(solution)
    if not found:
        pass
print(i)

The metabolite from the solar food BE = 10fthf_c coefficient -0.000223
The metabolite from the model = 10fthf_c initial coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.038488100878657526
The metabolite from the solar food BE = pydx5p_c coefficient -0.000223
The metabolite from the model = pydx5p_c initial coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.03848810087865847
The metabolite from the solar food BE = murein3px4p_p coefficient -0.000605
The metabolite from the model = murein3px4p_p initial coefficient -0.000605
The coefficient was updated -0.000605 ------> -0.000605
0.03848810087865847
The metabolite from the solar food BE = thr__L_c coefficient -0.33085175798343425
The metabolite from the model = thr__L_c initial coefficient -0.253687
The coefficient was updated -0.253687 ------> -0.33085175798343425
0.038333584225925706
The metabolite from the solar food BE = h_c coefficient 29.1804227450256
The metabolite from the model = h_c initial coefficient 75.72
The coefficient was updated 75.72 ------> 29.1804227450256
0.042070683287216776
The metabolite from the solar food BE = thmpp_c coefficient -0.000223
The metabolite from the model = thmpp_c initial coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.0420706832872175
The metabolite from the solar food BE = mn2_c coefficient -0.000658
The metabolite from the model = mn2_c initial coefficient -0.000691
The coefficient was updated -0.000691 ------> -0.000658
0.04207068487266963
The metabolite from the solar food BE = sheme_c coefficient -0.000223
The metabolite from the model = sheme_c initial coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.04207068487266963
The metabolite from the solar food BE = ser__L_c coefficient -0.29855906692147155
The metabolite from the model = ser__L_c initial coefficient -0.215792
The coefficient was updated -0.215792 ------> -0.29855906692147155
0.04194382171918742
The metabolite from the solar food BE = ctp_c coefficient -0.010737250405651103
The metabolite from the model = ctp_c initial coefficient -0.133508
The coefficient was updated -0.133508 ------> -0.010737250405651103
0.042701864726916
The metabolite from the solar food BE = accoa_c coefficient -0.000279
The metabolite from the model = accoa_c initial coefficient -0.000279
The coefficient was updated -0.000279 ------> -0.000279
0.042701864726916
The metabolite from the solar food BE = arg__L_c coefficient -0.2557979323259868
The metabolite from the model = arg__L_c initial coefficient -0.295792
The coefficient was updated -0.295792 ------> -0.2557979323259868
0.04283690078483552
The metabolite from the solar food BE = asp__L_c coefficient -0.2529593526847482
The metabolite from the model = asp__L_c initial coefficient -0.241055
The coefficient was updated -0.241055 ------> -0.2529593526847482
0.0428179346034863
The metabolite from the solar food BE = murein4p3p_p coefficient -0.001345
The metabolite from the model = murein4p3p_p initial coefficient -0.001345
The coefficient was updated -0.001345 ------> -0.001345
0.0428179346034863
The metabolite from the solar food BE = 5mthf_c coefficient -0.000223
The metabolite from the model = 5mthf_c initial coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.0428179346034863
The metabolite from the solar food BE = nad_c coefficient -0.001787
The metabolite from the model = nad_c initial coefficient -0.001831
The coefficient was updated -0.001831 ------> -0.001787
0.04281856962570967
The metabolite from the solar food BE = mg2_c coefficient -0.008253
The metabolite from the model = mg2_c initial coefficient -0.008675
The coefficient was updated -0.008675 ------> -0.008253
0.04281856962570967
The metabolite from the solar food BE = adp_c coefficient 29.1804227450256
The metabolite from the model = adp_c initial coefficient 75.72
The coefficient was updated 75.72 ------> 29.1804227450256
0.003952152447655952
The metabolite from the solar food BE = met__L_c coefficient -0.14267468516500864
The metabolite from the model = met__L_c initial coefficient -0.153686
The coefficient was updated -0.153686 ------> -0.14267468516500864
0.003952259828437731
The metabolite from the solar food BE = nh4_c coefficient -0.012379
The metabolite from the model = nh4_c initial coefficient -0.012379
The coefficient was updated -0.012379 ------> -0.012379
0.003952259828437731
The metabolite from the solar food BE = pi_c coefficient 29.1804227450256
The metabolite from the model = pi_c initial coefficient 75.72
The coefficient was updated 75.72 ------> 29.1804227450256
0.0039326248324050034
The metabolite from the solar food BE = chor_c coefficient -0.000223
The metabolite from the model = chor_c initial coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.0039326248324050034
The metabolite from the solar food BE = zn2_c coefficient -0.000324
The metabolite from the model = zn2_c initial coefficient -0.000341
The coefficient was updated -0.000341 ------> -0.000324
0.0039326248324050034
The metabolite from the solar food BE = tyr__L_c coefficient -0.1593258444308896
The metabolite from the model = tyr__L_c initial coefficient -0.137896
The coefficient was updated -0.137896 ------> -0.1593258444308896
0.003931491623929871
The metabolite from the solar food BE = cys__L_c coefficient -0.037472225353906465
The metabolite from the model = cys__L_c initial coefficient -0.09158
The coefficient was updated -0.09158 ------> -0.037472225353906465
0.003931559729642925
The metabolite from the solar food BE = amet_c coefficient -0.000223
The metabolite from the model = amet_c initial coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.003931559729642925
The metabolite from the solar food BE = trp__L_c coefficient -0.08097676930208217
The metabolite from the model = trp__L_c initial coefficient -0.056843
The coefficient was updated -0.056843 ------> -0.08097676930208217
0.003929859307711171
The metabolite from the solar food BE = lys__L_c coefficient -0.25760196352578224
The metabolite from the model = lys__L_c initial coefficient -0.343161
The coefficient was updated -0.343161 ------> -0.25760196352578224
0.003932658960378649
The metabolite from the solar food BE = atp_c coefficient -29.190681913288
The metabolite from the model = atp_c initial coefficient -75.72
The coefficient was updated -75.72 ------> -29.190681913288
0.048487468086792815
The metabolite from the solar food BE = thf_c coefficient -0.000223
The metabolite from the model = thf_c initial coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.048487468086795826
The metabolite from the solar food BE = dttp_c coefficient -0.013367475433835764
The metabolite from the model = dttp_c initial coefficient -0.026166
The coefficient was updated -0.026166 ------> -0.013367475433835764
0.04860126544213119
The metabolite from the solar food BE = dctp_c coefficient -0.0154992827580827
The metabolite from the model = dctp_c initial coefficient -0.027017
The coefficient was updated -0.027017 ------> -0.0154992827580827
0.0487026489979179
The metabolite from the solar food BE = cobalt2_c coefficient -2.4e-05
The metabolite from the model = cobalt2_c initial coefficient -0.0001
The coefficient was updated -0.0001 ------> -2.4e-05
0.048702668571005706
The metabolite from the solar food BE = utp_c coefficient -0.006775403427840368
The metabolite from the model = utp_c initial coefficient -0.144104
The coefficient was updated -0.144104 ------> -0.006775403427840368
2.812487755450263e-15
The metabolite from the solar food BE = k_c coefficient -0.18569
The metabolite from the model = k_c initial coefficient -0.195193
The coefficient was updated -0.195193 ------> -0.18569
1.20558036495179e-14
The metabolite from the solar food BE = fe2_c coefficient -0.006388
The metabolite from the model = fe2_c initial coefficient -0.006715
The coefficient was updated -0.006715 ------> -0.006388
1.306700844755146e-14
The metabolite from the solar food BE = datp_c coefficient -0.014832979735072188
The metabolite from the model = datp_c initial coefficient -0.026166
The coefficient was updated -0.026166 ------> -0.014832979735072188
1.1042912994730757e-14
The metabolite from the solar food BE = ppi_c coefficient 0.110381072928369
The metabolite from the model = ppi_c initial coefficient 0.773903
The coefficient was updated 0.773903 ------> 0.110381072928369
0.05013787927688252
The metabolite from the solar food BE = nadp_c coefficient -0.000112
The metabolite from the model = nadp_c initial coefficient -0.000447
The coefficient was updated -0.000447 ------> -0.000112
0.050145538209520876
The metabolite from the solar food BE = glu__L_c coefficient -0.275320637946572
The metabolite from the model = glu__L_c initial coefficient -0.26316
The coefficient was updated -0.26316 ------> -0.275320637946572
0.050089158649340146
The metabolite from the solar food BE = ile__L_c coefficient -0.24506430675451657
The metabolite from the model = ile__L_c initial coefficient -0.290529
The coefficient was updated -0.290529 ------> -0.24506430675451657
0.05031933728579516
The metabolite from the solar food BE = hemeO_c coefficient -0.000223
The metabolite from the model = hemeO_c initial coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.05031933728579516
The metabolite from the solar food BE = murein4p4p_p coefficient -0.005381
The metabolite from the model = murein4p4p_p initial coefficient -0.005381
The coefficient was updated -0.005381 ------> -0.005381
0.05031933728579516
The metabolite from the solar food BE = gln__L_c coefficient -0.2753206379465721
The metabolite from the model = gln__L_c initial coefficient -0.26316
The coefficient was updated -0.26316 ------> -0.2753206379465721
0.05025923098706838
The metabolite from the solar food BE = fe3_c coefficient -0.007428
The metabolite from the model = fe3_c initial coefficient -0.007808
The coefficient was updated -0.007808 ------> -0.007428
0.050259152821369134
The metabolite from the solar food BE = ala__L_c coefficient -0.8168723181883314
The metabolite from the model = ala__L_c initial coefficient -0.513689
The coefficient was updated -0.513689 ------> -0.8168723181883314
0.049481426756381834
The metabolite from the solar food BE = phe__L_c coefficient -0.22846254459317583
The metabolite from the model = phe__L_c initial coefficient -0.185265
The coefficient was updated -0.185265 ------> -0.22846254459317583
0.04912231384945891
The metabolite from the solar food BE = mlthf_c coefficient -0.000223
The metabolite from the model = mlthf_c initial coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.04912231384945891
The metabolite from the solar food BE = 2dmmql8_c coefficient -0.000223
The metabolite from the model = 2dmmql8_c initial coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.04912231384945891
The metabolite from the solar food BE = cu2_c coefficient -0.006744
The metabolite from the model = cu2_c initial coefficient -0.000709
The coefficient was updated -0.000709 ------> -0.006744
0.0491207327423272
The metabolite from the solar food BE = h2o_c coefficient -29.1804227450256
The metabolite from the model = h2o_c initial coefficient -75.72
The coefficient was updated -75.72 ------> -29.1804227450256
0.04912073274232807
The metabolite from the solar food BE = ca2_c coefficient -0.004952
The metabolite from the model = ca2_c initial coefficient -0.005205
The coefficient was updated -0.005205 ------> -0.004952
0.04912079902365478
The metabolite from the solar food BE = gly_c coefficient -0.6379660350235106
The metabolite from the model = gly_c initial coefficient -0.612638
The coefficient was updated -0.612638 ------> -0.6379660350235106
0.049077706204821187
The metabolite from the solar food BE = malcoa_c coefficient -3.1e-05
The metabolite from the model = malcoa_c initial coefficient -3.1e-05
The coefficient was updated -3.1e-05 ------> -3.1e-05
0.049077706204821187
The metabolite from the solar food BE = murein4px4p_p coefficient -0.005448
The metabolite from the model = murein4px4p_p initial coefficient -0.005448
The coefficient was updated -0.005448 ------> -0.005448
0.049077706204821187
The metabolite from the solar food BE = mql8_c coefficient -0.000223
The metabolite from the model = mql8_c initial coefficient -0.0001
The coefficient was updated -0.0001 ------> -0.000223
0.04907243134209144
The metabolite from the solar food BE = cl_c coefficient -0.004952
The metabolite from the model = cl_c initial coefficient -0.005205
The coefficient was updated -0.005205 ------> -0.004952
0.04907243134209144
The metabolite from the solar food BE = his__L_c coefficient -0.09352200626083922
The metabolite from the model = his__L_c initial coefficient -0.094738
The coefficient was updated -0.094738 ------> -0.09352200626083922
0.04908213046648787
The metabolite from the solar food BE = ribflv_c coefficient -0.000223
The metabolite from the model = ribflv_c initial coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.04908213046648787
The metabolite from the solar food BE = so4_c coefficient -0.004126
The metabolite from the model = so4_c initial coefficient -0.004338
The coefficient was updated -0.004338 ------> -0.004126
0.04908214432967779
The metabolite from the solar food BE = ptrc_c coefficient -0.03327
The metabolite from the model = ptrc_c initial coefficient -0.03327
The coefficient was updated -0.03327 ------> -0.03327
0.04908214432967779
The metabolite from the solar food BE = gtp_c coefficient -0.01659016153669234
The metabolite from the model = gtp_c initial coefficient -0.215096
The coefficient was updated -0.215096 ------> -0.01659016153669234
0.05160712822486658
The metabolite from the solar food BE = pheme_c coefficient -0.000223
The metabolite from the model = pheme_c initial coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.05160712822486658
The metabolite from the solar food BE = nadph_c coefficient -0.000335
The metabolite from the model = nadph_c initial coefficient -0.000335
The coefficient was updated -0.000335 ------> -0.000335
0.05160712822486658
The metabolite from the solar food BE = val__L_c coefficient -0.4108677675755479
The metabolite from the model = val__L_c initial coefficient -0.423162
The coefficient was updated -0.423162 ------> -0.4108677675755479
0.05166229236494034
The metabolite from the solar food BE = pro__L_c coefficient -0.28911581930944585
The metabolite from the model = pro__L_c initial coefficient -0.221055
The coefficient was updated -0.221055 ------> -0.28911581930944585
0.05135837592350357
The metabolite from the solar food BE = mobd_c coefficient -7e-06
The metabolite from the model = mobd_c initial coefficient -7e-06
The coefficient was updated -7e-06 ------> -7e-06
0.05135837592350357
The metabolite from the solar food BE = nadh_c coefficient -4.5e-05
The metabolite from the model = nadh_c initial coefficient -4.5e-05
The coefficient was updated -4.5e-05 ------> -4.5e-05
0.05135837592350357
The metabolite from the solar food BE = coa_c coefficient -0.000168
The metabolite from the model = coa_c initial coefficient -0.000576
The coefficient was updated -0.000576 ------> -0.000168
0.05136766705882969
The metabolite from the solar food BE = asn__L_c coefficient -0.2529593526847482
The metabolite from the model = asn__L_c initial coefficient -0.241055
The coefficient was updated -0.241055 ------> -0.2529593526847482
0.05131655954111775
The metabolite from the solar food BE = leu__L_c coefficient -0.4809387020057383
The metabolite from the model = leu__L_c initial coefficient -0.450531
The coefficient was updated -0.450531 ------> -0.4809387020057383
0.051138941491127694
The metabolite from the solar food BE = murein4px4px4p_p coefficient -0.000673
The metabolite from the model = murein4px4px4p_p initial coefficient -0.000673
The coefficient was updated -0.000673 ------> -0.000673
0.051138941491127694
The metabolite from the solar food BE = dgtp_c coefficient -0.02400546922059191
The metabolite from the model = dgtp_c initial coefficient -0.027017
The coefficient was updated -0.027017 ------> -0.02400546922059191
0.051178521773235425
The metabolite from the solar food BE = fad_c coefficient -0.000223
The metabolite from the model = fad_c initial coefficient -0.000223
The coefficient was updated -0.000223 ------> -0.000223
0.051178521773235425
The metabolite from the solar food BE = succoa_c coefficient -9.8e-05
The metabolite from the model = succoa_c initial coefficient -9.8e-05
The coefficient was updated -9.8e-05 ------> -9.8e-05
0.051178521773235425
The metabolite from the solar food BE = arab__L_c coefficient -0.03001579312991268
The metabolite from the model = arab__L_c initial coefficient -0.030016
The coefficient was updated -0.030016 ------> -0.03001579312991268
0.05117852259687822
The metabolite from the solar food BE = glc__D_c coefficient -0.11736684160157697
The metabolite from the model = glc__D_c initial coefficient -0.117366841601577
The coefficient was updated -0.117366841601577 ------> -0.11736684160157697
0.05117852259687822
The metabolite from the solar food BE = fru_c coefficient -0.6445556055168562
The metabolite from the model = fru_c initial coefficient -0.644556
The coefficient was updated -0.644556 ------> -0.6445556055168562
0.051178524616256285
The metabolite from the solar food BE = xyl__D_c coefficient -0.005772267909598585
The metabolite from the model = xyl__D_c initial coefficient -0.005772
The coefficient was updated -0.005772 ------> -0.005772267909598585
0.05117852347338955
The metabolite from the solar food BE = man_c coefficient -0.004810116459081017
The metabolite from the model = man_c initial coefficient -0.00481
The coefficient was updated -0.00481 ------> -0.004810116459081017
0.05117852287722901
The metabolite from the solar food BE = thm_c coefficient -1.3154306833538052e-05
The metabolite from the model = thm_c initial coefficient -1.3e-05
The coefficient was updated -1.3e-05 ------> -1.3154306833538052e-05
0.051178520869555
The metabolite from the solar food BE = rbflvrd_c coefficient -5.42885385395863e-05
The metabolite from the model = rbflvrd_c initial coefficient -5.42885385395863e-05
The coefficient was updated -5.42885385395863e-05 ------> -5.42885385395863e-05
0.051178520869555
The metabolite from the solar food BE = nac_c coefficient -0.0005023142220720257
The metabolite from the model = nac_c initial coefficient -0.000502314222072026
The coefficient was updated -0.000502314222072026 ------> -0.0005023142220720257
0.051178520869555
The metabolite from the solar food BE = pnto__R_c coefficient -8.609379583094386e-05
The metabolite from the model = pnto__R_c initial coefficient -8.60937958309439e-05
The coefficient was updated -8.60937958309439e-05 ------> -8.609379583094386e-05
0.051178520869555
The metabolite from the solar food BE = clpn161_p coefficient -0.00229
The metabolite from the model = clpn161_p initial coefficient -0.00229
The coefficient was updated -0.00229 ------> -0.00229
0.051178520869555
The metabolite from the solar food BE = pe160_p coefficient -0.044164
The metabolite from the model = pe160_p initial coefficient -0.045946
The coefficient was updated -0.045946 ------> -0.044164
0.05122506065253273
The metabolite from the solar food BE = pg160_p coefficient -0.010599
The metabolite from the model = pg160_p initial coefficient -0.010599
The coefficient was updated -0.010599 ------> -0.010599
0.05122506065253273
The metabolite from the solar food BE = clpn160_p coefficient -0.002944
The metabolite from the model = clpn160_p initial coefficient -0.002944
The coefficient was updated -0.002944 ------> -0.002944
0.05122506065253273
The metabolite from the solar food BE = clpn181_p coefficient -0.00118

Compare the coeff of the excel to the one in the model

In [10]:
i=0
reaction = copy_of_model.reactions.get_by_id('Growth')
for element in pd_biomass.Biomass_equation:
    for metabolite, coefficient in reaction.metabolites.items():
        if element == metabolite.id:
            print(element)
            normalized_mmol_g = pd_biomass.loc[pd_biomass['Biomass_equation'] == element, 'normalized_mmol/g'].values[0]
            print(normalized_mmol_g)
            print(coefficient)
            i+=1
print(i)

10fthf_c
-0.000223
-0.000223
pydx5p_c
-0.000223
-0.000223
murein3px4p_p
-0.000605
-0.000605
thr__L_c
-0.33085175798343425
-0.253687
h_c
29.1804227450256
29.18042275
thmpp_c
-0.000223
-0.000223
mn2_c
-0.000658
-0.000691
sheme_c
-0.000223
-0.000223
ser__L_c
-0.29855906692147155
-0.215792
ctp_c
-0.010737250405651103
-0.133508
accoa_c
-0.000279
-0.000279
arg__L_c
-0.2557979323259868
-0.295792
asp__L_c
-0.2529593526847482
-0.241055
murein4p3p_p
-0.001345
-0.001345
5mthf_c
-0.000223
-0.000223
nad_c
-0.001787
-0.001831
mg2_c
-0.008253
-0.008675
adp_c
29.1804227450256
29.18042275
met__L_c
-0.14267468516500864
-0.153686
nh4_c
-0.012379
-0.012379
pi_c
29.1804227450256
29.18042275
chor_c
-0.000223
-0.000223
zn2_c
-0.000324
-0.000341
tyr__L_c
-0.1593258444308896
-0.137896
cys__L_c
-0.037472225353906465
-0.09158
amet_c
-0.000223
-0.000223
trp__L_c
-0.08097676930208217
-0.056843
lys__L_c
-0.25760196352578224
-0.343161
atp_c
-29.190681913288
-29.18042275
thf_c
-0.000223
-0.000223
dttp_c
-0.013367475433835764
-0.026166
dctp_c
-0.0154992827580827
-0.027017
cobalt2_c
-2.4e-05
-0.0001
utp_c
-0.006775403427840368
-0.144104
k_c
-0.18569
-0.195193
fe2_c
-0.006388
-0.006715
datp_c
-0.014832979735072188
-0.026166
ppi_c
0.110381072928369
0.773903
nadp_c
-0.000112
-0.000447
glu__L_c
-0.275320637946572
-0.26316
ile__L_c
-0.24506430675451657
-0.290529
hemeO_c
-0.000223
-0.000223
murein4p4p_p
-0.005381
-0.005381
gln__L_c
-0.2753206379465721
-0.26316
fe3_c
-0.007428
-0.007808
ala__L_c
-0.8168723181883314
-0.513689
phe__L_c
-0.22846254459317583
-0.185265
mlthf_c
-0.000223
-0.000223
2dmmql8_c
-0.000223
-0.000223
cu2_c
-0.006744
-0.000709
h2o_c
-29.1804227450256
-29.18042275
ca2_c
-0.004952
-0.005205
gly_c
-0.6379660350235106
-0.612638
malcoa_c
-3.1e-05
-3.1e-05
murein4px4p_p
-0.005448
-0.005448
mql8_c
-0.000223
-0.0001
cl_c
-0.004952
-0.005205
his__L_c
-0.09352200626083922
-0.094738
ribflv_c
-0.000223
-0.000223
so4_c
-0.004126
-0.004338
ptrc_c
-0.03327
-0.03327
gtp_c
-0.01659016153669234
-0.215096
pheme_c
-0.000223
-0.000223
nadph_c
-0.000335
-0.000335
val__L_c
-0.4108677675755479
-0.423162
pro__L_c
-0.28911581930944585
-0.221055
mobd_c
-7e-06
-7e-06
nadh_c
-4.5e-05
-4.5e-05
coa_c
-0.000168
-0.000576
asn__L_c
-0.2529593526847482
-0.241055
leu__L_c
-0.4809387020057383
-0.450531
murein4px4px4p_p
-0.000673
-0.000673
dgtp_c
-0.02400546922059191
-0.027017
fad_c
-0.000223
-0.000223
succoa_c
-9.8e-05
-9.8e-05
arab__L_c
-0.03001579312991268
-0.030016
glc__D_c
-0.11736684160157697
-0.117366841601577
fru_c
-0.6445556055168562
-0.644556
xyl__D_c
-0.005772267909598585
-0.005772
man_c
-0.004810116459081017
-0.00481
rbflvrd_c
-5.42885385395863e-05
-5.42885385395863e-05
nac_c
-0.0005023142220720257
-0.000502314222072026
pnto__R_c
-8.609379583094386e-05
-8.60937958309439e-05
clpn161_p
-0.00229
-0.00229
pe160_p
-0.044164
-0.045946
pg160_p
-0.010599
-0.010599
clpn160_p
-0.002944
-0.002944
clpn181_p
-0.00118
-0.00118
pe181_p
-0.017704
-0.017704
pg161_p
-0.008244
-0.008244
ttdca_c
-0.0005942465517650057
-0.000594246551765006
hexadecacid_c
-0.049934570136758984
-0.049935
hexedecacid_c
-0.007033277906537638
-0.007033
octadecacid_c
-0.007173968847108888
-0.007174
octedecacid_c
-0.13197873979176503
-0.131979
95

Create a dict to see which metabolite are not in the model biomass equation

In [40]:
df_met_notfound = pd.DataFrame(columns=['metabolite_id','metabolite_name','coefficient'])
metabolomic_data = []
i = 0
reaction = copy_of_model.reactions.get_by_id('Growth')
for element in pd_biomass.Biomass_equation:
    found = False
    for metabolite, coefficient in reaction.metabolites.items():
        if element == metabolite.id:
            found = True
    if not found:
        normalized_mmol_g = pd_biomass.loc[pd_biomass['Biomass_equation'] == element, 'normalized_mmol/g'].values[0]
        name = pd_biomass.loc[pd_biomass['Biomass_equation'] == element, 'Unnamed: 1'].values[0]
        metabolomic_data.append({'metabolite_id': element, 'metabolite_name': name,'coefficient': normalized_mmol_g})
        i+=1
print(i)

# Create the df_metabolomic DataFrame from the list
df_met_notfound = pd.concat([df_met_notfound, pd.DataFrame(metabolomic_data)], ignore_index=True)


df_met_notfound.to_excel('C:\\Users\\adam-1y9pxi6q95ggpmx\\Desktop\\metabolitenotfound_biomass_equation.xlsx',index=False)

df_met_notfound

29

C:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\Temp\ipykernel_6856\3034590687.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_met_notfound = pd.concat([df_met_notfound, pd.DataFrame(metabolomic_data)], ignore_index=True)

   metabolite_id                      metabolite_name   coefficient
0       adocbl_c                    Adenosylcobalamin -2.230000e-04
1        gthrd_c                  Reduced glutathione -2.230000e-04
2          ni2_c                               Nickel -3.070000e-04
3         q8h2_c                          Ubiquinol-8 -2.230000e-04
4         spmd_c                           Spermidine -6.744000e-03
5      mococdp_c  Molybdopterin cytosine dinucleotide -7.000000e-06
6        2fe2s_c         [2Fe-2S] iron-sulfur cluster -2.500000e-05
7          btn_c                               Biotin -1.141455e-07
8        4fe4s_c         [4Fe-4S] iron-sulfur cluster -2.480000e-04
9        enter_c                         Enterochelin -2.230000e-04
10         rmn_c                           L-Rhamnose -1.245830e-01
11      gal__L_c                          L-Galactose -5.772140e-03
12       galam_c             D Galactosamine C6H13NO5 -4.836695e-03
13         gam_c                        D-Glucosamine -4.836695e-03
14     retinol_c                    All-trans-Retinol -9.074247e-09
15      avite1_c                     Alpha-Tocopherol -3.018077e-06
16       vitd3_c              Calciol; (+)-Vitamin D3 -5.633064e-10
17       vitd2_c           Vitamin D2; ergocalciferol -5.462623e-10
18       pydxn_c                           Pyridoxine -6.433608e-05
19        chol_c                      Choline C5H14NO -1.384112e-03
20         fol_c                               Folate -2.122695e-05
21     phllqne_c                        Phylloquinone -1.922766e-09
22        caro_c                        Beta-Carotene -3.993838e-05
23      colipa_e         Core oligosaccharide lipid A -8.151000e-03
24       hpdca_c       Heptadecanoate  C170  C17H33O2 -2.921740e-04
25       arach_c                       Arachidic acid -7.320957e-05
26      tmndnc_c           Timnodonic acid C20:5, n-3 -3.781486e-05
27    doco13ac_c              13Z)-13-docosenoic acid -6.705456e-05
28         ttc_c     Tetracosanoate  n C240  C24H47O2 -3.009322e-05

Create a dict to see which metabolite are only in the model and not in experimental biomass equation

In [39]:
df_met_notfound = pd.DataFrame(columns=['metabolite_id','metabolite_name','coefficient'])
metabolomic_data = []
i = 0
reaction = copy_of_model.reactions.get_by_id('Growth')
for metabolite, coefficient in reaction.metabolites.items():
    found = False
    for element in pd_biomass.Biomass_equation:
        if element == metabolite.id:
            found = True
    if not found:
        metabolomic_data.append({'metabolite_id': metabolite.id, 'metabolite_name': metabolite.name,'coefficient': coefficient})
        i+=1
print(i)

# Create the df_metabolomic DataFrame from the list
df_met_notfound = pd.concat([df_met_notfound, pd.DataFrame(metabolomic_data)], ignore_index=True)


df_met_notfound.to_excel('C:\\Users\\adam-1y9pxi6q95ggpmx\\Desktop\\metabolitenotfound_biomass.xlsx',index=False)

df_met_notfound

6

C:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\Temp\ipykernel_6856\2895765538.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_met_notfound = pd.concat([df_met_notfound, pd.DataFrame(metabolomic_data)], ignore_index=True)

,metabolite_id,metabolite_name,coefficient
0,kdo2lipid4_p,KDO(2)-lipid IV(A),-0.019456
1,murein5px4p_p,"Two disacharide linked murein units, pentapept...",-0.013894
2,pe160_c,"Phosphatidylethanolamine (dihexadecanoyl, n-C1...",-0.017868
3,pe161_c,"Phosphatidylethanolamine (dihexadec-9enoyl, n-...",-0.054154
4,pe161_p,"Phosphatidylethanolamine (dihexadec-9enoyl, n-...",-0.021060
5,gal_c,D-Galactose,-0.005772

Compare metabolite from another model biomass equation to the model

In [9]:
df_met_notfound = pd.DataFrame(columns=['metabolite_id','metabolite_name'])

In [16]:
# Initialize a counter for metabolites not found and a dictionary to store them
metabolomic_data = []
i = 0

# Retrieve the 'Growth' reaction from both models
reaction = copy_of_model.reactions.get_by_id('Growth')
reaction1 = copy_of_model1.reactions.get_by_id('BIOMASS_KT2440_WT3')

# Iterate over metabolites in the 'Growth' reaction of model1
for metabolite1 in reaction1.metabolites:
    found = False  # Initialize the found flag for each metabolite in reaction1
    for metabolite in reaction.metabolites:
        if metabolite1.id == metabolite.id:
            found = True
            break  # If metabolite is found, break the inner loop
    
    # If the metabolite was not found, add it to the dictionary and increment the counter
    if not found:
        metabolomic_data.append({'metabolite_id': metabolite1.id, 'metabolite_name': metabolite1.name})
        i += 1

# Print the number of metabolites not found
print(f"Number of metabolites not found: {i}")

# Create the df_metabolomic DataFrame from the list
df_met_notfound = pd.concat([df_met_notfound, pd.DataFrame(metabolomic_data)], ignore_index=True)

df_met_notfound

Number of metabolites not found: 28

In [37]:
df_met_notfound.to_excel('C:\\Users\\adam-1y9pxi6q95ggpmx\\Desktop\\metabolitenotfound.xlsx',index=False)

In [61]:
new_metabolite = Metabolite(
    id='vitd2_c',     # Metabolite ID
    name='Vitamin D2; ergocalciferol',     # Metabolite Name
    formula='C28H44O',         # Chemical Formula
    compartment='c'            # Compartment (e.g., cytoplasm)
)

new_metabolite.charge = 0

copy_of_model.add_metabolites([new_metabolite])

print(new_metabolite.formula)

C28H44O

In [ ]:
reaction = copy_of_model.reactions.get_by_id('Growth')
metabolite_to_add = 'adocbl_c'
reaction.add_metabolites({metabolite_to_add: -0.000223})
copy_of_model.slim_optimize()

In [33]:
reaction = copy_of_model.reactions.get_by_id(reaction_id_to_check)
metabolite_to_add = 'ptrc_c'
reaction.subtract_metabolites({metabolite_to_add: 0.03327})
copy_of_model.slim_optimize()

0.049369129795515644

Create a dict with the metabolite that are only in the model biomass equation

In [ ]:
model_BE_metabolite = {}

# Get the 'Growth' reaction
reaction = model1.reactions.get_by_id('BIOMASS_KT2440_WT3')

# Iterate over metabolites in the 'Growth' reaction
for metabolite, coefficient in reaction.metabolites.items():
    # Check if the metabolite ID is not in the 'Biomass_equation' column
    if metabolite.id not in pd_biomass['Biomass_equation'].values:
        # Add the metabolite ID and its coefficient to the dictionary
        model_BE_metabolite[metabolite.id] = coefficient

model_BE_metabolite

In [ ]:
reaction_id_to_check = 'Growth'
reaction = copy_of_model.reactions.get_by_id(reaction_id_to_check)
print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")
sum = 0
#reaction.name = '(S)-2-Acetolactate pyruvate-lyase (carboxylating)'
print("\nMetabolites and Stoichiometry:")
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id:<15}: {coefficient:>25}  Name: {metabolite.name:<60}  Charge: {metabolite.charge:>3}  Formula: {metabolite.formula}")
    sum += coefficient * metabolite.charge
print(f'\nSum charge: {sum}')
print("\nAssociated Genes:")
for gene in reaction.genes:
    print(gene.id)

#### add metabolite to the biomass composition

In [78]:
copy_of_model = model.copy()

In [77]:
metabolite_not_found.pop('spmd_c', None)

-0.006744

In [93]:
# Convert the dictionary to a DataFrame
df_metabolite_not_found = pd.DataFrame(list(metabolite_not_found.items()), columns=['Metabolite', 'Coefficient'])

# Save the DataFrame to an Excel file
output_file = 'C:\\Users\\adam-1y9pxi6q95ggpmx\\Desktop\\metabolite_not_found.xlsx'
df_metabolite_not_found.to_excel(output_file, index=False)

print(f"The data has been saved to {output_file}")

The data has been saved to C:\Users\adam-1y9pxi6q95ggpmx\Desktop\metabolite_not_found.xlsx

In [79]:
# Get the reaction 'Growth'
reaction = copy_of_model.reactions.get_by_id('Growth')

for metabolite_id, coefficient in metabolite_not_found.items():
    try:
        print(metabolite_id)
        # Add the metabolite to the reaction with its coefficient
        reaction.add_metabolites({metabolite_id: coefficient})
        # Optimize the model and print the result
        print(copy_of_model.slim_optimize())
    except KeyError:
        # If the metabolite is not found in the model, pass
        pass

#### GAM update

In [19]:
GAM_metabolites_1 = {'atp_c': -50.0, 'h2o_c': -50.0}
GAM_metabolites_2 = {'adp_c': 50.0, 'pi_c': 50.0, 'h_c': 50.0}

# Get the biomass reaction
reaction = model.reactions.get_by_id('Growth')

# Update the coefficients for GAM_metabolites_1
for element, new_coefficient in GAM_metabolites_1.items():
    metabolite = model.metabolites.get_by_id(element)
    if metabolite in reaction.metabolites:
        print(f'Old coefficient for {element}: {reaction.metabolites[metabolite]}')
        reaction.add_metabolites({metabolite: new_coefficient - reaction.metabolites[metabolite]})
        print(f'Updated {element} coefficient to {new_coefficient}')

# Update the coefficients for GAM_metabolites_2
for element, new_coefficient in GAM_metabolites_2.items():
    metabolite = model.metabolites.get_by_id(element)
    if metabolite in reaction.metabolites:
        print(f'Old coefficient for {element}: {reaction.metabolites[metabolite]}')
        reaction.add_metabolites({metabolite: new_coefficient - reaction.metabolites[metabolite]})
        print(f'Updated {element} coefficient to {new_coefficient}')

# Optimize the model
solution = model.slim_optimize()
print(f'Optimal solution: {solution}')

Old coefficient for atp_c: -50.5
Updated atp_c coefficient to -50.0
Old coefficient for h2o_c: -50.5
Updated h2o_c coefficient to -50.0
Old coefficient for adp_c: 50.5
Updated adp_c coefficient to 50.0
Old coefficient for pi_c: 50.5
Updated pi_c coefficient to 50.0
Old coefficient for h_c: 50.5
Updated h_c coefficient to 50.0
Optimal solution: 0.04601781298310009

# Update new model

### Update charges from excel

In [11]:
file_path = 'C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified reactions.xlsx'
file_path_1 = 'C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified formula.xlsx'

excel_data_charge = pd.read_excel(file_path)

# Iterate over each component in the Excel file
for component in excel_data_charge['metabolite changed']:
    # Check if a metabolite is present in the model's metabolites
    metabolite_id = component
    if metabolite_id in copy_of_model.metabolites:
        # Get the metabolite from the model
        metabolite = copy_of_model.metabolites.get_by_id(metabolite_id)
        
        # Change the charge of the metabolite to a new value from the Excel file
        new_charge = int(excel_data_charge.loc[excel_data_charge['metabolite changed'] == metabolite_id, 'New charge'].values[0])
        metabolite.charge = new_charge
        
        # Print information about the modified metabolite
        print(f"Modified metabolite: {metabolite.id}")
        print(f"Updated charge: {metabolite.charge}")
    else:
        print("Metabolite not found in the model.")

Modified metabolite: 2agpg161_c
Updated charge: -1
Modified metabolite: r3hbACP_c
Updated charge: -1
Modified metabolite: tmrs2eACP_c
Updated charge: -1
Modified metabolite: 4hoxpac_p
Updated charge: -1
Modified metabolite: 4oxptn_p
Updated charge: -1
Modified metabolite: 4oxptn_e
Updated charge: -1
Modified metabolite: 4hoxpac_e
Updated charge: -1
Modified metabolite: 6atha_e
Updated charge: -1
Metabolite not found in the model.
Modified metabolite: hethmpp_c
Updated charge: -2
Modified metabolite: Pald_c
Updated charge: -2
Modified metabolite: S2hglut_c
Updated charge: -2
Modified metabolite: sdhlam_c
Updated charge: -1
Modified metabolite: pqqh2_p
Updated charge: -3
Modified metabolite: ppad_c
Updated charge: -1
Modified metabolite: cmcbtt_c
Updated charge: 1
Modified metabolite: fcmcbtt_c
Updated charge: 4
Modified metabolite: R_3hpt_p
Updated charge: -1
Modified metabolite: R_3hpt_e
Updated charge: -1
Modified metabolite: R_3hpba_p
Updated charge: -1
Modified metabolite: R_3hpba_e
Updated charge: -1

In [23]:
print(len(cobra.manipulation.validate.check_mass_balance(copy_of_model)))
list_reactions = cobra.manipulation.validate.check_mass_balance(copy_of_model)
for reaction, balance_dict in list_reactions.items():
    reaction_id = reaction.id
    charge_balance = balance_dict
    print(f"Reaction ID: {reaction_id}, Charge Balance: {charge_balance}")

5
Reaction ID: DHNAOT, Charge Balance: {'charge': 2.0}
Reaction ID: HDECH, Charge Balance: {'charge': 2.0}
Reaction ID: MECDPDH4E, Charge Balance: {'charge': -1.0}
Reaction ID: P9DH, Charge Balance: {'charge': 4.0}
Reaction ID: THZSN_1, Charge Balance: {'H': -1.0}

### Create a list of reaction to update with the related model

In [94]:
import requests
list_reactions = cobra.manipulation.validate.check_mass_balance(model)

# Dictionary to store reaction ID and associated model
reaction_model_mapping = {}

for reaction, balance_dict in list_reactions.items():
    reaction_id = reaction.id  # Get the ID of the reaction
    # URL of the API endpoint for the reaction
    url = f'http://bigg.ucsd.edu/api/v2/universal/reactions/{reaction_id}'
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        # Extract the model ID from the JSON data
        model_of_reaction = data['models_containing_reaction'][0]['bigg_id']
        # Store the mapping of reaction ID to its model in the dictionary
        reaction_model_mapping[reaction_id] = model_of_reaction
    else:
        # If the request was not successful, print the status code
        print("Failed to retrieve data. Status code:", response.status_code)

Failed to retrieve data. Status code: 404
Failed to retrieve data. Status code: 404
Failed to retrieve data. Status code: 404
Failed to retrieve data. Status code: 404
Failed to retrieve data. Status code: 404
Failed to retrieve data. Status code: 404
Failed to retrieve data. Status code: 404
{'DHNAOT': 'iCN718', 'HDECH': 'iEK1008', 'MECDPDH4E': 'iCN900', 'P9DH': 'iCN900', 'THZSN_1': 'iJN678', '2S6HCCi': 'iCN718', 'ADPDA': 'iYO844', 'AMMQT8': 'iCN718', 'APTA1i': 'iYO844', 'BZ12DOX': 'iJN1463', 'BZDIOLDH': 'iJN1463', 'ECOAH2c': 'iYO844', 'FNRR3': 'iCN900', 'G3PGtex': 'iAF1260', 'GGTT': 'iAM_Pb448', 'GLUFT': 'iLJ478', 'HEXTT': 'iAM_Pb448', 'HIBHr': 'iYO844', 'IBHH': 'iCN900', 'MAN1Pt6': 'iYO844', 'NFORGLUAH': 'iHN637', 'OPP': 'iAM_Pb448', 'PPTT': 'iAM_Pb448', 'PRAIS_1': 'iNF517', 'PRFGCL': 'iCN718', 'R5PPpp': 'iAF1260', 'SALSYN': 'iAPECO1_1312', 'SCYSSL': 'iAPECO1_1312', 'SEPHCHCS': 'iAM_Pb448', 'SHCHCS3': 'iAM_Pb448', 'SHCHF_2': 'iYO844', 'SLCYSS': 'iAPECO1_1312', 'SUCBZS': 'iAF1260', 'UPP3MT_2': 'iYO844', 'ENTCS': 'iAF1260', 'ICHORT': 'iAF1260', 'DHBD': 'iAF1260', 'CSPMDDH': 'iAF987', 'CSPMDDC': 'iAF987', 'PETNLA161pp': 'iEC1344_C', 'PETNLA181pp': 'iEC1344_C', 'NIT1b': 'iAF987'}

### Update charge from BIGG API

In [96]:
for reaction, model_name in reaction_model_mapping.items():
    reaction_to_modify = model.reactions.get_by_id(reaction)
    for metabolite, coefficient in reaction_to_modify.metabolites.items():
        if metabolite.charge == 0:
            url = f'http://bigg.ucsd.edu/api/v2/models/{model_name}/metabolites/{metabolite.id}'
            response = requests.get(url)
            if response.status_code == 200:
                data = response.json()
                # Check if the charge information is available and matches the current metabolite charge
                if data['charge'] is not None and data['charge'] != metabolite.charge:
                    print(metabolite.id)
                    print(f' metabolite charge : {metabolite.charge}')
                    print(f'bigg metabolite charge : {data["charge"]}')
                    metabolite.charge = data['charge']
            else:
                print("Failed to retrieve data. Status code:", response.status_code)

26dapime_c
 metabolite charge : 0
bigg metabolite charge : -1
bz12diol_c
 metabolite charge : 0
bigg metabolite charge : -1
hibcoa_c
 metabolite charge : 0
bigg metabolite charge : -4
g3pg_e
 metabolite charge : 0
bigg metabolite charge : -1
pendp_c
 metabolite charge : 0
bigg metabolite charge : -3
hepdp_c
 metabolite charge : 0
bigg metabolite charge : -3
man1p_e
 metabolite charge : 0
bigg metabolite charge : -2
r5p_p
 metabolite charge : 0
bigg metabolite charge : -2
scys__L_c
 metabolite charge : 0
bigg metabolite charge : -1
2sephchc_c
 metabolite charge : 0
bigg metabolite charge : -3
2shchc_c
 metabolite charge : 0
bigg metabolite charge : -2
srch_c
 metabolite charge : 0
bigg metabolite charge : -8
shcl_c
 metabolite charge : 0
bigg metabolite charge : -8
23ddhb_c
 metabolite charge : 0
bigg metabolite charge : -1
cspmd_c
 metabolite charge : 0
bigg metabolite charge : 2
Failed to retrieve data. Status code: 404

### Update charge and formula from a curated model

In [65]:
model1 = read_sbml_model('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\Models\\Manual Curation\\updated_growth_gapfilled_autotrophic_1.sbml')

In [66]:
list_reactions = cobra.manipulation.validate.check_mass_balance(copy_of_model)
copy_of_model1 = model1.copy()
# Iterate through metabolites in the non-curated model
for metabolite in copy_of_model.metabolites:
    # Check if the metabolite exists in the curated model
    if metabolite.id in copy_of_model1.metabolites:
        # Find the corresponding metabolite in the curated model
        curated_metabolite = copy_of_model1.metabolites.get_by_id(metabolite.id)
        # Update the charge and formula of the non-curated metabolite
        metabolite.charge = curated_metabolite.charge
        metabolite.formula = curated_metabolite.formula
    else:
        print(f"Metabolite '{metabolite.id}' not found in the curated model.")

Metabolite 'etoh_e' not found in the curated model.

### Add reactions from a curated model

In [52]:
# Create a copy of the non-curated model
copy_of_model1 = model1.copy()

# Iterate through reactions in the curated model
for reaction in copy_of_model1.reactions:
    # Check if the reaction exists in the non-curated model
    if reaction.id not in copy_of_model.reactions:
        # Add the reaction to the non-curated model
        copy_of_model.add_reactions([reaction])
        print(f"Reaction '{reaction.id}' was added non-curated model.")
    else:
        pass

# Optimize the updated model
solution = copy_of_model.optimize()
print(f'Biomass reaction flux after adding reactions: {solution.objective_value}')

# Verify the addition of reactions
for reaction in copy_of_model1.reactions:
    if reaction.id not in copy_of_model.reactions:
        print(f"Reaction '{reaction.id}' was not added correctly.")

Reaction '3HAD160' was added non-curated model.
Reaction '13DAMPPabcpp' was added non-curated model.
Reaction '13DAMPPtex' was added non-curated model.
Reaction '15DAPabcpp' was added non-curated model.
Reaction '1PPDCRc' was added non-curated model.
Reaction '1PQQS' was added non-curated model.
Reaction '23CTI1' was added non-curated model.
Reaction '23CTI2' was added non-curated model.
Reaction '23CTI3' was added non-curated model.
Reaction '24DECOAR' was added non-curated model.
Reaction '26DAHtex' was added non-curated model.
Reaction '2AACLPGT160' was added non-curated model.
Reaction '2AACLPGT161' was added non-curated model.
Reaction '2AACLPGT180' was added non-curated model.
Reaction '2AACLPGT181' was added non-curated model.
Reaction '2AACLPPEAT160' was added non-curated model.
Reaction '2AACLPPEAT161' was added non-curated model.
Reaction '2AACLPPEAT180' was added non-curated model.
Reaction '2AACLPPEAT181' was added non-curated model.
Reaction '2AGPE160tipp' was added non-curated model.
Reaction '2AGPE180tipp' was added non-curated model.
Reaction '2DHGLCK' was added non-curated model.
Reaction '2DHGLCNtex' was added non-curated model.
Reaction '2PQQS' was added non-curated model.
Reaction '34DHCINMtex' was added non-curated model.
Reaction '34DHCINMtpp' was added non-curated model.
Reaction '34DHPHEtex' was added non-curated model.
Reaction '34DHPHEtpp' was added non-curated model.
Reaction '34HPPOR' was added non-curated model.
Reaction '3HAACOAT100' was added non-curated model.
Reaction '3HAACOAT120' was added non-curated model.
Reaction '3HAACOAT121' was added non-curated model.
Reaction '3HAACOAT141' was added non-curated model.
Reaction '3HAACOAT60' was added non-curated model.
Reaction '3HAACOAT80' was added non-curated model.
Reaction '3HAD100' was added non-curated model.
Reaction '3HAD120' was added non-curated model.
Reaction '3HAD121' was added non-curated model.
Reaction '3HAD141' was added non-curated model.
Reaction 'ACOAD34f' was added non-curated model.
Reaction 'ACOADH1' was added non-curated model.
Reaction 'ACOATA' was added non-curated model.
Reaction 'ACONIs' was added non-curated model.
Reaction 'ACONMT' was added non-curated model.
Reaction 'ACPPAT120' was added non-curated model.
Reaction 'ACPPAT141' was added non-curated model.
Reaction 'ACPPAT161' was added non-curated model.
Reaction 'ACPPAT180' was added non-curated model.
Reaction 'ACPS1' was added non-curated model.
Reaction 'ACSERtex' was added non-curated model.
Reaction 'ACSERtpp' was added non-curated model.
Reaction 'ACSPHAC142' was added non-curated model.
Reaction 'ACSPHAC40' was added non-curated model.
Reaction 'ACSPHAC50' was added non-curated model.
Reaction 'ACSPHAC70' was added non-curated model.
Reaction 'ACSPHAC90' was added non-curated model.
Reaction 'ACSPHACP100' was added non-curated model.
Reaction 'ACSPHACP40' was added non-curated model.
Reaction 'ACSPHACP70' was added non-curated model.
Reaction 'ACSPHACP80' was added non-curated model.
Reaction 'ACSPHACP90' was added non-curated model.
Reaction 'DGUDBUTNabcpp' was added non-curated model.
Reaction 'ALGE9' was added non-curated model.
Reaction 'ALGL' was added non-curated model.
Reaction 'ALGL2' was added non-curated model.
Reaction 'ALGSex1' was added non-curated model.
Reaction 'ALGSex10' was added non-curated model.
Reaction 'ALGSex11' was added non-curated model.
Reaction 'ALGSex12' was added non-curated model.
Reaction 'ALGSex13' was added non-curated model.
Reaction 'ALGSex2' was added non-curated model.
Reaction 'ALGSex3' was added non-curated model.
Reaction 'ALGSex4' was added non-curated model.
Reaction 'ALGSex5' was added non-curated model.
Reaction 'ALGSex6' was added non-curated model.
Reaction 'ALGSex7' was added non-curated model.
Reaction 'ALGSex8' was added non-curated model.
Reaction 'ALGSex9' was added non-curated model.
Reaction 'ALLTNRA' was added non-curated model.
Reaction 'ALLTNt2rpp' was added non-curated model.
Reaction 'ALLTNtex' was added non-curated model.
Reaction 'ALPATE160pp' was added non-curated model.
Reaction 'ALPATE161pp' was added non-curated model.
Reaction 'ALPATE180pp' was added non-curated model.
Reaction 'ALPATE181pp' was added non-curated model.
Reaction 'ALPATG160pp' was added non-curated model.
Reaction 'ALPATG161pp' was added non-curated model.
Reaction 'ALPATG180pp' was added non-curated model.
Reaction 'ALPATG181pp' was added non-curated model.
Reaction 'ALTRH' was added non-curated model.
Reaction 'AM4PCP' was added non-curated model.
Reaction 'AMAOTr' was added non-curated model.
Reaction 'AMID4' was added non-curated model.
Reaction 'AMPN' was added non-curated model.
Reaction 'AOBUTDs' was added non-curated model.
Reaction 'AOXHEXCYCL' was added non-curated model.
Reaction 'AOXSr2' was added non-curated model.
Reaction 'AP4AH' was added non-curated model.
Reaction 'AP4AS' was added non-curated model.
Reaction 'APCt5' was added non-curated model.
Reaction 'APCtpp' was added non-curated model.
Reaction 'APENTAMAH2' was added non-curated model.
Reaction 'APG3PAT120' was added non-curated model.
Reaction 'APG3PAT140' was added non-curated model.
Reaction 'APG3PAT141' was added non-curated model.
Reaction 'APG3PAT161' was added non-curated model.
Reaction 'APG3PAT180' was added non-curated model.
Reaction 'ARBTNR1' was added non-curated model.
Reaction 'ARBTNR2' was added non-curated model.
Reaction 'ARBTNabcpp' was added non-curated model.
Reaction 'ARBTNexs' was added non-curated model.
Reaction 'ARBTNtex' was added non-curated model.
Reaction 'ARBTNtonex' was added non-curated model.
Reaction 'ARBTNtpp' was added non-curated model.
Reaction 'ARGDr' was added non-curated model.
Reaction 'ARGDC' was added non-curated model.
Reaction 'ARGDCpp' was added non-curated model.
Reaction 'ARGORNt7pp' was added non-curated model.
Reaction 'ARGTRS' was added non-curated model.
Reaction 'ARGt2pp' was added non-curated model.
Reaction 'ARGtex' was added non-curated model.
Reaction 'ARUH' was added non-curated model.
Reaction 'ASNN' was added non-curated model.
Reaction 'ASNNpp' was added non-curated model.
Reaction 'ASNtex' was added non-curated model.
Reaction 'ASO3t2pp' was added non-curated model.
Reaction 'ASO3tex' was added non-curated model.
Reaction 'ASP3H' was added non-curated model.
Reaction 'ASPO1' was added non-curated model.
Reaction 'ASPO3' was added non-curated model.
Reaction 'ASPSALy' was added non-curated model.
Reaction 'ASPT' was added non-curated model.
Reaction 'BZDIOLDH' was added non-curated model.
Reaction 'BZt1pp' was added non-curated model.
Reaction 'BZt2_pp' was added non-curated model.
Reaction 'BZtex' was added non-curated model.
Reaction 'BIOMASS_KT2440_Core2' was added non-curated model.
Reaction 'BIOMASS_KT2440_WT3' was added non-curated model.
Reaction 'CA2tex' was added non-curated model.
Reaction 'CACOAHA' was added non-curated model.
Reaction 'CAFFCOA' was added non-curated model.
Reaction 'CARBSARAH' was added non-curated model.
Reaction 'CAT23DOX' was added non-curated model.
Reaction 'CATECHOLtex' was added non-curated model.
Reaction 'CATECHOLtpp' was added non-curated model.
Reaction 'CATpp' was added non-curated model.
Reaction 'CAt6pp' was added non-curated model.
Reaction 'CBIAT' was added non-curated model.
Reaction 'CBItonex' was added non-curated model.
Reaction 'CBIuabcpp' was added non-curated model.
Reaction 'CBL1abcpp' was added non-curated model.
Reaction 'CBL1tonex' was added non-curated model.
Reaction 'CBLAT' was added non-curated model.
Reaction 'CBMKr' was added non-curated model.
Reaction 'CCGS' was added non-curated model.
Reaction 'CDGR' was added non-curated model.
Reaction 'CDGS' was added non-curated model.
Reaction 'CELASEpp' was added non-curated model.
Reaction 'CELLS' was added non-curated model.
Reaction 'CELLex' was added non-curated model.
Reaction 'CFAS160E' was added non-curated model.
Reaction 'CFAS160G' was added non-curated model.
Reaction 'CFAS180E' was added non-curated model.
Reaction 'CFAS180G' was added non-curated model.
Reaction 'CGLYtex' was added non-curated model.
Reaction 'CHLtex' was added non-curated model.
Reaction 'CHOLS_ex' was added non-curated model.
Reaction 'CHOLSabc' was added non-curated model.
Reaction 'CREAT' was added non-curated model.
Reaction 'CREATtex' was added non-curated model.
Reaction 'CREATtpp' was added non-curated model.
Reaction 'CRO2t3pp' was added non-curated model.
Reaction 'CRO2tex' was added non-curated model.
Reaction 'CRO2tpp' was added non-curated model.
Reaction 'CRO4Rx' was added non-curated model.
Reaction 'CRO4Ry' was added non-curated model.
Reaction 'CRO4tex' was added non-curated model.
Reaction 'CRTNIH' was added non-curated model.
Reaction 'CRTNtex' was added non-curated model.
Reaction 'CRTNtpp' was added non-curated model.
Reaction 'CSNt2pp' was added non-curated model.
Reaction 'CSNtex' was added non-curated model.
Reaction 'CSPMDDC' was added non-curated model.
Reaction 'CSPMDDH' was added non-curated model.
Reaction 'CU2tex' was added non-curated model.
Reaction 'CU2tpp' was added non-curated model.
Reaction 'CUt3' was added non-curated model.
Reaction 'CUtex' was added non-curated model.
Reaction 'CUt2pp' was added non-curated model.
Reaction 'CYO1_KT' was added non-curated model.
Reaction 'CYRDAAT' was added non-curated model.
Reaction 'CYRDAR' was added non-curated model.
Reaction 'CYSDabcpp' was added non-curated model.
Reaction 'CYSDtex' was added non-curated model.
Reaction 'SLCYSS' was added non-curated model.
Reaction 'CYSSADS' was added non-curated model.
Reaction 'CYSTGL' was added non-curated model.
Reaction 'CYSTRS' was added non-curated model.
Reaction 'CYSTS' was added non-curated model.
Reaction 'CYStex' was added non-curated model.
Reaction 'CYTBO3_4pp' was added non-curated model.
Reaction 'CYTCAA3pp' was added non-curated model.
Reaction 'CYTDH' was added non-curated model.
Reaction 'DH3MCHCDH' was added non-curated model.
Reaction 'DH4MCHCDH' was added non-curated model.
Reaction 'DHAD1_copy1' was added non-curated model.
Reaction 'DHMPTR' was added non-curated model.
Reaction 'DHMPTRx' was added non-curated model.
Reaction 'DHNPTE' was added non-curated model.
Reaction 'DHORD2' was added non-curated model.
Reaction 'DHPM1' was added non-curated model.
Reaction 'DHPS' was added non-curated model.
Reaction 'DHQTi_copy1' was added non-curated model.
Reaction 'DHSKDH' was added non-curated model.
Reaction 'DKGLCNR3' was added non-curated model.
Reaction 'DLASNR' was added non-curated model.
Reaction 'DLMETR' was added non-curated model.
Reaction 'DLYSPYRAT' was added non-curated model.
Reaction 'DLYSabcpp' was added non-curated model.
Reaction 'DLYStex' was added non-curated model.
Reaction 'METDtex' was added non-curated model.
Reaction 'DMGLYBabcpp' was added non-curated model.
Reaction 'DMGLYtex' was added non-curated model.
Reaction 'DMQMT' was added non-curated model.
Reaction 'DMSO2abcpp' was added non-curated model.
Reaction 'DMSO2tex' was added non-curated model.
Reaction 'DM_5drib_c' was added non-curated model.
Reaction 'DM_amob_c' was added non-curated model.
Reaction 'DM_C100aPHA_c' was added non-curated model.
Reaction 'DM_C100pPHA_c' was added non-curated model.
Reaction 'DM_C101PAH_c' was added non-curated model.
Reaction 'DM_C120aPHA_c' was added non-curated model.
Reaction 'DM_C121aPHA_c' was added non-curated model.
Reaction 'DM_C121d6PHA_c' was added non-curated model.
Reaction 'DM_C140aPHA_c' was added non-curated model.
Reaction 'DM_C141aPHA_c' was added non-curated model.
Reaction 'DM_C141d5PHA_c' was added non-curated model.
Reaction 'DM_C142PHA_c' was added non-curated model.
Reaction 'DM_C40aPHA_c' was added non-curated model.
Reaction 'DM_C40atPHA_c' was added non-curated model.
Reaction 'DM_C40pPHA_c' was added non-curated model.
Reaction 'DM_C50aPHA_c' was added non-curated model.
Reaction 'DM_C50pPHA_c' was added non-curated model.
Reaction 'DM_C60aPHA_c' was added non-curated model.
Reaction 'DM_C60atPHA_c' was added non-curated model.
Reaction 'DM_C60pPHA_c' was added non-curated model.
Reaction 'ECOAH29' was added non-curated model.
Reaction 'ECOAH30' was added non-curated model.
Reaction 'ECTOH' was added non-curated model.
Reaction 'ECTOabcpp' was added non-curated model.
Reaction 'ECTOtex' was added non-curated model.
Reaction 'EDTXS1_kt' was added non-curated model.
Reaction 'EDTXS2_kt' was added non-curated model.
Reaction 'EDTXS5_kt' was added non-curated model.
Reaction 'EDTXS6_kt' was added non-curated model.
Reaction 'EGMEACPR' was added non-curated model.
Reaction 'EPMEACPR' was added non-curated model.
Reaction 'ETHAt2pp' was added non-curated model.
Reaction 'ETHAtex' was added non-curated model.
Reaction 'ETHSO3abcpp' was added non-curated model.
Reaction 'ETHSO3tex' was added non-curated model.
Reaction 'ETOHtex' was added non-curated model.
Reaction 'EX_12dgr160_e' was added non-curated model.
Reaction 'EX_12dgr180_e' was added non-curated model.
Reaction 'EX_13dampp_e' was added non-curated model.
Reaction 'EX_15dap_e' was added non-curated model.
Reaction 'EX_1ag160_e' was added non-curated model.
Reaction 'EX_1ag180_e' was added non-curated model.
Reaction 'EX_1ag181d9_e' was added non-curated model.
Reaction 'EX_1ag182d9d12_e' was added non-curated model.
Reaction 'EX_26dap__M_e' was added non-curated model.
Reaction 'EX_AEP_e' was added non-curated model.
Reaction 'EX_2ddglcn_e' was added non-curated model.
Reaction 'EX_2dhglcn_e' was added non-curated model.
Reaction 'EX_34dhcinm_e' was added non-curated model.
Reaction 'EX_34dhphe_e' was added non-curated model.
Reaction 'EX_3mb_e' was added non-curated model.
Reaction 'EX_btd_RR_e' was added non-curated model.
Reaction 'EX_btn_e' was added non-curated model.
Reaction 'EX_butso3_e' was added non-curated model.
Reaction 'EX_catechol_e' was added non-curated model.
Reaction 'EX_cbi_e' was added non-curated model.
Reaction 'EX_cbl1_e' was added non-curated model.
Reaction 'EX_cell4_e' was added non-curated model.
Reaction 'EX_chor_e' was added non-curated model.
Reaction 'EX_cit_e' was added non-curated model.
Reaction 'EX_cmcbtt_e' was added non-curated model.
Reaction 'EX_confrl_e' was added non-curated model.
Reaction 'EX_creat_e' was added non-curated model.
Reaction 'EX_cro2_e' was added non-curated model.
Reaction 'EX_cro4_e' was added non-curated model.
Reaction 'EX_crtn_e' was added non-curated model.
Reaction 'EX_cu_e' was added non-curated model.
Reaction 'EX_cys__D_e' was added non-curated model.
Reaction 'EX_dag181d9_e' was added non-curated model.
Reaction 'EX_dag182d9d12_e' was added non-curated model.
Reaction 'EX_dgudbutn_e' was added non-curated model.
Reaction 'EX_dmanur_e' was added non-curated model.
Reaction 'EX_dmgly_e' was added non-curated model.
Reaction 'EX_dmso2_e' was added non-curated model.
Reaction 'EX_dopa_e' was added non-curated model.
Reaction 'EX_ecto__L_e' was added non-curated model.
Reaction 'EX_etha_e' was added non-curated model.
Reaction 'EX_ethso3_e' was added non-curated model.
Reaction 'EX_fcmcbtt_e' was added non-curated model.
Reaction 'EX_fe3mcbtt_e' was added non-curated model.
Reaction 'EX_fe3pyovd_e' was added non-curated model.
Reaction 'EX_fecrm_e' was added non-curated model.
Reaction 'EX_fecrm_un_e' was added non-curated model.
Reaction 'EX_feoxam_e' was added non-curated model.
Reaction 'EX_feoxam_un_e' was added non-curated model.
Reaction 'EX_fer_e' was added non-curated model.
Reaction 'EX_fum_e' was added non-curated model.
Reaction 'EX_ga_e' was added non-curated model.
Reaction 'EX_galct__D_e' was added non-curated model.
Reaction 'EX_glutar_e' was added non-curated model.
Reaction 'EX_glyald_e' was added non-curated model.
Reaction 'EX_glyc__R_e' was added non-curated model.
Reaction 'EX_glyc_e' was added non-curated model.
Reaction 'EX_glycol_e' was added non-curated model.
Reaction 'EX_gudac_e' was added non-curated model.
Reaction 'EX_gudptn_e' was added non-curated model.
Reaction 'EX_hcys__L_e' was added non-curated model.
Reaction 'EX_hg2_e' was added non-curated model.
Reaction 'EX_hgentis_e' was added non-curated model.
Reaction 'EX_hom__L_e' was added non-curated model.
Reaction 'EX_hxan_e' was added non-curated model.
Reaction 'EX_ins_e' was added non-curated model.
Reaction 'EX_isetac_e' was added non-curated model.
Reaction 'EX_lac__D_e' was added non-curated model.
Reaction 'EX_lac__L_e' was added non-curated model.
Reaction 'EX_lpspput_e' was added non-curated model.
Reaction 'EX_lys__D_e' was added non-curated model.
Reaction 'EX_mal__D_e' was added non-curated model.
Reaction 'EX_mal__L_e' was added non-curated model.
Reaction 'EX_manur_e' was added non-curated model.
Reaction 'EX_mcbtt_e' was added non-curated model.
Reaction 'EX_meoh_e' was added non-curated model.
Reaction 'EX_mmet_e' was added non-curated model.
Reaction 'EX_nac_e' was added non-curated model.
Reaction 'EX_ni2_e' was added non-curated model.
Reaction 'EX_o_xyl_e' was added non-curated model.
Reaction 'EX_oaa_e' was added non-curated model.
Reaction 'EX_orot_e' was added non-curated model.
Reaction 'EX_oxa_e' was added non-curated model.
Reaction 'EX_5g2oxpt_e' was added non-curated model.
Reaction 'EX_pac_e' was added non-curated model.
Reaction 'EX_pacald_e' was added non-curated model.
Reaction 'EX_pb2_e' was added non-curated model.
Reaction 'EX_phe__D_e' was added non-curated model.
Reaction 'EX_phpyr_e' was added non-curated model.
Reaction 'EX_pnto__R_e' was added non-curated model.
Reaction 'EX_ppa_e' was added non-curated model.
Reaction 'EX_ppi_e' was added non-curated model.
Reaction 'EX_prealg_MG_14_e' was added non-curated model.
Reaction 'EX_prealg_MG_23_e' was added non-curated model.
Reaction 'EX_prealg_MG_32_e' was added non-curated model.
Reaction 'EX_prealg_MG_41_e' was added non-curated model.
Reaction 'EX_prealginate_G_e' was added non-curated model.
Reaction 'EX_pro__D_e' was added non-curated model.
Reaction 'EX_pyovd_e' was added non-curated model.
Reaction 'EX_pyr_e' was added non-curated model.
Reaction 'EX_quin_e' was added non-curated model.
Reaction 'EX_sbo3_e' was added non-curated model.
Reaction 'EX_ser__D_e' was added non-curated model.
Reaction 'EX_skm_e' was added non-curated model.
Reaction 'EX_so2_e' was added non-curated model.
Reaction 'EX_sulfac_e' was added non-curated model.
Reaction 'EX_tag160_e' was added non-curated model.
Reaction 'EX_tag180_e' was added non-curated model.
Reaction 'EX_tag181d9_e' was added non-curated model.
Reaction 'EX_tag182d9d12_e' was added non-curated model.
Reaction 'EX_thym_e' was added non-curated model.
Reaction 'EX_tmanur_e' was added non-curated model.
Reaction 'EX_tungs_e' was added non-curated model.
Reaction 'EX_ura_e' was added non-curated model.
Reaction 'EX_uri_e' was added non-curated model.
Reaction 'EX_vanlt_e' was added non-curated model.
Reaction 'EX_xan_e' was added non-curated model.
Reaction 'FA100ACPHi' was added non-curated model.
Reaction 'FA120ACPHi' was added non-curated model.
Reaction 'FA140ACPHi' was added non-curated model.
Reaction 'FA141ACPHi' was added non-curated model.
Reaction 'FA160ACPHi' was added non-curated model.
Reaction 'FA161ACPHi' was added non-curated model.
Reaction 'FA80ACPHi' was added non-curated model.
Reaction 'HMR_0180_copy1' was added non-curated model.
Reaction 'HMR_0188' was added non-curated model.
Reaction 'FACOAL141' was added non-curated model.
Reaction 'FACOAL180' was added non-curated model.
Reaction 'FACOAL60i' was added non-curated model.
Reaction 'FACOAL80' was added non-curated model.
Reaction 'FALDH2' was added non-curated model.
Reaction 'FALDM' was added non-curated model.
Reaction 'FALDtex' was added non-curated model.
Reaction 'FALDtpp' was added non-curated model.
Reaction 'FALDtpp2' was added non-curated model.
Reaction 'PPAtex' was added non-curated model.
Reaction 'FALGTHLs' was added non-curated model.
Reaction 'FBACS' was added non-curated model.

### Add metabolites from a curated model

In [51]:
# Create a copy of the non-curated model
copy_of_model1 = model1.copy()

# Iterate through reactions in the curated model
for metabolite in copy_of_model1.metabolites:
    # Check if the reaction exists in the non-curated model
    if metabolite.id not in copy_of_model.metabolites:
        new_metabolite = Metabolite(
        id=metabolite.id,     # Metabolite ID
        name=metabolite.name,     # Metabolite Name
        formula=metabolite.formula,         # Chemical Formula
        compartment=metabolite.compartment,            # Compartment (e.g., cytoplasm)
        )

        new_metabolite.charge = metabolite.charge 
        new_metabolite.annotation = metabolite.annotation

        copy_of_model.add_metabolites([new_metabolite])
        print(f"Reaction '{metabolite.id}' was added to the non-curated model.")
    else:
        pass

Reaction '12dgr160_e' was added to the non-curated model.
Reaction '12dgr180_e' was added to the non-curated model.
Reaction '13dampp_e' was added to the non-curated model.
Reaction '13dampp_p' was added to the non-curated model.
Reaction '3mb_e' was added to the non-curated model.
Reaction '3mb_p' was added to the non-curated model.
Reaction '3mbzalc_c' was added to the non-curated model.
Reaction '3mbzald_c' was added to the non-curated model.
Reaction '3mcat_c' was added to the non-curated model.
Reaction '15dap_e' was added to the non-curated model.
Reaction '2ombzl_c' was added to the non-curated model.
Reaction '2omcm_c' was added to the non-curated model.
Reaction '15dap_p' was added to the non-curated model.
Reaction '2omhmbl_c' was added to the non-curated model.
Reaction '2ommbl_c' was added to the non-curated model.
Reaction '3ocddec5eACP_c' was added to the non-curated model.
Reaction '2omph_c' was added to the non-curated model.
Reaction '3ocmrs7eACP_c' was added to the non-curated model.
Reaction '1ag160_e' was added to the non-curated model.
Reaction '3ocpalm9eACP_c' was added to the non-curated model.
Reaction '1ag180_e' was added to the non-curated model.
Reaction '3ocvac11eACP_c' was added to the non-curated model.
Reaction '1ag181d9_e' was added to the non-curated model.
Reaction '1ag182d9d12_e' was added to the non-curated model.
Reaction '1agpe160_p' was added to the non-curated model.
Reaction '1agpe161_p' was added to the non-curated model.
Reaction '1agpe180_p' was added to the non-curated model.
Reaction '3oddecACP_c' was added to the non-curated model.
Reaction '3odecACP_c' was added to the non-curated model.
Reaction '2pqq_c' was added to the non-curated model.
Reaction '34dhbald_c' was added to the non-curated model.
Reaction '1agpg160_p' was added to the non-curated model.
Reaction '1agpg161_p' was added to the non-curated model.
Reaction '1agpg180_p' was added to the non-curated model.
Reaction '34dhcinm_c' was added to the non-curated model.
Reaction '34dhcinm_e' was added to the non-curated model.
Reaction '1ddecg3p_c' was added to the non-curated model.
Reaction '1hdec9eg3p_c' was added to the non-curated model.
Reaction '34dhcinm_p' was added to the non-curated model.
Reaction '1odecg3p_c' was added to the non-curated model.
Reaction '3ohdd7coa_c' was added to the non-curated model.
Reaction '3ohexACP_c' was added to the non-curated model.
Reaction '34dhphe_c' was added to the non-curated model.
Reaction '1pipdn2c_c' was added to the non-curated model.
Reaction '3omrsACP_c' was added to the non-curated model.
Reaction '1pqq_c' was added to the non-curated model.
Reaction '3ooctACP_c' was added to the non-curated model.
Reaction '1tdec7eg3p_c' was added to the non-curated model.
Reaction '1tdecg3p_c' was added to the non-curated model.
Reaction '3ooctdACP_c' was added to the non-curated model.
Reaction '34dhphe_e' was added to the non-curated model.
Reaction '34dhphe_p' was added to the non-curated model.
Reaction '3oodecoa_c' was added to the non-curated model.
Reaction '3opalmACP_c' was added to the non-curated model.
Reaction '3_rhma13unaga_c' was added to the non-curated model.
Reaction '26dap__M_e' was added to the non-curated model.
Reaction '3hasp__L_c' was added to the non-curated model.
Reaction '26dap__M_p' was added to the non-curated model.
Reaction '3oxoadp_e' was added to the non-curated model.
Reaction '2agpe160_p' was added to the non-curated model.
Reaction '3oxoadp_p' was added to the non-curated model.
Reaction '2agpe180_c' was added to the non-curated model.
Reaction '2agpe180_p' was added to the non-curated model.
Reaction '3hcddec5eACP_c' was added to the non-curated model.
Reaction '3hcmrs7eACP_c' was added to the non-curated model.
Reaction '3pqq_c' was added to the non-curated model.
Reaction '3hcpalm9eACP_c' was added to the non-curated model.
Reaction '3hcvac11eACP_c' was added to the non-curated model.
Reaction '3hddecACP_c' was added to the non-curated model.
Reaction '3hdecACP_c' was added to the non-curated model.
Reaction 'coucoa_c' was added to the non-curated model.
Reaction '3hhdd7coa_c' was added to the non-curated model.
Reaction '4fe4s_c' was added to the non-curated model.
Reaction '3hhexACP_c' was added to the non-curated model.
Reaction '2ddglcn_e' was added to the non-curated model.
Reaction '2dhglcn_e' was added to the non-curated model.
Reaction '2fe1s_c' was added to the non-curated model.
Reaction '2fe2s_c' was added to the non-curated model.
Reaction '4hbz_e' was added to the non-curated model.
Reaction '3hoctACP_c' was added to the non-curated model.
Reaction '3hoctaACP_c' was added to the non-curated model.
Reaction '4hoxoh_c' was added to the non-curated model.
Reaction '3hodecoa_c' was added to the non-curated model.
Reaction '3hpalmACP_c' was added to the non-curated model.
Reaction '2hchd_c' was added to the non-curated model.
Reaction '2hmc_c' was added to the non-curated model.
Reaction '4izp_c' was added to the non-curated model.
Reaction '4mbzalc_c' was added to the non-curated model.
Reaction '4mbzald_c' was added to the non-curated model.
Reaction '4mcat_c' was added to the non-curated model.
Reaction '4pqq_c' was added to the non-curated model.
Reaction '56dura_c' was added to the non-curated model.
Reaction 'Lpipecol_c' was added to the non-curated model.
Reaction 'R_3htd5e_e' was added to the non-curated model.
Reaction 'Ncarbsar_c' was added to the non-curated model.
Reaction 'R_3htd5e_p' was added to the non-curated model.
Reaction '5apentam_c' was added to the non-curated model.
Reaction 'Nforglu_c' was added to the non-curated model.
Reaction 'PHAg_c' was added to the non-curated model.
Reaction 'R_3httdca_e' was added to the non-curated model.
Reaction '5aptn_e' was added to the non-curated model.
Reaction 'R_3httdca_p' was added to the non-curated model.
Reaction '5aptn_p' was added to the non-curated model.
Reaction 'R3hdec4e_e' was added to the non-curated model.
Reaction 'R3hdec4e_p' was added to the non-curated model.
Reaction 'Sfglutth_c' was added to the non-curated model.
Reaction 'T4hcinnm_c' was added to the non-curated model.
Reaction 'T4hcinnm_e' was added to the non-curated model.
Reaction 'R_3h4atba_e' was added to the non-curated model.
Reaction 'R_3h4atba_p' was added to the non-curated model.
Reaction 'R_3h6atha_e' was added to the non-curated model.
Reaction 'T4hcinnm_p' was added to the non-curated model.
Reaction 'aac24dab_c' was added to the non-curated model.
Reaction 'R_3h6atha_p' was added to the non-curated model.
Reaction '5mdr1p_c' was added to the non-curated model.
Reaction 'R_3hcmrs7e_e' was added to the non-curated model.
Reaction '5mdru1p_c' was added to the non-curated model.
Reaction 'R_3hcmrs7e_p' was added to the non-curated model.
Reaction 'acACP_c' was added to the non-curated model.
Reaction 'R_3hdcaa_e' was added to the non-curated model.
Reaction 'R_3hdcaa_p' was added to the non-curated model.
Reaction '5oxpro_e' was added to the non-curated model.
Reaction 'acac_e' was added to the non-curated model.
Reaction 'acac_p' was added to the non-curated model.
Reaction 'R_3hdd5ea_e' was added to the non-curated model.
Reaction 'R_3hdd5ea_p' was added to the non-curated model.
Reaction '5oxpro_p' was added to the non-curated model.
Reaction '5prdmbz_c' was added to the non-curated model.
Reaction 'R_3hdd6e_e' was added to the non-curated model.
Reaction 'R_3hdd6e_p' was added to the non-curated model.
Reaction 'R_3hdda_e' was added to the non-curated model.
Reaction 'R_3hdda_p' was added to the non-curated model.
Reaction '6hnac_e' was added to the non-curated model.
Reaction 'R_3hhdca_e' was added to the non-curated model.
Reaction '6hnac_p' was added to the non-curated model.
Reaction 'R_3hhdca_p' was added to the non-curated model.
Reaction '6p2dhglcn_c' was added to the non-curated model.
Reaction '8aonn_c' was added to the non-curated model.
Reaction 'acon_T_c' was added to the non-curated model.
Reaction 'aconm_c' was added to the non-curated model.
Reaction 'C100aPHA_c' was added to the non-curated model.
Reaction 'R_3hhxa_e' was added to the non-curated model.
Reaction 'C100pPHA_c' was added to the non-curated model.
Reaction 'R_3hhxa_p' was added to the non-curated model.
Reaction 'C101PAH_c' was added to the non-curated model.
Reaction 'acser_e' was added to the non-curated model.
Reaction 'acser_p' was added to the non-curated model.
Reaction 'C120aPHA_c' was added to the non-curated model.
Reaction 'C121aPHA_c' was added to the non-curated model.
Reaction 'C121d6PHA_c' was added to the non-curated model.
Reaction 'C140aPHA_c' was added to the non-curated model.
Reaction 'R_3hocta_e' was added to the non-curated model.
Reaction 'C141aPHA_c' was added to the non-curated model.
Reaction 'R_3hocta_p' was added to the non-curated model.
Reaction 'C141d5PHA_c' was added to the non-curated model.
Reaction 'C142PHA_c' was added to the non-curated model.
Reaction 'actn__R_p' was added to the non-curated model.
Reaction 'C40aPHA_c' was added to the non-curated model.
Reaction 'C40atPHA_c' was added to the non-curated model.
Reaction 'C40pPHA_c' was added to the non-curated model.
Reaction 'ad_c' was added to the non-curated model.
Reaction 'C50aPHA_c' was added to the non-curated model.
Reaction 'C50pPHA_c' was added to the non-curated model.
Reaction 'adcobdam_c' was added to the non-curated model.
Reaction 'C60aPHA_c' was added to the non-curated model.
Reaction 'C60atPHA_c' was added to the non-curated model.
Reaction 'C60pPHA_c' was added to the non-curated model.
Reaction 'C70aPHA_c' was added to the non-curated model.
Reaction 'R_3hphxa_e' was added to the non-curated model.
Reaction 'C70pPHA_c' was added to the non-curated model.
Reaction 'R_3hphxa_p' was added to the non-curated model.
Reaction 'C80aPHA_c' was added to the non-curated model.
Reaction 'adn_e' was added to the non-curated model.
Reaction 'C80pPHA_c' was added to the non-curated model.
Reaction 'adn_p' was added to the non-curated model.
Reaction 'C90aPHA_c' was added to the non-curated model.
Reaction 'C90pPHA_c' was added to the non-curated model.
Reaction 'adocbl_c' was added to the non-curated model.
Reaction 'adocbl_e' was added to the non-curated model.
Reaction 'adocbl_p' was added to the non-curated model.
Reaction 'R_3hppta_e' was added to the non-curated model.
Reaction 'adphep_DD_c' was added to the non-curated model.
Reaction 'met__D_p' was added to the non-curated model.
Reaction 'adphep_LD_c' was added to the non-curated model.
Reaction 'R_3hppta_p' was added to the non-curated model.
Reaction 'ala_B_p' was added to the non-curated model.
Reaction 'ag_c' was added to the non-curated model.
Reaction 'ag_e' was added to the non-curated model.
Reaction 'ag_p' was added to the non-curated model.
Reaction 'agdpcbi_c' was added to the non-curated model.
Reaction 'alaala_e' was added to the non-curated model.
Reaction 'asptrna_c' was added to the non-curated model.
Reaction 'akg_e' was added to the non-curated model.
Reaction 'akg_p' was added to the non-curated model.
Reaction 'ala_B_e' was added to the non-curated model.
Reaction 'balaala_c' was added to the non-curated model.
Reaction 'balaala_e' was added to the non-curated model.
Reaction 'balaala_p' was added to the non-curated model.
Reaction 'balabala_c' was added to the non-curated model.
Reaction 'balabala_e' was added to the non-curated model.
Reaction 'alatrna_c' was added to the non-curated model.
Reaction 'balabala_p' was added to the non-curated model.
Reaction 'cell4_e' was added to the non-curated model.
Reaction 'balagly_c' was added to the non-curated model.
Reaction 'balagly_e' was added to the non-curated model.
Reaction 'cell4_p' was added to the non-curated model.
Reaction 'balagly_p' was added to the non-curated model.
Reaction 'cellb_p' was added to the non-curated model.
Reaction 'algac_MG_14_e' was added to the non-curated model.
Reaction 'balaleu_c' was added to the non-curated model.
Reaction 'algac_MG_14_p' was added to the non-curated model.
Reaction 'balaleu_e' was added to the non-curated model.
Reaction 'algac_MG_23_e' was added to the non-curated model.
Reaction 'algac_MG_23_p' was added to the non-curated model.
Reaction 'balaleu_p' was added to the non-curated model.
Reaction 'algac_MG_32_e' was added to the non-curated model.
Reaction 'balamd_c' was added to the non-curated model.
Reaction 'algac_MG_32_p' was added to the non-curated model.
Reaction 'balamd_e' was added to the non-curated model.
Reaction 'algac_MG_41_e' was added to the non-curated model.
Reaction 'ch4s_c' was added to the non-curated model.
Reaction 'balamd_p' was added to the non-curated model.
Reaction 'algac_MG_41_p' was added to the non-curated model.
Reaction 'algac__M_e' was added to the non-curated model.
Reaction 'algac__M_p' was added to the non-curated model.
Reaction 'bglyg4n_c' was added to the non-curated model.
Reaction 'alltn__R_c' was added to the non-curated model.
Reaction 'chols_p' was added to the non-curated model.
Reaction 'alltn_e' was added to the non-curated model.
Reaction 'alltn_p' was added to the non-curated model.
Reaction 'alpp_p' was added to the non-curated model.
Reaction 'altrn_c' was added to the non-curated model.
Reaction 'chor_e' was added to the non-curated model.
Reaction 'biliverd_c' was added to the non-curated model.
Reaction 'chor_p' was added to the non-curated model.
Reaction 'amob_c' was added to the non-curated model.
Reaction 'biliverd_e' was added to the non-curated model.
Reaction 'amp_p' was added to the non-curated model.
Reaction 'biliverd_p' was added to the non-curated model.
Reaction 'bmoco1gdp_c' was added to the non-curated model.
Reaction 'bmoco_c' was added to the non-curated model.
Reaction 'cit_e' was added to the non-curated model.
Reaction 'bmocogdp_c' was added to the non-curated model.
Reaction 'btamp_c' was added to the non-curated model.
Reaction 'btd_RR_c' was added to the non-curated model.
Reaction 'ap4a_c' was added to the non-curated model.
Reaction 'apc_c' was added to the non-curated model.
Reaction 'btd_RR_e' was added to the non-curated model.
Reaction 'btd_RR_p' was added to the non-curated model.
Reaction 'apoACP_c' was added to the non-curated model.
Reaction 'btn_e' was added to the non-curated model.
Reaction 'btn_p' was added to the non-curated model.
Reaction 'clpn161e9_p' was added to the non-curated model.
Reaction 'butACP_c' was added to the non-curated model.
Reaction 'clpn181e11_p' was added to the non-curated model.
Reaction 'butso3_c' was added to the non-curated model.
Reaction 'arbtn_c' was added to the non-curated model.
Reaction 'butso3_e' was added to the non-curated model.
Reaction 'arbtn_e' was added to the non-curated model.
Reaction 'butso3_p' was added to the non-curated model.
Reaction 'arbtn_fe3_c' was added to the non-curated model.
Reaction 'bwco1gdp_c' was added to the non-curated model.
Reaction 'arbtn_fe3_e' was added to the non-curated model.
Reaction 'bwco_c' was added to the non-curated model.
Reaction 'arbtn_fe3_p' was added to the non-curated model.
Reaction 'bwcogdp_c' was added to the non-curated model.
Reaction 'arbtn_p' was added to the non-curated model.
Reaction 'bz12diol_c' was added to the non-curated model.
Reaction 'cmcbtt_e' was added to the non-curated model.
Reaction 'cmcbtt_p' was added to the non-curated model.
Reaction 'arg__D_e' was added to the non-curated model.
Reaction 'bz_p' was added to the non-curated model.
Reaction 'arg__D_p' was added to the non-curated model.
Reaction 'cmp_p' was added to the non-curated model.
Reaction 'bzalc_c' was added to the non-curated model.
Reaction 'co1dam_c' was added to the non-curated model.
Reaction 'argtrna_c' was added to the non-curated model.
Reaction 'co2dam_c' was added to the non-curated model.
Reaction 'asn__D_c' was added to the non-curated model.
Reaction 'asn__D_e' was added to the non-curated model.
Reaction 'asn__D_p' was added to the non-curated model.
Reaction 'caffcoa_c' was added to the non-curated model.
Reaction 'cala_c' was added to the non-curated model.
Reaction 'asn__L_p' was added to the non-curated model.
Reaction 'aso3_p' was added to the non-curated model.
Reaction 'confrl_c' was added to the non-curated model.
Reaction 'confrl_e' was added to the non-curated model.
Reaction 'confrl_p' was added to the non-curated model.
Reaction 'catechol_e' was added to the non-curated model.
Reaction 'conialdh_c' was added to the non-curated model.
Reaction 'catechol_p' was added to the non-curated model.
Reaction 'cpe160_c' was added to the non-curated model.
Reaction 'cpe180_c' was added to the non-curated model.
Reaction 'cpg160_c' was added to the non-curated model.
Reaction 'cu_c' was added to the non-curated model.
Reaction 'cbi_c' was added to the non-curated model.
Reaction 'cpg180_c' was added to the non-curated model.
Reaction 'cbi_e' was added to the non-curated model.
Reaction 'cu_e' was added to the non-curated model.
Reaction 'cbi_p' was added to the non-curated model.
Reaction 'cph4_c' was added to the non-curated model.
Reaction 'cbl1_c' was added to the non-curated model.
Reaction 'cpmp_c' was added to the non-curated model.
Reaction 'cu_p' was added to the non-curated model.
Reaction 'cbl1_e' was added to the non-curated model.
Reaction 'cbl1_p' was added to the non-curated model.
Reaction 'cchoxod_c' was added to the non-curated model.
Reaction 'cys__D_e' was added to the non-curated model.
Reaction 'creat_c' was added to the non-curated model.
Reaction 'cys__D_p' was added to the non-curated model.
Reaction 'creat_e' was added to the non-curated model.
Reaction 'creat_p' was added to the non-curated model.
Reaction 'cddec5eACP_c' was added to the non-curated model.
Reaction 'cdec3eACP_c' was added to the non-curated model.
Reaction 'cdg_c' was added to the non-curated model.
Reaction 'cystrna_c' was added to the non-curated model.
Reaction 'cro2_c' was added to the non-curated model.
Reaction 'cro2_e' was added to the non-curated model.
Reaction 'cro2_p' was added to the non-curated model.
Reaction 'cytd_p' was added to the non-curated model.
Reaction 'cro4_e' was added to the non-curated model.
Reaction 'dad_2_p' was added to the non-curated model.
Reaction 'crtn_c' was added to the non-curated model.
Reaction 'dmso2_e' was added to the non-curated model.
Reaction 'dag181d9_e' was added to the non-curated model.
Reaction 'dmso2_p' was added to the non-curated model.
Reaction 'dag182d9d12_e' was added to the non-curated model.
Reaction 'crtn_e' was added to the non-curated model.
Reaction 'crtn_p' was added to the non-curated model.
Reaction 'damp_p' was added to the non-curated model.
Reaction 'dann_c' was added to the non-curated model.
Reaction 'csn_p' was added to the non-curated model.
Reaction 'dopa_c' was added to the non-curated model.
Reaction 'cspmd_c' was added to the non-curated model.
Reaction 'dopa_e' was added to the non-curated model.
Reaction 'dcaACP_c' was added to the non-curated model.
Reaction 'dopa_p' was added to the non-curated model.
Reaction 'doxopa_c' was added to the non-curated model.
Reaction 'dsbaox_p' was added to the non-curated model.
Reaction 'dsbard_p' was added to the non-curated model.
Reaction 'feoxam_c' was added to the non-curated model.
Reaction 'dsbcox_p' was added to the non-curated model.
Reaction 'feoxam_e' was added to the non-curated model.
Reaction 'dcmp_p' was added to the non-curated model.
Reaction 'dsbcrd_p' was added to the non-curated model.
Reaction 'feoxam_p' was added to the non-curated model.
Reaction 'dsbdox_c' was added to the non-curated model.
Reaction 'feoxam_un_c' was added to the non-curated model.
Reaction 'feoxam_un_e' was added to the non-curated model.
Reaction 'dsbdrd_c' was added to the non-curated model.
Reaction 'feoxam_un_p' was added to the non-curated model.
Reaction 'dcyt_p' was added to the non-curated model.
Reaction 'dsbgox_p' was added to the non-curated model.

### Update metabolite with coa substring

In [16]:
substring_to_check = 'coa'
for metabolite in copy_of_model.metabolites:
    if substring_to_check in metabolite.id:
        if metabolite.charge == 0:
            metabolite.charge = -4
            # Print information about the modified metabolite
            print(f"Modified metabolite: {metabolite.id}")
            print(f"Updated charge of : {metabolite.charge}")

Modified metabolite: 2maacoa_c
Updated charge of : -4
Modified metabolite: 3hhd710coa_c
Updated charge of : -4
Modified metabolite: 3hhdccoa_c
Updated charge of : -4
Modified metabolite: 3hhdd4coa_c
Updated charge of : -4
Modified metabolite: 3hlnlccoa_c
Updated charge of : -4
Modified metabolite: 3hocoa_c
Updated charge of : -4
Modified metabolite: 3hodcoa_c
Updated charge of : -4
Modified metabolite: 3mgcoa_c
Updated charge of : -4
Modified metabolite: 3ohd710coa_c
Updated charge of : -4
Modified metabolite: 3ohdccoa_c
Updated charge of : -4
Modified metabolite: 3ohdd4coa_c
Updated charge of : -4
Modified metabolite: 3olnlccoa_c
Updated charge of : -4
Modified metabolite: benzcoa_c
Updated charge of : -4
Modified metabolite: ctncoa_c
Updated charge of : -4
Modified metabolite: hd2coa_c
Updated charge of : -4
Modified metabolite: hd710_2_coa_c
Updated charge of : -4
Modified metabolite: hd_7_10_coa_c
Updated charge of : -4
Modified metabolite: hdd4_2_coa_c
Updated charge of : -4
Modified metabolite: hmpscoa_c
Updated charge of : -4
Modified metabolite: lnlc2coa_c
Updated charge of : -4
Modified metabolite: lnlccoa_c
Updated charge of : -4
Modified metabolite: m2bcoa_c
Updated charge of : -4
Modified metabolite: oc2coa_c
Updated charge of : -4
Modified metabolite: phitcoa_c
Updated charge of : -4
Modified metabolite: sbzcoa_c
Updated charge of : -4
Modified metabolite: td2coa_c
Updated charge of : -4
Modified metabolite: td_5_8_coa_c
Updated charge of : -4
Modified metabolite: tde_2Z_coa_c
Updated charge of : -4
Modified metabolite: tdecoa_c
Updated charge of : -4
Modified metabolite: vacccoa_c
Updated charge of : -4

I noticed that carveme doesn't provide the appropriate charge for metabolites with Coa molecules

# Create a list of all reactions

In [ ]:
df_reactions = pd.DataFrame(columns=['reaction_id','reaction_name','reaction_equation','reaction_lower_bound','reaction_upper_bound','reaction_gene','reaction_annotation'])

In [16]:
# Iterate over all reactions in the model and populate the DataFrame
for reaction in copy_of_model.reactions:
    # Create a DataFrame for the current reaction
    reaction_data = pd.DataFrame([{
        "reaction_id": reaction.id,
        "reaction_name": reaction.name,
        "reaction_equation": reaction.reaction,
        "reaction_lower_bound": reaction.lower_bound,
        "reaction_upper_bound": reaction.upper_bound,
        "reaction_gene": reaction.gene_reaction_rule,
        "reaction_annotation": reaction.annotation
    }])
    
    # Concatenate the current reaction's DataFrame to the main DataFrame
    df_reactions = pd.concat([df_reactions, reaction_data], ignore_index=True)

# Print the resulting DataFrame to verify the results
df_reactions.to_excel('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\reaction_list.xlsx',index=False)

# Create a list of all metabolites

In [18]:
df_metabolites = pd.DataFrame(columns=['metabolite_id','metabolite_name','metabolite_formula','metabolite_charge','related_reactions'])

In [19]:
# Iterate over all reactions in the model and populate the DataFrame
for metabolite in copy_of_model.metabolites:
    # Create a DataFrame for the current reaction
    metabolite_data = pd.DataFrame([{
        "metabolite_id": metabolite.id,
        "metabolite_name": metabolite.name,
        "metabolite_formula": metabolite.formula,
        "metabolite_charge": metabolite.charge,
        "related_reactions": list(metabolite.reactions),
    }])
    # Concatenate the current reaction's DataFrame to the main DataFrame
    df_metabolites = pd.concat([df_metabolites, metabolite_data], ignore_index=True)

# Print the resulting DataFrame to verify the results
df_metabolites.to_excel('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\metabolites_list.xlsx',index=False)

# Create a list of all metabolites in a reaction

In [7]:
df_reaction2 = pd.DataFrame(columns=['met_id','met_name','met_coeff','met_charge'])

In [8]:
reaction_id_to_check = 'Growth'
reaction = copy_of_model.reactions.get_by_id(reaction_id_to_check)
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id:<15}: {coefficient:>25}  Name: {metabolite.name:<60}  Charge: {metabolite.charge:>3}  Formula: {metabolite.formula}")
    # Create a DataFrame for the current reaction
    reaction_data = pd.DataFrame([{
        "met_id": metabolite.id,
        "met_name": metabolite.name,
        "met_coeff": coefficient,
        "met_charge": metabolite.charge,
    }])
    # Concatenate the current reaction's DataFrame to the main DataFrame
    df_reaction2 = pd.concat([df_reaction2, reaction_data], ignore_index=True)

df_reaction2.to_excel('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\Data\\Models\\Manual Curation\\Biomass Equation\\growth_met_list_updated.xlsx',index=False)

10fthf_c       :                 -0.000223  Name: 10-Formyltetrahydrofolate                                     Charge:  -2  Formula: C20H21N7O7
ala__L_c       :                 -0.513689  Name: L-Alanine                                                     Charge:   0  Formula: C3H7NO2
amet_c         :                 -0.000223  Name: S-Adenosyl-L-methionine                                       Charge:   1  Formula: C15H23N6O5S
arg__L_c       :                 -0.295792  Name: L-Arginine                                                    Charge:   1  Formula: C6H15N4O2
asn__L_c       :                 -0.241055  Name: L-Asparagine                                                  Charge:   0  Formula: C4H8N2O3
asp__L_c       :                 -0.241055  Name: L-Aspartate                                                   Charge:  -1  Formula: C4H6NO4
atp_c          :              -29.18042275  Name: ATP C10H12N5O13P3                                             Charge:  -4  Formula: C10H12N5O13P3
ca2_c          :                 -0.005205  Name: Calcium                                                       Charge:   2  Formula: Ca
cl_c           :                 -0.005205  Name: Chloride                                                      Charge:  -1  Formula: Cl
coa_c          :                 -0.000576  Name: Coenzyme A                                                    Charge:  -4  Formula: C21H32N7O16P3S
cobalt2_c      :                   -0.0001  Name: Co2+                                                          Charge:   2  Formula: Co
ctp_c          :                 -0.133508  Name: CTP C9H12N3O14P3                                              Charge:  -4  Formula: C9H12N3O14P3
cu2_c          :                 -0.000709  Name: Copper                                                        Charge:   2  Formula: Cu
cys__L_c       :                  -0.09158  Name: L-Cysteine                                                    Charge:   0  Formula: C3H7NO2S
datp_c         :                 -0.026166  Name: DATP C10H12N5O12P3                                            Charge:  -4  Formula: C10H12N5O12P3
dctp_c         :                 -0.027017  Name: DCTP C9H12N3O13P3                                             Charge:  -4  Formula: C9H12N3O13P3
dgtp_c         :                 -0.027017  Name: DGTP C10H12N5O13P3                                            Charge:  -4  Formula: C10H12N5O13P3
dttp_c         :                 -0.026166  Name: DTTP C10H13N2O14P3                                            Charge:  -4  Formula: C10H13N2O14P3
fad_c          :                 -0.000223  Name: Flavin adenine dinucleotide oxidized                          Charge:  -2  Formula: C27H31N9O15P2
fe2_c          :                 -0.006715  Name: Fe2+ mitochondria                                             Charge:   2  Formula: Fe
fe3_c          :                 -0.007808  Name: Iron (Fe3+)                                                   Charge:   3  Formula: Fe
gln__L_c       :                  -0.26316  Name: L-Glutamine                                                   Charge:   0  Formula: C5H10N2O3
glu__L_c       :                  -0.26316  Name: L-Glutamate                                                   Charge:  -1  Formula: C5H8NO4
gly_c          :                 -0.612638  Name: Glycine                                                       Charge:   0  Formula: C2H5NO2
gtp_c          :                 -0.215096  Name: GTP C10H12N5O14P3                                             Charge:  -4  Formula: C10H12N5O14P3
h2o_c          :              -29.18042275  Name: H2O H2O                                                       Charge:   0  Formula: H2O
his__L_c       :                 -0.094738  Name: L-Histidine                                                   Charge:   0  Formula: C6H9N3O2
ile__L_c       :                 -0.290529  Name: L-Isoleucine                                                  Charge:   0  Formula: C6H13NO2
k_c            :                 -0.195193  Name: Potassium                                                     Charge:   1  Formula: K
kdo2lipid4_p   :                 -0.019456  Name: KDO(2)-lipid IV(A)                                            Charge:  -6  Formula: C84H148N2O37P2
leu__L_c       :                 -0.450531  Name: L-Leucine                                                     Charge:   0  Formula: C6H13NO2
lys__L_c       :                 -0.343161  Name: L-Lysine                                                      Charge:   1  Formula: C6H15N2O2
met__L_c       :                 -0.153686  Name: L-Methionine                                                  Charge:   0  Formula: C5H11NO2S
mg2_c          :                 -0.008675  Name: Magnesium                                                     Charge:   2  Formula: Mg
mlthf_c        :                 -0.000223  Name: 5,10-Methylenetetrahydrofolate                                Charge:  -2  Formula: C20H21N7O6
mn2_c          :                 -0.000691  Name: Manganese                                                     Charge:   2  Formula: Mn
mql8_c         :                   -0.0001  Name: Menaquinol 8                                                  Charge:   0  Formula: C51H74O2
murein5px4p_p  :                 -0.013894  Name: Two disacharide linked murein units, pentapeptide crosslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C77H117N15O40
nad_c          :                 -0.001831  Name: Nicotinamide adenine dinucleotide                             Charge:  -1  Formula: C21H26N7O14P2
nadp_c         :                 -0.000447  Name: Nicotinamide adenine dinucleotide phosphate                   Charge:  -3  Formula: C21H25N7O17P3
pe160_c        :                 -0.017868  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pe160_p        :                 -0.045946  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pe161_c        :                 -0.054154  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70NO8P
pe161_p        :                  -0.02106  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70NO8P
phe__L_c       :                 -0.185265  Name: L-Phenylalanine                                               Charge:   0  Formula: C9H11NO2
pheme_c        :                 -0.000223  Name: Protoheme C34H30FeN4O4                                        Charge:  -2  Formula: C34H30FeN4O4
pro__L_c       :                 -0.221055  Name: L-Proline                                                     Charge:   0  Formula: C5H9NO2
pydx5p_c       :                 -0.000223  Name: Pyridoxal 5'-phosphate                                        Charge:  -2  Formula: C8H8NO6P
ribflv_c       :                 -0.000223  Name: Riboflavin C17H20N4O6                                         Charge:   0  Formula: C17H20N4O6
ser__L_c       :                 -0.215792  Name: L-Serine                                                      Charge:   0  Formula: C3H7NO3
sheme_c        :                 -0.000223  Name: Siroheme C42H36FeN4O16                                        Charge:  -8  Formula: C42H36FeN4O16
so4_c          :                 -0.004338  Name: Sulfate                                                       Charge:  -2  Formula: O4S
thf_c          :                 -0.000223  Name: 5,6,7,8-Tetrahydrofolate                                      Charge:  -2  Formula: C19H21N7O6
thmpp_c        :                 -0.000223  Name: Thiamine diphosphate                                          Charge:  -2  Formula: C12H16N4O7P2S
thr__L_c       :                 -0.253687  Name: L-Threonine                                                   Charge:   0  Formula: C4H9NO3
trp__L_c       :                 -0.056843  Name: L-Tryptophan                                                  Charge:   0  Formula: C11H12N2O2
tyr__L_c       :                 -0.137896  Name: L-Tyrosine                                                    Charge:   0  Formula: C9H11NO3
utp_c          :                 -0.144104  Name: UTP C9H11N2O15P3                                              Charge:  -4  Formula: C9H11N2O15P3
val__L_c       :                 -0.423162  Name: L-Valine                                                      Charge:   0  Formula: C5H11NO2
zn2_c          :                 -0.000341  Name: Zinc                                                          Charge:   2  Formula: Zn
murein3px4p_p  :                 -0.000605  Name: Two disacharide linked murein units, tripeptide crosslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C71H107N13O38
accoa_c        :                 -0.000279  Name: Acetyl-CoA                                                    Charge:  -4  Formula: C23H34N7O17P3S
murein4p3p_p   :                 -0.001345  Name: Two linked disacharide tetrapeptide and tripeptide murein units (uncrosslinked, middle of chain)  Charge:  -4  Formula: C71H109N13O39
5mthf_c        :                 -0.000223  Name: 5-Methyltetrahydrofolate                                      Charge:  -1  Formula: C20H24N7O6
nh4_c          :                 -0.012379  Name: Ammonium                                                      Charge:   1  Formula: H4N
chor_c         :                 -0.000223  Name: Chorismate                                                    Charge:  -2  Formula: C10H8O6
hemeO_c        :                 -0.000223  Name: Heme O C49H56FeN4O5                                           Charge:  -2  Formula: C49FeH56N4O5
murein4p4p_p   :                 -0.005381  Name: Two linked disacharide tetrapeptide murein units (uncrosslinked, middle of chain)  Charge:  -4  Formula: C74H114N14O40
2dmmql8_c      :                 -0.000223  Name: 2-Demethylmenaquinol 8                                        Charge:   0  Formula: C50H72O2
malcoa_c       :                  -3.1e-05  Name: Malonyl CoA C24H33N7O19P3S                                    Charge:  -5  Formula: C24H33N7O19P3S
murein4px4p_p  :                 -0.005448  Name: Two disacharide linked murein units, tetrapeptide corsslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C74H112N14O39
ptrc_c         :                  -0.03327  Name: Putrescine                                                    Charge:   2  Formula: C4H14N2
nadph_c        :                 -0.000335  Name: Nicotinamide adenine dinucleotide phosphate - reduced         Charge:  -4  Formula: C21H26N7O17P3
mobd_c         :                    -7e-06  Name: Molybdate                                                     Charge:  -2  Formula: MoO4
nadh_c         :                  -4.5e-05  Name: Nicotinamide adenine dinucleotide - reduced                   Charge:  -2  Formula: C21H27N7O14P2
murein4px4px4p_p:                 -0.000673  Name: Three disacharide linked murein units (tetrapeptide crosslinked tetrapeptide (A2pm->D-ala) & tetrapeptide corsslinked tetrapeptide (A2pm->D-ala)) (middle of chain)  Charge:  -6  Formula: C111H167N21O58
succoa_c       :                  -9.8e-05  Name: Succinyl-CoA                                                  Charge:  -5  Formula: C25H35N7O19P3S
glc__D_c       :        -0.117366841601577  Name: D-Glucose                                                     Charge:   0  Formula: C6H12O6
rbflvrd_c      :     -5.42885385395863e-05  Name: Reduced riboflavin                                            Charge:   0  Formula: C17H22N4O6
nac_c          :     -0.000502314222072026  Name: Nicotinate                                                    Charge:  -1  Formula: C6H4NO2
pnto__R_c      :     -8.60937958309439e-05  Name: (R)-Pantothenate                                              Charge:  -1  Formula: C9H16NO5
clpn161_p      :                  -0.00229  Name: Cardiolipin (tetrahexadec-9-enoyl, n-C16:1)                   Charge:  -2  Formula: C73H132O17P2
pg160_p        :                 -0.010599  Name: Phosphatidylglycerol (dihexadecanoyl, n-C16:0)                Charge:  -1  Formula: C38H74O10P
clpn160_p      :                 -0.002944  Name: Cardiolipin (tetrahexadecanoyl, n-C16:0)                      Charge:  -2  Formula: C73H140O17P2
clpn181_p      :                  -0.00118  Name: Cardiolipin (tetraoctadec-11-enoyl, n-C18:1)                  Charge:  -2  Formula: C81H148O17P2
pe181_p        :                 -0.017704  Name: Phosphatidylethanolamine (dioctadec-11-enoyl, n-C18:1)        Charge:   0  Formula: C41H78NO8P
pg161_p        :                 -0.008244  Name: Phosphatidylglycerol (dihexadec-9-enoyl, n-C16:1)             Charge:  -1  Formula: C38H70O10P
ttdca_c        :     -0.000594246551765006  Name: Tetradecanoate (n-C14:0)                                      Charge:  -1  Formula: C14H27O2
hexadecacid_c  :                 -0.049935  Name: Hexadecanoic acid                                             Charge:   0  Formula: C16H32O2
hexedecacid_c  :                 -0.007033  Name: Hexadecenoic acid                                             Charge:   0  Formula: C16H30O2
octedecacid_c  :                 -0.131979  Name: Octadecenoic acid                                             Charge:   0  Formula: C18H34O2
octadecacid_c  :                 -0.007174  Name: Octadecanoic acid                                             Charge:   0  Formula: C18H36O2
fru_c          :                 -0.644556  Name: D-Fructose                                                    Charge:   0  Formula: C6H12O6
gal_c          :                 -0.005772  Name: D-Galactose                                                   Charge:   0  Formula: C6H12O6
xyl__D_c       :                 -0.005772  Name: D-Xylose                                                      Charge:   0  Formula: C5H10O5
man_c          :                  -0.00481  Name: D-Mannose                                                     Charge:   0  Formula: C6H12O6
adp_c          :               29.18042275  Name: ADP C10H12N5O10P2                                             Charge:  -3  Formula: C10H12N5O10P2
h_c            :               29.18042275  Name: H+                                                            Charge:   1  Formula: H
pi_c           :               29.18042275  Name: Phosphate                                                     Charge:  -2  Formula: HO4P
ppi_c          :                  0.773903  Name: Diphosphate                                                   Charge:  -3  Formula: HO7P2

C:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\Temp\ipykernel_16580\849467163.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_reaction2 = pd.concat([df_reaction2, reaction_data], ignore_index=True)