In [ ]:
%pip install cobra

In [2]:
import cobra
import numpy as np
import pandas as pd
from cobra.io import load_model
from cobra.io import load_json_model, save_json_model, load_matlab_model, save_matlab_model, read_sbml_model, write_sbml_model
from cobra import Model, Reaction, Metabolite, Gene
from sklearn.metrics import r2_score  # Ensure this function is correctly imported

In [39]:
model = read_sbml_model('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.09 Models\\Manual_curation\\Energy_consumption\\250303_hydrogenases_completed.sbml')

## NGAM calculation

In [9]:
reaction = model.reactions.get_by_id('EX_co2_e')
reaction.bounds = -100.0, 0.0

reaction = model.reactions.get_by_id('EX_o2_e')
reaction.bounds = -100.0, 0.0

# set reactions bounds for a specific reaction 
reaction = model.reactions.get_by_id('EX_h2_e')
reaction.bounds = -8.7009, -8.7009

In [43]:
reaction = model.reactions.get_by_id('EX_h2_e')
reaction.bounds = -8.7, 1000.0

In [44]:
model.objective = 'ATPM'
solution = model.optimize()
print(f"Flux through ATPM: {solution.objective_value} mmol/gDW/hr")

Flux through ATPM: 17.400000000000002 mmol/gDW/hr

GAM determination

In [4]:
reaction = model.reactions.get_by_id('ATPM')
reaction.bounds = 21.2, 1000.0

In [23]:
model.objective = 'Growth'
solution = model.optimize()
model.summary()

In [72]:
reaction = model.reactions.get_by_id('EX_co2_e')
reaction.bounds = -100.0, 0.0

reaction = model.reactions.get_by_id('EX_o2_e')
reaction.bounds = -100.0, 0.0

In [66]:
list_h2_fluxes=[18,19]
dict_slope={}

for gam in range(1,30):


    GAM_metabolites_1 = {'atp_c': -gam, 'h2o_c': -gam}
    GAM_metabolites_2 = {'adp_c': gam, 'pi_c': gam, 'h_c': gam}

    # Get the biomass reaction
    reaction = model.reactions.get_by_id('Growth')

    # Update the coefficients for GAM_metabolites_1
    for element, new_coefficient in GAM_metabolites_1.items():
        metabolite = model.metabolites.get_by_id(element)
        if metabolite in reaction.metabolites:
            reaction.add_metabolites({metabolite: new_coefficient - reaction.metabolites[metabolite]})
    
    

    # Update the coefficients for GAM_metabolites_2
    for element, new_coefficient in GAM_metabolites_2.items():
        metabolite = model.metabolites.get_by_id(element)
        if metabolite in reaction.metabolites:
            reaction.add_metabolites({metabolite: new_coefficient - reaction.metabolites[metabolite]})
    list_growth=[]

    # set reactions bounds for a specific reaction 
    for fluxe in list_h2_fluxes:
        reaction = model.reactions.get_by_id('EX_h2_e')
        reaction.bounds = -fluxe, 0.0
        model.objective = 'Growth'
        solution = model.slim_optimize()
        list_growth.append(solution)
        print(solution)
    
    dict_slope[gam]=(list_h2_fluxes[0]-list_h2_fluxes[1])/(list_growth[0]-list_growth[1])

print(dict_slope)

0.06914166192587129
0.07376137207682044
0.06892937277712688
0.07353489879787112
0.0687183832423727
0.07330981196681127
0.06850868142386493
0.07308609889093862
0.06830025556863437
0.07286374703202346
0.06809309406630788
0.07264274400392284
0.06788718544695646
0.07242307757036007
0.06768251837895006
0.07220473564258076
0.06747908166691849
0.07198770627718139
0.06727686424967555
0.07177197767392424
0.06707585519824819
0.0715575381736346
0.06687604371386337
0.07134437625599425
0.06667741912606337
0.0711324805376037
0.06647997089076073
0.07092183976987437
0.06628368858840475
0.07071244283707395
0.06608856192213651
0.07050427875435207
0.0658945807159913
0.07029733666583451
0.06570173491312248
0.07009160584273019
0.0655100145740695
0.06988707568146807
0.06531940987505554
0.06968373570189706
0.06512991110629392
0.06948157554546742
0.06494150867035617
0.06928058497349539
0.06475419308054252
0.06908075386543078
0.06456795495928316
0.06888207221714145
0.0643827850365908
0.06868453013925843
0.06419867414851523
0.06848811785554332
0.0640156132356171
0.06829282570124874
0.06383359334150923
0.06809864412156658
0.0636526056113653
0.06790556367002956
{1: 216.46379693205262, 2: 217.13046359868426, 3: 217.79713026521546, 4: 218.46379693204906, 5: 219.13046359844537, 6: 219.7971302654166, 7: 220.4637969321078, 8: 221.13046359854516, 9: 221.79713026534046, 10: 222.46379693236327, 11: 223.13046359861718, 12: 223.79713026531223, 13: 224.46379693209497, 14: 225.1304635988142, 15: 225.79713026535399, 16: 226.4637969319821, 17: 227.13046359874008, 18: 227.79713026536785, 19: 228.46379693207757, 20: 229.1304635987048, 21: 229.79713026538542, 22: 230.46379693220044, 23: 231.13046359888986, 24: 231.79713026540313, 25: 232.4637969320571, 26: 233.13046359870336, 27: 233.7971302653825, 28: 234.46379693199216, 29: 235.130463598805}

In [67]:
reaction_id_to_check = 'Growth'
reaction = model.reactions.get_by_id(reaction_id_to_check)
print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")
sum = 0
#reaction.name = '(S)-2-Acetolactate pyruvate-lyase (carboxylating)'
print("\nMetabolites and Stoichiometry:")
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id:<15}: {coefficient:>25}  Name: {metabolite.name:<60}  Charge: {metabolite.charge:>3}  Formula: {metabolite.formula}")
    sum += coefficient * metabolite.charge
print(f'\nSum charge: {sum}')
print("\nAssociated Genes:")
for gene in reaction.genes:
    print(gene.id)

Reaction ID: Growth
Name: Biomass reaction
Equation: 0.000223 10fthf_c + 0.000223 2dmmql8_c + 0.000223 5mthf_c + 0.000279 accoa_c + 0.513689 ala__L_c + 0.000223 amet_c + 0.030016 arab__L_c + 0.295792 arg__L_c + 0.241055 asn__L_c + 0.241055 asp__L_c + 29.0 atp_c + 0.005205 ca2_c + 0.000223 chor_c + 0.005205 cl_c + 0.002944 clpn160_p + 0.00229 clpn161_p + 0.00118 clpn181_p + 0.000576 coa_c + 0.0001 cobalt2_c + 0.133508 ctp_c + 0.000709 cu2_c + 0.09158 cys__L_c + 0.026166 datp_c + 0.027017 dctp_c + 0.027017 dgtp_c + 0.026166 dttp_c + 0.000223 fad_c + 0.006715 fe2_c + 0.007808 fe3_c + 0.644556 fru_c + 0.005772 gal_c + 0.117366841601577 glc__D_c + 0.26316 gln__L_c + 0.26316 glu__L_c + 0.612638 gly_c + 0.215096 gtp_c + 29.0 h2o_c + 0.000223 hemeO_c + 0.049935 hexadecacid_c + 0.007033 hexedecacid_c + 0.094738 his__L_c + 0.290529 ile__L_c + 0.195193 k_c + 0.019456 kdo2lipid4_p + 0.450531 leu__L_c + 0.005903 lnlc_c + 0.000364 lnlncg_c + 0.343161 lys__L_c + 3.1e-05 malcoa_c + 0.00481 man_c + 0.153686 met__L_c + 0.008675 mg2_c + 0.000223 mlthf_c + 0.000691 mn2_c + 7e-06 mobd_c + 0.0001 mql8_c + 0.000605 murein3px4p_p + 0.001345 murein4p3p_p + 0.005381 murein4p4p_p + 0.005448 murein4px4p_p + 0.000673 murein4px4px4p_p + 0.013894 murein5px4p_p + 0.000502314222072026 nac_c + 0.001831 nad_c + 4.5e-05 nadh_c + 0.000447 nadp_c + 0.000335 nadph_c + 0.012379 nh4_c + 0.007174 octadecacid_c + 0.131979 octedecacid_c + 0.017868 pe160_c + 0.045946 pe160_p + 0.054154 pe161_c + 0.02106 pe161_p + 0.017704 pe181_p + 0.010599 pg160_p + 0.008244 pg161_p + 0.185265 phe__L_c + 0.000223 pheme_c + 8.60937958309439e-05 pnto__R_c + 0.221055 pro__L_c + 0.03327 ptrc_c + 0.000223 pydx5p_c + 5.42885385395863e-05 rbflvrd_c + 0.000223 ribflv_c + 0.215792 ser__L_c + 0.000223 sheme_c + 0.004338 so4_c + 9.8e-05 succoa_c + 0.000223 thf_c + 1.3e-05 thm_c + 0.000223 thmpp_c + 0.253687 thr__L_c + 0.056843 trp__L_c + 0.000594246551765006 ttdca_c + 0.137896 tyr__L_c + 0.144104 utp_c + 0.423162 val__L_c + 0.005772 xyl__D_c + 0.000341 zn2_c --> 29.0 adp_c + 29.0 h_c + 29.0 pi_c + 0.773903 ppi_c
Lower Bound: 0.0
Upper Bound: 1000.0

Metabolites and Stoichiometry:
10fthf_c       :                 -0.000223  Name: 10-Formyltetrahydrofolate                                     Charge:  -2  Formula: C20H21N7O7
ala__L_c       :                 -0.513689  Name: L-Alanine                                                     Charge:   0  Formula: C3H7NO2
amet_c         :                 -0.000223  Name: S-Adenosyl-L-methionine                                       Charge:   1  Formula: C15H23N6O5S
arg__L_c       :                 -0.295792  Name: L-Arginine                                                    Charge:   1  Formula: C6H15N4O2
asn__L_c       :                 -0.241055  Name: L-Asparagine                                                  Charge:   0  Formula: C4H8N2O3
asp__L_c       :                 -0.241055  Name: L-Aspartate                                                   Charge:  -1  Formula: C4H6NO4
atp_c          :                     -29.0  Name: ATP C10H12N5O13P3                                             Charge:  -4  Formula: C10H12N5O13P3
ca2_c          :                 -0.005205  Name: Calcium                                                       Charge:   2  Formula: Ca
cl_c           :                 -0.005205  Name: Chloride                                                      Charge:  -1  Formula: Cl
coa_c          :                 -0.000576  Name: Coenzyme A                                                    Charge:  -4  Formula: C21H32N7O16P3S
cobalt2_c      :                   -0.0001  Name: Co2+                                                          Charge:   2  Formula: Co
ctp_c          :                 -0.133508  Name: CTP C9H12N3O14P3                                              Charge:  -4  Formula: C9H12N3O14P3
cu2_c          :                 -0.000709  Name: Copper                                                        Charge:   2  Formula: Cu
cys__L_c       :                  -0.09158  Name: L-Cysteine                                                    Charge:   0  Formula: C3H7NO2S
datp_c         :                 -0.026166  Name: DATP C10H12N5O12P3                                            Charge:  -4  Formula: C10H12N5O12P3
dctp_c         :                 -0.027017  Name: DCTP C9H12N3O13P3                                             Charge:  -4  Formula: C9H12N3O13P3
dgtp_c         :                 -0.027017  Name: DGTP C10H12N5O13P3                                            Charge:  -4  Formula: C10H12N5O13P3
dttp_c         :                 -0.026166  Name: DTTP C10H13N2O14P3                                            Charge:  -4  Formula: C10H13N2O14P3
fad_c          :                 -0.000223  Name: Flavin adenine dinucleotide oxidized                          Charge:  -2  Formula: C27H31N9O15P2
fe2_c          :                 -0.006715  Name: Fe2+ mitochondria                                             Charge:   2  Formula: Fe
fe3_c          :                 -0.007808  Name: Iron (Fe3+)                                                   Charge:   3  Formula: Fe
gln__L_c       :                  -0.26316  Name: L-Glutamine                                                   Charge:   0  Formula: C5H10N2O3
glu__L_c       :                  -0.26316  Name: L-Glutamate                                                   Charge:  -1  Formula: C5H8NO4
gly_c          :                 -0.612638  Name: Glycine                                                       Charge:   0  Formula: C2H5NO2
gtp_c          :                 -0.215096  Name: GTP C10H12N5O14P3                                             Charge:  -4  Formula: C10H12N5O14P3
h2o_c          :                     -29.0  Name: H2O H2O                                                       Charge:   0  Formula: H2O
his__L_c       :                 -0.094738  Name: L-Histidine                                                   Charge:   0  Formula: C6H9N3O2
ile__L_c       :                 -0.290529  Name: L-Isoleucine                                                  Charge:   0  Formula: C6H13NO2
k_c            :                 -0.195193  Name: Potassium                                                     Charge:   1  Formula: K
kdo2lipid4_p   :                 -0.019456  Name: KDO(2)-lipid IV(A)                                            Charge:  -6  Formula: C84H148N2O37P2
leu__L_c       :                 -0.450531  Name: L-Leucine                                                     Charge:   0  Formula: C6H13NO2
lys__L_c       :                 -0.343161  Name: L-Lysine                                                      Charge:   1  Formula: C6H15N2O2
met__L_c       :                 -0.153686  Name: L-Methionine                                                  Charge:   0  Formula: C5H11NO2S
mg2_c          :                 -0.008675  Name: Magnesium                                                     Charge:   2  Formula: Mg
mlthf_c        :                 -0.000223  Name: 5,10-Methylenetetrahydrofolate                                Charge:  -2  Formula: C20H21N7O6
mn2_c          :                 -0.000691  Name: Manganese                                                     Charge:   2  Formula: Mn
mql8_c         :                   -0.0001  Name: Menaquinol 8                                                  Charge:   0  Formula: C51H74O2
murein5px4p_p  :                 -0.013894  Name: Two disacharide linked murein units, pentapeptide crosslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C77H117N15O40
nad_c          :                 -0.001831  Name: Nicotinamide adenine dinucleotide                             Charge:  -1  Formula: C21H26N7O14P2
nadp_c         :                 -0.000447  Name: Nicotinamide adenine dinucleotide phosphate                   Charge:  -3  Formula: C21H25N7O17P3
pe160_c        :                 -0.017868  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pe160_p        :                 -0.045946  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pe161_c        :                 -0.054154  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70NO8P
pe161_p        :                  -0.02106  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70NO8P
phe__L_c       :                 -0.185265  Name: L-Phenylalanine                                               Charge:   0  Formula: C9H11NO2
pheme_c        :                 -0.000223  Name: Protoheme C34H30FeN4O4                                        Charge:  -2  Formula: C34H30FeN4O4
pro__L_c       :                 -0.221055  Name: L-Proline                                                     Charge:   0  Formula: C5H9NO2
pydx5p_c       :                 -0.000223  Name: Pyridoxal 5'-phosphate                                        Charge:  -2  Formula: C8H8NO6P
ribflv_c       :                 -0.000223  Name: Riboflavin C17H20N4O6                                         Charge:   0  Formula: C17H20N4O6
ser__L_c       :                 -0.215792  Name: L-Serine                                                      Charge:   0  Formula: C3H7NO3
sheme_c        :                 -0.000223  Name: Siroheme C42H36FeN4O16                                        Charge:  -8  Formula: C42H36FeN4O16
so4_c          :                 -0.004338  Name: Sulfate                                                       Charge:  -2  Formula: O4S
thf_c          :                 -0.000223  Name: 5,6,7,8-Tetrahydrofolate                                      Charge:  -2  Formula: C19H21N7O6
thmpp_c        :                 -0.000223  Name: Thiamine diphosphate                                          Charge:  -2  Formula: C12H16N4O7P2S
thr__L_c       :                 -0.253687  Name: L-Threonine                                                   Charge:   0  Formula: C4H9NO3
trp__L_c       :                 -0.056843  Name: L-Tryptophan                                                  Charge:   0  Formula: C11H12N2O2
tyr__L_c       :                 -0.137896  Name: L-Tyrosine                                                    Charge:   0  Formula: C9H11NO3
utp_c          :                 -0.144104  Name: UTP C9H11N2O15P3                                              Charge:  -4  Formula: C9H11N2O15P3
val__L_c       :                 -0.423162  Name: L-Valine                                                      Charge:   0  Formula: C5H11NO2
zn2_c          :                 -0.000341  Name: Zinc                                                          Charge:   2  Formula: Zn
murein3px4p_p  :                 -0.000605  Name: Two disacharide linked murein units, tripeptide crosslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C71H107N13O38
accoa_c        :                 -0.000279  Name: Acetyl-CoA                                                    Charge:  -4  Formula: C23H34N7O17P3S
murein4p3p_p   :                 -0.001345  Name: Two linked disacharide tetrapeptide and tripeptide murein units (uncrosslinked, middle of chain)  Charge:  -4  Formula: C71H109N13O39
5mthf_c        :                 -0.000223  Name: 5-Methyltetrahydrofolate                                      Charge:  -1  Formula: C20H24N7O6
nh4_c          :                 -0.012379  Name: Ammonium                                                      Charge:   1  Formula: H4N
chor_c         :                 -0.000223  Name: Chorismate                                                    Charge:  -2  Formula: C10H8O6
hemeO_c        :                 -0.000223  Name: Heme O C49H56FeN4O5                                           Charge:  -2  Formula: C49FeH56N4O5
murein4p4p_p   :                 -0.005381  Name: Two linked disacharide tetrapeptide murein units (uncrosslinked, middle of chain)  Charge:  -4  Formula: C74H114N14O40
2dmmql8_c      :                 -0.000223  Name: 2-Demethylmenaquinol 8                                        Charge:   0  Formula: C50H72O2
malcoa_c       :                  -3.1e-05  Name: Malonyl CoA C24H33N7O19P3S                                    Charge:  -5  Formula: C24H33N7O19P3S
murein4px4p_p  :                 -0.005448  Name: Two disacharide linked murein units, tetrapeptide corsslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C74H112N14O39
ptrc_c         :                  -0.03327  Name: Putrescine                                                    Charge:   2  Formula: C4H14N2
nadph_c        :                 -0.000335  Name: Nicotinamide adenine dinucleotide phosphate - reduced         Charge:  -4  Formula: C21H26N7O17P3
mobd_c         :                    -7e-06  Name: Molybdate                                                     Charge:  -2  Formula: MoO4
nadh_c         :                  -4.5e-05  Name: Nicotinamide adenine dinucleotide - reduced                   Charge:  -2  Formula: C21H27N7O14P2
murein4px4px4p_p:                 -0.000673  Name: Three disacharide linked murein units (tetrapeptide crosslinked tetrapeptide (A2pm->D-ala) & tetrapeptide corsslinked tetrapeptide (A2pm->D-ala)) (middle of chain)  Charge:  -6  Formula: C111H167N21O58
succoa_c       :                  -9.8e-05  Name: Succinyl-CoA                                                  Charge:  -5  Formula: C25H35N7O19P3S
glc__D_c       :        -0.117366841601577  Name: D-Glucose                                                     Charge:   0  Formula: C6H12O6
rbflvrd_c      :     -5.42885385395863e-05  Name: Reduced riboflavin                                            Charge:   0  Formula: C17H22N4O6
nac_c          :     -0.000502314222072026  Name: Nicotinate                                                    Charge:  -1  Formula: C6H4NO2
pnto__R_c      :     -8.60937958309439e-05  Name: (R)-Pantothenate                                              Charge:  -1  Formula: C9H16NO5
clpn161_p      :                  -0.00229  Name: Cardiolipin (tetrahexadec-9-enoyl, n-C16:1)                   Charge:  -2  Formula: C73H132O17P2
pg160_p        :                 -0.010599  Name: Phosphatidylglycerol (dihexadecanoyl, n-C16:0)                Charge:  -1  Formula: C38H74O10P
clpn160_p      :                 -0.002944  Name: Cardiolipin (tetrahexadecanoyl, n-C16:0)                      Charge:  -2  Formula: C73H140O17P2
clpn181_p      :                  -0.00118  Name: Cardiolipin (tetraoctadec-11-enoyl, n-C18:1)                  Charge:  -2  Formula: C81H148O17P2
pe181_p        :                 -0.017704  Name: Phosphatidylethanolamine (dioctadec-11-enoyl, n-C18:1)        Charge:   0  Formula: C41H78NO8P
pg161_p        :                 -0.008244  Name: Phosphatidylglycerol (dihexadec-9-enoyl, n-C16:1)             Charge:  -1  Formula: C38H70O10P
ttdca_c        :     -0.000594246551765006  Name: Tetradecanoate (n-C14:0)                                      Charge:  -1  Formula: C14H27O2
hexadecacid_c  :                 -0.049935  Name: Hexadecanoic acid                                             Charge:   0  Formula: C16H32O2
hexedecacid_c  :                 -0.007033  Name: Hexadecenoic acid                                             Charge:   0  Formula: C16H30O2
octedecacid_c  :                 -0.131979  Name: Octadecenoic acid                                             Charge:   0  Formula: C18H34O2
octadecacid_c  :                 -0.007174  Name: Octadecanoic acid                                             Charge:   0  Formula: C18H36O2
fru_c          :                 -0.644556  Name: D-Fructose                                                    Charge:   0  Formula: C6H12O6
gal_c          :                 -0.005772  Name: D-Galactose                                                   Charge:   0  Formula: C6H12O6
xyl__D_c       :                 -0.005772  Name: D-Xylose                                                      Charge:   0  Formula: C5H10O5
man_c          :                  -0.00481  Name: D-Mannose                                                     Charge:   0  Formula: C6H12O6
arab__L_c      :                 -0.030016  Name: L-Arabinose                                                   Charge:   0  Formula: C5H10O5
thm_c          :                  -1.3e-05  Name: Thiamin                                                       Charge:   1  Formula: C12H17N4OS
lnlc_c         :                 -0.005903  Name: Linoleic acid (all cis C18:2) n-6                             Charge:  -1  Formula: C18H31O2
lnlncg_c       :                 -0.000364  Name: Gamma-linolenic acid                                          Charge:  -1  Formula: C18H29O2
adp_c          :                      29.0  Name: ADP C10H12N5O10P2                                             Charge:  -3  Formula: C10H12N5O10P2
h_c            :                      29.0  Name: H+                                                            Charge:   1  Formula: H
pi_c           :                      29.0  Name: Phosphate                                                     Charge:  -2  Formula: HO4P
ppi_c          :                  0.773903  Name: Diphosphate                                                   Charge:  -3  Formula: HO7P2

Sum charge: -0.10762534543035152

Associated Genes:

## Oxidative Phosphorylation complex addition

In [1]:
# we set an unlimited bound for the limiting substrate
reaction = model.reactions.get_by_id('EX_co2_e')
reaction.bounds = -100.0, 0.0

NameError: name 'model' is not defined

In [ ]:

reaction = model.reactions.get_by_id('EX_o2_e')
reaction.bounds = -6.92, 0.0

Addition of proton translocation to the NADH dehydrogenase reaction

In [ ]:
reaction = model.reactions.get_by_id('NADH5')
metabolite_to_add = 'h_p'
reaction.add_metabolites({metabolite_to_add: 4.0})

print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")
print(reaction.annotation)
print(f"Genes: {[gene.id for gene in reaction.genes]}")

Reaction ID: NADH5
Name: NADH dehydrogenase (ubiquinone-8 )
Equation: 5.0 h_c + nadh_c + q8_c --> 4.0 h_p + nad_c + q8h2_c
Lower Bound: 0.0
Upper Bound: 1000.0
{'sbo': 'SBO:0000176', 'rhea': ['29107', '29108', '29109', '29110'], 'metanetx.reaction': 'MNXR101872', 'seed.reaction': 'rxn08975'}
Genes: ['AAFOLC_07640']

In [ ]:
summary = model.metabolites.get_by_id('h_p').summary()
summary

In [ ]:
model.slim_optimize()

0.024017630944258673

In [ ]:
model.summary()

# Setting the GAM value

In [5]:
GAM_metabolites_1 = {'atp_c': -40.0, 'h2o_c': -40.0}
GAM_metabolites_2 = {'adp_c': 40.0, 'pi_c': 40.0, 'h_c': 40.0}

# Get the biomass reaction
reaction = model.reactions.get_by_id('Growth')

# Update the coefficients for GAM_metabolites_1
for element, new_coefficient in GAM_metabolites_1.items():
    metabolite = model.metabolites.get_by_id(element)
    if metabolite in reaction.metabolites:
        print(f'Old coefficient for {element}: {reaction.metabolites[metabolite]}')
        reaction.add_metabolites({metabolite: new_coefficient - reaction.metabolites[metabolite]})
        print(f'Updated {element} coefficient to {new_coefficient}')

# Update the coefficients for GAM_metabolites_2
for element, new_coefficient in GAM_metabolites_2.items():
    metabolite = model.metabolites.get_by_id(element)
    if metabolite in reaction.metabolites:
        print(f'Old coefficient for {element}: {reaction.metabolites[metabolite]}')
        reaction.add_metabolites({metabolite: new_coefficient - reaction.metabolites[metabolite]})
        print(f'Updated {element} coefficient to {new_coefficient}')

# Optimize the model
solution = model.slim_optimize()
print(f'Optimal solution: {solution}')

Old coefficient for atp_c: -75.5
Updated atp_c coefficient to -40.0
Old coefficient for h2o_c: -75.5
Updated h2o_c coefficient to -40.0
Old coefficient for adp_c: 75.5
Updated adp_c coefficient to 40.0
Old coefficient for pi_c: 75.5
Updated pi_c coefficient to 40.0
Old coefficient for h_c: 75.5
Updated h_c coefficient to 40.0
Optimal solution: 0.045785650370645546

Set the NGAM value

In [ ]:
reaction = model.reactions.get_by_id('ATPM')
reaction.bounds = 9.27, 1000.0

# Combining different GAM and NGAM values

In [28]:
#file_path ='C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.03 Fluxes values\\plot_data - Copy.xlsx'
file_path ='240823_growth_data.xlsx'
excel_data = pd.read_excel(file_path)
excel_data = excel_data.drop([4,5])
excel_data

,Unnamed: 0,dilRate,H2 Flux theoretic,O2 flux theoretic,CO2 flux theoretic
0,0,0.046160,19.489454,6.926103,2.509541
1,1,0.035260,17.380479,6.315240,2.058461
2,2,0.026357,15.628204,5.897692,1.617025
3,3,0.020724,15.387005,6.040324,1.431369

run this to set the functions

In [38]:

def compute_r2_score(excel_data):
    """
    Computes the R² (coefficient of determination) between experimental and simulated growth rates.
    """
    if 'dilRate' not in excel_data.columns or 'growth_rate' not in excel_data.columns:
        raise ValueError("DataFrame must contain 'dilRate' and 'growth_rate' columns.")

    r2_value = r2_score(excel_data['dilRate'], excel_data['growth_rate'])  

    return r2_value

In [24]:

def compute_mean_difference(excel_data):
    """
    Computes the mean absolute difference between experimental and simulated growth rates.

    Parameters:
    - excel_data: Pandas DataFrame containing 'dilRate' (experimental) and 'growth_rate' (simulated).

    Returns:
    - mean_difference: The average absolute difference between experimental and simulated values.
    """
    
    # Ensure columns exist
    if 'dilRate' not in excel_data.columns or 'growth_rate' not in excel_data.columns:
        raise ValueError("DataFrame must contain 'dilRate' and 'growth_rate' columns.")
    
    # Compute absolute difference for each row
    differences = abs(excel_data['dilRate'] - excel_data['growth_rate'])
    # Compute the mean difference
    mean_difference = differences.mean()

    return mean_difference

In [ ]:
def compute_growth_rates(model, excel_data):
    """
    Computes growth rates by adjusting H2, O2, and CO2 fluxes in the model and optimizing.

    Parameters:
    - model: COBRApy model object
    - excel_data: Pandas DataFrame containing columns 'H2 Flux theoretic' and 'CO2 flux theoretic'

    Returns:
    - Updated DataFrame with calculated growth rates and model-predicted fluxes.
    """
    model.objective = 'Growth'


    # Add columns for growth rate and modeled fluxes
    excel_data['growth_rate'] = None
    excel_data['H2 Flux model'] = None
    excel_data['O2 Flux model'] = None
    excel_data['CO2 Flux model'] = None

    # Get the exchange reactions
    h2_reaction = model.reactions.get_by_id('EX_h2_e')
    o2_reaction = model.reactions.get_by_id('EX_o2_e')
    co2_reaction = model.reactions.get_by_id('EX_co2_e')

    # Iterate over each row in the DataFrame
    for index, row in excel_data.iterrows():
        
        # Set bounds for H2 flux
        h2_reaction.bounds = (-row['H2 Flux theoretic'], 0.0)

        # Set bounds for O2 flux
        o2_reaction.bounds = (-100, 0.0)

        # Set bounds for CO2 flux
        co2_reaction.bounds = (-row['CO2 flux theoretic'], 0.0)

        # Optimize the model
        solution = model.slim_optimize()
        #print(solution)

        # Store results in DataFrame
        excel_data.at[index, 'growth_rate'] = solution
        excel_data.at[index, 'H2 Flux model'] = h2_reaction.flux
        excel_data.at[index, 'O2 Flux model'] = o2_reaction.flux
        excel_data.at[index, 'CO2 Flux model'] = co2_reaction.flux
    print(excel_data)
    return excel_data

In [ ]:
def calculate_difference_for_gam(model, gam_value):
    """
    Updates the Growth-Associated Maintenance (GAM) coefficients in the biomass reaction.
    
    Parameters:
    - model: COBRApy model object
    - gam_value: integer, the new GAM coefficient value

    Returns:
    - solution: The optimized solution after modifying the biomass reaction
    """

    # Define the GAM metabolite changes
    GAM_metabolites_1 = {'atp_c': -gam_value, 'h2o_c': -gam_value}
    GAM_metabolites_2 = {'adp_c': gam_value, 'pi_c': gam_value, 'h_c': gam_value}

    # Get the biomass reaction
    reaction = model.reactions.get_by_id('Growth')

    # Function to update metabolite coefficients in the reaction
    def update_coefficients(metabolites):
        for element, new_coefficient in metabolites.items():
            metabolite = model.metabolites.get_by_id(element)
            if metabolite in reaction.metabolites:
                old_coefficient = reaction.metabolites[metabolite]
                reaction.add_metabolites({metabolite: new_coefficient - old_coefficient})

    # Update coefficients for both metabolite groups
    update_coefficients(GAM_metabolites_1)
    update_coefficients(GAM_metabolites_2)


    compute_growth_rates(model,excel_data)

    mean_diff = compute_mean_difference(excel_data)
    r2_value  = compute_r2_score(excel_data)

    
    return mean_diff,r2_value

In [37]:
# Define the H2 uptake range and step size
h2_range = (8.7, 14.7)  # Start and end values
step_size = 0.1  # Step size for iteration

ngam_values = []  # Store ATPM flux values

# list to store result
results = []

# Iterate over the defined range
for uptake in np.arange(h2_range[0], h2_range[1] + step_size, step_size):
    # Get the reaction
    reaction = model.reactions.get_by_id('EX_h2_e')
    reaction.bounds = (-uptake, 1000.0)  # Set H2 uptake flux
    
    model.objective = 'ATPM'  # Set ATP maintenance as the objective
    solution = model.optimize()  # Optimize model
    
    #ngam_values.append(solution.objective_value)  # Store ATPM values

    reaction = model.reactions.get_by_id('ATPM') 
    reaction.bounds = solution.objective_value, 1000.0 #change ATPM bounds

    print('uptake :',uptake)
    print('flux through atpm ',solution.objective_value)
    for gam_value in np.arange(10,150,10):
        mean_difference, r2_value = calculate_difference_for_gam(model, gam_value)  # Get both values
        print(f"GAM Value: {gam_value}, Mean Difference: {mean_difference}")
        # Store the result in a dictionary
        results.append({
            "H2_uptake": uptake,
            "ATPM_flux": solution.objective_value,
            "GAM_value": gam_value,
            "Mean_Difference": mean_difference,
            "R2_Score": r2_value  # Store the R² score
        })

# Convert results into a Pandas DataFrame
results_df = pd.DataFrame(results)
# Save to an Excel or CSV file for further analysis
#results_df.to_excel("gam_analysis_results.xlsx", index=False)
#results_df.to_csv("gam_analysis_results.csv", index=False)

uptake : 8.7
flux through atpm  17.400000000000002
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.052538    -19.254259     -6.926103      -2.509541
1            2.058461    0.043095    -17.136006      -6.31524      -2.058461
2            1.617025    0.033853    -15.332473     -5.897692      -1.617025
3            1.431369    0.029966     -15.16182     -6.040324      -1.431369
GAM Value: 10, Mean Difference: 0.007737472592803283
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.052538    -19.317124     -6.926103      -2.509541
1            2.058461    0.043095     -17.19757      -6.31524      -2.058461
2            1.617025    0.033853    -15.380835     -5.897692      -1.617025
3            1.431369    0.029966     -15.16182     -6.040324      -1.431369
GAM Value: 20, Mean Difference: 0.007737472592803318
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.052538    -19.392179     -6.926103      -2.509541
1            2.058461    0.043095    -17.234902      -6.31524      -2.058461
2            1.617025    0.033853    -15.412388     -5.897692      -1.617025
3            1.431369    0.029966    -15.282372     -6.040324      -1.431369
GAM Value: 30, Mean Difference: 0.007737472592803887
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.052538    -19.465615     -6.926103      -2.509541
1            2.058461    0.043095    -17.234902      -6.31524      -2.058461
2            1.617025    0.033853    -15.412388     -5.897692      -1.617025
3            1.431369    0.029966    -15.282372     -6.040324      -1.431369
GAM Value: 40, Mean Difference: 0.007737472592804026
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.052538    -19.465615     -6.926103      -2.509541
1            2.058461    0.043095    -17.231257      -6.31524      -2.058461
2            1.617025    0.033853    -15.412276     -5.897692      -1.617025
3            1.431369    0.029966    -15.282272     -6.040324      -1.431369
GAM Value: 50, Mean Difference: 0.007737472592803119
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.052538    -19.465441     -6.926103      -2.509541
1            2.058461    0.041147     -17.02002      -6.31524      -1.965456
2            1.617025    0.032405    -15.252292     -5.897692      -1.547862
3            1.431369    0.029966    -15.277387     -6.040324      -1.431369
GAM Value: 60, Mean Difference: 0.006888709808879164
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.051255    -19.319958     -6.926103      -2.448235
1            2.058461    0.039101    -16.801682      -6.31524      -1.867693
2            1.617025    0.030793    -15.080344     -5.897692       -1.47087
3            1.431369    0.029966    -15.277387     -6.040324      -1.431369
GAM Value: 70, Mean Difference: 0.005653211209497821
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.048826    -19.060877     -6.926103      -2.332229
1            2.058461    0.037248    -16.604036      -6.31524      -1.779195
2            1.617025    0.029334    -14.924691     -5.897692      -1.401175
3            1.431369    0.029966    -15.277387     -6.040324      -1.431369
GAM Value: 80, Mean Difference: 0.004218097259304885
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.046617    -18.825237     -6.926103      -2.226719
1            2.058461    0.035563    -16.424272      -6.31524      -1.698704
2            1.617025    0.028007    -14.783121     -5.897692      -1.337786
3            1.431369    0.029966    -15.277387     -6.040324      -1.431369
GAM Value: 90, Mean Difference: 0.002912832306348881
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.044599    -18.609994     -6.926103      -2.130342
1            2.058461    0.034024     -16.26007      -6.31524      -1.625181
2            1.617025    0.026795    -14.653806     -5.897692      -1.279884
3            1.431369    0.029264    -15.202496     -6.040324      -1.397836
GAM Value: 100, Mean Difference: 0.0029437405327441537
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.042749    -18.412611     -6.926103      -2.041963
1            2.058461    0.032612    -16.109491      -6.31524      -1.557759
2            1.617025    0.025683    -14.535221     -5.897692      -1.226787
3            1.431369     0.02805    -15.072982     -6.040324      -1.339845
GAM Value: 110, Mean Difference: 0.003514790462103785
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.041046    -18.230953     -6.926103      -1.960624
1            2.058461    0.031313    -15.970909      -6.31524      -1.495707
2            1.617025     0.02466    -14.426083     -5.897692      -1.177919
3            1.431369    0.026933    -14.953786     -6.040324      -1.286474
GAM Value: 120, Mean Difference: 0.0042417010498204035
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.039474    -18.063213     -6.926103      -1.885516
1            2.058461    0.030114    -15.842945      -6.31524       -1.43841
2            1.617025    0.023715    -14.325306     -5.897692      -1.132796
3            1.431369    0.025901    -14.843722     -6.040324      -1.237192
GAM Value: 130, Mean Difference: 0.004912918962494992
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.038018    -17.907851     -6.926103      -1.815951
1            2.058461    0.029003    -15.724423      -6.31524      -1.385341
2            1.617025     0.02284    -14.231966     -5.897692      -1.091002
3            1.431369    0.024945     -14.74178     -6.040324      -1.191546
GAM Value: 140, Mean Difference: 0.005534608451060953
uptake : 8.799999999999999
flux through atpm  17.599999999999973
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.052538    -19.254259     -6.926103      -2.509541
1            2.058461    0.043095    -17.129223      -6.31524      -2.058461
2            1.617025    0.033853    -15.332405     -5.897692      -1.617025
3            1.431369    0.029966     -15.16182     -6.040324      -1.431369
GAM Value: 10, Mean Difference: 0.007737472592803853
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.052538    -19.326171     -6.926103      -2.509541
1            2.058461    0.043095    -17.210126      -6.31524      -2.058461
2            1.617025    0.033853    -15.396825     -5.897692      -1.617025
3            1.431369    0.029966     -15.16182     -6.040324      -1.431369
GAM Value: 20, Mean Difference: 0.007737472592803732
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.052538    -19.401225     -6.926103      -2.509541
1            2.058461    0.043095    -17.218252      -6.31524      -2.058461
2            1.617025    0.033853    -15.399308     -5.897692      -1.617025
3            1.431369    0.029966    -15.270794     -6.040324      -1.431369
GAM Value: 30, Mean Difference: 0.00773747259280403
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.052538    -19.445316     -6.926103      -2.509541
1            2.058461    0.043095    -17.227733      -6.31524      -2.058461
2            1.617025    0.033853    -15.406757     -5.897692      -1.617025
3            1.431369    0.029966    -15.277387     -6.040324      -1.431369
GAM Value: 40, Mean Difference: 0.007737472592804821
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.052538    -19.456875     -6.926103      -2.509541
1            2.058461    0.042316    -17.144629      -6.31524      -2.021251
2            1.617025     0.03309    -15.325387     -5.897692      -1.580591
3            1.431369    0.029966    -15.277387     -6.040324      -1.431369
GAM Value: 50, Mean Difference: 0.007352030709608362
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.052538    -19.456875     -6.926103      -2.509541
1            2.058461    0.040101     -16.90834      -6.31524       -1.91545
2            1.617025    0.031358    -15.140613     -5.897692      -1.497856
3            1.431369    0.029966    -15.277387     -6.040324      -1.431369
GAM Value: 60, Mean Difference: 0.006365268858537958
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541     0.05026    -19.213834     -6.926103      -2.400717
1            2.058461    0.038106    -16.695558      -6.31524      -1.820175
2            1.617025    0.029798    -14.974219     -5.897692      -1.423352
3            1.431369    0.029966    -15.277387     -6.040324      -1.431369
GAM Value: 70, Mean Difference: 0.0049071040861562425
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.047878    -18.959781     -6.926103      -2.286962
1            2.058461      0.0363     -16.50294      -6.31524      -1.733929
2            1.617025    0.028386    -14.823595     -5.897692      -1.355909
3            1.431369    0.029966    -15.277387     -6.040324      -1.431369
GAM Value: 80, Mean Difference: 0.0035073433718553143
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.045712    -18.728714     -6.926103        -2.1835
1            2.058461    0.034658     -16.32775      -6.31524      -1.655486
2            1.617025    0.027102    -14.686598     -5.897692      -1.294567
3            1.431369    0.029683    -15.247206     -6.040324      -1.417855
GAM Value: 90, Mean Difference: 0.0026885397407587722
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.043734     -18.51765     -6.926103      -2.088994
1            2.058461    0.033158    -16.167725      -6.31524      -1.583833
2            1.617025    0.025929    -14.561461     -5.897692      -1.238536
3            1.431369    0.028399    -15.110151     -6.040324      -1.356487
GAM Value: 100, Mean Difference: 0.0031577746432273207
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.041919    -18.324098     -6.926103       -2.00233
1            2.058461    0.031782    -16.020978      -6.31524      -1.518126
2            1.617025    0.024853    -14.446707     -5.897692      -1.187154
3            1.431369     0.02722    -14.984468     -6.040324      -1.300212
GAM Value: 110, Mean Difference: 0.003929653310605009
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541     0.04025    -18.145966     -6.926103      -1.922569
1            2.058461    0.030516    -15.885922      -6.31524      -1.457653
2            1.617025    0.023863    -14.341095     -5.897692      -1.139865
3            1.431369    0.026136    -14.868798     -6.040324      -1.248419
GAM Value: 120, Mean Difference: 0.004640038363077464
   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324


c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541      0.0291    -16.956576     -6.926103       -1.39001
1            2.058461    0.011776    -13.886747      -6.31524      -0.562505
2            1.617025         NaN    -11.786935     -5.897692       0.003926
3            1.431369     0.00398    -12.505183     -6.040324      -0.190089
GAM Value: 10, Mean Difference: 0.0190961877105594

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.027174    -16.751048     -6.926103      -1.297983
1            2.058461    0.010997    -13.803574      -6.31524      -0.525263
2            1.617025         NaN    -11.787547     -5.897692       0.003641
3            1.431369    0.003716    -12.477076     -6.040324      -0.177504
GAM Value: 20, Mean Difference: 0.020086104188951636

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025486    -16.571045     -6.926103      -1.217384
1            2.058461    0.010314    -13.730731      -6.31524      -0.492647
2            1.617025         NaN    -11.788146     -5.897692       0.003366
3            1.431369    0.003485     -12.45246     -6.040324      -0.166482
GAM Value: 30, Mean Difference: 0.020953082905186177

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023996    -16.412089     -6.926103       -1.14621
1            2.058461    0.009711    -13.666405      -6.31524      -0.463845
2            1.617025         NaN    -11.804616     -5.897692            0.0
3            1.431369    0.003282    -12.430722     -6.040324      -0.156749
GAM Value: 40, Mean Difference: 0.021718686400381743

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022671    -16.270693     -6.926103      -1.082899
1            2.058461    0.009174    -13.609186      -6.31524      -0.438224
2            1.617025         NaN    -11.788326     -5.897692       0.003389
3            1.431369      0.0031    -12.411385     -6.040324      -0.148091
GAM Value: 50, Mean Difference: 0.022399713158597293

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.021484    -16.144099     -6.926103      -1.026216
1            2.058461    0.008694    -13.557956      -6.31524      -0.415286
2            1.617025         NaN    -11.788702     -5.897692       0.003208
3            1.431369    0.002938    -12.394073     -6.040324      -0.140339
GAM Value: 60, Mean Difference: 0.023009444458108718

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020416    -16.030099     -6.926103      -0.975171
1            2.058461    0.008262    -13.511823      -6.31524      -0.394629
2            1.617025         NaN    -11.804616     -5.897692           -0.0
3            1.431369    0.002792    -12.378483     -6.040324      -0.133359
GAM Value: 70, Mean Difference: 0.023558519108831555

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019448    -15.926903     -6.926103      -0.928964
1            2.058461     0.00787    -13.470062      -6.31524       -0.37593
2            1.617025         NaN    -11.787851     -5.897692       0.003266
3            1.431369     0.00266    -12.364371     -6.040324       -0.12704
GAM Value: 80, Mean Difference: 0.024055559500554585

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018568    -15.833044     -6.926103      -0.886938
1            2.058461    0.007514    -13.432079      -6.31524      -0.358923
2            1.617025         NaN    -11.787851     -5.897692       0.003266
3            1.431369    0.002539    -12.351535     -6.040324      -0.121292
GAM Value: 90, Mean Difference: 0.02450762771676579

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017765    -15.747309     -6.926103       -0.84855
1            2.058461    0.007189    -13.397385      -6.31524      -0.343388
2            1.617025         NaN    -11.797153     -5.897692            0.0
3            1.431369    0.002429    -12.339811     -6.040324      -0.116043
GAM Value: 100, Mean Difference: 0.02492056319967803

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017028    -15.668689     -6.926103      -0.813346
1            2.058461    0.006891    -13.365569      -6.31524      -0.329142
2            1.617025         NaN    -11.796822     -5.897692            0.0
3            1.431369    0.002329    -12.329059     -6.040324      -0.111228
GAM Value: 110, Mean Difference: 0.025299236364452724

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016349    -15.596331     -6.926103      -0.780948
1            2.058461    0.006616    -13.336287      -6.31524      -0.316031
2            1.617025         NaN    -11.790813     -5.897692       0.002126
3            1.431369    0.002236    -12.319164     -6.040324      -0.106798
GAM Value: 120, Mean Difference: 0.025647741599015006

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015723    -15.529518     -6.926103      -0.751031
1            2.058461    0.006363    -13.309249      -6.31524      -0.303925
2            1.617025         NaN    -11.796426     -5.897692            0.0
3            1.431369     0.00215    -12.310027     -6.040324      -0.102707
GAM Value: 130, Mean Difference: 0.02596954590349175

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015143    -15.467634     -6.926103      -0.723322
1            2.058461    0.006128    -13.284206      -6.31524      -0.292712
2            1.617025         NaN      -11.7963     -5.897692            0.0
3            1.431369    0.002071    -12.301564     -6.040324      -0.098917
GAM Value: 140, Mean Difference: 0.02626760462584153
uptake : 11.899999999999988
flux through atpm  23.800000000000004

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.027682    -16.805307     -6.926103      -1.322277
1            2.058461    0.010358    -13.735477      -6.31524      -0.494772
2            1.617025         NaN      -11.6016     -5.897692       0.090034
3            1.431369    0.002562    -12.353913     -6.040324      -0.122357
GAM Value: 10, Mean Difference: 0.020514189789007434

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541     0.02585    -16.609793     -6.926103      -1.234734
1            2.058461    0.009672    -13.662319      -6.31524      -0.462015
2            1.617025         NaN    -11.617856     -5.897692       0.082481
3            1.431369    0.002392    -12.335821     -6.040324      -0.114256
GAM Value: 20, Mean Difference: 0.021410225900449567

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.024244    -16.438561     -6.926103      -1.158064
1            2.058461    0.009072    -13.598247      -6.31524      -0.433326
2            1.617025         NaN    -11.631295     -5.897692        0.07631
3            1.431369    0.002243    -12.319976     -6.040324      -0.107161
GAM Value: 30, Mean Difference: 0.022194983255794342

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022827    -16.287351     -6.926103      -1.090358
1            2.058461    0.008541    -13.541667      -6.31524      -0.407992
2            1.617025         NaN    -11.795384     -5.897692            0.0
3            1.431369    0.002112    -12.305984     -6.040324      -0.100896
GAM Value: 40, Mean Difference: 0.02288797947690536

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.021566    -16.152845     -6.926103      -1.030132
1            2.058461     0.00807    -13.491338      -6.31524      -0.385457
2            1.617025         NaN    -11.795384     -5.897692            0.0
3            1.431369    0.001996    -12.293541     -6.040324      -0.095323
GAM Value: 50, Mean Difference: 0.023504419935812274

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020437    -16.032463     -6.926103       -0.97621
1            2.058461    0.007647    -13.446293      -6.31524       -0.36528
2            1.617025         NaN    -11.619135     -5.897692       0.084626
3            1.431369    0.001891    -12.282394     -6.040324      -0.090334
GAM Value: 60, Mean Difference: 0.024056326358791263

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019421    -15.923975     -6.926103      -0.927653
1            2.058461    0.007267    -13.405699      -6.31524      -0.347111
2            1.617025         NaN    -11.619135     -5.897692       0.084626
3            1.431369    0.001797    -12.272359     -6.040324       -0.08584
GAM Value: 70, Mean Difference: 0.02455332860662375

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018501    -15.825807     -6.926103      -0.883698
1            2.058461    0.006923    -13.368966      -6.31524      -0.330664
2            1.617025         NaN    -11.624674     -5.897692       0.074025
3            1.431369    0.001712    -12.263275     -6.040324      -0.081773
GAM Value: 80, Mean Difference: 0.025003231350489777

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017664    -15.736521     -6.926103      -0.843719
1            2.058461    0.006609    -13.335557      -6.31524      -0.315704
2            1.617025         NaN    -11.795384     -5.897692            0.0
3            1.431369    0.001634    -12.255013     -6.040324      -0.078074
GAM Value: 90, Mean Difference: 0.025412426929513805

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016899    -15.654965     -6.926103      -0.807201
1            2.058461    0.006323     -13.30504      -6.31524       -0.30204
2            1.617025         NaN    -11.835433     -5.897692            0.0
3            1.431369    0.001564    -12.247466     -6.040324      -0.074694
GAM Value: 100, Mean Difference: 0.025786200992742103

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016198    -15.580175     -6.926103      -0.773714
1            2.058461    0.006061    -13.277055      -6.31524       -0.28951
2            1.617025         NaN    -11.832096     -5.897692            0.0
3            1.431369    0.001499    -12.240545     -6.040324      -0.071596
GAM Value: 110, Mean Difference: 0.026128962061455735

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015553    -15.511343     -6.926103      -0.742894
1            2.058461     0.00582    -13.251299      -6.31524      -0.277977
2            1.617025         NaN    -11.690795     -5.897692       0.048645
3            1.431369    0.001439    -12.234176     -6.040324      -0.068744
GAM Value: 120, Mean Difference: 0.026444416225527356

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014957    -15.447786     -6.926103      -0.714435
1            2.058461    0.005597    -13.227517      -6.31524      -0.267329
2            1.617025         NaN    -11.819055     -5.897692            0.0
3            1.431369    0.001384    -12.228295     -6.040324       -0.06611
GAM Value: 130, Mean Difference: 0.026735701661657243

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014405    -15.388918     -6.926103      -0.688076
1            2.058461     0.00539     -13.20549      -6.31524      -0.257466
2            1.617025         NaN     -11.81614     -5.897692            0.0
3            1.431369    0.001333    -12.222847     -6.040324      -0.063671
GAM Value: 140, Mean Difference: 0.027005493516703828
uptake : 11.999999999999988
flux through atpm  23.999999999999677

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.026264    -16.654037     -6.926103      -1.254545
1            2.058461     0.00894    -13.584207      -6.31524       -0.42704
2            1.617025         NaN    -11.416707     -5.897692       0.175937
3            1.431369    0.001144    -12.202643     -6.040324      -0.054625
GAM Value: 10, Mean Difference: 0.021932191867452728

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.024525    -16.468538     -6.926103      -1.171486
1            2.058461    0.008348    -13.521065      -6.31524      -0.398767
2            1.617025         NaN    -11.448164     -5.897692       0.161321
3            1.431369    0.001068    -12.194566     -6.040324      -0.051008
GAM Value: 20, Mean Difference: 0.02273434761194268

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023003    -16.306077     -6.926103      -1.098743
1            2.058461     0.00783    -13.465764      -6.31524      -0.374006
2            1.617025         NaN    -11.474415     -5.897692       0.149268
3            1.431369    0.001002    -12.187492     -6.040324      -0.047841
GAM Value: 30, Mean Difference: 0.02343688357737922

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.021658    -16.162613     -6.926103      -1.034505
1            2.058461    0.007372    -13.416929      -6.31524       -0.35214
2            1.617025         NaN    -11.795384     -5.897692            0.0
3            1.431369    0.000943    -12.181246     -6.040324      -0.045044
GAM Value: 40, Mean Difference: 0.024057272553425362

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020461    -16.034996     -6.926103      -0.977364
1            2.058461    0.006965    -13.373489      -6.31524      -0.332689
2            1.617025         NaN    -11.472273     -5.897692       0.155142
3            1.431369    0.000891    -12.175689     -6.040324      -0.042556
GAM Value: 50, Mean Difference: 0.024609126713023937

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541     0.01939     -15.92074     -6.926103      -0.926205
1            2.058461      0.0066    -13.334597      -6.31524      -0.315275
2            1.617025         NaN    -11.499236     -5.897692       0.142196
3            1.431369    0.000844    -12.170714     -6.040324      -0.040328
GAM Value: 60, Mean Difference: 0.025103208193182163

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018426     -15.81785     -6.926103      -0.880135
1            2.058461    0.006272    -13.299574      -6.31524      -0.299593
2            1.617025         NaN    -11.526379     -5.897692       0.125116
3            1.431369    0.000802    -12.166234     -6.040324      -0.038322
GAM Value: 70, Mean Difference: 0.02554813810440804

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017553    -15.724711     -6.926103      -0.838431
1            2.058461    0.005975     -13.26787      -6.31524      -0.285397
2            1.617025         NaN     -11.94187     -5.897692            0.0
3            1.431369    0.000764    -12.162179     -6.040324      -0.036506
GAM Value: 80, Mean Difference: 0.025950903183525026

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016759    -15.639999     -6.926103        -0.8005
1            2.058461    0.005705    -13.239035      -6.31524      -0.272486
2            1.617025         NaN    -11.892584     -5.897692            0.0
3            1.431369     0.00073     -12.15849     -6.040324      -0.034855
GAM Value: 90, Mean Difference: 0.026317226126852486

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016033     -15.56262     -6.926103      -0.765853
1            2.058461    0.005458    -13.212695      -6.31524      -0.260692
2            1.617025         NaN    -11.898521     -5.897692            0.0
3            1.431369    0.000698    -12.155121     -6.040324      -0.033346
GAM Value: 100, Mean Difference: 0.026651838771702917

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015368    -15.491661     -6.926103      -0.734081
1            2.058461    0.005231    -13.188541      -6.31524      -0.249877
2            1.617025         NaN    -11.879726     -5.897692            0.0
3            1.431369    0.000669    -12.152032     -6.040324      -0.031963
GAM Value: 110, Mean Difference: 0.02695868774549792

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014756    -15.426356     -6.926103       -0.70484
1            2.058461    0.005023    -13.166312      -6.31524      -0.239923
2            1.617025         NaN    -11.629111     -5.897692       0.095144
3            1.431369    0.000642    -12.149188     -6.040324       -0.03069
GAM Value: 120, Mean Difference: 0.027241090852045107

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014191    -15.366053     -6.926103      -0.677839
1            2.058461     0.00483    -13.145785      -6.31524      -0.230732
2            1.617025         NaN     -11.85769     -5.897692            0.0
3            1.431369    0.000618    -12.146562     -6.040324      -0.029514
GAM Value: 130, Mean Difference: 0.027501857458254318

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013667    -15.310201     -6.926103       -0.65283
1            2.058461    0.004652    -13.126773      -6.31524       -0.22222
2            1.617025         NaN    -11.835981     -5.897692            0.0
3            1.431369    0.000595     -12.14413     -6.040324      -0.028425
GAM Value: 140, Mean Difference: 0.027743382374628745
uptake : 12.099999999999987
flux through atpm  24.16129496885871

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.267456     -5.897692       0.245281
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 10, Mean Difference: 0.023075774872878457

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35462     -6.926103      -1.120478
1            2.058461     0.00728    -13.407146      -6.31524      -0.347759
2            1.617025         NaN    -11.324991     -5.897692       0.224905
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 20, Mean Difference: 0.023802218463049644

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199232     -6.926103      -1.050902
1            2.058461    0.006828    -13.358919      -6.31524      -0.326165
2            1.617025         NaN    -11.350739     -5.897692       0.207963
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.024438444998286474

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062014     -6.926103      -0.989462
1            2.058461    0.006429    -13.316331      -6.31524      -0.307096
2            1.617025         NaN    -11.380299     -5.897692       0.193037
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.025000278005250672

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.408171     -5.897692       0.180096
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.025500044939169325

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.431501     -5.897692       0.169244
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177321462

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.486077     -5.897692       0.174429
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.026350426939242198

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -12.034293     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.026715176708045196

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029     -15.56219     -6.926103      -0.765646
1            2.058461    0.004975    -13.161202      -6.31524      -0.237631
2            1.617025         NaN    -11.955589     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.027046923946477088

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904589     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.02734995389017841

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN    -11.884557     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.027627840660753012

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN     -11.50988     -5.897692        0.13279
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 120, Mean Difference: 0.02788358889741153

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859876     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835023904

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.852098     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.0283384712359266
uptake : 12.199999999999987
flux through atpm  24.16129496885875

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.267456     -5.897692       0.245281
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 10, Mean Difference: 0.023075774872878374

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35467     -6.926103      -1.120478
1            2.058461     0.00728    -13.407161      -6.31524      -0.347759
2            1.617025         NaN     -11.31131     -5.897692       0.224905
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 20, Mean Difference: 0.023802218463050268

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199232     -6.926103      -1.050902
1            2.058461    0.006828    -13.358919      -6.31524      -0.326165
2            1.617025         NaN    -11.351552     -5.897692       0.207939
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.024438444998288678

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062014     -6.926103      -0.989462
1            2.058461    0.006429    -13.316331      -6.31524      -0.307096
2            1.617025         NaN    -11.380299     -5.897692       0.193037
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.025000278005250898

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939996     -6.926103      -0.934808
1            2.058461    0.006074    -13.278461      -6.31524      -0.290133
2            1.617025         NaN    -11.359243     -5.897692       0.209413
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.025500044939139727

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.432523     -5.897692       0.168769
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177321837

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.446043     -5.897692       0.174429
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.02635042693924673

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -12.034293     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.02671517670804223

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029     -15.56219     -6.926103      -0.765646
1            2.058461    0.004975    -13.161202      -6.31524      -0.237631
2            1.617025         NaN    -11.955082     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.027046923946476176

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904311     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890177737

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN    -11.884557     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.027627840660752353

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN    -11.560806     -5.897692        0.13279
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 120, Mean Difference: 0.027883588897412465

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859929     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.02811974283502283

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.860108     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235925807
uptake : 12.299999999999986
flux through atpm  24.161294968858765

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.266404     -5.897692       0.245771
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.02307577487288214

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35462     -6.926103      -1.120478
1            2.058461     0.00728    -13.407146      -6.31524      -0.347759
2            1.617025         NaN    -11.310416     -5.897692        0.22532
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 20, Mean Difference: 0.02380221846305075

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199232     -6.926103      -1.050902
1            2.058461    0.006828    -13.358919      -6.31524      -0.326165
2            1.617025         NaN    -11.348255     -5.897692       0.207939
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.024438444998285538

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062058     -6.926103      -0.989462
1            2.058461    0.006429    -13.316345      -6.31524      -0.307096
2            1.617025         NaN    -11.380299     -5.897692       0.193037
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.02500027800525494

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.415294     -5.897692         0.1816
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.0255000449391712

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.429385     -5.897692       0.170229
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177322447

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.484647     -5.897692       0.174429
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.026350426939246926

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -11.998107     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.026715176708043284

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029     -15.56219     -6.926103      -0.765646
1            2.058461    0.004975    -13.161202      -6.31524      -0.237631
2            1.617025         NaN    -11.955869     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.02704692394647749

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.923754     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.0273499538901779

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN     -11.88427     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.027627840660753144

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357845     -6.926103       -0.67415
1            2.058461     0.00438     -13.09778      -6.31524      -0.209234
2            1.617025         NaN    -11.553887     -5.897692       0.132643
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 120, Mean Difference: 0.027883588897410133

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859876     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835024237

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.852098     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235925155
uptake : 12.399999999999986
flux through atpm  24.161294968858773

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.267456     -5.897692       0.245281
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.023075774872880376

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35467     -6.926103      -1.120478
1            2.058461     0.00728    -13.407161      -6.31524      -0.347759
2            1.617025         NaN     -11.31131     -5.897692       0.224905
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 20, Mean Difference: 0.02380221846304979

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199232     -6.926103      -1.050902
1            2.058461    0.006828    -13.358919      -6.31524      -0.326165
2            1.617025         NaN    -11.348255     -5.897692       0.207939
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.024438444998288924

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062014     -6.926103      -0.989462
1            2.058461    0.006429    -13.316331      -6.31524      -0.307096
2            1.617025         NaN    -11.380315     -5.897692       0.193052
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.025000278005251637

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.342257     -5.897692       0.201847
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.025500044939178245

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830713     -6.926103      -0.885877
1            2.058461    0.005756    -13.244543      -6.31524      -0.274947
2            1.617025         NaN    -11.355318     -5.897692       0.190825
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177321396

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.795384     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 70, Mean Difference: 0.026350426939244522

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -12.035043     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.026715176708043586

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.931562     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.02704692394647692

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904311     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890178153

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN    -11.884557     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.02762784066075384

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN    -11.510148     -5.897692       0.132665
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 120, Mean Difference: 0.027883588897412853

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859895     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835023012

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.851982     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.02833847123592423
uptake : 12.499999999999986
flux through atpm  24.161294968858808

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.273262     -5.897692       0.242583
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.02307577487287926

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35467     -6.926103      -1.120478
1            2.058461     0.00728    -13.407161      -6.31524      -0.347759
2            1.617025         NaN     -11.31131     -5.897692       0.224905
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 20, Mean Difference: 0.023802218463049706

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN    -11.352224     -5.897692       0.205899
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 30, Mean Difference: 0.024438444998292272

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062058     -6.926103      -0.989462
1            2.058461    0.006429    -13.316345      -6.31524      -0.307096
2            1.617025         NaN    -11.376636     -5.897692       0.194762
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.02500027800525248

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.916897     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.025500044939174366

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.429683     -5.897692        0.17009
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177321663

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.795384     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 70, Mean Difference: 0.026350426939243277

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -12.034293     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.026715176708042326

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.931562     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.027046923946477033

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904743     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.02734995389017786

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN    -11.884455     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.02762784066075379

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN    -11.518523     -5.897692       0.132643
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 120, Mean Difference: 0.027883588897414515

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859779     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835027203

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.851982     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235925224
uptake : 12.599999999999985
flux through atpm  24.161294968858765

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.266404     -5.897692       0.245771
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.0230757748728761

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35467     -6.926103      -1.120478
1            2.058461     0.00728    -13.407161      -6.31524      -0.347759
2            1.617025         NaN     -11.31131     -5.897692       0.224905
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 20, Mean Difference: 0.023802218463051573

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199232     -6.926103      -1.050902
1            2.058461    0.006828    -13.358919      -6.31524      -0.326165
2            1.617025         NaN     -11.35229     -5.897692       0.206062
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.024438444998286662

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062014     -6.926103      -0.989462
1            2.058461    0.006429    -13.316331      -6.31524      -0.307096
2            1.617025         NaN    -11.376622     -5.897692       0.194747
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.02500027800525184

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -12.702285     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.025500044939172264

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.430873     -5.897692       0.169536
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177321202

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.420596     -5.897692       0.174316
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.026350426939244276

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -11.999607     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.02671517670803888

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.931562     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.027046923946476984

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904743     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890177036

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN    -11.884455     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.027627840660753283

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN    -11.510195     -5.897692       0.132643
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 120, Mean Difference: 0.027883588897412662

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859779     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835024598

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.852098     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235923184
uptake : 12.699999999999985
flux through atpm  24.16129496885877

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.273262     -5.897692       0.242583
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 10, Mean Difference: 0.023075774872876792

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35467     -6.926103      -1.120478
1            2.058461     0.00728    -13.407161      -6.31524      -0.347759
2            1.617025         NaN    -11.315972     -5.897692        0.22274
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 20, Mean Difference: 0.023802218463050185

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN     -11.35229     -5.897692       0.206062
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 30, Mean Difference: 0.02443844499829725

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062058     -6.926103      -0.989462
1            2.058461    0.006429    -13.316345      -6.31524      -0.307096
2            1.617025         NaN    -11.376286     -5.897692       0.195958
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.025000278005252254

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.329899     -5.897692       0.201847
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 50, Mean Difference: 0.02550004493916619

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.443521     -5.897692       0.170229
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.02594749217731872

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.485953     -5.897692       0.174429
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 70, Mean Difference: 0.026350426939243343

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -11.998107     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.026715176708043246

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.931562     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.027046923946476245

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904311     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890177803

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420308     -6.926103      -0.702118
1            2.058461    0.004562    -13.117167      -6.31524      -0.217914
2            1.617025         NaN    -11.900136     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.02762784066075358

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN    -11.518523     -5.897692       0.132643
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 120, Mean Difference: 0.02788358889741352

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.861258     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835024133

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.874157     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235925384
uptake : 12.799999999999985
flux through atpm  24.161294968858765

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.272056     -5.897692       0.243144
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 10, Mean Difference: 0.02307577487287829

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35467     -6.926103      -1.120478
1            2.058461     0.00728    -13.407161      -6.31524      -0.347759
2            1.617025         NaN    -11.307995     -5.897692       0.226445
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 20, Mean Difference: 0.023802218463050296

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN    -11.352224     -5.897692       0.205899
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.024438444998293157

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062058     -6.926103      -0.989462
1            2.058461    0.006429    -13.316345      -6.31524      -0.307096
2            1.617025         NaN    -11.385392     -5.897692       0.193052
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.025000278005248632

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -12.365911     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.02550004493917242

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.485593     -5.897692       0.169105
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177321414

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -12.365911     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.026350426939244814

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -11.999607     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.026715176708042934

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.931562     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.02704692394647436

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904311     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890178122

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN     -11.88427     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.027627840660752745

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN    -11.534074     -5.897692       0.132643
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 120, Mean Difference: 0.02788358889741197

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859854     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.02811974283502491

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.852098     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235925967
uptake : 12.899999999999984
flux through atpm  24.161294968858765

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.273097     -5.897692        0.24266
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.023075774872878055

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35467     -6.926103      -1.120478
1            2.058461     0.00728    -13.407161      -6.31524      -0.347759
2            1.617025         NaN    -11.310416     -5.897692        0.22532
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 20, Mean Difference: 0.02380221846304928

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN     -11.35229     -5.897692       0.206062
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.024438444998288077

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062058     -6.926103      -0.989462
1            2.058461    0.006429    -13.316345      -6.31524      -0.307096
2            1.617025         NaN    -11.379332     -5.897692       0.193486
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.0250002780052488

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.404935     -5.897692         0.1816
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.02550004493917089

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN     -11.43231     -5.897692       0.168868
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177320456

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.419809     -5.897692       0.174682
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 70, Mean Difference: 0.026350426939242295

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -11.998402     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.026715176708042822

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.947163     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.02704692394647611

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.934129     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890179555

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN     -11.88427     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.02762784066075494

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN    -11.510195     -5.897692       0.132643
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 120, Mean Difference: 0.02788358889741444

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859779     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835011754

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.852098     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235925266
uptake : 12.999999999999984
flux through atpm  24.16129496885872

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.273262     -5.897692       0.242583
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 10, Mean Difference: 0.02307577487287854

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35467     -6.926103      -1.120478
1            2.058461     0.00728    -13.407161      -6.31524      -0.347759
2            1.617025         NaN    -11.307995     -5.897692       0.226445
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 20, Mean Difference: 0.02380221846305008

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN    -11.348255     -5.897692       0.207939
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.024438444998294635

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062058     -6.926103      -0.989462
1            2.058461    0.006429    -13.316345      -6.31524      -0.307096
2            1.617025         NaN    -11.375902     -5.897692       0.195082
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.0250002780052523

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.795384     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.02550004493917038

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.429673     -5.897692       0.170095
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.02594749217732166

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.795384     -5.897692           -0.0
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.026350426939239627

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -11.998107     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.026715176708043284

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.930894     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.027046923946475815

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904311     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890185342

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN     -11.88427     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.027627840660752457

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN     -11.50988     -5.897692        0.13279
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 120, Mean Difference: 0.027883588897412617

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859929     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835023265

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.852098     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.02833847123592292
uptake : 13.099999999999984
flux through atpm  24.16129496885884

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.266404     -5.897692       0.245771
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.02307577487287897

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35462     -6.926103      -1.120478
1            2.058461     0.00728    -13.407146      -6.31524      -0.347759
2            1.617025         NaN    -11.312077     -5.897692       0.224548
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 20, Mean Difference: 0.023802218463051122

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN     -11.35195     -5.897692        0.20622
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 30, Mean Difference: 0.024438444998289538

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062058     -6.926103      -0.989462
1            2.058461    0.006429    -13.316345      -6.31524      -0.307096
2            1.617025         NaN    -11.375915     -5.897692       0.195098
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.02500027800525365

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.359243     -5.897692       0.209413
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.025500044939170297

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.430352     -5.897692       0.169779
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177322003

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.423945     -5.897692       0.176445
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.02635042693924543

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -11.999607     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.0267151767080441

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.931562     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.02704692394656824

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904311     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890178285

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN     -11.88427     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.02762784066075349

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN     -11.55652     -5.897692       0.132643
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 120, Mean Difference: 0.02788358889741385

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859929     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835029854

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.862084     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235925297
uptake : 13.199999999999983
flux through atpm  24.161294968858684

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.272232     -5.897692       0.243063
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.0230757748728781

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35462     -6.926103      -1.120478
1            2.058461     0.00728    -13.407146      -6.31524      -0.347759
2            1.617025         NaN    -11.315967     -5.897692       0.222741
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 20, Mean Difference: 0.0238022184630487

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN     -11.35229     -5.897692       0.206062
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.02443844499827365

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062014     -6.926103      -0.989462
1            2.058461    0.006429    -13.316331      -6.31524      -0.307096
2            1.617025         NaN    -11.380299     -5.897692       0.193037
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.02500027800525134

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939996     -6.926103      -0.934808
1            2.058461    0.006074    -13.278461      -6.31524      -0.290133
2            1.617025         NaN    -11.314796     -5.897692       0.230755
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.02550004493916924

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.429385     -5.897692       0.170229
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.02594749217732012

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.441596     -5.897692       0.174361
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.026350426939237514

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -11.998107     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.026715176708042108

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.931562     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.027046923946476276

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904311     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890179215

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN     -11.88427     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.027627840660754202

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN    -11.555191     -5.897692       0.132643
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 120, Mean Difference: 0.027883588897411746

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.869355     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.02811974283502361

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.852098     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235924725
uptake : 13.299999999999983
flux through atpm  24.161294968858765

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.266404     -5.897692       0.245771
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.023075774872880424

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35462     -6.926103      -1.120478
1            2.058461     0.00728    -13.407146      -6.31524      -0.347759
2            1.617025         NaN    -11.311308     -5.897692       0.224909
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 20, Mean Difference: 0.023802218463050553

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN    -11.348255     -5.897692       0.207939
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.024438444998292255

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062014     -6.926103      -0.989462
1            2.058461    0.006429    -13.316331      -6.31524      -0.307096
2            1.617025         NaN    -11.380299     -5.897692       0.193037
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.025000278005251415

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.404909     -5.897692       0.181592
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.025500044939172222

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.427018     -5.897692        0.17133
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177320997

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.420743     -5.897692       0.174248
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.026350426939248578

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -12.022506     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.02671517670804291

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.931562     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.02704692394647815

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904589     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890178136

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN    -11.884557     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.02762784066075458

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN    -11.560735     -5.897692        0.13279
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 120, Mean Difference: 0.027883588897406567

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.860878     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.02811974283502343

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.876225     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235924974
uptake : 13.399999999999983
flux through atpm  24.16129496885877

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN      -11.2716     -5.897692       0.243357
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.023075774872876948

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35462     -6.926103      -1.120478
1            2.058461     0.00728    -13.407146      -6.31524      -0.347759
2            1.617025         NaN     -11.31131     -5.897692       0.224905
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 20, Mean Difference: 0.02380221846305138

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN    -11.348255     -5.897692       0.207939
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 30, Mean Difference: 0.024438444998314972

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062014     -6.926103      -0.989462
1            2.058461    0.006429    -13.316331      -6.31524      -0.307096
2            1.617025         NaN    -11.376595     -5.897692       0.194782
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.02500027800525158

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.404362     -5.897692       0.181867
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.0255000449391702

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.431811     -5.897692         0.1691
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177319533

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.420053     -5.897692       0.174569
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.026350426939245258

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -12.018277     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.02671517670804305

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.931562     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.027046923946476422

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.795384     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890177654

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN    -11.884398     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.027627840660754285

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN    -11.510195     -5.897692       0.132643
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 120, Mean Difference: 0.02788358889741299

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859779     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835024053

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.851982     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.02833847123592681
uptake : 13.499999999999982
flux through atpm  24.16129496885872

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.272232     -5.897692       0.243063
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 10, Mean Difference: 0.023075774872878995

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35462     -6.926103      -1.120478
1            2.058461     0.00728    -13.407146      -6.31524      -0.347759
2            1.617025         NaN    -11.311308     -5.897692       0.224906
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 20, Mean Difference: 0.023802218463032626

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN     -11.35229     -5.897692       0.206062
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.02443844499828833

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062058     -6.926103      -0.989462
1            2.058461    0.006429    -13.316345      -6.31524      -0.307096
2            1.617025         NaN    -11.392356     -5.897692       0.194762
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.025000278005254534

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.407589     -5.897692       0.180366
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.025500044939170758

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.426938     -5.897692       0.171366
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.02594749217732137

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.420743     -5.897692       0.174248
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.026350426939249744

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789    -15.643215     -6.926103      -0.801925
1            2.058461    0.005211     -13.18635      -6.31524      -0.248891
2            1.617025         NaN     -12.03606     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.026715176708038302

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029     -15.56219     -6.926103      -0.765646
1            2.058461    0.004975    -13.161202      -6.31524      -0.237631
2            1.617025         NaN    -11.955869     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.027046923946476398

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488179     -6.926103      -0.732507
1            2.058461     0.00476    -13.138232      -6.31524      -0.227346
2            1.617025         NaN    -11.924082     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890178646

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN    -11.884455     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.027627840660752745

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN     -11.50988     -5.897692        0.13279
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 120, Mean Difference: 0.027883588897411285

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859779     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835023494

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.852057     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.02833847123592546
uptake : 13.599999999999982
flux through atpm  24.161294968858776

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.262443     -5.897692       0.247611
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.023075774872879207

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35467     -6.926103      -1.120478
1            2.058461     0.00728    -13.407161      -6.31524      -0.347759
2            1.617025         NaN    -11.307088     -5.897692       0.226866
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 20, Mean Difference: 0.023802218463050456

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199232     -6.926103      -1.050902
1            2.058461    0.006828    -13.358919      -6.31524      -0.326165
2            1.617025         NaN    -11.348247     -5.897692       0.207744
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.024438444998291804

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062014     -6.926103      -0.989462
1            2.058461    0.006429    -13.316331      -6.31524      -0.307096
2            1.617025         NaN    -11.376259     -5.897692       0.194938
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.02500027800525177

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.422571     -5.897692       0.181955
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.025500044939170408

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.426716     -5.897692        0.17147
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.02594749217731374

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.420053     -5.897692       0.174569
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.026350426939244786

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -12.034639     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.02671517670804244

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029     -15.56219     -6.926103      -0.765646
1            2.058461    0.004975    -13.161202      -6.31524      -0.237631
2            1.617025         NaN    -11.955589     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.02704692394647686

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904743     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890178563

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN    -11.884557     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.027627840660753026

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN    -11.510148     -5.897692       0.132665
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 120, Mean Difference: 0.027883588897412867

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859876     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835023404

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.852098     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235925634
uptake : 13.699999999999982
flux through atpm  24.16129496885875

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.267456     -5.897692       0.245281
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.02307577487288176

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35462     -6.926103      -1.120478
1            2.058461     0.00728    -13.407146      -6.31524      -0.347759
2            1.617025         NaN    -11.315967     -5.897692       0.222741
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 20, Mean Difference: 0.023802218463050594

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN     -11.35229     -5.897692       0.206062
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.02443844499829158

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062014     -6.926103      -0.989462
1            2.058461    0.006429    -13.316331      -6.31524      -0.307096
2            1.617025         NaN    -11.376636     -5.897692       0.194762
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.025000278005252046

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.329899     -5.897692       0.201847
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.025500044939170564

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830713     -6.926103      -0.885877
1            2.058461    0.005756    -13.244543      -6.31524      -0.274947
2            1.617025         NaN    -11.355318     -5.897692       0.190825
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.02594749217732108

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.484178     -5.897692       0.176187
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.026350426939244182

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -11.998402     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.02671517670804312

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.931324     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.027046923946474722

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904589     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890177917

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN    -11.884557     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.02762784066075195

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN     -11.50988     -5.897692        0.13279
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 120, Mean Difference: 0.02788358889741274

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859929     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.02811974283502817

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.858947     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235924274
uptake : 13.799999999999981
flux through atpm  24.16129496885886

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.266404     -5.897692       0.245771
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.023075774872877274

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35467     -6.926103      -1.120478
1            2.058461     0.00728    -13.407161      -6.31524      -0.347759
2            1.617025         NaN    -11.315967     -5.897692       0.222741
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 20, Mean Difference: 0.023802218463050626

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN     -11.35229     -5.897692       0.206062
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 30, Mean Difference: 0.02443844499829401

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062058     -6.926103      -0.989462
1            2.058461    0.006429    -13.316345      -6.31524      -0.307096
2            1.617025         NaN    -11.373048     -5.897692       0.196431
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.025000278005258798

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939996     -6.926103      -0.934808
1            2.058461    0.006074    -13.278461      -6.31524      -0.290133
2            1.617025         NaN    -12.365911     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.025500044939169214

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -12.250576     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177323294

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732301     -6.926103      -0.841813
1            2.058461     0.00547    -13.213999      -6.31524      -0.261271
2            1.617025         NaN    -11.795384     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 70, Mean Difference: 0.026350426939244494

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -12.034293     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.02671517670804348

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.931562     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.027046923946476998

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904589     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890177855

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN    -11.884455     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.027627840660754178

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN    -11.561256     -5.897692       0.132643
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 120, Mean Difference: 0.02788358889741346

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859929     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.02811974283502187

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.861174     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235925422
uptake : 13.89999999999998
flux through atpm  24.16129496885877

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.272067     -5.897692        0.24314
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.023075774872878003

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35462     -6.926103      -1.120478
1            2.058461     0.00728    -13.407146      -6.31524      -0.347759
2            1.617025         NaN     -11.31131     -5.897692       0.224905
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 20, Mean Difference: 0.023802218463051042

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN    -11.348255     -5.897692       0.207939
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.02443844499828807

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062058     -6.926103      -0.989462
1            2.058461    0.006429    -13.316345      -6.31524      -0.307096
2            1.617025         NaN    -11.393102     -5.897692       0.194762
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.02500027800518149

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.795384     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.025500044939170307

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.429683     -5.897692        0.17009
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177322146

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.485953     -5.897692       0.174429
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.026350426939244404

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -11.998107     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.02671517670804299

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.930894     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.027046923946476776

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904311     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890178098

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN     -11.88427     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.027627840660753616

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN     -11.50988     -5.897692        0.13279
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 120, Mean Difference: 0.02788358889741753

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859929     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835028837

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.852098     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235924284
uptake : 13.99999999999998
flux through atpm  24.16129496885877

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.272067     -5.897692        0.24314
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.02307577487286958

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35467     -6.926103      -1.120478
1            2.058461     0.00728    -13.407161      -6.31524      -0.347759
2            1.617025         NaN    -11.310416     -5.897692        0.22532
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 20, Mean Difference: 0.023802218463052745

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN    -11.362503     -5.897692       0.206575
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.024438444998288008

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062014     -6.926103      -0.989462
1            2.058461    0.006429    -13.316331      -6.31524      -0.307096
2            1.617025         NaN    -11.404359     -5.897692       0.193052
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.025000278005253434

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.409487     -5.897692       0.182609
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.02550004493917067

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.452413     -5.897692       0.169101
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177322284

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.483108     -5.897692       0.176823
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 70, Mean Difference: 0.02635042693924269

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -11.986761     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.026715176708042895

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.930894     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.027046923946477088

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904311     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.02734995389017748

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN     -11.88427     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.027627840660754716

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN    -11.558104     -5.897692       0.132643
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 120, Mean Difference: 0.027883588897415282

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859929     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.02811974283502372

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.852057     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.02833847123592376
uptake : 14.09999999999998
flux through atpm  24.161294968858755

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.273273     -5.897692        0.24258
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.023075774872874936

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35467     -6.926103      -1.120478
1            2.058461     0.00728    -13.407161      -6.31524      -0.347759
2            1.617025         NaN    -11.307086     -5.897692       0.226867
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 20, Mean Difference: 0.023802218463050345

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199232     -6.926103      -1.050902
1            2.058461    0.006828    -13.358919      -6.31524      -0.326165
2            1.617025         NaN    -11.348255     -5.897692       0.207939
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.024438444998289455

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062014     -6.926103      -0.989462
1            2.058461    0.006429    -13.316331      -6.31524      -0.307096
2            1.617025         NaN    -11.380299     -5.897692       0.193037
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.025000278005251734

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.795384     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.02550004493916941

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN    -11.795384     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.025947492177321948

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732264     -6.926103      -0.841813
1            2.058461     0.00547    -13.213987      -6.31524      -0.261271
2            1.617025         NaN    -11.420743     -5.897692       0.174248
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.026350426939241542

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789     -15.64318     -6.926103      -0.801925
1            2.058461    0.005211    -13.186339      -6.31524      -0.248891
2            1.617025         NaN    -11.999607     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.026715176708046143

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.382512     -5.897692       0.198241
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.027046923946476814

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.923754     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890180866

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN    -11.884557     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.02762784066075305

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357815     -6.926103       -0.67415
1            2.058461     0.00438    -13.097771      -6.31524      -0.209234
2            1.617025         NaN    -11.560806     -5.897692        0.13279
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 120, Mean Difference: 0.027883588897412947

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859929     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835021694

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.860112     -5.897692            0.0
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235925877
uptake : 14.19999999999998
flux through atpm  24.16129496885881

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.267467     -5.897692       0.245277
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.02307577487290755

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35462     -6.926103      -1.120478
1            2.058461     0.00728    -13.407146      -6.31524      -0.347759
2            1.617025         NaN     -11.31131     -5.897692       0.224905
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 20, Mean Difference: 0.02380221846304925

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199279     -6.926103      -1.050902
1            2.058461    0.006828    -13.358933      -6.31524      -0.326165
2            1.617025         NaN    -11.345261     -5.897692       0.209331
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 30, Mean Difference: 0.024438444998289274

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.020715    -16.062058     -6.926103      -0.989462
1            2.058461    0.006429    -13.316345      -6.31524      -0.307096
2            1.617025         NaN    -11.376636     -5.897692       0.194762
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 40, Mean Difference: 0.02500027800525267

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.019571    -15.939955     -6.926103      -0.934808
1            2.058461    0.006074    -13.278448      -6.31524      -0.290133
2            1.617025         NaN    -11.404672     -5.897692       0.181723
3            1.431369         0.0    -12.080647     -6.040324            0.0
GAM Value: 50, Mean Difference: 0.025500044939170408

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.018546    -15.830674     -6.926103      -0.885877
1            2.058461    0.005756    -13.244531      -6.31524      -0.274947
2            1.617025         NaN     -11.42732     -5.897692       0.171189
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 60, Mean Difference: 0.02594749217732238

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.017624    -15.732301     -6.926103      -0.841813
1            2.058461     0.00547    -13.213999      -6.31524      -0.261271
2            1.617025         NaN      -11.4205     -5.897692       0.174361
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 70, Mean Difference: 0.026350426939246458

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016789    -15.643215     -6.926103      -0.801925
1            2.058461    0.005211     -13.18635      -6.31524      -0.248891
2            1.617025         NaN    -11.985702     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 80, Mean Difference: 0.026715176708045504

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.016029    -15.562156     -6.926103      -0.765646
1            2.058461    0.004975    -13.161192      -6.31524      -0.237631
2            1.617025         NaN    -11.355318     -5.897692       0.190825
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 90, Mean Difference: 0.02704692394647777

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.015335    -15.488146     -6.926103      -0.732507
1            2.058461     0.00476    -13.138222      -6.31524      -0.227346
2            1.617025         NaN    -11.904743     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 100, Mean Difference: 0.027349953890178063

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014699    -15.420277     -6.926103      -0.702118
1            2.058461    0.004562    -13.117157      -6.31524      -0.217914
2            1.617025         NaN    -11.894074     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 110, Mean Difference: 0.027627840660753644

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.014114    -15.357845     -6.926103       -0.67415
1            2.058461     0.00438     -13.09778      -6.31524      -0.209234
2            1.617025         NaN    -11.510195     -5.897692       0.132643
3            1.431369        -0.0    -12.080647     -6.040324           -0.0
GAM Value: 120, Mean Difference: 0.02788358889741341

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013573    -15.300139     -6.926103      -0.648325
1            2.058461    0.004213     -13.07987      -6.31524      -0.201218
2            1.617025         NaN    -11.859929     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 130, Mean Difference: 0.028119742835022544

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.013072    -15.246718     -6.926103      -0.624405
1            2.058461    0.004057     -13.06329      -6.31524      -0.193795
2            1.617025         NaN    -11.852057     -5.897692            0.0
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 140, Mean Difference: 0.028338471235925356
uptake : 14.29999999999998
flux through atpm  24.161294968858762

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.025121    -16.532041     -6.926103       -1.19992
1            2.058461    0.007797    -13.462212      -6.31524      -0.372415
2            1.617025         NaN    -11.272221     -5.897692       0.243067
3            1.431369        -0.0    -12.080647     -6.040324            0.0
GAM Value: 10, Mean Difference: 0.023075774872877864

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.023458     -16.35467     -6.926103      -1.120478
1            2.058461     0.00728    -13.407161      -6.31524      -0.347759
2            1.617025         NaN    -11.307995     -5.897692       0.226445
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 20, Mean Difference: 0.02380221846305014

c:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\anaconda3\Lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

   Unnamed: 0   dilRate  H2 Flux theoretic  O2 flux theoretic  \
0           0  0.046160          19.489454           6.926103
1           1  0.035260          17.380479           6.315240
2           2  0.026357          15.628204           5.897692
3           3  0.020724          15.387005           6.040324

   CO2 flux theoretic growth_rate H2 Flux model O2 Flux model CO2 Flux model
0            2.509541    0.022001    -16.199232     -6.926103      -1.050902
1            2.058461    0.006828    -13.358919      -6.31524      -0.326165
2            1.617025         NaN    -11.348255     -5.897692       0.207939
3            1.431369         0.0    -12.080647     -6.040324           -0.0
GAM Value: 30, Mean Difference: 0.024438444998288664

KeyboardInterrupt:

In [ ]:
# Find the row with the minimum Mean Difference
best_result = results_df.loc[results_df['Mean_Difference'].idxmin()]
best_r2_square = results_df.loc[results_df['R2_Score'].idxmax()]

# Print the best GAM value with lowest mean difference
print("Best GAM Value with Lowest Mean Difference:")
print(best_result)
print("Best GAM Value with highest r2 score:")
print(best_r2_square)

NameError: name 'results_df' is not defined

In [ ]:
sbml_filename = "C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.09 Models\\Manual_curation\\Energy_consumption\\250317_final_model_1.sbml"
cobra.io.write_sbml_model(model, sbml_filename)